### ISSUE TITLE
unable to find the IP address for the container

### ISSUE THREAD

**Issue by bisrikarim** [StanGirard/quivr#1010]
backend-core exited with code 1
quivr-traefik-1  | time="2023-08-22T07:22:39Z" level=error msg="service \"backend-core\" error: unable to find the IP address for the container \"/backend-core\": the server is ignored" providerName=docker container=backend-core-quivr-c97236fbeacd57d8d9442446bd130156595a44fcf216d0672b8d90b4993bab94

**Comment by mamadoudicko** [comment]
Also had that issue a few minutes ago.

Could you please restart Docker and ensure you have the latest version of main?
