### ISSUE TITLE
[Improvement] AAU, on the "add new brain" page, I should see an asterisk next to "Brain name". And if I click on "Create", leaving the "Brain name" field empty, I should see an error message[Issue]

### ISSUE THREAD

**Issue by danielpinkhassov** [StanGirard/quivr#1017]
Observed issue : 
AAU, In the "add new brain" page, when I click on the "create" button without having added a "Brain name", nothing happens

Loom : https://www.loom.com/share/ab4429a116614997a5d8b7d75fcc65be

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/1055

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/1065
