### ISSUE TITLE
[Issue] want to using private model, but get error message

### ISSUE THREAD

**Issue by KevinKuo2519** [StanGirard/quivr#1026]
Hi, I use 0.0.46 version, want to using private model "nous-hermes-13b.ggmlv3.q4_0.bin"

and I configure .env file such as:

#Private LLM Variables
PRIVATE=**True**
MODEL_PATH=./local_models/**nous-hermes-13b.ggmlv3.q4_0.bin**

and I put the **file in backend/local_models**

when I ask brain question, then I get error message below, Is there anything I missing to do?

backend-core-private  | 2023-08-23 08:48:28,594 [INFO] llm.private_gpt4all: Using private model: gpt4all-j-1.3
backend-core-private  | 2023-08-23 08:48:28,594 [INFO] llm.private_gpt4all: Streaming is set to False
backend-core-private  | INFO:     172.20.0.1:51346 - "POST /chat/1b12bf3a-2620-4e4e-8f74-19800ce6990e/question?brain_id=02f62eb1-65bf-4292-b454-c734aa1ae3ef HTTP/1.1" 500 Internal Server Error
backend-core-private  | ERROR:    Exception in ASGI application
backend-core-private  | Traceback (most recent call last):
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core-private  |     result = await app(  # type: ignore[func-returns-value]
backend-core-private  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core-private  |     return await self.app(scope, receive, send)
backend-core-private  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core-private  |     await super().__call__(scope, receive, send)
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core-private  |     await self.middleware_stack(scope, receive, send)
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core-private  |     raise exc
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core-private  |     await self.app(scope, receive, _send)
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core-private  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core-private  |     await self.app(scope, receive, send)
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core-private  |     raise exc
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core-private  |     await self.app(scope, receive, sender)
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core-private  |     raise e
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core-private  |     await self.app(scope, receive, send)
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core-private  |     await route.handle(scope, receive, send)
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core-private  |     await self.app(scope, receive, send)
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-core-private  |     response = await func(request)
backend-core-private  |                ^^^^^^^^^^^^^^^^^^^
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend-core-private  |     raw_response = await run_endpoint_function(
backend-core-private  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend-core-private  |     return await dependant.call(**values)
backend-core-private  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core-private  |   File "/code/routes/chat_routes.py", line 225, in create_question_handler
backend-core-private  |     chat_answer = gpt_answer_generator.generate_answer(  # pyright: ignore reportPrivateUsage=none
backend-core-private  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core-private  |   File "/code/llm/qa_base.py", line 139, in generate_answer
backend-core-private  |     model_response = self._call_chain(self.qa, question, transformed_history)
backend-core-private  |                                       ^^^^^^^
backend-core-private  |   File "/code/llm/qa_base.py", line 94, in qa
backend-core-private  |     question_generator=self.question_generator,
backend-core-private  |                        ^^^^^^^^^^^^^^^^^^^^^^^
backend-core-private  |   File "/code/llm/qa_base.py", line 82, in question_generator
backend-core-private  |     return LLMChain(llm=self.question_llm, prompt=CONDENSE_QUESTION_PROMPT)
backend-core-private  |                         ^^^^^^^^^^^^^^^^^
backend-core-private  |   File "/code/llm/qa_base.py", line 72, in question_llm
backend-core-private  |     return self._create_llm(model=self.model, streaming=False)
backend-core-private  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core-private  |   File "/code/llm/private_gpt4all.py", line 72, in _create_llm
backend-core-private  |     return GPT4All(
backend-core-private  |            ^^^^^^^^
backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/langchain/load/serializable.py", line 74, in __init__
backend-core-private  |     super().__init__(**kwargs)
backend-core-private  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-core-private  | pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
backend-core-private  | __root__
backend-core-private  |   Invalid model directory: ./local_models/ (type=value_error)

**Comment by Tafboy22** [comment]
> Hi, I use 0.0.46 version, want to using private model "nous-hermes-13b.ggmlv3.q4_0.bin"
> 
> 
> 
> and I configure .env file such as:
> 
> 
> 
> #Private LLM Variables
> 
> PRIVATE=**True**
> 
> MODEL_PATH=./local_models/**nous-hermes-13b.ggmlv3.q4_0.bin**
> 
> 
> 
> and I put the **file in backend/local_models**
> 
> 
> 
> when I ask brain question, then I get error message below, Is there anything I missing to do?
> 
> 
> 
> 
> 
> backend-core-private  | 2023-08-23 08:48:28,594 [INFO] llm.private_gpt4all: Using private model: gpt4all-j-1.3
> 
> backend-core-private  | 2023-08-23 08:48:28,594 [INFO] llm.private_gpt4all: Streaming is set to False
> 
> backend-core-private  | INFO:     172.20.0.1:51346 - "POST /chat/1b12bf3a-2620-4e4e-8f74-19800ce6990e/question?brain_id=02f62eb1-65bf-4292-b454-c734aa1ae3ef HTTP/1.1" 500 Internal Server Error
> 
> backend-core-private  | ERROR:    Exception in ASGI application
> 
> backend-core-private  | Traceback (most recent call last):
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
> 
> backend-core-private  |     result = await app(  # type: ignore[func-returns-value]
> 
> backend-core-private  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
> 
> backend-core-private  |     return await self.app(scope, receive, send)
> 
> backend-core-private  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
> 
> backend-core-private  |     await super().__call__(scope, receive, send)
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
> 
> backend-core-private  |     await self.middleware_stack(scope, receive, send)
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
> 
> backend-core-private  |     raise exc
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
> 
> backend-core-private  |     await self.app(scope, receive, _send)
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
> 
> backend-core-private  |     await self.simple_response(scope, receive, send, request_headers=headers)
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
> 
> backend-core-private  |     await self.app(scope, receive, send)
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
> 
> backend-core-private  |     raise exc
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
> 
> backend-core-private  |     await self.app(scope, receive, sender)
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
> 
> backend-core-private  |     raise e
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
> 
> backend-core-private  |     await self.app(scope, receive, send)
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
> 
> backend-core-private  |     await route.handle(scope, receive, send)
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
> 
> backend-core-private  |     await self.app(scope, receive, send)
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
> 
> backend-core-private  |     response = await func(request)
> 
> backend-core-private  |                ^^^^^^^^^^^^^^^^^^^
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
> 
> backend-core-private  |     raw_response = await run_endpoint_function(
> 
> backend-core-private  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
> 
> backend-core-private  |     return await dependant.call(**values)
> 
> backend-core-private  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> backend-core-private  |   File "/code/routes/chat_routes.py", line 225, in create_question_handler
> 
> backend-core-private  |     chat_answer = gpt_answer_generator.generate_answer(  # pyright: ignore reportPrivateUsage=none
> 
> backend-core-private  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> backend-core-private  |   File "/code/llm/qa_base.py", line 139, in generate_answer
> 
> backend-core-private  |     model_response = self._call_chain(self.qa, question, transformed_history)
> 
> backend-core-private  |                                       ^^^^^^^
> 
> backend-core-private  |   File "/code/llm/qa_base.py", line 94, in qa
> 
> backend-core-private  |     question_generator=self.question_generator,
> 
> backend-core-private  |                        ^^^^^^^^^^^^^^^^^^^^^^^
> 
> backend-core-private  |   File "/code/llm/qa_base.py", line 82, in question_generator
> 
> backend-core-private  |     return LLMChain(llm=self.question_llm, prompt=CONDENSE_QUESTION_PROMPT)
> 
> backend-core-private  |                         ^^^^^^^^^^^^^^^^^
> 
> backend-core-private  |   File "/code/llm/qa_base.py", line 72, in question_llm
> 
> backend-core-private  |     return self._create_llm(model=self.model, streaming=False)
> 
> backend-core-private  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> backend-core-private  |   File "/code/llm/private_gpt4all.py", line 72, in _create_llm
> 
> backend-core-private  |     return GPT4All(
> 
> backend-core-private  |            ^^^^^^^^
> 
> backend-core-private  |   File "/usr/local/lib/python3.11/site-packages/langchain/load/serializable.py", line 74, in __init__
> 
> backend-core-private  |     super().__init__(**kwargs)
> 
> backend-core-private  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> 
> backend-core-private  | pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
> 
> backend-core-private  | __root__
> 
> backend-core-private  |   Invalid model directory: ./local_models/ (type=value_error)

Message anonyme piratage
