### ISSUE TITLE
[Issue] Error processing file: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by baha-ott** [StanGirard/quivr#1028]
I'm getting this error when trying to upload a file. 

I'm using latest version.

* I'm working with local LLM 
* os: windows and also facing the same problem on macOS 
* docker version:  24.0.5

**Comment by DittoDuckPenguin** [comment]
`backend-upload   | 2023-09-05 06:20:27,810 [INFO] models.files: Computing documents from file 1.txt
backend-upload   | 2023-09-05 06:20:27,844 [INFO] utils.vectors: Creating vector for document
backend-upload   | 2023-09-05 06:20:27,844 [INFO] utils.vectors: Document: page_content="###################################################" metadata={'file_sha1': '6bae0528752c597b99f7d11aa7b7e14d70e91499', 'file_size': 0, 'file_name': '1.txt', 'chunk_size': 500, 'chunk_overlap': 0, 'date': '20230905', 'summarization': 'false'}
backend-upload   | 2023-09-05 06:20:28,212:INFO - error_code=None error_message='Invalid URL (POST /v1).' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
backend-upload   | 2023-09-05 06:20:28,213 [ERROR] utils.vectors: Error creating vector for document Invalid URL (POST /v1).
backend-upload   | document []
backend-upload   | file sha1 6bae0528752c597b99f7d11aa7b7e14d70e91499
backend-upload   | file_sha1 6bae0528752c597b99f7d11aa7b7e14d70e91499
backend-upload   | vectors_ids []
backend-upload   | len(vectors_ids) 0
backend-upload   | response.data []
backend-upload   | documents [Document(page_content="###################################################", metadata={'source': '/tmp/tmpnoiw5uxi1.txt'})]
backend-upload   | [Document(page_content="###################################################", metadata={'source': '/tmp/tmpnoiw5uxi1.txt'})]
backend-upload   | Error processing file: 'NoneType' object is not subscriptable
backend-upload   | INFO:     172.18.0.7:34156 - "POST /upload?brain_id=81aa1236-b76e-479d-af0c-100f805d6144 HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.7:37458 - "GET /prompts HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.7:37466 - "GET /brains/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.7:37466 - "GET /prompts HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.7:37466 - "GET /brains/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.7:37466 - "GET /prompts HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.7:37466 - "GET /brains/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.7:37466 - "GET /prompts HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.7:37466 - "GET /brains/ HTTP/1.1" 200 OK`

Got the same problem.

Specs:
- Local Install via Docker
- SupaBase Online DB
- Custom OpenAI-BaseURL
- Ubuntu 20.04.5 LTS
