### ISSUE TITLE
💝 Thank you for making Quivr and feedback on specific usecase

### ISSUE THREAD

**Issue by adriens** [StanGirard/quivr#1035]
Hi,

I'm working at https://www.opt.nc/ and I have used Quivr to better understand our Strategiv plan.

Below is a storytelling which relies in part on Quivr : 

- [Discover Quivr](https://youtu.be/BN5Fdtvu21Q?si=8VpAKrOSDPWw1IQo)
- [Get feedback on innovation from Quivr](https://youtu.be/BN5Fdtvu21Q?si=oua1Jtkyr5FCbtHe)
- Whole DEV.to article : [🦜🔗 Track Package Delivery w. Langchain Agent Custom Tools](https://dev.to/adriens/track-package-delivery-w-langchain-agent-custom-tools-18jf)

Thanks a lot for the great app you are delivering 🙏 🤩

**Comment by StanGirard** [comment]
Awesome :) Thanks a lot! I'll be closing the Issue but feel free to come to Discord to chat

**Comment by adriens** [comment]
U R Welcome, on my side, a lot of people asked more about Quivr 💪
