### ISSUE TITLE
Unhandled Runtime Error AxiosError: Network Error

### ISSUE THREAD

**Issue by bogorad** [StanGirard/quivr#104]
Freshly docker-compose'd. Opened the web page, uploaded two docs, asked "what do I have" and got this error:

Unhandled Runtime Error
AxiosError: Network Error

Call Stack
XMLHttpRequest.handleError
node_modules/axios/lib/adapters/xhr.js (158:0)

![6ca4ab0c-85ef-4540-9167-3fd78551984c](https://github.com/StanGirard/quivr/assets/2777398/9f18539b-9cb8-4601-bebd-b55e49ee2e8d)

Nothing in the web/backend docker-logs.

**Comment by bogorad** [comment]
Same when trying to upload files:

> Failed to upload file: AxiosError: Network Error

backend works:

chuck@u2204:~/git/Quivr$ curl localhost:5000
{"message":"Hello World"}

**Comment by bogorad** [comment]
it's using localhost:500 for backend.

**Comment by lzhgus** [comment]
```
Request URL:
http://localhost:5000/upload
Request Method:
POST
Status Code:
403 Forbidden
Referrer Policy:
strict-origin-when-cross-origin
```
For me It's using port 5000. but I am still getting the same error. How did you resolve the issue from your side?

**Comment by bogorad** [comment]
sorry, my mistake, it's :5000

**Comment by woshichuanqilz** [comment]
same error on me
![image](https://github.com/StanGirard/quivr/assets/11295355/86ba290f-cbd8-4118-8a70-e9fe94d5f4fd)

**Comment by lix2k3** [comment]
Same error here.
