### ISSUE TITLE
[BUG] AAU, on the history chat page, I should be able to scroll through the history instead of having it fixed

### ISSUE THREAD

**Issue by danielpinkhassov** [StanGirard/quivr#1042]
https://github.com/StanGirard/quivr/assets/121382169/8e21b734-ebe2-48b1-bfc8-981d088467d7

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/1064

**Comment by mamadoudicko** [comment]
Validation criterias:

- Create multiple chats
- Check that you can scroll through
