### ISSUE TITLE
[UX-Chat] 6a - Remove brain button in navbar and replace the settings button with brain icon

### ISSUE THREAD

**Issue by mamadoudicko** [StanGirard/quivr#1050]
# Epic

Include the issue that represents the epic.

# Functional

- Remove brain button in navbar  
- Replace the settings button with brain icon

### Tech

- [] To-do

### Tests

- [] it ...

### Validation Checks

- Check that in the header there is no settings icon
- Check that now brain icon redirect to settings page

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/1052

**Comment by gozineb** [comment]
Please add the Validation Criteria: 
@mamadoudicko
