### ISSUE TITLE
Error when uploading files

### ISSUE THREAD

**Issue by uzziwizzle** [StanGirard/quivr#107]
I am getting the below. How can I fix this?

Failed to upload file: AxiosError: Network Error

**Comment by lzhgus** [comment]
+1

**Comment by dheerapat** [comment]
can you give us an error log from docker back-end ?

**Comment by spectramaster** [comment]
> can you give us an error log from docker back-end ? what is the type of file you trying to upload?

backend  | ERROR:    Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
backend  |     async with self.lifespan_context(app) as maybe_state:
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
backend  |     await self._router.startup()
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
backend  |     await handler()
backend  |   File "/code/api.py", line 52, in startup_event
backend  |     pypandoc.download_pandoc()
backend  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 231, in download_pandoc
backend  |     pandoc_urls, _ = _get_pandoc_urls(version)
backend  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 49, in _get_pandoc_urls
backend  |     response = urlopen(url)
backend  |                ^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
backend  |     return opener.open(url, data, timeout)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/urllib/request.py", line 525, in open
backend  |     response = meth(req, response)
backend  |                ^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/urllib/request.py", line 634, in http_response
backend  |     response = self.parent.error(
backend  |                ^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/urllib/request.py", line 557, in error
backend  |     result = self._call_chain(*args)
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
backend  |     result = func(*args)
backend  |              ^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/urllib/request.py", line 749, in http_error_302
backend  |     return self.parent.open(new, timeout=req.timeout)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
backend  |     response = self._open(req, data)
backend  |                ^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
backend  |     result = self._call_chain(self.handle_open, protocol, protocol +
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
backend  |     result = func(*args)
backend  |              ^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
backend  |     return self.do_open(http.client.HTTPSConnection, req,
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/urllib/request.py", line 1352, in do_open
backend  |     r = h.getresponse()
backend  |         ^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/http/client.py", line 1375, in getresponse
backend  |     response.begin()
backend  |   File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
backend  |     version, status, reason = self._read_status()
backend  |                               ^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
backend  |     raise RemoteDisconnected("Remote end closed connection without"
backend  | http.client.RemoteDisconnected: Remote end closed connection without response
backend  | 
backend  | ERROR:    Application startup failed. Exiting.

**Comment by spectramaster** [comment]
The file type I want to  upload  is PDF
