### ISSUE TITLE
[Bug] AAU, I can enter an email on the share modal opened from the chat brain mention input

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#1072]
![Image](https://github.com/StanGirard/quivr/assets/100568984/f5cc7f82-8654-4528-951e-9d37ca187b3d)

For now, instead of modal, we've added a rediction to brain management page, people tab

Validation criterias:
- Go to chat page
- Trigger the brain list (`@`)
- Click on share icon (you'll be redirected to brain management page, peope tab)
- Check that everything goes right when you share brain with others

**Comment by mamadoudicko** [comment]
Temporally add redirection to settings page, share tab

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/1078

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/1082

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/1085
