### ISSUE TITLE
[Issue] Any plans to support images?

### ISSUE THREAD

**Issue by MatthewPattell** [StanGirard/quivr#1074]
Hello. The question is quite straightforward - is image uploading support planned? Currently, I can't do this (even though there's an option to upload videos). I've checked the roadmap and tried to find similar questions in the issues, but without any success. Thanks.

- Recognize text from images (screenshots, etc.)

**Comment by micuentadecasa** [comment]
I'm also interested on this feature, can I suggest to investigate the use of Idefics (HuggingFace) for analyzing the images?
