### ISSUE TITLE
[UX Upload] 1-a AAUser, when I click on the plus button, the input composant in the ChatBar is turned into an input bar to enter the brain to feed

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#1083]
# Epic

[#849](https://github.com/StanGirard/quivr/issues/849)

# Functional

![Image](https://github.com/StanGirard/quivr/assets/100568984/e2f059ac-9eed-45f9-8175-efd1c9d95ecb)

- User has to choose a brain he can feed knowledge to. The list of brains should only contain the brains for which the user is owner or editor (right to add knowledge to a brain)
- The send icon is grey until a brain is chosen 
- When a brain is chosen the icon to send can be clicked again 

### Tech

- [] Add '+' button in ChatBar
- [] On click on '+', bar should switch to FeedBrainInput
- [] Create a component FeedBrainInput: Placeholder + submit button
- [] FeatureFlag: on click on '+' redirect towards /upload page

### Tests

- [] it ...

### Validation Checks

[here for inspiration](https://user-images.githubusercontent.com/63923024/265467074-7c27fcaa-1ec9-4f0f-91c8-17dcae708fb3.mov)

- Go to chat page
- Click on plus (+) icon and check that the input changed
- Check that the new input allows only `@`
- Check that you can switch inputs and keep brain selected

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/1101

**Comment by lamiabnn** [comment]
When I open the modal and I add a brain, I can't delete it

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/1154
