### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by ythknn** [StanGirard/quivr#110]
Hi. Even though I haven't used it yet, I get "You exceeded your current quota, please check your plan and billing details." warning and can't access anything. How can I fix that?

**Comment by StanGirard** [comment]
You need to put your card :)

**Comment by ythknn** [comment]
Actually I did. And that is the reason I'm reporting this as an issue. I did put my card. It must be working but I think the problem is caused by OpenAI.

**Comment by StanGirard** [comment]
On platform.openai.com ? 

Is your API key setup ?

**Comment by ythknn** [comment]
I believe it is. I didn't want to try but I tried the 5 USD subscription too. (5 USD is a lot of money in Turkey😔 )

**Comment by StanGirard** [comment]
Sorry guys 😥 we will try to work something out so that you can try without paying. Bare with us the project is only a week old

**Comment by imperorrp** [comment]
> Sorry guys 😥 we will try to work something out so that you can try without paying. Bare with us the project is only a week old

That would be pretty helpful! Maybe using open-source models, like through integrating GPT4All and running Quivr locally?
