### ISSUE TITLE
[BUG] AAU, new chats should be displayed in the chatlist when I send my first message

### ISSUE THREAD

**Issue by lamiabnn** [StanGirard/quivr#1100]
# How to reproduce: 
- Go to chat page
- Send message in a blank new chat
--> THe chat is not added to the chat list immediately
- If i click on "New chat", then I arrive on a new chat and I can't go back to previous chat without refreshing so that it appears on the chat list

New chat is not added to chat list when clicking on ‘New chat’ button (need to reload)

# Validation:
- Go to chat page
- Start chatting
- Check that the chat name appears in the chats list

**Comment by GORGUI1** [comment]
Bonjour,
Quand je télécharge un fichier csv, le chatbot n'arrive pas à lire tous les tableaux du fichier. Qui peut m'aider là-dessous ?

**Comment by mamadoudicko** [comment]
Salut @GORGUI1 ,

Peux-tu créer un nouveau pour le problème rencontré stp ? 

Merci
