### ISSUE TITLE
[UX Upload] 2.b AAUser, I can upload a file with a new UX by clicking on enter or by clicking on the send in the FeedBrainCommandBar

### ISSUE THREAD

**Issue by mamadoudicko** [StanGirard/quivr#1108]
# Epic

https://github.com/StanGirard/quivr/issues/849

# Functional

- Update feeding documents URL (icon by file type)
- Update supported types in the DnD
- Config the send button to submit feeding content on click (crawling + documents)
- Trim documents name

### Tech

- [] To-do

### Tests

- [] it ...

### Validation Checks

- Go to chat page
- Click on plus button on left
- Add documents to upload
- Check that added documents display is correct
- Check that name is trimmed 
- Add some urls to crawl
- Click on submit button and check that all contents have been successfully crawled

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/1112

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/issues/1108

**Comment by lamiabnn** [comment]
Cannot submit when clicking on enter
