### ISSUE TITLE
[Feature request] I'd like the sources that Quivr referred to, to get the answer

### ISSUE THREAD

**Issue by Darkshadenl** [StanGirard/quivr#1121]
### DESCRIPTION. 
I've been uploading parts of my journal to Quivr. When I ask questions, I wonder which journal file it based itself on. 
What files is he referencing? 

### RATIONALE. 
For research purposes. Quivr is not going to replace files, but it's going to help us find connections in the data that we wouldn't be able to find without Quivr. If I can't go back from connection the connection that Quivr found to the file(s) which it bases itself on, it's not of much use in any serious situations. 

A simple example:
In the case of a journal.

User: "what lessons did I learn in december of 2022?"
Quivr: "bla bla lesson blabla"

User wants to read the files. Can't blindly trust AI. 
Can't find it, because there's a 100 files in december of 2022.

### IMPLEMENTATION. 
We might be able to tag files with metadata somehow, but honestly I don't know.
Bing chat has a reference feature though.

**Comment by mgoann** [comment]
this idea is very good

**Comment by mgoann** [comment]
This is a great feature, I hope the official can support it.
