### ISSUE TITLE
[BUG] AAU, when I upload a file or I crawl a website I have an unclear error message

### ISSUE THREAD

**Issue by lamiabnn** [StanGirard/quivr#1123]
Example of message

![Image](https://github.com/StanGirard/quivr/assets/143498502/55ec3669-545c-40f7-a146-66351c39638a)

![Image](https://github.com/StanGirard/quivr/assets/143498502/9d42ae5c-8b46-4a0b-bebf-03b0911155f6)

One of the possible causes is a timeout, and the document is actually uploaded on the brain

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/1166

**Comment by mamadoudicko** [comment]
Celery workers are coming soon. This will solve axios timeout issues since long request will be handled asynchronously
