### ISSUE TITLE
[BUG], AAU when I delete a file, I have an error message and the file is not deleted

### ISSUE THREAD

**Issue by lamiabnn** [StanGirard/quivr#1124]
When I test it, sometimes it works, sometimes not

![Image](https://github.com/StanGirard/quivr/assets/143498502/efaf6e95-2766-47b7-aa28-f80249f880b7)

**Comment by matthieujacq** [comment]
Hello! Can't reproduce.


![Image](https://github.com/StanGirard/quivr/assets/67386567/99415076-1c08-422e-9daf-e70286b19b65)
