### ISSUE TITLE
[Epic]we need a system where the ai can back up the sources and pinpoint the data i feed. when i ask him a guestion.

### ISSUE THREAD

**Issue by dality17** [StanGirard/quivr#1138]
# The why: we need a system where the ai can back up the sources and pinpoint the data i feed. when i ask him a guestion.

why do we need this function? 
create a system where the ai can detect the page number of the word file or pdf file. So if we ask a guestion it wil always answer guestion and back up the sources.
 And tell us exacly where it is written. on the file. so we can look it up for ourself.

chatpdf.com has this system and it works like a charm because you feel much much secure knowing it answer based on the files you feed. but also you can look it up for youself and pin point the answer. for example lets say you feed him 15 pdf files. and you have also 3 important filed that is related to my guestion.  you ask him  if he give a summary based on the guestion i gave  he wil pinpoint all 3 files and give me the source name of the file.  and the page number .  this wil prevent artificial hallucination. and preventing me for writing wrong info because i can look it up.

**Comment by Darkshadenl** [comment]
Seems like the same issue: https://github.com/StanGirard/quivr/issues/1121
