### ISSUE TITLE
How to provide comprehensive and complete self built services and unbind Supabase and Openai

### ISSUE THREAD

**Issue by hktalent** [StanGirard/quivr#114]
# How to provide comprehensive and complete self built services and unbind Supabase and Openai？
* 1. How to build a local database to replace Supabase
* 2. Local self built other services to replace OpenAI

After all, there are many data and documents that are relatively private and cannot be sent to servers on Openai or Supabase

**Comment by StanGirard** [comment]
We are looking at a privateGPT integration but they are not ready yet for a clean integration. 

It is not a package yet. 


For supabase I added a postgresql vector store to the roadmap

**Comment by hbakhtiyor** [comment]
maybe these projects have clean integration 
https://github.com/PromtEngineer/localGPT
https://github.com/jmorganca/ollama
