### ISSUE TITLE
[frontend]: chat feature is not mobile responsive

### ISSUE THREAD

**Issue by Diya116** [StanGirard/quivr#1145]
frontend

. chat section is not mobile-responsive
. dark mode  color issue

**Comment by bmsptra24** [comment]
Hi @Diya116,

I noticed the issue #1145 related to mobile responsiveness in the chat feature of this project. It also involves a problem with colors in dark mode. I'm interested in helping to resolve this issue.

Before I begin, are there any specific guidelines I should follow in addressing it? I want to make sure that my contribution aligns with the project's vision and fixes the existing issues.

Thank you!
