### ISSUE TITLE
Responses generate no more than ~1300 characters

### ISSUE THREAD

**Issue by sanjayws** [StanGirard/quivr#1146]
Please try to be as detailed as possible in your report. Include information on

- Your Operating System - Self-hosted on Ubuntu 22 with 16 cores, 16GB Ram and 1TB SSD, local LLM=False
- Your Docker and Docker Compose versions - Docker 24.0.6, Docker Compose 1.25.0
- Your Supabase version and setup - Hosted Free tier, all related functions are working fine
- Detailed steps to reproduce the issue

Hello, thank you for this project. I got it working well an even exposed it via internet perfectly fine. However, it cannot generate responses more than 1.4-1.5k characters regardless of any model, including Turbo16k or the paid GPT4. I've set the setting on both brain and chat level and the output is consistently that size, no matter.

So far i can't really find issues related to this problem or perhaps i could be using some alien term that none uses to report on. Appreciate any help.

Thank you.

**Comment by sanjayws** [comment]
A bit of testing scenario, i uplaoded this file:
[100text.txt](https://github.com/StanGirard/quivr/files/12572869/100text.txt)

It is random words generated by ChatGPT.

So i created a BRAIN called SizeTesting and set the configuration of the brain as such:
![image](https://github.com/StanGirard/quivr/assets/25242465/6888aca4-72eb-4bee-9bdd-7e70c57524b0)

And while in the chat as such (after initial chat, to reconfirm, i set it as below):
![image](https://github.com/StanGirard/quivr/assets/25242465/554df4a6-dcf4-4104-9e27-115a83488cf2)

But the output is about only that much, approximately :
![image](https://github.com/StanGirard/quivr/assets/25242465/e02dffea-b766-42d6-9024-1edb0c980fdc)

**Comment by commandodev** [comment]
I just signed up today and I'm seeing something similar. My response cuts off in the same way as this.

**Comment by sanjayws** [comment]
@StanGirard @mamadoudicko appreciate some light on the matter, thank you so much.
