### ISSUE TITLE
[Issue] Migration error

### ISSUE THREAD

**Issue by chrisoei** [StanGirard/quivr#1167]
I did a git pull today and got commit 2b4c3ecbbcd00a6a9650de653301eb08068bd881. I was previously on git commit 56bde0976e7d613db8c8e226e2640889516a1bc9 (which worked just fine). I ran the migration script, which failed as follows:
```
Last migration executed: 202308181004030_rename_users_table
Running migration 202308217004800_add_public_prompts_examples.sql
INSERT 0 8
INSERT 0 1
psql:scripts/202308217004800_add_public_prompts_examples.sql:55: WARNING:  there is no transaction in progress
COMMIT
ERROR:  column "id" of relation "migrations" does not exist
LINE 1: INSERT INTO migrations (id) VALUES ('202308217004800_add_pub...
                                ^
Running migration 20230906151400_add_notifications_table.sql
BEGIN
CREATE TABLE
INSERT 0 1
COMMIT
ERROR:  column "id" of relation "migrations" does not exist
LINE 1: INSERT INTO migrations (id) VALUES ('20230906151400_add_noti...
                                ^
Running migration 202309127004032_add_user_limits.sql
CREATE TABLE
INSERT 0 1
psql:scripts/202309127004032_add_user_limits.sql:19: WARNING:  there is no transaction in progress
COMMIT
ERROR:  column "id" of relation "migrations" does not exist
LINE 1: INSERT INTO migrations (id) VALUES ('202309127004032_add_use...
                                ^
Migration script completed.
```
I'm running Supabase as hosted by Supabase (not a local install).

I think the error arises from line 62 of migration.sh:
```
            PGPASSWORD=${DB_PASSWORD} psql -h "${DB_HOST}" -p "${DB_PORT}" -d "${DB_NAME}" -U "${DB_USER}" -c "INSERT INTO migrations (id) VALUES ('${MIGRATION_ID}');"
```
My migrations table doesn't have an id field, and I can't find a migration that adds an ID field to the migrations table.

**Comment by Godsing** [comment]
Although this error does not affect the final result (I checked the migrations table in the supabase dashboard and the record was inserted correctly), I also think this is an error and the `id` should be changed to `name` as it is in [tables.sql](https://github.com/StanGirard/quivr/blob/be7acf052bb73175c99f45fcaf4399473842b288/scripts/tables.sql#L226C3-L226C3)  - I have verified it, and this can avoid the error.
