### ISSUE TITLE
AAU i should not have theses bugs

### ISSUE THREAD

**Issue by mamadoudicko** [StanGirard/quivr#1199]
- [x] Add a hover on “upload” button to know whats the use
- [x] UX Upload -> Remove tle ” Upload”
- [x] @default brain -> reuploads
- [x] Delete userBrain from local cache
- [x] When changing the params of a chat, on enter, should not send empty msg
- [x] Chat is not ordered by creation date (-> choose a name for the file with openai ?)
- [x] Show brain name instead of brain_id in the hover “file xx has been succe....”
- [x] Change wording:
- “filesUploading”:  “Your files are being processed, please wait before asking a question about them”, -> “feedingBrain”: “You newly added knowledge is being processed, you can keep chatting in the meantime !”
- “add_content_card_button_tooltip”: “Add knowledge to a brain”

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/issues/1173

**Comment by mrshehzad1** [comment]
how can i implement this? i am not an expert in coding and I am getting the same error

**Comment by mrshehzad1** [comment]
> * [x]  Add a hover on “upload” button to know whats the use
> * [x]  UX Upload -> Remove tle ” Upload”
> * [x]  @default brain -> reuploads
> * [x]  Delete userBrain from local cache
> * [x]  When changing the params of a chat, on enter, should not send empty msg
> * [x]  Chat is not ordered by creation date (-> choose a name for the file with openai ?)
> * [x]  Show brain name instead of brain_id in the hover “file xx has been succe....”
> * [x]  Change wording:
> * “filesUploading”:  “Your files are being processed, please wait before asking a question about them”, -> “feedingBrain”: “You newly added knowledge is being processed, you can keep chatting in the meantime !”
> * “add_content_card_button_tooltip”: “Add knowledge to a brain”

Can you help, please?

**Comment by mamadoudicko** [comment]
@mrshehzad1 Thanks for the intent!

These bugs have already been fixed in [this PR](https://github.com/StanGirard/quivr/pull/1201)
