### ISSUE TITLE
[BUG]Upload or delet files in the brain is not working properly. It shows success, but in reality, it does not take effect.

### ISSUE THREAD

**Issue by xiaoxuan220** [StanGirard/quivr#1204]
Version: v0.0.75

Upload or deleti files in the brain is not working properly. It shows success, but in reality, it does not take effect.

**Comment by dpaulgp** [comment]
Same error, online too

**Comment by fadi-alkh** [comment]
Same, after uploading successfully in the chat, the knowledge tab displays: Oh No, Your Brain is empty.
