### ISSUE TITLE
[Private/Public Brains]  4- AAUser, I can unsubscribe from a brain

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#1212]
# Epic

#963 

# Functional

-In the settings section, add "Unsubscribe from brain" instead of the « delete brain » 

### Tech

- in `BrainManagementTabs/BrainManagementTabs.tsx`, Change delete button to conditionally render `unsubscribe` or `delete` button
- Rename ConfirmationDeleteModal to DeleteOrUnsubscribeConfirmationModal
- Update DeleteOrUnsubscribeConfirmationModal interface
- Update translations
- In subscription_routes add `/POST  "/brains/{brain_id}/unsubscribe"`: remove user from brain_user table
- Redirect to `/brains-management` when cannot get brain from back...

### Tests

- [] it ...

### Validation Checks
- Go to brain management page
- Subscribe to a brain
- Try to chat with and check everything is working
- Go to management page and unsubscribe from it
- Check that confirmation modal content is relevant
- Check that there is no "Delete" button but just "Unsubscribe from brain"
- Unsubscribe and check everything goes right
- Go Check that brains list go updated and no longer contains unsubscribed brain

**Comment by chloeimb** [comment]
Hi there, I would like to work on this if possible.
