### ISSUE TITLE
[Private/Public Brains] 5-AAUser, I can set my brain on private after setting it on public.

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#1213]
# Epic

#963 

# Functional

- The owner can set brain access to private in the settings tab (can see a toggle)
- Confirmation modal to confirm access change to private
- Refetch brain list on access change
- Cancel all subscriptions (unless owner)
- In db change brain status to private
- New public brains are not tagged
- Check that user has access to brain while chatting

### Tech

- [] To-do

### Tests

- 

### Validation Checks

- The brain won’t be in the brain library section anymore
- Check that brain is not in your brains list (chat, upload and brains management) unless you're the owner
- Check that you can share brain to other users once it becomes private

**Comment by Chloeroumengas** [comment]
https://www.loom.com/share/6c9a78a6a29b4e2484e76860d270a45f?sid=115a84e6-33c1-441b-8999-6e4ce48b2bf1

Going from private to public doesn't work @mamadoudicko

**Comment by mamadoudicko** [comment]
Modification should be saved by clicking on SAVE button

**Comment by Chloeroumengas** [comment]
AAUSer, when I click on the button, the change is made. No need to click on save. 

![Image](https://github.com/StanGirard/quivr/assets/138109838/d24428b3-33d8-4d39-81ad-e4b27d155a2f)
