### ISSUE TITLE
[Issue] How to upload pdf files with size > 1M? 

### ISSUE THREAD

**Issue by zsp0901** [StanGirard/quivr#1224]
I just tested and verified Quivr does not take care and upload >1m pdfs. 

I tried to modify 'file.py' but with no change.

I think it would be unreasonale to have this limitation since most of the files are >1M.

Many thanks!

**Comment by bizrockman** [comment]
Where you see this size limit exactly? I wonder why I am not getting an error of some sort. 

I have an issue with pdfs myself. Maybe it is the error with that limit, but the Frontend to not get any info and the console log also giving no clue what is not working.

**Comment by zsp0901** [comment]
> Where you see this size limit exactly? I wonder why I am not getting an error of some sort.
> 
> I have an issue with pdfs myself. Maybe it is the error with that limit, but the Frontend to not get any info and the console log also giving no clue what is not working.
> 
> Did you tested it with a smaller pdf?

Yes, I tested sereral times by selecting multiple pdfs with > or < 1m. As a result, I found that only pdfs < 1m were uploaded in the dialog. In Supabase, I can also see that only pdfs < 1m were there.

Even I only tried to upload 1 pdf with > 1m each time, it still failed. Consequently, the AI gave me negative results when I asked it with "According to the conext provided, ....".

No clue or error was given during the whole process.

**Comment by StanGirard** [comment]
On the webapp it should be updated now :)

**Comment by StanGirard** [comment]
https://github.com/StanGirard/quivr/pull/1235

**Comment by zsp0901** [comment]
> On the webapp it should be updated now :)

Thanks a lot!!
