### ISSUE TITLE
[Improvement UX Layout ]

### ISSUE THREAD

**Issue by Chloeroumengas** [StanGirard/quivr#1231]
# The what  

Change the layout of the pages: Remove navbar, clear left side bar from top (logo at top) to bottom (User). 

## A- Chat Page 

As a user, I notice that the chat occupies the entire screen, starting from the top. I can see a sidebar on the left that includes the logo and a 'sidebar' icon. There is no more icone on the top right of the page

![Image](https://github.com/StanGirard/quivr/assets/138109838/bdbc44bc-ceec-4fa1-a370-57419cfd1bc0)

I observe that the Brain logo is displayed next to 'My Brain,' and when I click on it, it redirects me to the Brain Management page.

I also see my username and profile picture next to it. If I click on my username, it takes me to the User Profile page. 

I can see a new icon next to the logo : When I click on the sidebar icon, the sidebar disappears, and the chat along with the aligned question bar occupy the entire screen.

![Image](https://github.com/StanGirard/quivr/assets/138109838/d0f9a412-7a90-44f5-b38b-f3a0d3fc73fb)

If I click on the sidebar icon again, the sidebar reappears

## B- Brains management Tab

**Comment by gozineb** [comment]
# The how 

A.0 AAU, I can set the language + light preferences in the user page
A.1. AAU, I see the "My brains" and "user"  at the bottom of the left bar ( no more navbar)
-> What about discord ? github ? etc ?
A.2. AAU, I can see a clear responsive sidebar
1.3.AAU, I see the chat taking the whole space



B.1 AAU, when i'm on brains management or brain library I see the "user" at  the bottom of the left bar ( no more navbar)
- "Add new brain" goes up in the leftbar
B.2 AAU, I can see the tabs in brains management taking all the space left

**Comment by gozineb** [comment]
https://github.com/users/StanGirard/projects/5/views/2?pane=issue&itemId=39795748
