### ISSUE TITLE
[Bug]: Cannot choose other model than gpt-3.5-turbo

### ISSUE THREAD

**Issue by forestmaster** [StanGirard/quivr#1239]
### What happened?

I cannot choose another model other than gpt-3.5-turbo although the Open AI Key is correctly provided in the brain management and in the .env file.

**Comment by forestmaster** [comment]
Ah, thank you so much for the super quick response! I thought I remember that in earlier versions I could also choose the gpt-4 model (without changes in the code), that's why I asked.

**Comment by StanGirard** [comment]
In the user_settings table add the models you want access to. 

Sorry about that didn't do demo

**Comment by B0rrA** [comment]
gpt-4 is no longer visible as a selectable model on brain settings of quivr.app, even when OpenAI key was provided, i think that is what @forestmaster is refering to

**Comment by marshmallowcreme** [comment]
> gpt-4 is no longer visible as a selectable model on brain settings of quivr.app, even when OpenAI key was provided, i think that is what @forestmaster is refering to

Yes, I have this problem too. Cannot select GPT-4 on quivr.app/chat 

I tried to run the app locally but I get a Network Error when creating a brain. So I was hoping the web app would work.

**Comment by marshmallowcreme** [comment]
Actually, I got Quivr running locally via Docker and still only had access to gpt-3.5-turbo. However, I did what @StanGirard said and added it to the models in the user_settings table and was able to select gpt-4 from the frontend interface.

**Comment by B0rrA** [comment]
Yes, locally is working with that configuration, so maybe it has to make gpt-4 available on quivr.app too

**Comment by riccardopandolfijakala** [comment]
> Actually, I got Quivr running locally via Docker and still only had access to gpt-3.5-turbo. However, I did what @StanGirard said and added it to the models in the user_settings table and was able to select gpt-4 from the frontend interface.
@marshmallowcreme 

How did you modified the table?

**Comment by zentryb** [comment]
Any new info on this? A selection in the brain for ChatGPT 4 on the $14.99 subscription.
