### ISSUE TITLE
[Bug]: Backend error

### ISSUE THREAD

**Issue by rainstorm-studio-australia** [StanGirard/quivr#1250]
### What happened?

I have this issue.
Do you have any idea how to fix it?
![image](https://github.com/StanGirard/quivr/assets/19511189/0e21a58a-46a2-48d1-9e08-9aee7099da83)

**Comment by StanGirard** [comment]
Hey @rainstorm-studio-australia  you forgot to run the migrations on your database :) 

Please run the scripts with the migration script found in the readme

**Comment by rainstorm-studio-australia** [comment]
HI @StanGirard 

PostgreSQL and Charm-gum are already installed on Windows 11

I did run the scripts
![image](https://github.com/StanGirard/quivr/assets/19511189/ffbbe52c-7ea3-4805-8155-087171ada09d)

Is this correct?
