### ISSUE TITLE
[Improvement UX Chat ] A.1. AAU, I see the "My brains" and "user" at the bottom of the left bar ( no more navbar)

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#1257]
# Epic

#1231 

# Functional

a.Replace brain icon in the navbar with a button "My brains" redirecting on click to /brains-management
b.Replace the user icon with a button : 
- Leave space for image (use gravatar in next ticket)
- Display email (trimmed according to the size of the left bar)

c. Remove both brain icon and user icon from navbar
d. Remove navbar from chatpage

![Image](https://github.com/StanGirard/quivr/assets/100568984/3d7cba9b-72b4-4676-99da-8691a5f18830)

### Tech
- [x] understand the structure of the left bar when the chat is opened
- [x] find the place where I will inject the two buttons (between the list of the chat history and the footer with the social icons)
- [x] inject the raw buttons
- [x] display them in column
- [x] add a separator
- [x] create a dedicated component for those two buttons
- [x] style as two big buttons
- [x] style the inside of the buttons
- [x] move nav items to the appropriate folders
- [x] fetch user email
- [x] remove navbar from chatpage
- [x] trim email if necessary

## Schema
- [] To-do

### Tests

- [] it ...

**Comment by Chloeroumengas** [comment]
<img width="1435" alt="image" src="https://github.com/StanGirard/quivr/assets/138109838/3d9f6956-56c0-4437-96c0-8ba598bd5b66">

- [ ] There is a space at the end of the page that shouldn't exists. 

- [ ] Maw width of the sidebar should be the same as in brain management 

- [ ] Less padding around buttons 

- [ ] Border radius is the same as other buttons. 

<img width="269" alt="image" src="https://github.com/StanGirard/quivr/assets/138109838/144f713a-867f-4e5e-8f1d-cae03ee3cd28">

- [ ] The buttons my brains and user should have the same radius as the other buttons
