### ISSUE TITLE
Mobile website

### ISSUE THREAD

**Issue by 618T** [StanGirard/quivr#126]
![Screenshot_2023-05-23-08-28-39-471_com.opera.browser.jpg](https://github.com/StanGirard/quivr/assets/93539314/4b64d16f-5594-417d-9b6a-ef2db0f5711e)

The navigation bar...

It looks nice in the desktop site view but it looks kinda bad in the mobile version.

**Comment by StanGirard** [comment]
Thanks 🙏 

I'm not an experienced web dev 😂 would you be keen on opening a pull request ?

**Comment by 618T** [comment]
Sorry, I'm new in GitHub

I don't even know what is a pull request
Is it a thing for helping other people's projects or something? If it's, please tell me how can I do that.

Please let me know
