### ISSUE TITLE
[Bug]: CORS header 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by schoenix** [StanGirard/quivr#1280]
### What happened?

If I want to go to http://somehost:3000/user I got an eternal spinner and the web console printed me this error "CORS header 'Access-Control-Allow-Origin' missing". I tried it with localhost and with another computer and with firefox and chromium. Meanwhile the chat works.

### Relevant log output

```bash
Access to XMLHttpRequest at 'http://192.168.20.124:5050/user' from origin,'http://192.168.20.124:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by schoenix** [comment]
I did it, but I still got

"9530-bd297a4f57801ca6.js:1 
 GET https://cdn.growthbook.io/api/features/%3Cignore-me-or-change-me%3E 400 (Bad Request)
6269-dbf6ac675356bb15.js:1 
 GET http://192.168.20.124:3000/_vercel/insights/script.js net::ERR_ABORTED 404 (Not Found)
9222-7e071601b78b146c.js:6 
 GET http://192.168.20.124:3000/%3Cignore-me-or-change-me%3E 404 (Not Found)
7621-972a21b3e52680c5.js:1 
 POST https://api.june.so/sdk/identify 401 (Unauthorized)
user:1 Access to XMLHttpRequest at 'http://192.168.20.124:5050/user' from origin 'http://192.168.20.124:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
9222-7e071601b78b146c.js:6 
 GET http://192.168.20.124:5050/user net::ERR_FAILED 500 (Internal Server Error)
user:1 Access to XMLHttpRequest at 'http://192.168.20.124:5050/brains/default/' from origin 'http://192.168.20.124:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
9222-7e071601b78b146c.js:6 
 GET http://192.168.20.124:5050/brains/default/ net::ERR_FAILED 500 (Internal Server Error)"

**Comment by zoernert** [comment]
Struggling with the same issue.

- There is no Response header present at all.
- It seems as the `cors.py` declaration is not used.
- Trying to figure out if some sort of build caching might have caused this issue on my side.

**Comment by chenmnkken** [comment]
I got the same issue too, and I already set the web domain in `cors.py`.

**Comment by jm-rizkallah** [comment]
Yeah same here i'm not sure the cors.py is taken into consideration

**Comment by raisindetre** [comment]
For reference, first encountered this issue using 0.0.81 #fa3412b7 on OSX 13.5.1. v0.0.81 introduced CORS issues and failure to retrieve chat responses/brains config data. v0.0.82 is the same but with excessive backend API calls and rapid UI refreshes in Brains config screens. Same issues are observed in HEAD (> v0.0.88, #f13f08c5). Have not tested tagged releases between 0.0.82 and 0.0.88 but assuming issue persists through them.

**Comment by zoernert** [comment]
Checkout the `frontend/next.config.js` there look at the  `ContentSecurityPolicy`. I assume this is the root cause if frontend is run as "local" even if it is on another server.

**Comment by raisindetre** [comment]
Possibly but I also found that 0.0.81 introduced a backend error caused by the last_update property of the BrainEntity not being set.
```backend-core  | INFO:     192.168.65.1:37299 - "GET /user HTTP/1.1" 500 Internal Server Error
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
...
backend-core  |   File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 341, in __init__
backend-core  |     raise validation_error
backend-core  | pydantic.error_wrappers.ValidationError: 1 validation error for BrainEntity
backend-core  | last_update
backend-core  |   field required (type=value_error.missing)

I edited `quivr/backend/models/brain_entity.py` lines 18 and 44 from `last_update: str` to `last_update: str = ""` and rebuilt the Docker image and was able to make successful API calls to retrieve Brain data and chat without CORS errors.

So, it seems like backend errors in code are also triggering the CORS errors. As a side note I noticed other errors in the backend log after doing this so I wouldn't recommend it as a fix.

**Comment by zoernert** [comment]
> So, it seems like backend errors in code are also triggering the CORS errors. 

I can confirm this. Had backend errors with file uploads and CORS issue appeared again.

**Comment by mamadoudicko** [comment]
Hi here 👋🏽,

Are you still facing this ?

If yes, do you have an error on back side ?

Thanks

**Comment by alex-crr** [comment]
Hey, I get the same error when trying to send a prompt. Usually it ends up being recorded in Supabase, but I get an empty assistant answer. I also seem to get a POST 401 error, but I'm not sure as where it comes from.


> Hi here 👋🏽,
> 
> Are you still facing this ?
> 
> If yes, do you have an error on back side ?
> 
> Thanks

How should I check If there is any backend error?

**Comment by MeTaNoV** [comment]
> Hi here 👋🏽,
> 
> Are you still facing this ?
> 
> If yes, do you have an error on back side ?
> 
> Thanks

Yes, it seems there are still CORS issues around. Here some logs from the backend:

```
backend-core  | INFO:     172.21.0.2:37624 - "GET /brains/default/ HTTP/1.1" 500 Internal Server Error
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/venv/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core  |     raise exc
backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core  |     raise exc
backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core  |     await self.app(scope, receive, sender)
backend-core  |   File "/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core  |     raise e
backend-core  |   File "/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/venv/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend-core  |     raw_response = await run_endpoint_function(
backend-core  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/venv/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend-core  |     return await dependant.call(**values)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/routes/brain_routes.py", line 59, in retrieve_default_brain
backend-core  |     brain = get_default_user_brain_or_create_new(current_user)
backend-core  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/repository/brain/get_default_user_brain_or_create_new.py", line 12, in get_default_user_brain_or_create_new
backend-core  |     default_brain = get_user_default_brain(user.id)
backend-core  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/repository/brain/get_default_user_brain.py", line 21, in get_user_default_brain
backend-core  |     return get_brain_by_id(brain_id)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/repository/brain/get_brain_by_id.py", line 9, in get_brain_by_id
backend-core  |     return supabase_db.get_brain_by_id(brain_id)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/models/databases/supabase/brains.py", line 326, in get_brain_by_id
backend-core  |     return BrainEntity(**response[0])
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-core  | pydantic.error_wrappers.ValidationError: 1 validation error for BrainEntity
backend-core  | brain_type
backend-core  |   field required (type=value_error.missing)
backend-core  | INFO:     172.21.0.2:37634 - "GET /user/identity HTTP/1.1" 200 OK
```

**Comment by MeTaNoV** [comment]
> > Hi here 👋🏽,
> > Are you still facing this ?
> > If yes, do you have an error on back side ?
> > Thanks
> 
> Yes, it seems there are still CORS issues around. Here some logs from the backend:
> 
> ```
> backend-core  | INFO:     172.21.0.2:37624 - "GET /brains/default/ HTTP/1.1" 500 Internal Server Error
> backend-core  | ERROR:    Exception in ASGI application
> backend-core  | Traceback (most recent call last):
> backend-core  |   File "/venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
> backend-core  |     result = await app(  # type: ignore[func-returns-value]
> backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> backend-core  |   File "/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
> backend-core  |     return await self.app(scope, receive, send)
> backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> backend-core  |   File "/venv/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
> backend-core  |     await super().__call__(scope, receive, send)
> backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
> backend-core  |     await self.middleware_stack(scope, receive, send)
> backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
> backend-core  |     raise exc
> backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
> backend-core  |     await self.app(scope, receive, _send)
> backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
> backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
> backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
> backend-core  |     await self.app(scope, receive, send)
> backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
> backend-core  |     raise exc
> backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
> backend-core  |     await self.app(scope, receive, sender)
> backend-core  |   File "/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
> backend-core  |     raise e
> backend-core  |   File "/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
> backend-core  |     await self.app(scope, receive, send)
> backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
> backend-core  |     await route.handle(scope, receive, send)
> backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
> backend-core  |     await self.app(scope, receive, send)
> backend-core  |   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
> backend-core  |     response = await func(request)
> backend-core  |                ^^^^^^^^^^^^^^^^^^^
> backend-core  |   File "/venv/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
> backend-core  |     raw_response = await run_endpoint_function(
> backend-core  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> backend-core  |   File "/venv/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
> backend-core  |     return await dependant.call(**values)
> backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> backend-core  |   File "/code/routes/brain_routes.py", line 59, in retrieve_default_brain
> backend-core  |     brain = get_default_user_brain_or_create_new(current_user)
> backend-core  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> backend-core  |   File "/code/repository/brain/get_default_user_brain_or_create_new.py", line 12, in get_default_user_brain_or_create_new
> backend-core  |     default_brain = get_user_default_brain(user.id)
> backend-core  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> backend-core  |   File "/code/repository/brain/get_default_user_brain.py", line 21, in get_user_default_brain
> backend-core  |     return get_brain_by_id(brain_id)
> backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
> backend-core  |   File "/code/repository/brain/get_brain_by_id.py", line 9, in get_brain_by_id
> backend-core  |     return supabase_db.get_brain_by_id(brain_id)
> backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> backend-core  |   File "/code/models/databases/supabase/brains.py", line 326, in get_brain_by_id
> backend-core  |     return BrainEntity(**response[0])
> backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> backend-core  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> backend-core  | pydantic.error_wrappers.ValidationError: 1 validation error for BrainEntity
> backend-core  | brain_type
> backend-core  |   field required (type=value_error.missing)
> backend-core  | INFO:     172.21.0.2:37634 - "GET /user/identity HTTP/1.1" 200 OK
> ```
> 
> PS: Using the Traefik integration for a deployment on a server, and added the configured FRONTEND URL in cors.py

So, it seems that the CORS issue was a side effect of the last migrations that didn't run properly... After running the migration manually in Supabase, the CORS issue on the FrontEnd disappeared! (At least for me)

**Comment by Greyvend** [comment]
I'm still facing this issue.

**Comment by MeTaNoV** [comment]
> I'm still facing this issue.

check error message in your backend logs, it is probably due to some DB issues, like the one I had (see previous messages)

**Comment by melfebulu** [comment]
oh, the same error....    

> Access to XMLHttpRequest at 'http://192.168.237.68:5050/brains/default/' from origin 'http://192.168.237.68:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> backend-core  | The above exception was the direct cause of the following exception:
backend-core  | 
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-core  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-core  |     await app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
backend-core  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-core  |     await app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
backend-core  |     raise e
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
backend-core  |     raw_response = await run_endpoint_function(
backend-core  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
backend-core  |     return await dependant.call(**values)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/modules/user/controller/user_controller.py", line 37, in get_user_endpoint
backend-core  |     user_settings = user_daily_usage.get_user_settings()
backend-core  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/models/user_usage.py", line 40, in get_user_settings
backend-core  |     request = self.supabase_db.get_user_settings(self.id)
backend-core  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/models/databases/supabase/user_usage.py", line 178, in get_user_settings
backend-core  |     .execute()
backend-core  |      ^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 57, in execute
backend-core  |     r = self.session.request(
backend-core  |         ^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 814, in request
backend-core  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
backend-core  |     response = self._send_handling_auth(
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
backend-core  |     response = self._send_handling_redirects(
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
backend-core  |     response = self._send_single_request(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
backend-core  |     response = transport.handle_request(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
backend-core  |     with map_httpcore_exceptions():
backend-core  |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
backend-core  |     self.gen.throw(typ, value, traceback)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
backend-core  |     raise mapped_exc(message) from exc
backend-core  | httpx.ConnectError: [Errno -2] Name or service not known

**Comment by Amirjab21** [comment]
still a problem for me

**Comment by piyush-saurabh** [comment]
Self hosting with custom domain is a pain. I had to do the following changes to make it work. 

**Step 1**
Update the environment variables in `.env`
```
NEXT_PUBLIC_BACKEND_URL=https://subdomain-server.mydomain.com # in reverse proxy, map it to port 5050.
NEXT_PUBLIC_SUPABASE_URL=https://subdomain-db.mydomain.com # in reverse proxy, map it to port 54321.
NEXT_PUBLIC_CMS_URL=https://subdomain.mydomain.com
NEXT_PUBLIC_FRONTEND_URL=https://subdomain.mydomain.com # important for CORS

```

**Step 2**
Environment variables defined in `.env` for `frontend` service in `docker-compose.yml` will not take effect untill we rebuild the the container. I appended the following environment variables at the end of`frontend/Dockerfile`

```
ARG NEXT_PUBLIC_AUTH_MODES
ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_CMS_URL
ARG NEXT_PUBLIC_FRONTEND_URL

ENV NEXT_PUBLIC_AUTH_MODES=$NEXT_PUBLIC_AUTH_MODES
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_CMS_URL=$NEXT_PUBLIC_CMS_URL
ENV NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD ["node", "server.js"]
```

**Step 3**
Import all the environment variables in the current terminal session. This is important before running `docker compose`.
```
export $(grep -v '^#' .env | xargs)
```

**Step 4**
Rebuild the project. (this will take some time)
```
docker compose up --build
```
