### ISSUE TITLE
[Feature]: Custom prompts and being able to save them

### ISSUE THREAD

**Issue by JJRobertsSex30** [StanGirard/quivr#1289]
### The Feature

When I install quivr locally the "Custom Prompt" drop down box in create brain is empty and when using the online version there are a few options but even online I cannot see a way to save a new custom prompt

Where are the contents of this drop down stored and how do I added to the drop down and create my own custom prompts?

### Motivation, pitch

I would like to create a db of custom prompts

**Comment by JJRobertsSex30** [comment]
Thanks but is this ability to save custom prompts already actively available in the current UI or do I have to add it?

**Comment by sanjayws** [comment]
Custom prompts doesn't get saved after you've entered them.

**Comment by JJRobertsSex30** [comment]
Can the feature to save custom prompt to the db as you add them via the GUI be added?
