### ISSUE TITLE
[Bug]: What is the proper upgrade/migration process???

### ISSUE THREAD

**Issue by lugfug** [StanGirard/quivr#1290]
### What happened?

I was successfully using an install of Quivr, version 0.0.81 (in Docker desktop on macOS) installed on 09-21-2023 with a fresh/new Suppabase database. 

NOTE: I'm a paid user of Suppabase, and I have plenty of capacity in my account. 

All was functioning as expected in Quivr, with 30 PDF documents uploaded across 2 Brains.

I opened the Quivr web interface today 09-29-2023 and none of the brains OR user configurations are functional. Many errors are presented in the red error panels, the same as in the Docker console. 

I looked and Docker, discovering that `worker` and `flower` containers were repeatedly restarting, over and over and over and over and over and over and over and ... 

I double-checked Suppabase, and no errors were present. 

I did a Git Pull for my installation of Quivr and effectively upgraded to version 0.0.85 BUT with NO change in the errorring behavior displayed in the previously installed version.

With this upgrade to v0.0.85, the Web UI was different, and the restarting behavior was resolved ... obviously, the upgrade was "successful". 

HOWEVER, my Brains and the user configurations were still not accessible. Just as before the upgrade, many errors are presented in the red error panels, the same as in the Docker console. 

In hopes of fixing/isolating the issues, I installed Qrivr v0.0.85 and a different folder on my computer and connected it to my existing Suppabase database... AND... SAME issues persist. 

So now I have a brand new fresh install of Quivr v0.0.85 that can't use my existing Suppabase database.

What do you recommend I do to fix this issue? 

What is the proper upgrade/migration process??

How can such fragile behavior be mitigated and resolved???

**Comment by lugfug** [comment]
@dosu-bot do not reply to this message with general advice. ONLY reply if you have a specific resolution to the described issues with 90% confidence your recommendation will Fully Resolve the user's issue.

**Comment by StanGirard** [comment]
@lugfug Please run the migration script. There are migrations to be ran.

**Comment by kbekus** [comment]
@StanGirard sorry to jump in.... how does the migration script work? It seems to directly reference a postgreSQL database... however that database is hosted inside Supabase and is not directly accessible? Is there a config step I'm missing?

**Comment by lugfug** [comment]
> @lugfug Please run the migration script. There are migrations to be ran.

@StanGirard yeah, see that's the problem… How do you run the migration script? I know I'm missing something that's probably pretty obvious to most people… But I don't see the instructions or any sort of guidance on how to properly run the script.

I know you're doing your best and it's a great product, however, the documentation could use some improvement.

**Comment by kbekus** [comment]
@lugfug apologies in advance if I get the terminology wrong, I'm not familiar with Mac computers... can you open a terminal window or equivalent?  If so change into the cloned Quivr folder, you should see a migration.sh file. Run that. 
`./migration.sh`
It's step 4 in the installation guide.

**Comment by lugfug** [comment]
@kbekus Thanks for the guidance, I ran the `migration.sh` with all know-correct information. The script reported back `./migration.sh: line 52: psql: command not found` sooooooo.... yeah.  That wasn't helpful.

**Comment by StanGirard** [comment]
@lugfug read the readme ;) You need to install psql

**Comment by lugfug** [comment]
@lugfug Thank you for the guidance. On macOS 14.0 (23A344) I installed PostgreSQL 16 via Homebrew by running `brew install postgresql@16` which allowed the `./migration.sh` command to run the migration script, resulting in the following output.

`
Running migration 20230921160000_add_last_update_field_to_brain.sql
DO
INSERT 0 1
psql:scripts/20230921160000_add_last_update_field_to_brain.sql:23: WARNING:  there is no transaction in progress
COMMIT
ERROR:  column "id" of relation "migrations" does not exist
LINE 1: INSERT INTO migrations (id) VALUES ('20230921160000_add_last...
                                ^
`

Presumably, 🤷🏻‍♂️ this helped to resolve the underlying issues/behavior that I described in the first post of this thread.

I am now able to interact with my local Quivr docker instance. 

Hopefully, this thread helps others navigate the update/migration process. 

I love the usage of Quivr... however, I dread doing ANY updates to it because that process is NOT user-friendly and the documentation assumes a LOT of information/skill sets the end user must already possess. 

I'm back up and running... for now. 

Hopefully, future updates are smoother.

**Comment by winklr** [comment]
> @StanGirard Thank you for the guidance. On macOS 14.0 (23A344) I installed PostgreSQL 16 via Homebrew by running `brew install postgresql@16` which allowed the `./migration.sh` command to run the migration script, resulting in the following output.
> 
> `Running migration 20230921160000_add_last_update_field_to_brain.sql DO INSERT 0 1 psql:scripts/20230921160000_add_last_update_field_to_brain.sql:23: WARNING: there is no transaction in progress COMMIT ERROR: column "id" of relation "migrations" does not exist LINE 1: INSERT INTO migrations (id) VALUES ('20230921160000_add_last... ^`

I get the exact same error running the migration.sh script (MacOS 13.5, PgSql 14.9).
