### ISSUE TITLE
[Bug]: Cant select any other models except gpt3.5-turbo

### ISSUE THREAD

**Issue by sanjayws** [StanGirard/quivr#1294]
### What happened?

Using latest version 0.85 docker with completely new install and can't seem to select other models and i have GPT4 API key (paid).

![image](https://github.com/StanGirard/quivr/assets/25242465/a331d675-657e-4ae3-a372-a1a119328bb2)

Any help is greatly appreciated.

**Comment by sanjayws** [comment]
That solution didn't seem to work.

**Comment by geekaz01d** [comment]
@dosu-bot changing 

> export type Model = (typeof freeModels)[number] | (typeof paidModels)[number];
[...]
> Please note that you'll need to rebuild the application after making this change.
>This change will allow the Model type to include both free and paid models, thus enabling the selection of the "gpt-4" model.

>You can find this code in the [frontend/lib/types/brainConfig.ts](https://github.com/StanGirard/quivr/blob/main/frontend/lib/types/brainConfig.ts) file.

Changing this line of code and rebuilding did not result in any new options in the Model menu for Brain Settings for existing or new brains. Only gpt-3.5-turbo is available.

**Comment by mamadoudicko** [comment]
Probably fixed in https://github.com/StanGirard/quivr/pull/1590

**Comment by pseudobun** [comment]
> Probably fixed in #1590

I can choose only `huggingface/mistralai/Mistral-7B-Instruct-v0.1` and `gtp-3.5-turbo`. It still doesn't work with others even after the mentioned PR.

**Comment by eWizardII** [comment]
I am also experiencing the same issue too.

**Comment by justin007755** [comment]
@mamadoudicko Even I upgraded to latest version [v0.0.119](https://github.com/StanGirard/quivr/releases/tag/v0.0.119) I still couldn't select gpt-4, and only has gpt-3.5-turbo-16k, gpt-3.5-turbo-1106 and gpt-3.5-turbo. I noticed you said this gpt-4 supporting was already merged to version [v0.0.107](https://github.com/StanGirard/quivr/releases/tag/v0.0.107) , but I guess for some reason it was broken??? Cause I see you screen video showed gpt-4, so could you help fix this problem?
