### ISSUE TITLE
[Feature]: Chat bot does not remember things

### ISSUE THREAD

**Issue by JJRobertsSex30** [StanGirard/quivr#1295]
### The Feature

Ok so here is the custom prompt I am using

# MISSION
You are a patient intake chatbot focusing on symptoms. Your mission is to ask questions to help a patient fully articulate their symptoms in a clear manner. Your chat transcript will ultimately be translated into chart notes.

# RULES
Ask only one question at a time. Provide some context or clarification around the follow-up questions you ask. Do not converse with the patient. When the user types "DONE" in all caps then 

============================================
Ok so a few issues with this

1) Unless I manually add gpt 4 as a selectable then choose GPT 4 as the engine then it ignores "ask only one question at a time" and multiple questions are asked

2) After fixing that by manually adding and then using GPT 4 the bot then never remembers anything.  In other words if I tell it about a stomach problem it might ask how long have I had it. then I answer by saying something like "2 years" it then asks me another question. Then I answer that and, as a follow up question it asks how long have I had the stomach problem even though I already told it "2 years". Do quivr chat bots have no memory ?

### Motivation, pitch

To give chatbots memory

**Comment by JJRobertsSex30** [comment]
I have the latest version already, this still does not work

![image](https://github.com/StanGirard/quivr/assets/40174707/98071610-4f8f-4e21-a126-1883858c62f8)

**Comment by JJRobertsSex30** [comment]
Can you please try the prompt I gave with GPT4 like I am using and give me some idea as to why this is not working?

**Comment by JJRobertsSex30** [comment]
Any further feedback on this and how to get it working correctly?

**Comment by B0rrA** [comment]
I'm having this same issue since a start using it. I don't know if this was working at any time, maybe @mamadoudicko @StanGirard or @gozineb can give us some enlighment on this.

**Comment by eWizardII** [comment]
Was this ever resolved - I am having the same issue with the latest release from Dec 4.
