### ISSUE TITLE
[Private/Public Brains] 6- AAU, I can set a brain from private to public 

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#1296]
### Link to the Epic

#963

### Explain the Functionality

Go from private to a public brain with a confirmation modal -> Use same wording as epic

### Tech To-dos

Frontend: 
- Use the toggle used in "public" brains for private brains too
- Return the correct confirmation modal if private to public or public to private 

### Tests

Test 

### Validation Checks

- Change a private brain (with people accessing it: viewer, editor and owner) to public
- Verify that according to the type of access the user has the adequate tabs and rights
- Subscribe to this public brain with another account

**Comment by Chloeroumengas** [comment]
https://github.com/users/StanGirard/projects/5/views/2?pane=issue&itemId=38995981

**Comment by Chloeroumengas** [comment]
AAUSer, when I click on the button, the change is made. No need to click on save. 

![Image](https://github.com/StanGirard/quivr/assets/138109838/d24428b3-33d8-4d39-81ad-e4b27d155a2f)
