### ISSUE TITLE
[Bug]: Words are skipped during streaming in front-end 

### ISSUE THREAD

**Issue by Giulianini** [StanGirard/quivr#1302]
### What happened?

In chat
![image](https://github.com/StanGirard/quivr/assets/39558398/56a9db15-ee9b-4536-99fc-fbf6b49ab692)
After refresh
![image](https://github.com/StanGirard/quivr/assets/39558398/c4818967-669b-439d-b3b7-3aa28eeba23c)

**Comment by cdukedev** [comment]
When the Page is refreshed, it looks like the API is called and provides a new response.
