### ISSUE TITLE
[Feature]: PKM integration

### ISSUE THREAD

**Issue by darragh-downey** [StanGirard/quivr#1332]
### The Feature

The ability to upload PKM files (Obsidian / Logseq, etc.) or pass a file path to the location of aforementioned PKM files / notes.

### Motivation, pitch

Quivr is incredibly useful as-is, however, allowing users to integrate their personal notes stored in their PKM of choice (for example, Obsidian / Logseq) with Quivr could allow for meaningful breakthroughs in thought - prior to the publishing stage. As it stands a user would have to compile their notes into a single document and upload via the UI.

Further, since these PKM tools can be completely self-hosted, it [potentially] allows for a true individualised local assistant, which in some cases. such as, highly restrictive legal requirements, can support a user where other tools cannot [by design].

### Twitter / LinkedIn details

@dd0wney

**Comment by AnkushMalaker** [comment]
Given a obsidian vault, wouldn't it be easy to convert all the files to required format (since they're just markdown), and consume them?
Whats blocking this feature?

**Comment by FrostyTheSouthernSnowman** [comment]
I'd like to see this integrated into obsidian. Maybe a secondary frontend that is just an obsidian extension? Lot's of projects have successfully figured out how to give LLMs access to full directories and even full codebases. Obsidian's metadata also could enhance Quivr's understanding of the information in Obsidian. If converting takes to long, you could use the metadata and some settings to only convert the minimum required data. Also, when a user puts in a prompt that needs data that Quivr doesn't have uploaded, it could crawl the graph to try to find it.
