### ISSUE TITLE
[Bug]: syntax error at or near "insert"

### ISSUE THREAD

**Issue by Exist2Resist** [StanGirard/quivr#1343]
### What happened?

A bug happened when running the table creation script. 

psql client is version 14

### Relevant log output

```bash
When running the `migration.sh` script to create tables I receive the following error.


CREATE TABLE
psql:scripts/tables.sql:271: ERROR:  syntax error at or near "insert"
LINE 8: insert into
```
```


### Twitter / LinkedIn details

_No response_

**Comment by HiroLaBete** [comment]
https://github.com/StanGirard/quivr/pull/1348

Looks like a merge was performed 4 hours ago to fix something that may be related.
