### ISSUE TITLE
[Bug]: Disordered layout of webpage. Any suggestion to fix it? Many thanks!

### ISSUE THREAD

**Issue by zsp0901** [StanGirard/quivr#1347]
### What happened?

After install 0.0.88, I get disordered layout of webpage, tested on Edge, Firefox and Chrome of both PC and mobile phone.

It seems no response after login.

![image](https://github.com/StanGirard/quivr/assets/144313533/c819c948-dabd-47b5-829b-9089b4750973)

**Comment by StanGirard** [comment]
Look at the CSP in the code :)

**Comment by StanGirard** [comment]
@dosu-beta can you explain how to update CSP ?

**Comment by zsp0901** [comment]
> _🤖_
> 
> Hello,
> 
> The disordered layout issue you're experiencing might be due to the Content Security Policy (CSP) blocking certain resources from being loaded.
> 
> To fix this, you need to identify the resources that are being blocked and add them to the appropriate directive in the CSP. The browser's console should show warnings about the blocked resources.
> 
> In Quivr, the CSP is defined in the `cms/quivr/config/middlewares.js` file. Once you've identified the blocked resources, you can add them to the CSP in this file. For example, if a CSS file from `https://example.com` is being blocked, you would add `https://example.com` to the `style-src` directive:
> 
> ```js
> module.exports = [
>   // ...
>   {
>     name: 'strapi::security',
>     config: {
>       contentSecurityPolicy: {
>         useDefaults: true,
>         directives: {
>           // ...
>           'style-src': [
>             "'self'",
>             'https:',
>             'https://example.com', // Add the new source here
>           ],
>           // ...
>         },
>       },
>     },
>   },
>   // ...
> ];
> ```
> 
> Remember to add the new source to the correct directive. If a script is being blocked, it should be added to `script-src`. If a font is being blocked, it should be added to `font-src`, and so on.
> 
> After updating the CSP, you should rebuild and redeploy your application. The layout issues should be resolved if the CSP was the cause.
> 
> Unfortunately, I can't see the image you've attached, so I can't identify the specific resources that are being blocked. You can check the browser's console for warnings about blocked resources.
> 
> Let me know if you need further assistance.
> 
> Best, Dosu
> 

Dear Dosu,

Attached please find my snapshot. 

I followed your instructions with 'font-src', 'script-src' or 'style-src'. But all failed.
![273236302-c819c948-dabd-47b5-829b-9089b4750973](https://github.com/StanGirard/quivr/assets/144313533/222b6d5c-0da2-468b-b600-e7681fe4d3f1)

**Comment by stef-bloom** [comment]
I have the same issue, and it began after I pulled the latest update, after there was a change to 
const ContentSecurityPolicy  (line 21) in
https://github.com/StanGirard/quivr/blob/main/frontend/next.config.js
Could that have something to do with it?

**Comment by stef-bloom** [comment]
Here's how I just fixed it. 
In frontend/.env, I changed
NEXT_PUBLIC_ENV=local
 to 
NEXT_PUBLIC_ENV=prod

and in frontend/next.config.js, I changed all 3 instances of 

prod: "https://www.quivr.app/",
to
prod: "https://[mydomainname]/",  // <-- use whatever domain name you're running this on (plus port #, if you're running this on a specific port)

**Comment by zsp0901** [comment]
> Here's how I just fixed it. In frontend/.env, I changed NEXT_PUBLIC_ENV=local to NEXT_PUBLIC_ENV=prod
> 
> and in frontend/next.config.js, I changed all 3 instances of
> 
> prod: "https://www.quivr.app/", to prod: "https://[mydomainname]/", // <-- use whatever domain name you're running this on (plus port #, if you're running this on a specific port)
> 
> Caveat: This will break the localhost UI, but works on the server.

It doesn't work for me. I changed back to this commit 408aa8f87adfe8fd24aa53b5a70ffaab40dff19b, and it works.

Thanks a lot!

**Comment by BabakSarf** [comment]
While we are on the website topic. can someone tell me how to fix error 404 forbidden to access data when I log in to quivr remotely

**Comment by BabaSarf** [comment]
I have the same issue after upgrade to version 88l

**Comment by zsp0901** [comment]
> Here's how I just fixed it. In frontend/.env, I changed NEXT_PUBLIC_ENV=local to NEXT_PUBLIC_ENV=prod
> 
> and in frontend/next.config.js, I changed all 3 instances of
> 
> prod: "https://www.quivr.app/", to prod: "https://[mydomainname]/", // <-- use whatever domain name you're running this on (plus port #, if you're running this on a specific port)
> 
> Caveat: This will break the localhost UI, but works on the server.

I run Quivr on a server, and finally fixed this problem by replacing all 'localhost' with my real IP in frontend/next.config.js.

Thanks for your clue.

**Comment by ingeniumdesign** [comment]
i edit in the .env all "`localhost`" in my local IP from the Server. But i cant login with the default user: admin@quir.app and pw: admin
