### ISSUE TITLE
[Bug]: localhost:3000 taking me to quivr.app

### ISSUE THREAD

**Issue by gwwharton** [StanGirard/quivr#1355]
### What happened?

A bug happened!
<img width="1360" alt="Screenshot 2023-10-08 at 7 17 48 PM" src="https://github.com/StanGirard/quivr/assets/137230589/4d8deeb2-b2ca-4a95-a807-7f54f8c28611">

**Comment by slbillups** [comment]
More information would be helpful...

Are you trying to run quivr headless? Or are you just having issues logging in/accessing quivr after its built?

If it's just an issue with not being able to login, I'd check and verify you have a user setup in postgresql after creating a user in supabase. Supabase -> Auth -> create user via email/password. If it's not working for whatever reason you could try creating the user via psql in Docker's CLI

``sql CREATE USER <name> WITH PASSWORD '<password>';  ``

As far as running it headless, I haven't attempted myself/don't know if it's possible.

**Comment by shariqmasood** [comment]
Hello, I am encountering exactly same problem. I have given detailed description of the status of my system in attached document. Please go through it and help, if possible. Thanking u in anticipation.

[quivr issue.docx](https://github.com/StanGirard/quivr/files/13225157/quivr.issue.docx)
