### ISSUE TITLE
[Bug]: frequently get 'SyntaxError: Unterminated string...'

### ISSUE THREAD

**Issue by zsp0901** [StanGirard/quivr#1363]
### What happened?

Errors like SyntaxError: Unterminated string in JSON at position xxx (line 1 column xxx)
xxx is different each time.

![image](https://github.com/StanGirard/quivr/assets/144313533/dc2ecdaf-d6ed-43da-b44e-aaab8573552d)

**Comment by zsp0901** [comment]
I found that "go to other pages or tabs and get back" can make the answer completely show up in the dialog. It is weird.

**Comment by zsp0901** [comment]
Can this issue be taken care? I run Quivr from remote Ubuntu server and open website in local computer. I think this maybe the reason and many other weird issues.

Right now, I can't fix this problem by simply "go to other pages or tabs and get back".

![image](https://github.com/StanGirard/quivr/assets/144313533/f83be754-540e-4642-bc21-555ac2e6f8c2)


> I found that "go to other pages or tabs and get back" can make the answer completely show up in the dialog. It is weird.

**Comment by zsp0901** [comment]
I finally fixed by adding a key in "OPENAI_API_KEY=" and rebuilded. It seems this parameter can't be empty.

**Comment by anypasss** [comment]
> I finally fixed by adding a key in "OPENAI_API_KEY=" and rebuilded. It seems this parameter can't be empty.
Can you explain specifically how it was modified? Which file is it?

**Comment by adeyali1** [comment]
> I finally fixed by adding a key in "OPENAI_API_KEY=" and rebuilded. It seems this parameter can't be empty.

Please, Can you explain specifically how it was modified? Which file is it?
