### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Freddie-GER** [StanGirard/quivr#1374]
### What happened?

A bug happened!?

Hi everyone, I have set up a local supabase container, and am trying to now deploy quivr. 

Having tried different settings, I get the same output when trying to deploy: 

[+] Running 5/5
 ✔ Container redis         Running                                                                                                                     0.0s
 ✔ Container worker        Recreated                                                                                                                   2.3s
 ✔ Container web           Recreated                                                                                                                   0.3s
 ✔ Container flower        Recreated                                                                                                                   1.0s
 ✔ Container backend-core  Recreated                                                                                                                   0.3s
Attaching to backend-core, flower, redis, web, worker
web           | yarn run v1.22.19
web           | $ next start
backend-core  | INFO:     Will watch for changes in these directories: ['/code']
backend-core  | WARNING:  "workers" flag is ignored when reloading is enabled.
backend-core  | INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
backend-core  | INFO:     Started reloader process [1] using StatReload
web           | - ready started server on [::]:3000, url: http://localhost:3000
web           | - info Loaded env from /app/.env
web           | - info Loaded env from /app/.env
worker        | /usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
worker        | absolutely not recommended!
worker        |
worker        | Please specify a different user using the --uid option.
worker        |
worker        | User information: uid=0 euid=0 gid=0 egid=0
worker        |
worker        |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
worker        |
worker        |  -------------- celery@d9fd07cba355 v5.2.7 (dawn-chorus)
worker        | --- ***** -----
worker        | -- ******* ---- Linux-5.15.0-86-generic-x86_64-with-glibc2.31 2023-10-10 09:11:30
worker        | - *** --- * ---
worker        | - ** ---------- [config]
worker        | - ** ---------- .> app:         celery_worker:0x7fe3264b1790
worker        | - ** ---------- .> transport:   redis://redis:6379/0
worker        | - ** ---------- .> results:     redis://redis:6379/0
worker        | - *** --- * --- .> concurrency: 1 (prefork)
worker        | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker        | --- ***** -----
worker        |  -------------- [queues]
worker        |                 .> celery           exchange=celery(direct) key=celery
worker        |
worker        |
worker        | [tasks]
worker        |   . celery_task.create_embedding_for_document
worker        |   . process_crawl_and_notify
worker        |   . process_file_and_notify
worker        |
worker        | [2023-10-10 09:11:30,994: INFO/MainProcess] Connected to redis://redis:6379/0
worker        | [2023-10-10 09:11:31,032: INFO/MainProcess] mingle: searching for neighbors
flower        | 2023-10-10 09:11:31,421:INFO - Visit me at http://0.0.0.0:5555
flower        | 2023-10-10 09:11:31,431:INFO - Broker: redis://redis:6379/0
flower        | 2023-10-10 09:11:31,436:INFO - Registered tasks:
flower        | ['celery.accumulate',
flower        |  'celery.backend_cleanup',
flower        |  'celery.chain',
flower        |  'celery.chord',
flower        |  'celery.chord_unlock',
flower        |  'celery.chunks',
flower        |  'celery.group',
flower        |  'celery.map',
flower        |  'celery.starmap',
flower        |  'celery_task.create_embedding_for_document',
flower        |  'process_crawl_and_notify',
flower        |  'process_file_and_notify']
flower        | 2023-10-10 09:11:31,460:INFO - Connected to redis://redis:6379/0
worker        | [2023-10-10 09:11:32,087: INFO/MainProcess] mingle: all alone
worker        | [2023-10-10 09:11:32,112: INFO/MainProcess] celery@d9fd07cba355 ready.
flower        | 2023-10-10 09:11:32,549:WARNING - Inspect method active failed
flower        | 2023-10-10 09:11:32,549:WARNING - Inspect method active_queues failed
flower        | 2023-10-10 09:11:32,556:WARNING - Inspect method registered failed
flower        | 2023-10-10 09:11:32,562:WARNING - Inspect method stats failed
flower        | 2023-10-10 09:11:32,563:WARNING - Inspect method scheduled failed
backend-core  | 2023-10-10 09:11:32,738:INFO - NumExpr defaulting to 1 threads.
backend-core  | Process SpawnProcess-1:
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
backend-core  |     self.run()
backend-core  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
backend-core  |     self._target(*self._args, **self._kwargs)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
backend-core  |     target(sockets=sockets)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
backend-core  |     return asyncio.run(self.serve(sockets=sockets))
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
backend-core  |     return runner.run(main)
backend-core  |            ^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
backend-core  |     return self._loop.run_until_complete(task)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
backend-core  |     return future.result()
backend-core  |            ^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
backend-core  |     config.load()
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
backend-core  |     self.loaded_app = import_from_string(self.app)
backend-core  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
backend-core  |     module = importlib.import_module(module_str)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend-core  |     return _bootstrap._gcd_import(name[level:], package, level)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend-core  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend-core  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend-core  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend-core  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend-core  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend-core  |   File "/code/main.py", line 26, in <module>
backend-core  |     from routes.subscription_routes import subscription_router
backend-core  |   File "/code/routes/subscription_routes.py", line 31, in <module>
backend-core  |     subscription_service = SubscriptionInvitationService()
backend-core  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/repository/brain_subscription/subscription_invitation_service.py", line 12, in __init__
backend-core  |     self.supabase_client = get_supabase_client()
backend-core  |                            ^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/models/settings.py", line 29, in get_supabase_client
backend-core  |     supabase_client: Client = create_client(
backend-core  |                               ^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/supabase/client.py", line 248, in create_client
backend-core  |     return Client(supabase_url=supabase_url, supabase_key=supabase_key, options=options)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/supabase/client.py", line 51, in __init__
backend-core  |     raise SupabaseException("Invalid URL")
backend-core  | supabase.client.SupabaseException: Invalid URL

**Comment by Freddie-GER** [comment]
> backend-core | supabase.client.SupabaseException: Invalid URL

Now this is the part that irritates me, I have tried all, setting 
- localhost 
- localhost:8000
- the IP of the local host, with port and w/o

Thanks for Ideas and help :)

**Comment by Freddie-GER** [comment]
Okay interesting update: This error also appears when using supabase from their website, so it seems to not be limited to local supabase installs

**Comment by mamadoudicko** [comment]
Your Supabase url seems invalid according to Supabase client.

Can you please check that you specified the correct one in `backend/.env` ?
