### ISSUE TITLE
[New Homepage] 1.b AAUser, I see a new navbar with the login, sign up and log in

### ISSUE THREAD

**Issue by matthieujacq** [StanGirard/quivr#1377]
## 🚩 Feature flag

Use in growthbook the flag: `new-homepage-activated` (boolean)

## 📱 Mobile

![Image](https://github.com/StanGirard/quivr/assets/67386567/e9e070c3-0ae9-46d7-9b20-67198ed44dcd)

### 🍔 Hamburger menu

![Image](https://github.com/StanGirard/quivr/assets/67386567/3adb52ff-6a83-4fce-9d12-b97faca34806)

## 🖥️ Desktop

![Image](https://github.com/StanGirard/quivr/assets/67386567/037abce6-640d-4a9a-8df2-52359e794e94)

## Strat tech

- [x] create a growthbook account and link it to my local dev env
- [x] create a feature flag and enable the new page according to it
- [x] create the navbar

**Comment by Chloeroumengas** [comment]
@matthieujacq Il y a un peu trop d'écarts sur les côtés. Sinon très propre.
