### ISSUE TITLE
[Bug]: SyntaxError: Unterminated string in JSON at position 268 (line 1 column 269)

### ISSUE THREAD

**Issue by adeyali1** [StanGirard/quivr#1396]
### What happened?

Hello Developers,
Thanks For Your Hard Work,

I've Problem When I'm Asking A Question I'm Getting -> SyntaxError: Unterminated string in JSON at position 268 (line 1 column 269)
Please See The Image:
![screencapture-ai-mawsool-tech-chat-2023-10-06-23_04_09](https://github.com/StanGirard/quivr/assets/141839336/db58baf9-62e4-4527-b3e5-e577fed51022)

The Website is:
https://ai.mawsool.tech/

**Comment by fmalafaya** [comment]
Hello @adeyali1 , 
Im new here, what question are you asking? Im not being able to replicate your error
Thank You!

**Comment by zsp0901** [comment]
It is weird and annoying issues. I am still suffering from it!

**Comment by zsp0901** [comment]
You may try add a key to "OPENAI_API_KEY=" and re-build

**Comment by BabakSarf** [comment]
I also have the same issue. I will check k the file and and report back if I manage to fix the problem

**Comment by MeTaNoV** [comment]
definitely worth to dig, it also happened quite some time for us too

**Comment by mamadoudicko** [comment]
Can you please explain how to reproduce this bug @adeyali1 ?
