### ISSUE TITLE
[Feature]: Can the manual for other models be updated? e.g. Mistral-7B-Instruct-v0.1

### ISSUE THREAD

**Issue by zsp0901** [StanGirard/quivr#1403]
### The Feature

The tutorial for non-openAI models seems no update for a long time. (https://brain.quivr.app/docs/get_started/run_fully_local).

It will be great if the manuals can be updated since there already are options for Mistral, Claude and others in Quivr.

### Motivation, pitch

If it is feasible, can you do Mistral first? Thanks a lot!

**Comment by mamadoudicko** [comment]
I'll work on this soon

**Comment by akup06** [comment]
since https://github.com/oobabooga/text-generation-webui can offer an openai api endpoint, it is may be easier if quivr get a parameter in the backend.env with a url to the openai api from oobabooga. The openai key could be sk_1111111111111111

**Comment by cccc11231** [comment]
Did you try this:
https://brain.quivr.app/docs/Developers/selfHosted/run_fully_local

I am looking for completely offline version. Do you know does the above instruction work?

I try to deploy quiver locally a few month ago, at that time, everything works except embedding part which still rely on openAI. I don't know current status. Do you guys know if we can deploy it completely offline or not?

Thanks.
