### ISSUE TITLE
[Monetisation] 1.b AAU, I can see the "upgrade to plus" button in user settings page if i'm not paying

### ISSUE THREAD

**Issue by mamadoudicko** [StanGirard/quivr#1431]
EPIC: https://github.com/StanGirard/quivr/issues/1429

Functional:

1. On user settings page `/user` add a button (displayed only for non paying users) which allows to subscribe to Quivr Plus (design below)
2. On click on the button, a modal containing Quivr princing table (Stripe embed) should be displayed (as in https://github.com/StanGirard/quivr/issues/1430)

<img width="872" alt="Screenshot 2023-10-18 at 18 26 24" src="https://github.com/StanGirard/quivr/assets/63923024/50170264-bf57-4905-976a-228dae62b5f2">
<img width="872" alt="Screenshot 2023-10-18 at 18 26 21" src="https://github.com/StanGirard/quivr/assets/63923024/62e63a9f-41be-4118-a27f-b109089f866e">

**Comment by jiahuamld** [comment]
good!

**Comment by LordDougall** [comment]
are there certain requirements that must be met prior to this button displaying?

currently have stripe products/table setup, envs set accordingly 
potentially tied to webhooks or strapi?  unsure am noob 

any insight appreciated - thanks
