### ISSUE TITLE
[Feature]: Combine this with MemGPT

### ISSUE THREAD

**Issue by dality17** [StanGirard/quivr#1449]
### The Feature

Memgpt is a open source project and its amazing! it should be easy to combine this with memgpt.

https://www.youtube.com/watch?v=-xzX9o2BeUM

### Motivation, pitch

when im chatting with chatbot in quivr. what i notice is they really  lack the information to continue the topic for the answer i gave. and they start to give totally unrelevant information. thats really sad.

**Comment by mamadoudicko** [comment]
@StanGirard

**Comment by dality17** [comment]
> @StanGirard

Also dont forget. the beauty of it is it wil prevent Artificial hallucination. and it wil self improve of its own.


you have no idea how many times i chat with my documents and it just give me false information that is totally not in me pdf file.  even when i put the temperature 0) it stil happens sometimes. sometimes i wonder if my file is really uploaded.

**Comment by zsp0901** [comment]
> ### The Feature
> Memgpt is a open source project and its amazing! it should be easy to combine this with memgpt.
> 
> https://www.youtube.com/watch?v=-xzX9o2BeUM
> 
> ### Motivation, pitch
> when im chatting with chatbot in quivr. what i notice is they really lack the information to continue the topic for the answer i gave. and they start to give totally unrelevant information. thats really sad.
> 
> ### Twitter / LinkedIn details
> _No response_

I also feel Quivr seems not remember what I have talked with it before in the same dialog window. For example, it made several suggestions. When I asked for more details about one of the suggestions above ( giving it the exact same words), it just said it hadn't give such suggestion.

**Comment by dality17** [comment]
@StanGirard  there is a new memgpt out! it is a upgrade memgpt 2.0 check this open source https://www.youtube.com/watch?v=awDkuSwfEQA
