### ISSUE TITLE
[Bug]: Can nor create any brain after installed the latest version

### ISSUE THREAD

**Issue by BabaSarf** [StanGirard/quivr#1455]
### What happened?

I have installed Quivr on VPS with the domain name. I can create a user and log in but to start I need to create a brain the hourglass turns for a minit or so then stop without creating any brain with no error on the docker terminal

**Comment by BabaSarf** [comment]
None of the above suggestions fixed the problem I am facing

**Comment by StanGirard** [comment]
Please give more informations. Logs required to help debug :)

**Comment by BabaSarf** [comment]
No docker logs at all related to the error. Everything fine on the terminal but I will load the logs anyway just incase I am missing something .
