### ISSUE TITLE
[Bug]:  Preview page moves to the right

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#1457]
EPIC: https://github.com/StanGirard/quivr/issues/1232

### What happened?

A bug happened!
<img width="1521" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/1f127a1f-af41-4810-8904-bdf4b5c5e902">

**Comment by matthieujacq** [comment]
Indeed, the image should be cropped on the right: hiding the overflow on the container should do the job. I'm on it, it'll be done in the morning ;)
