### ISSUE TITLE
Can you support uploading GitHub repolinks?

### ISSUE THREAD

**Issue by superbayes** [StanGirard/quivr#148]
Can you support uploading GitHub warehouse links?
such as: https://github.com/panjh/dxflib.git

**Comment by StanGirard** [comment]
Yea ! That would require a new kind of loader. Interesting in doing it ? ;)

**Comment by superbayes** [comment]
> Yea ! That would require a new kind of loader. Interesting in doing it ? ;)

For programmers, I think this will be a very useful feature
Imagine your boss quickly familiarizing you with a niche source code library, but there are few online reference materials
Therefore, it's great to have GPT help us read the source code

**Comment by StanGirard** [comment]
Agreed 👍

**Comment by gogo-ashacode** [comment]
Would this only load the README in the root of the project and save it, or more than that?

**Comment by StanGirard** [comment]
There is a git loader in langchain  that could be used.

**Comment by mattlebel** [comment]
@StanGirard I'd be up to help with this.

I want to think a bit about what this implementation might look like (which [file extensions / folders we might want to exclude](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/git.html#filtering-files-to-load) by default in the import, etc.), but I can post a plan of attack here this weekend and get feedback before starting on it.

**Comment by StanGirard** [comment]
The implementation would be:

Feed the url
In the crawl endpoint if the url has GitHub in it and then finishes with .git then we load the GitHub repo :)

**Comment by mattlebel** [comment]
Ah, you're 100% right - we can just trust that the user has made decisions via their `.gitignore` and take all files.

Any objections to also looking for `gitlab.com` URLs in addition to `github.com`?

I am starting on this

**Comment by StanGirard** [comment]
Exactly ! There is even a git loader if interested. 


https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/git.html#clone-repository-from-url

**Comment by mattlebel** [comment]
> Ah, you're 100% right - we can just trust that the user has made decisions via their `.gitignore` and take all files.
> 
> Any objections to also looking for `gitlab.com` URLs in addition to `github.com`?
> 
> I am starting on this

An update on my end - while I still plan to finish this, I have not gotten the gitloader functionality built yet. This request to add the functionality remains open for now.

**Comment by JarrodWoodard** [comment]
I'm look forward to this feature and dropping the quivr repo into it. I'll be a lot better at helping out and providing feedback afterwards. :)

**Comment by JarrodWoodard** [comment]
I tried this feature again seeing as their was a recent update. I tried crawling the quivr repo so I can hopefully not have to bug others with dilettante questions and maybe be able to contribute here and there. 

It looked like it worked in the end but their was a message in the browser that said it failed.

**Comment by mattlebel** [comment]
Just an update - I am no longer actively working on this in case someone else would like to grab it.
