### ISSUE TITLE
error

### ISSUE THREAD

**Issue by szyvvv** [StanGirard/quivr#149]
<img width="1015" alt="image" src="https://github.com/StanGirard/quivr/assets/51510595/f83f6a2d-9fe6-45c0-88dd-a6b1faa9c9cb">

**Comment by StanGirard** [comment]
Please give more insights.

**Comment by roycehwa** [comment]
I have the same issue, when the dock is up running and visit localhost:3000, I get this.
<img width="959" alt="截屏2023-05-25 14 20 38" src="https://github.com/StanGirard/quivr/assets/76505330/5929c513-eb05-43ed-b343-f66b59bcd743">

**Comment by StanGirard** [comment]
Please guys give me more logs. The logs in the backend, the frontend in chrome and all

**Comment by roycehwa** [comment]
<img width="1086" alt="截屏2023-05-25 14 28 53" src="https://github.com/StanGirard/quivr/assets/76505330/258f63b9-9d2f-47eb-b6e1-c117ecf2c063">

**Comment by StanGirard** [comment]
You forgot to change the XXXX in your frontend/.env file 😂

**Comment by StanGirard** [comment]
<img width="875" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/c94b1d36-65e3-4f86-ace1-f9565aedaf6c">

**Comment by roycehwa** [comment]
I have changed the backend/.env, XXXX in the frontend/.env shall be replaced with the same info in backend/.env?

NEXT_PUBLIC_ENV=local
NEXT_PUBLIC_BACKEND_URL=http://localhost:5050
NEXT_PUBLIC_SUPABASE_URL="XXXX"
NEXT_PUBLIC_SUPABASE_ANON_KEY="XXX"

**Comment by StanGirard** [comment]
Yes 👍

**Comment by roycehwa** [comment]
Thanks a lot
