### ISSUE TITLE
TypeError: Invalid URL: XXXX/auth/v1 

### ISSUE THREAD

**Issue by shiliu2023** [StanGirard/quivr#151]
Server Error
TypeError: Invalid URL: XXXX/auth/v1

This error happened while generating the page. Any console logs will be displayed in the terminal window.

**Comment by shiliu2023** [comment]
good

**Comment by arron123456** [comment]
I met the same problem, how did u finger it ?
<img width="559" alt="image" src="https://github.com/StanGirard/quivr/assets/38456883/6794e73e-27ec-4583-96c9-8477191bf575">

**Comment by arron123456** [comment]
thx

**Comment by Buantum** [comment]
> The issue is not having these variables set properly in your `frontend/.env` file:
> 
> ```
> NEXT_PUBLIC_SUPABASE_URL=""
> NEXT_PUBLIC_SUPABASE_ANON_KEY=""
> ```
> 
> Both the URL and `anon` key can be found in Supabase -> Project Settings -> API
![image](https://github.com/StanGirard/quivr/assets/49450053/32fe3ad6-5c72-460d-8b1b-0c96d9e5a907)

still failed
