### ISSUE TITLE
[Bug]: Demo video auto launching on iPhone

### ISSUE THREAD

**Issue by matthieujacq** [StanGirard/quivr#1513]
### What happened?

On scroll on iphone, the video launches automatically (it's supposed to stay hidden). Cannot be reproduced with chrome dev tools, need a real iphone or a simulator.

https://github.com/StanGirard/quivr/assets/67386567/02733fd0-fd4a-4905-97f6-026e20a3302e

**Comment by StanGirard** [comment]
Love the spirit 🥰
