### ISSUE TITLE
[Bug]: Overflowing Error Message Due to Excessive Content Length

### ISSUE THREAD

**Issue by ludovicobesana** [StanGirard/quivr#1518]
### What happened?

When the content of the error message is too lengthy, it overflows its container. This results in the message extending beyond the visible boundaries of the page, obstructing complete content visibility.

![bug](https://github.com/StanGirard/quivr/assets/35035423/03127c7e-4442-45e3-ad2d-83a2f41a1d84)

**What did you expect to happen?**
I expected the error message or displayed content to fit properly within the visible area of the page, allowing for clear reading without the need for horizontal scrolling or other adjustments.

### Twitter / LinkedIn details

https://www.linkedin.com/in/ludovicobesana/

**Comment by danboyce92** [comment]
Hey there, I would like to try to resolve this css issue, can it be assigned to me?

Also I've tried to run this project locally on my machine and I get supabaseKey error due to the fact that the env file isn't present. How do additional contributors avoid this issue?
Thanks,
Daniel
