### ISSUE TITLE
[Bug]: is it possible to use public host? cannot continue both with email magic link or google on public host

### ISSUE THREAD

**Issue by malikal-hh** [StanGirard/quivr#1520]
### What happened?

So I tried to host quivr on public but i can't continue both with email magic link or google on public host. On magic link the email link keeps sending "http://localhost:3000" like this https://yzgkhemnkicfkyhyzgdg.supabase.co/auth/v1/verify?token=d7ad27e9ef711e072d2137643870f582f32db7084d4245d2878c1329&type=magiclink&redirect_to=http://localhost:3000 and on google i got {"code":400,"msg":"Unsupported provider: provider is not enabled"}. is it not possible to use public host?

**Comment by malikal-hh** [comment]
@dosu-bot I think it's the code redirect always to http://localhost and also always callback to http://localhost:3000

**Comment by malikal-hh** [comment]
@dosu-bot now I got another issue with the API, I cannot access the API I always get {"detail":"Not Found"} with 404

**Comment by malikal-hh** [comment]
@dosu-bot now I got another issue, when hosting the backend to public host I got ERR_SSL_VERSION_OR_CIPHER_MISMATCH This site can’t provide a secure connection api.com uses an unsupported protocol.

**Comment by BabaSarf** [comment]
On supabase changes the redirect url from localhost:3000 to your real url and hope this change is solved your problem with ligin

**Comment by why2000** [comment]
This is super helpful, thx!
