### ISSUE TITLE
[Feature]: email/password login method support, configurable

### ISSUE THREAD

**Issue by jerryshang** [StanGirard/quivr#1524]
### The Feature

An env config for login modes support, and take back the password login function

### Motivation, pitch

The email/password login mode is supported in old Quivr releases, but since v0.0.98, it dispeared.  
In case of self-hosted Quivr (with self-hosted Supabase too), it's not easy to find or deploy a free smtp service for sending magic link. And although Google login mode is not implemented yet, it's worth to mention that Google is not availiable in my country, and so is the Google SSO.
So the lagacy password login mode should be kept. Besides, it's couldn't be better if there were an env value to specify which login modes Quivr would support, like: 
`NEXT_PUBLIC_SUPABASE_LOGIN_MODES=magic_link,password,google_sso`

**Comment by StanGirard** [comment]
@jerryshang I did not see it that way. You are right it adds complexity. We'll discuss it with the team. Thanks a lot for the issue.

@Chloeroumengas @gozineb @mamadoudicko

**Comment by mamadoudicko** [comment]
Thanks for your suggestion @jerryshang
https://github.com/StanGirard/quivr/issues/1524
