### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/root/bin/pandoc'

### ISSUE THREAD

**Issue by abmahmoodi** [StanGirard/quivr#1527]
### What happened?

I installed Quivr on Ubuntu local machine. in the last step when I run this command: docker compose up --build
I get the following error:

[ERROR] Found /root/bin/pandoc, but not using it because of an error:
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/__init__.py", line 703, in _ensure_pandoc_path
backend-core  |     version_string = _get_pandoc_version(path)
backend-core  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/__init__.py", line 567, in _get_pandoc_version
backend-core  |     p = subprocess.Popen(
backend-core  |         ^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
backend-core  |     self._execute_child(args, executable, preexec_fn, close_fds,
backend-core  |   File "/usr/local/lib/python3.11/subprocess.py", line 1950, in _execute_child
backend-core  |     raise child_exception_type(errno_num, err_msg, err_filename)
backend-core  | PermissionError: [Errno 13] Permission denied: '/root/bin/pandoc'
backend-core  | 2023-10-31 09:40:16,587:ERROR - Found /root/bin/pandoc, but not using it because of an error:
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/__init__.py", line 703, in _ensure_pandoc_path
backend-core  |     version_string = _get_pandoc_version(path)
backend-core  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/__init__.py", line 567, in _get_pandoc_version
backend-core  |     p = subprocess.Popen(
backend-core  |         ^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
backend-core  |     self._execute_child(args, executable, preexec_fn, close_fds,
backend-core  |   File "/usr/local/lib/python3.11/subprocess.py", line 1950, in _execute_child
backend-core  |     raise child_exception_type(errno_num, err_msg, err_filename)
backend-core  | PermissionError: [Errno 13] Permission denied: '/root/bin/pandoc'
worker        | [2023-10-31 09:40:17,060: INFO/MainProcess] mingle: all alone
worker        | [2023-10-31 09:40:17,088: INFO/MainProcess] celery@c0a8fc362a49 ready.
backend-core  | [INFO] Using already downloaded file pandoc-3.1.9-1-amd64.deb
backend-core  | 2023-10-31 09:40:18,566:INFO - Using already downloaded file pandoc-3.1.9-1-amd64.deb
backend-core  | [INFO] Unpacking pandoc-3.1.9-1-amd64.deb to tempfolder...
backend-core  | 2023-10-31 09:40:18,567:INFO - Unpacking pandoc-3.1.9-1-amd64.deb to tempfolder...
backend-core  | [INFO] Copying pandoc to /root/bin ...
backend-core  | 2023-10-31 09:40:19,280:INFO - Copying pandoc to /root/bin ...
backend-core  | ERROR:    Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
backend-core  |     async with self.lifespan_context(app) as maybe_state:
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
backend-core  |     await self._router.startup()
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
backend-core  |     await handler()
backend-core  |   File "/code/main.py", line 56, in startup_event
backend-core  |     pypandoc.download_pandoc()
backend-core  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 267, in download_pandoc
backend-core  |     unpack(filename, targetfolder)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 105, in _handle_linux
backend-core  |     shutil.copyfile(src, dst)
backend-core  |   File "/usr/local/lib/python3.11/shutil.py", line 258, in copyfile
backend-core  |     with open(dst, 'wb') as fdst:
backend-core  |          ^^^^^^^^^^^^^^^
backend-core  | PermissionError: [Errno 13] Permission denied: '/root/bin/pandoc'
backend-core  | 
backend-core  | ERROR:    Application startup failed. Exiting.
worker        | [2023-10-31 09:40:20,485: INFO/MainProcess] Events of group {task} enabled by remote.

**Comment by abmahmoodi** [comment]
This error occurred in the docker container backend-core

**Comment by abmahmoodi** [comment]
Now I have this error:

[INFO] Using already downloaded file pandoc-3.1.9-1-amd64.deb
backend-core  | 2023-10-31 10:19:54,976:INFO - Using already downloaded file pandoc-3.1.9-1-amd64.deb
backend-core  | [INFO] Unpacking pandoc-3.1.9-1-amd64.deb to tempfolder...
backend-core  | 2023-10-31 10:19:54,976:INFO - Unpacking pandoc-3.1.9-1-amd64.deb to tempfolder...
backend-core  | [INFO] Copying pandoc to /root/bin ...
backend-core  | 2023-10-31 10:19:55,731:INFO - Copying pandoc to /root/bin ...
backend-core  | ERROR:    Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
backend-core  |     async with self.lifespan_context(app) as maybe_state:
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
backend-core  |     await self._router.startup()
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
backend-core  |     await handler()
backend-core  |   File "/code/main.py", line 56, in startup_event
backend-core  |     pypandoc.download_pandoc()
backend-core  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 267, in download_pandoc
backend-core  |     unpack(filename, targetfolder)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/pandoc_download.py", line 105, in _handle_linux
backend-core  |     shutil.copyfile(src, dst)
backend-core  |   File "/usr/local/lib/python3.11/shutil.py", line 258, in copyfile
backend-core  |     with open(dst, 'wb') as fdst:
backend-core  |          ^^^^^^^^^^^^^^^
backend-core  | PermissionError: [Errno 13] Permission denied: '/root/bin/pandoc'
backend-core  | 
backend-core  | ERROR:    Application startup failed. Exiting.

**Comment by jerryshang** [comment]
Have you tried `docker compose` with `root` user? I know it's not recommended, but using a `root` can help avoid many Docker permission issues.

**Comment by abmahmoodi** [comment]
@jerryshang 
Yes, I added User root to `DockerFile` in `backend` folder but did not solve the problem. I have temporarily removed `pandoc`  from requirements.
