### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by G-linch** [StanGirard/quivr#153]
I installed step by step according to the steps until docker compose build. It prompted "=> CANCELED [5/6] RUN yarn install   240.2s.   failed to solve: process "/bin/sh -c pip install --no-cache-dir --upgrade -r /code/requirements.txt --timeout 100" did not complete successfully: exit code: 2". I don't know what happened. Does anyone know?

**Comment by StanGirard** [comment]
How is your connection speed ?

**Comment by G-linch** [comment]
> How is your connection speed ?
I checked it out,  I don't think it's related to speed, it's not a timeout issue. Do you have any suggestions?Here is the complete error message: 
 => ERROR [5/6] RUN yarn install             313.6s
------
 > [5/6] RUN yarn install:
#0 0.897 yarn install v1.22.19
#0 0.935 info No lockfile found.
#0 0.944 warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[+] Building 318.8s (8/9)
 => [internal] load .dockerignore              0.0s
 => => transferring context: 2B                0.0s
 => [internal] load build definition from Doc  0.0s
 => => transferring dockerfile: 306B           0.0s
 => [internal] load metadata for docker.io/li  2.8s
 => [internal] load build context              0.0s
 => => transferring context: 796B              0.0s
 => [1/5] FROM docker.io/library/python:3.11@  0.0s
 => CACHED [2/5] WORKDIR /code                 0.0s: => CACHED [3/5] COPY ./requirements.txt /cod  0.0sO => CANCELED [4/5] RUN pip install --no-cac  316.0s
failed to solve: process "/bin/sh -c yarn install" did not complete successfully: exit code: 1

**Comment by sam1am** [comment]
Same issue here on M1 Max Mac OS.
