### ISSUE TITLE
[Feature]: I hope to be provided with the data source for the answers

### ISSUE THREAD

**Issue by xiaoxuan220** [StanGirard/quivr#1532]
### The Feature

I hope to be provided with the data source for the answers I receive from my questions. 
Otherwise, it is difficult for me to distinguish whether the response is generated by AI or from the documents I uploaded to Quivr. 
Every time I receive an answer, I have to search through the documents to feel reassured.
 It would be incredible if a feature could be added to indicate the source of the response.

### Motivation, pitch

Thx

**Comment by abmahmoodi** [comment]
how to force Quivr create answer from uploaded file information not external information?
