### ISSUE TITLE
[Bug]: internal privoxy error

### ISSUE THREAD

**Issue by georgeqin96** [StanGirard/quivr#1544]
### What happened?

A bug happened! when install quivr-0.0.102
382.5 Get:96 http://deb.debian.org/debian bullseye/main amd64 libwebp6 amd64 0.6.1-2.1+deb11u2 [259 kB]
382.5 E: Failed to fetch http://deb.debian.org/debian/pool/main/liba/libalgorithm-diff-perl/libalgorithm-diff-perl_1.201-1_all.deb  500  Internal Privoxy Error [IP: 151.101.110.132 80]
382.5 E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cmark-gfm/libcmark-gfm-extensions0_0.29.0.gfm.0-6_amd64.deb  500  Internal Privoxy Error [IP: 151.101.110.132 80]
382.5 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
382.5 Fetched 120 MB in 6min 6s (328 kB/s)
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y     libgeos-dev     libcurl4-openssl-dev     libssl-dev     pandoc     binutils     curl     git     build-essential &&     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&     rm -rf /var/lib/apt/lists/* && apt-get clean" did not complete successfully: exit code: 100

**Comment by StanGirard** [comment]
There has been un update from Docker which impacted the certificates because there was a new version of the docker. Make sure to delete the docker cache by doing  ```docker system prune```
