### ISSUE TITLE
nginx proxy

### ISSUE THREAD

**Issue by localdevjs** [StanGirard/quivr#1548]
### The Feature

I'm trying to use quivr on a publicly accessible domain. Quivr is installed and works perfectly on the server when logged into it and using "localhost:3000" as the url.

Trying to get this working through nginx so that users can use "https://mydomain.com/chat" etc, I had to give in and completely remove the CSP header through nginx because some stylesheets and js wouldn't load despite my attempts to tweak the CSP header in nginx. 

Finally after completely removing the header, the page would load correctly on the public domain, but the app is still expecting to load content from "http://localhost:5050/onboarding" or "http://localhost:5050/user/identity" etc, there are many of these GET urls that simply won't work through the proxy. So this shows up as "Error occurred while fetching your chats" etc.

### Motivation, pitch

Please see the feature request.

**Comment by localdevjs** [comment]
The bot reply above is fascinating, what a world we live in.

But unfortunately it's not correct for me. As I mentioned in my first post, the API calls do not have a "/api/" directory in the URL. My first post has examples of the URLs that are failing. Since there is no (sub)directory in the URL, there is no way for me to proxy different urls to different localhost:port services, they all end up going to the main proxy "/" section.

**Comment by localdevjs** [comment]
This was fixed by editing the "NEXT_PUBLIC_BACKEND_URL" URL in "frontend/.env" and just using my public domain. I changed it to "https://mydomain.com/api" and rebuilt in docker.

Then I followed the bots advice above and created a second "location" section using the "/api/" path, then proxying all traffic to "http://localhost:5050".

**Comment by MakeTooRRSS** [comment]
Hi, so what is your final configuration? how do I configure the .env file? there is no documentation for quirv to work in a domain, thank you. @localdevjs
