### ISSUE TITLE
[Bug]: Brains Management screen won't scroll down 

### ISSUE THREAD

**Issue by St-Bloom** [StanGirard/quivr#1576]
### What happened?

After latest pull of fresh repo, the scrollbar is missing in "brains management". 
It is still visible in Quivr.app, but in localhost it is now missing.
Tested in Chrome, Edge, and Firefox. Missing everywhere.
Looked at inspector and found an "overflow: hidden". 
When unclicking the setting, the scrollbar returns.
Pls see screenshots.

![Screenshot 2023-11-02 164135](https://github.com/StanGirard/quivr/assets/149593769/51376426-10f7-48b9-8bea-88bc874c1692)
![Screenshot 2023-11-02 165925](https://github.com/StanGirard/quivr/assets/149593769/3ff04010-028b-4f4f-a5c2-22d7c3b59197)
![Screenshot 2023-11-02 170427](https://github.com/StanGirard/quivr/assets/149593769/630d500b-1b4c-42b0-ba73-f9776a48e921)

**Comment by mamadoudicko** [comment]
Thanks @St-Bloom,

Just fixed it in https://github.com/StanGirard/quivr/pull/1577
