### ISSUE TITLE
API_base

### ISSUE THREAD

**Issue by nimrod1990** [StanGirard/quivr#158]
I hope to set up API forwarding or set environment variables.

**Comment by StanGirard** [comment]
Can you please provide more details ?

**Comment by nimrod1990** [comment]
I want to know if the API Endpoint can be customized. I have an api key, but I want to redirect it to another URL. Should I add it when modifying env?

**Comment by StanGirard** [comment]
API endpoint of openai ? Yes it can but you have to modify the code yourself

**Comment by nimrod1990** [comment]
> API endpoint of openai ? Yes it can but you have to modify the code yourself

I would like to know if you know how to modify this option? I am a beginner and not quite sure how to proceed. I need to replace “api.openai.com” with “api.chatanywhere.com.cn”. Can I set a global variable like this:
“”“
import openai
openai.api_base = "https://api.chatanywhere.com.cn/v1"
”“”
and where  to do that. Thanks! 🤣
