### ISSUE TITLE
[Bug]: the "signup" page is now gone. 

### ISSUE THREAD

**Issue by localdevjs** [StanGirard/quivr#1582]
### What happened?

Default install, click "sign up" link on main page and the link goes to login. A few commits ago (last week?) the link directed to "/signup". Even manually trying to load that page gives a 404.

I have no way of creating a user account for myself on my locally hosted system.

**Comment by StanGirard** [comment]
Can you please look at the env variables ? There is a new one that came out ;) 

NEXT_PUBLIC_AUTH_MODES=magic_link,password,google_sso in your frontend/.env

**Comment by localdevjs** [comment]
That worked, thanks. The URL I get goes to supabase, and then gets redirected to "localhost:3000". Is there something I'm missing in my env files that causes this?

Just having a hard time trying to put this application behind an nginx reverse proxy so that others can reach it via public domain. I haven't found any guides on this, and the web console is showing lots of 404 errors, lots of urls in the form "localhost" when they should be "mydomain.com" as the majority of them are. I must be missing something somewhere.

**Comment by StanGirard** [comment]
Go to supabase and in auth change your website's url :)

**Comment by localdevjs** [comment]
Thanks, fixed!
