### ISSUE TITLE
[Feature]: make quivr fully 100% percent locally get rid of supabase

### ISSUE THREAD

**Issue by dality17** [StanGirard/quivr#1588]
### The Feature

why are we always depended on some form of server what is the point calling this open source if you are depending on subabase?
can someone not make fully locally? 
superagi is fully locally. 

### Motivation, pitch

the reason for this feature. is giving you more assurance and security that your data is your data. 
locally not depending on any form of server but your own.

**Comment by StanGirard** [comment]
Hey @dality17 ! Supabase is open-source ;) You can run it locally. I'll explain how soon.

**Comment by dality17** [comment]
@StanGirard Awsome!!! thank you so much Stan! :D

**Comment by zono50** [comment]
Yeah would love to know this as well

**Comment by Omaha2002** [comment]
Ditto, tried to install Supabase locally, is working but integration with Quivr is not fully working.

https://supabase.com/docs/guides/self-hosting/docker

**Comment by Omaha2002** [comment]
Well actually, none, I'm now looking at an exact replica of the Quivr home page but run locally:

![afbeelding](https://github.com/StanGirard/quivr/assets/3179748/d0bb7815-4f74-4dfc-bc07-f471a71c09a2)

Is there a standard user defined or do I need to create one in the locally running Supabase?

**Comment by StanGirard** [comment]
Awesome ! Could you post the solution as a doc ? That would be awesome !

**Comment by Omaha2002** [comment]
I can do that but first I need to make sure Quivr is working correctly by logging in and see if things work.

Besides that I just followed the instructions on: https://supabase.com/docs/guides/self-hosting/docker

Afterwards I could acces Supabase locally with http://ip:8000 run the scripts to create the database/tables.

Then installed Quivr as instructed and in the backend .env filled in the details for the database to localhost:

SUPABASE_URL=http://10.100.100.18:3000
JWT_SECRET and the SUPABASE_SERVICE_KEY as instructed.

frontend .env:

NEXT_PUBLIC_SUPABASE_URL=http://localhost
NEXT_PUBLIC_SUPABASE_ANON_KEY=******

**Comment by MeTaNoV** [comment]
definitely a must to get rid of those massive egress... :)
