### ISSUE TITLE
Add answers to context

### ISSUE THREAD

**Issue by Swader** [StanGirard/quivr#16]
As discussed [here](https://twitter.com/_StanGirard/status/1657738724879355908?s=20).

The ideal UX flow would be:

- on answer, add three buttons
  - 1. Build on answer
  - 2. New context answer
  - 3. Fork context

- "Build on answer" adds this question and answer to the DB for future queries.
- "New context answer" works as it does now, fresh context API call with only current raw-data vectors, previous questions and answers are ignored, even if there are some.
- "Fork context" allows you to branch off of a certain answer (even past ones) with a different query, like so: suppose there was Context 0 -> Question 1 -> Answer 1 -> Question 2 -> Answer 2. I can scroll up to Answer 1, click Fork Context, and the next query I write will pretend Question 2 and Answer 2 never happened. This allows the user to have branched context-persistent conversations with the API and the ability to fine tune responses from the past based on new prompt insights from the future. It is also very useful for prompt auditing and reporting.

I understand 3) is very hard to build right now as it also requires a separate UI element for the forked conversations so 1) and 2) would be good enough, especially 1) which is very important in longer-context plans.

**Comment by StanGirard** [comment]
Very interesting approach. 

I'll work on 1 & 2 shortly. Look for a PR draft shortly. 

I'll start once im done with the vector stores interface. PR currently in draft

**Comment by StanGirard** [comment]
Closing in favor of #1. 

You can join the discussion on Discord or in the discussion panel 😉
