### ISSUE TITLE
[Bug]: exit code:100 ！！！

### ISSUE THREAD

**Issue by Eric-llllll** [StanGirard/quivr#1640]
### What happened?

failed to solve: process "/bin/sh -c apt-get update && apt-get install -y     libgeos-dev     libcurl4-openssl-dev     libssl-dev     pandoc     binutils     curl     git     build-essential &&     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&     rm -rf /var/lib/apt/lists/* && apt-get clean" did not complete successfully: exit code: 100

**Comment by JuanMartinMarina** [comment]
@Eric-llllll hi! I get the same issue since a few days ago. Maybe you're running this on Windows, and when you run into the CMD the Docker compilation with `docker compose up --build` the issue appears?
