### ISSUE TITLE
[Bug]: I Frontend Can't Communicate With The CMS ERROR 403

### ISSUE THREAD

**Issue by adeyali1** [StanGirard/quivr#1655]
### What happened?

After Deploying The Whole Quivr Code on My Webhost I Got Some Errors on The Frontend Like:

GET https://cms.mawsool.tech/api/notification-banner 403 (Forbidden)
GET https://ai.mawsool.tech/_vercel/insights/script.js net::ERR_ABORTED 404 (Not Found)

chat:1 Refused to execute script from 'https://ai.mawsool.tech/_vercel/insights/script.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

GET https://cms.mawsool.tech/api/notification-banner 403 (Forbidden)
GET https://cms.mawsool.tech/api/notification-banner 403 (Forbidden)
GET https://cms.mawsool.tech/api/notification-banner 403 (Forbidden)

Website: https://ai.mawsool.tech/
CMS: https://cms.mawsool.tech/

Please Help!

Best Wishes

**Comment by adeyali1** [comment]
Hello,
OK, Many Thanks Mr. Dosubot

**Comment by StanGirard** [comment]
@adeyali1 the cms is something that you have to deploy too :) It is just for the content of the homepage and the blog. You can keep cms.quivr.app or deploy your own -> cms folder to see what it is.

**Comment by adeyali1** [comment]
OK, Many Thanks Let Me Double Check It.
