### ISSUE TITLE
[Bug]: "Failed to upload file to storage" when trying to upload a PDF to my brain with an accent in the title

### ISSUE THREAD

**Issue by xaviermarchal** [StanGirard/quivr#1667]
## Scenario

1. Create a brain, go to setting and knowledge. Try to add the PDF in attached piece

<img width="1066" alt="image" src="https://github.com/StanGirard/quivr/assets/57732330/c093130a-881d-4c42-b000-a177f112229d">

2. The PDF should be uploaded, but i see an error message (error 500): "Failed to upload file to storage."

<img width="1373" alt="image" src="https://github.com/StanGirard/quivr/assets/57732330/6e240e9f-b101-457f-afb9-9a3c2ad95e35">

Link to video : https://www.loom.com/share/3cf063c832f44b93a9aa7bac003584c2?sid=db8e567c-fb14-4c9f-b76b-dc4c19653bc3

PDF uploaded: 
[Révision_ 62304 modifications 2018.pdf](https://github.com/StanGirard/quivr/files/13415501/Revision_.62304.modifications.2018.pdf)

**Comment by StanGirard** [comment]
@xaviermarchal Merci :)

**Comment by mamadoudicko** [comment]
Thanks Xavier,

Just fixed it in https://github.com/StanGirard/quivr/pull/1695

**Comment by StanGirard** [comment]
Fixed
