### ISSUE TITLE
[Feature]: Connect to external Redis inctance

### ISSUE THREAD

**Issue by israellev** [StanGirard/quivr#1692]
### The Feature

Allow an option to connect external Redis instance.

### Motivation, pitch

We're using only the backend API of Quivr, and we deploy it into Google Cloud Run (on demand). 
GCR support only `Dockerfile` but not `docker-compose.yaml`, so it can't deploy both Redis & python in parallel.
So, we suggest allowing python code to connect an external Redis server by getting it's variables on `/backend/.env` file.

**Comment by StanGirard** [comment]
@israellev it is already possible :) Just update the /backend/.env url for the celery worker :)

**Comment by israellev** [comment]
@StanGirard awesome!
Where can I put the password?

**Comment by StanGirard** [comment]
`CELERY_BROKER_URL` you can put the url in it

https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/redis.html

For more info

**Comment by israellev** [comment]
@StanGirard thank you very much!
