### ISSUE TITLE
"How to change the 3000 port to 3010？

### ISSUE THREAD

**Issue by shiliu2023** [StanGirard/quivr#170]
How to change the 3000 port to 3010? I have changed it and started the service, but the webpage cannot be accessed.

**Comment by StanGirard** [comment]
Search for 3000 and change it to 3010 in the code ;)

**Comment by shiliu2023** [comment]
😂thank you！

**Comment by xiaoyvr** [comment]
Find the package.json under the frontend folder. change the 
```
  "scripts": {
    "dev": "next dev",
```
to
```
  "scripts": {
    "dev": "next dev -p 3010",
```

Find the Dockerfile under the frontend folder, change 
```
EXPOSE 3000
```
to 
```
EXPOSE 3010
```

**Comment by sam1am** [comment]
I have changed every reference of 3000 to 3010. 
I have changed line 5 & 6 in package.json to 
```
  "scripts": {
    "dev": "next dev -p 3010",
```

But it still starts on port 3000.

**Comment by srigas** [comment]
> I have changed every reference of 3000 to 3010. I have changed line 5 & 6 in package.json to
> 
> ```
>   "scripts": {
>     "dev": "next dev -p 3010",
> ```
> 
> But it still starts on port 3000.

You are probably not working on the `dev` environment then, but instead trying to run the base build. In this case, leave the "dev" part in the `package.json` file as it was, and change `"start": "next start",` to `"start": "next start -p 3030",`. This, along with exposing the correct port at the Dockerfile and setting the correct port at the `docker-compose.yml` file, should do the job.
