### ISSUE TITLE
[Bug]: Public Brain subscriptions - Not functioning

### ISSUE THREAD

**Issue by LordDougall** [StanGirard/quivr#1713]
### What happened?

Seems as if the new secrets tied to brain created an issue when going to subscribe to public brains.  

![bug](https://github.com/StanGirard/quivr/assets/84426196/b5993455-2e87-42bf-b9f6-cb522c05f3aa)

**Comment by LordDougall** [comment]
Error produced when a brain, set to public, containing knowledge, is listed in brains-management/library.  

When another user (not owner) attempts to subscribe by clicking button on /brains-management/library page, there is no error message popup - Only error is displayed in console

fd9d1056-84dd40c146c17fec.js:9 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at handleBrainSubscription (page-2756b7c2d943bf60.js:1:2457)
    at onClick (page-2756b7c2d943bf60.js:1:2911)
    at Object.l5 (fd9d1056-84dd40c146c17fec.js:9:67290)
    at ar (fd9d1056-84dd40c146c17fec.js:9:67444)
    at fd9d1056-84dd40c146c17fec.js:9:132983
    at u2 (fd9d1056-84dd40c146c17fec.js:9:133082)
    at u3 (fd9d1056-84dd40c146c17fec.js:9:133496)
    at fd9d1056-84dd40c146c17fec.js:9:138988
    at oS (fd9d1056-84dd40c146c17fec.js:9:88337)
    
    functions as expected in v.0.0.98

**Comment by LordDougall** [comment]
Correction - Functions as expected in v0.0.111

**Comment by LordDougall** [comment]
![Screenshot 2023-11-26 212634](https://github.com/StanGirard/quivr/assets/84426196/34f11362-bd65-457f-a487-452f76ad15c1)

commenting out all related to "secrets" within these four files provided a temp fix, subscribe function works however will conflict with api - look forward to solution!

**Comment by mamadoudicko** [comment]
Thanks to @LordDougall for describing this issue so well!

Just fixed it in https://github.com/StanGirard/quivr/pull/1727

**Comment by LordDougall** [comment]
nice seems to be working
