### ISSUE TITLE
Module not found: Can't resolve '@supabase/auth-helpers-nextjs'

### ISSUE THREAD

**Issue by laihenyi** [StanGirard/quivr#173]
I did install this module and un/install for several times.
This error keeps happening.

Error Log:
web      | - wait compiling /middleware (client and server)...
web      | - error ./middleware.ts:1:0
web      | Module not found: Can't resolve '@supabase/auth-helpers-nextjs'
web      | > 1 | import { createMiddlewareSupabaseClient } from '@supabase/auth-helpers-nextjs'
web      |   2 | import { NextResponse } from 'next/server'
web      |   3 |
web      |   4 | import type { NextRequest } from 'next/server'
web      |
web      | https://nextjs.org/docs/messages/module-not-found
web      | - wait compiling /_error (client and server)...
web      | - event compiled client and server successfully in 206 ms (312 modules)

**Comment by iMADi-ARCH** [comment]
are you using docker? try `docker compose build` first, then do `docker compose up`.

**Comment by laihenyi** [comment]
> are you using docker? try `docker compose build` first, then do `docker compose up`.

I tried. The same situation.

**Comment by iMADi-ARCH** [comment]
can you send the contents of your `frontend/package.json` file?
also try `git pull origin main` if you haven't already.

**Comment by laihenyi** [comment]
"scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "test-type": "tsc --noEmit --emitDeclarationOnly false",
    "test": "yarn test-type",
    "precommit": "yarn lint && yarn test"
  },
  "dependencies": {
    "@radix-ui/react-dialog": "^1.0.3",
    "@radix-ui/react-toast": "^1.1.3",
    "@supabase/auth-helpers-nextjs": "^0.6.1",
    "@supabase/auth-ui-react": "^0.4.2",
    "@supabase/auth-ui-shared": "^0.1.6",
    "@supabase/supabase-js": "^2.22.0",
    "@types/node": "20.1.7",
    "@types/react": "18.2.6",
    "@types/react-dom": "18.2.4",
    "@typescript-eslint/eslint-plugin": "^5.59.7",
    "@vercel/analytics": "^1.0.1",
    "autoprefixer": "10.4.14",
    "axios": "^1.4.0",
    "class-variance-authority": "^0.6.0",
    "clsx": "^1.2.1",
    "encoding": "^0.1.13",
    "eslint": "^8.41.0",
    "eslint-config-next": "13.4.2",
    "framer-motion": "^10.12.12",
    "next": "13.4.2",
    "postcss": "8.4.23",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-dropzone": "^14.2.3",
    "react-markdown": "^8.0.7",
    "rehype-highlight": "^6.0.0",
    "tailwind-merge": "^1.12.0",
    "tailwindcss": "3.3.2",
    "typescript": "^5.0.4"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.9",
    "@types/next": "^9.0.0",
    "husky": "^8.0.3",
    "react-icons": "^4.8.0"
  }
}

**Comment by iMADi-ARCH** [comment]
I don't see any reason why the `@supabase/auth-helpers-nextjs` package is not being installed.

**Comment by shashank-crypto** [comment]
What is your npm version ?

**Comment by laihenyi** [comment]
> What is your npm version ?
9.6.7

**Comment by phowse** [comment]
I'm having the same|similar issue

```
./middleware.ts:1:0
Module not found: Can't resolve '@supabase/auth-helpers-nextjs'
> 1 | import { createMiddlewareSupabaseClient } from '@supabase/auth-helpers-nextjs'
  2 | import { NextResponse } from 'next/server'
  3 | 
  4 | import type { NextRequest } from 'next/server'

https://nextjs.org/docs/messages/module-not-found
```

**Comment by philipmorg** [comment]
I was able to resolve this by updating my .env files to the new version and re-building the Docker container. The new .env file format requires some additional API keys that weren't needed in the old version. Lacking those additional API keys seems to be what was causing this error for me.

**Comment by laihenyi** [comment]
> I was able to resolve this by updating my .env files to the new version and re-building the Docker container. The new .env file format requires some additional API keys that weren't needed in the old version. Lacking those additional API keys seems to be what was causing this error for me.

Didn't work for me.
I also reinstall(git clone), and No Luck was found...
