### ISSUE TITLE
[Bug]: Quivr replied with an empty message

### ISSUE THREAD

**Issue by hongruilin** [StanGirard/quivr#1734]
### What happened?

A bug happened!
I have deployed Quivr for the first time and have not uploaded any documents. When I select the default brain to ask a question, it will return empty. If I do not select the default brain, it will reply normally. I have checked the server logs and obtained the following information

### Relevant log output

```bash
backend-core  | 2023-11-27 15:20:02,481 [INFO] repository.chat.create_chat: New chat entry in chats table for user f6420558-056f-4699-bb85-cf16960ce753
backend-core  | 2023-11-27 15:20:03,006:INFO - HTTP Request: POST https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/chats "HTTP/1.1 201 Created"
backend-core  | 2023-11-27 15:20:03,007 [INFO] repository.chat.create_chat: Insert response [{'chat_id': 'bff40da1-6b20-4199-85d3-1263a93ab1fb', 'user_id': 'f6420558-056f-4699-bb85-cf16960ce753', 'creation_time': '2023-11-27T15:20:03.006055', 'history': None, 'chat_name': '你好'}]
backend-core  | INFO:     13.230.43.211:1387 - "POST /chat HTTP/1.1" 200 OK
backend-core  | INFO:     13.230.43.211:1387 - "OPTIONS /chat/bff40da1-6b20-4199-85d3-1263a93ab1fb/question/stream?brain_id=a485993b-6b6f-4f51-8907-228c833a9383 HTTP/1.1" 200 OK
backend-core  | 2023-11-27 15:20:07,921:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/chats?select=chat_id%2Cuser_id%2Ccreation_time%2Cchat_name&user_id=eq.f6420558-056f-4699-bb85-cf16960ce753&order=creation_time "HTTP/1.1 200 OK"
backend-core  | INFO:     13.230.43.211:32649 - "GET /chat HTTP/1.1" 200 OK
backend-core  | 2023-11-27 15:20:08,033:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains?select=%2A&brain_id=eq.a485993b-6b6f-4f51-8907-228c833a9383 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:09,213:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains_users?select=id%3Abrain_id%2C%20rights%2C%20brains%20%28id%3A%20brain_id%2C%20status%2C%20name%2C%20brain_type%29&user_id=eq.f6420558-056f-4699-bb85-cf16960ce753&brain_id=eq.a485993b-6b6f-4f51-8907-228c833a9383 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:09,512:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/user_settings?select=%2A&user_id=eq.f6420558-056f-4699-bb85-cf16960ce753 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:09,760:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/users?select=%2A&id=eq.f6420558-056f-4699-bb85-cf16960ce753 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:10,070:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/customers?select=email&email=eq.495079044%40qq.com "HTTP/1.1 405 Method Not Allowed"
backend-core  | 2023-11-27 15:20:10,071 [ERROR] models.databases.supabase.user_usage: Error while checking if user is a premium user
backend-core  | 2023-11-27 15:20:10,071 [ERROR] models.databases.supabase.user_usage: {'code': '25006', 'details': None, 'hint': None, 'message': 'cannot execute INSERT in a read-only transaction'}
backend-core  | 2023-11-27 15:20:10,071:INFO - Streaming request for gpt-3.5-turbo
backend-core  | 2023-11-27 15:20:10,221:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/user_settings?select=%2A&user_id=eq.f6420558-056f-4699-bb85-cf16960ce753 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:10,329:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/users?select=%2A&id=eq.f6420558-056f-4699-bb85-cf16960ce753 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:10,587:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/customers?select=email&email=eq.495079044%40qq.com "HTTP/1.1 405 Method Not Allowed"
backend-core  | 2023-11-27 15:20:10,587 [ERROR] models.databases.supabase.user_usage: Error while checking if user is a premium user
backend-core  | 2023-11-27 15:20:10,587 [ERROR] models.databases.supabase.user_usage: {'code': '25006', 'details': None, 'hint': None, 'message': 'cannot execute INSERT in a read-only transaction'}
backend-core  | 2023-11-27 15:20:10,870:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/user_daily_usage?select=daily_requests_count&user_id=eq.f6420558-056f-4699-bb85-cf16960ce753&date=eq.20231127 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:11,175:INFO - HTTP Request: PATCH https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/user_daily_usage?user_id=eq.f6420558-056f-4699-bb85-cf16960ce753&date=eq.20231127 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:11,176 [INFO] models.user_usage: User 495079044@qq.com request count updated to 12
backend-core  | 2023-11-27 15:20:11,440:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.a485993b-6b6f-4f51-8907-228c833a9383 "HTTP/1.1 200 OK"
backend-core  | INFO:     13.230.43.211:25169 - "POST /chat/bff40da1-6b20-4199-85d3-1263a93ab1fb/question/stream?brain_id=a485993b-6b6f-4f51-8907-228c833a9383 HTTP/1.1" 200 OK
backend-core  | 2023-11-27 15:20:11,745:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/chat_history?select=%2A&chat_id=eq.bff40da1-6b20-4199-85d3-1263a93ab1fb&order=message_time "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:12,014:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.a485993b-6b6f-4f51-8907-228c833a9383 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:12,306:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.a485993b-6b6f-4f51-8907-228c833a9383 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:12,439:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.a485993b-6b6f-4f51-8907-228c833a9383 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:12,724:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.a485993b-6b6f-4f51-8907-228c833a9383 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:13,005:INFO - HTTP Request: POST https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/chat_history "HTTP/1.1 201 Created"
backend-core  | 2023-11-27 15:20:13,140:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.a485993b-6b6f-4f51-8907-228c833a9383 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:13,229:INFO - error_code=rate_limit_exceeded error_message='Rate limit reached for text-embedding-ada-002 in organization org-1w9YcpXjN6IXHk4tfGYHnv1m on requests per day (RPD): Limit 200, Used 200, Requested 1. Please try again in 7m12s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.' error_param=None error_type=requests message='OpenAI API error received' stream_error=False
backend-core  | 2023-11-27 15:20:13,229:WARNING - Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for text-embedding-ada-002 in organization org-1w9YcpXjN6IXHk4tfGYHnv1m on requests per day (RPD): Limit 200, Used 200, Requested 1. Please try again in 7m12s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing..
backend-core  | 2023-11-27 15:20:17,323:INFO - error_code=rate_limit_exceeded error_message='Rate limit reached for text-embedding-ada-002 in organization org-1w9YcpXjN6IXHk4tfGYHnv1m on requests per day (RPD): Limit 200, Used 200, Requested 1. Please try again in 7m12s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.' error_param=None error_type=requests message='OpenAI API error received' stream_error=False
backend-core  | 2023-11-27 15:20:17,324 [ERROR] llm.qa_base: Caught exception: Rate limit reached for text-embedding-ada-002 in organization org-1w9YcpXjN6IXHk4tfGYHnv1m on requests per day (RPD): Limit 200, Used 200, Requested 1. Please try again in 7m12s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.
backend-core  | 2023-11-27 15:20:17,324 [ERROR] llm.qa_base: Error processing source documents: 'NoneType' object has no attribute 'get'
backend-core  | 2023-11-27 15:20:17,585:INFO - HTTP Request: PATCH https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/chat_history?message_id=eq.4a1205e3-96a3-4197-820e-a270af95d133 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:17,586 [INFO] repository.chat.update_message_by_id: Message 4a1205e3-96a3-4197-820e-a270af95d133 updated
backend-core  | INFO:     13.230.43.211:25169 - "OPTIONS /chat/bff40da1-6b20-4199-85d3-1263a93ab1fb/history HTTP/1.1" 200 OK
backend-core  | 2023-11-27 15:20:18,932:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/onboardings?select=onboarding_a%2Conboarding_b1%2Conboarding_b2%2Conboarding_b3&user_id=eq.f6420558-056f-4699-bb85-cf16960ce753&limit=1 "HTTP/1.1 200 OK"
backend-core  | INFO:     13.230.43.211:9848 - "GET /onboarding HTTP/1.1" 200 OK
backend-core  | 2023-11-27 15:20:20,557:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/chat_history?select=%2A&chat_id=eq.bff40da1-6b20-4199-85d3-1263a93ab1fb&order=message_time "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:20,576:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/user_settings?select=%2A&user_id=eq.f6420558-056f-4699-bb85-cf16960ce753 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:20,690:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.a485993b-6b6f-4f51-8907-228c833a9383 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:20,826:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/users?select=%2A&id=eq.f6420558-056f-4699-bb85-cf16960ce753 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:21,078:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/customers?select=email&email=eq.495079044%40qq.com "HTTP/1.1 405 Method Not Allowed"
backend-core  | 2023-11-27 15:20:21,079 [ERROR] models.databases.supabase.user_usage: Error while checking if user is a premium user
backend-core  | 2023-11-27 15:20:21,079 [ERROR] models.databases.supabase.user_usage: {'code': '25006', 'details': None, 'hint': None, 'message': 'cannot execute INSERT in a read-only transaction'}
backend-core  | 2023-11-27 15:20:21,129:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/notifications?select=%2A&chat_id=eq.bff40da1-6b20-4199-85d3-1263a93ab1fb&datetime=gt.2023-11-27%2015%3A15%3A20.695816 "HTTP/1.1 200 OK"
backend-core  | INFO:     13.230.43.211:23268 - "GET /chat/bff40da1-6b20-4199-85d3-1263a93ab1fb/history HTTP/1.1" 200 OK
backend-core  | 2023-11-27 15:20:21,403:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/user_daily_usage?select=%2A&user_id=eq.f6420558-056f-4699-bb85-cf16960ce753 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:21,640:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains_users?select=brain_id&user_id=eq.f6420558-056f-4699-bb85-cf16960ce753&default_brain=eq.True "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:21,649 [INFO] repository.brain.get_default_user_brain: Default brain response: a485993b-6b6f-4f51-8907-228c833a9383
backend-core  | 2023-11-27 15:20:21,649 [INFO] repository.brain.get_default_user_brain: Default brain id: a485993b-6b6f-4f51-8907-228c833a9383
backend-core  | 2023-11-27 15:20:21,924:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.a485993b-6b6f-4f51-8907-228c833a9383 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 15:20:22,406:INFO - HTTP Request: GET https://vhbwmlbjqbdeoxhdhuyd.supabase.co/rest/v1/brains_vectors?select=vector_id&brain_id=eq.a485993b-6b6f-4f51-8907-228c833a9383 "HTTP/1.1 200 OK"
backend-core  | INFO:     13.230.43.211:11138 - "GET /user HTTP/1.1" 200 OK
```

**Comment by StanGirard** [comment]
You are rate limited from OpenAI -> backend-core  | 2023-11-27 15:20:17,323:INFO - error_code=rate_limit_exceeded error_message='Rate limit reached for text-embedding-ada-002 in organization org-1w9YcpXjN6IXHk4tfGYHnv1m on requests per day (RPD): Limit 200, Used 200, Requested 1. Please try again in 7m12s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.' error_param=None error_type=requests message='OpenAI API error received' stream_error=False

**Comment by hongruilin** [comment]
> _🤖_
> 
> Hello @hongruilin,
> 
> Nice to meet you! I'm an AI bot here to assist you with your issues and questions regarding the Quivr repository. While we're waiting for a human maintainer, I'll do my best to help you out. Let's get that bug squashed!
> 
> Based on the error messages you've provided, it seems like there are a few different issues happening here.
> 
> Firstly, the error message 'cannot execute INSERT in a read-only transaction' suggests that there's an attempt to write to the database in a transaction that's been marked as read-only. This could be happening when the default brain is selected and the system tries to update some information in the database. This is likely a configuration issue with the database transaction settings. You might want to check your database configuration and ensure that it allows write operations.
> 
> The second error message 'Error processing source documents: 'NoneType' object has no attribute 'get'' indicates that there's an attempt to call the 'get' method on a NoneType object. This could be related to the function . If the default brain doesn't exist for the user, this function will return None, and any subsequent attempt to call 'get' on this NoneType object will result in this error. You might want to add a check to ensure that the default brain exists before calling 'get' on it.`get_user_default_brain(user.id)`
> 
> Lastly, the rate limit error from the OpenAI API suggests that the daily request limit for the 'text-embedding-ada-002' model has been reached. This is likely causing the empty message you're seeing when you select the default brain, as the system is unable to process any more requests to the OpenAI API. You'll need to wait until the rate limit resets before you can make more requests. Alternatively, you could consider increasing your rate limit if you find that you're consistently hitting it.
> 
> I hope this helps! Let me know if you have any other questions.
> 
> ## Sources
> * [backend/repository/brain/get_default_user_brain_or_create_new.py](https://github.com/StanGirard/quivr/blob/main/backend/repository/brain/get_default_user_brain_or_create_new.py)

Please help me check what issues have arisen with the new log. Thank you

backend-core  | 2023-11-27 17:02:50,144:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/brains?select=%2A&brain_id=eq.bfb0b151-bdec-4897-b0b1-82a50da1ccc6 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:50,271:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/brains_users?select=id%3Abrain_id%2C%20rights%2C%20brains%20%28id%3A%20brain_id%2C%20status%2C%20name%2C%20brain_type%29&user_id=eq.9c13b311-4306-4eec-96b8-9fad440fc6fb&brain_id=eq.bfb0b151-bdec-4897-b0b1-82a50da1ccc6 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:50,416:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/user_settings?select=%2A&user_id=eq.9c13b311-4306-4eec-96b8-9fad440fc6fb "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:50,514:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/users?select=%2A&id=eq.9c13b311-4306-4eec-96b8-9fad440fc6fb "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:50,621:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/customers?select=email&email=eq.495079044%40qq.com "HTTP/1.1 405 Method Not Allowed"
backend-core  | 2023-11-27 17:02:50,621 [ERROR] models.databases.supabase.user_usage: Error while checking if user is a premium user
backend-core  | 2023-11-27 17:02:50,622 [ERROR] models.databases.supabase.user_usage: {'code': '25006', 'details': None, 'hint': None, 'message': 'cannot execute INSERT in a read-only transaction'}
backend-core  | 2023-11-27 17:02:50,622:INFO - Streaming request for huggingface/mistralai/Mistral-7B-Instruct-v0.1
backend-core  | 2023-11-27 17:02:50,750:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/user_settings?select=%2A&user_id=eq.9c13b311-4306-4eec-96b8-9fad440fc6fb "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:50,804:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/users?select=%2A&id=eq.9c13b311-4306-4eec-96b8-9fad440fc6fb "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:50,892:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/customers?select=email&email=eq.495079044%40qq.com "HTTP/1.1 405 Method Not Allowed"
backend-core  | 2023-11-27 17:02:50,892 [ERROR] models.databases.supabase.user_usage: Error while checking if user is a premium user
backend-core  | 2023-11-27 17:02:50,893 [ERROR] models.databases.supabase.user_usage: {'code': '25006', 'details': None, 'hint': None, 'message': 'cannot execute INSERT in a read-only transaction'}
backend-core  | 2023-11-27 17:02:51,007:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/user_daily_usage?select=daily_requests_count&user_id=eq.9c13b311-4306-4eec-96b8-9fad440fc6fb&date=eq.20231127 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:51,105:INFO - HTTP Request: PATCH https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/user_daily_usage?user_id=eq.9c13b311-4306-4eec-96b8-9fad440fc6fb&date=eq.20231127 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:51,106 [INFO] models.user_usage: User 495079044@qq.com request count updated to 3
backend-core  | 2023-11-27 17:02:51,231:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.bfb0b151-bdec-4897-b0b1-82a50da1ccc6 "HTTP/1.1 200 OK"
backend-core  | INFO:     13.230.43.211:8601 - "POST /chat/1752594b-f8b0-4183-9bd6-a0ade6f49687/question/stream?brain_id=bfb0b151-bdec-4897-b0b1-82a50da1ccc6 HTTP/1.1" 200 OK
backend-core  | 2023-11-27 17:02:51,382:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/chat_history?select=%2A&chat_id=eq.1752594b-f8b0-4183-9bd6-a0ade6f49687&order=message_time "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:51,505:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.bfb0b151-bdec-4897-b0b1-82a50da1ccc6 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:51,631:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.bfb0b151-bdec-4897-b0b1-82a50da1ccc6 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:51,768:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.bfb0b151-bdec-4897-b0b1-82a50da1ccc6 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:51,879:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.bfb0b151-bdec-4897-b0b1-82a50da1ccc6 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:52,019:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.bfb0b151-bdec-4897-b0b1-82a50da1ccc6 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:52,156:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.bfb0b151-bdec-4897-b0b1-82a50da1ccc6 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:52,258:INFO - HTTP Request: POST https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/chat_history "HTTP/1.1 201 Created"
backend-core  | 2023-11-27 17:02:52,377:INFO - HTTP Request: GET https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/brains?select=id%3Abrain_id%2C%20name%2C%20%2A&brain_id=eq.bfb0b151-bdec-4897-b0b1-82a50da1ccc6 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:54,185:INFO - HTTP Request: POST https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/rpc/match_vectors "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:55,607 [INFO] llm.qa_base: No source documents found or source_documents is not a list.
backend-core  | 2023-11-27 17:02:55,743:INFO - HTTP Request: PATCH https://bnheubdenjlyzjkdjsgq.supabase.co/rest/v1/chat_history?message_id=eq.b4bc4325-1a9c-477a-9533-a079dee22656 "HTTP/1.1 200 OK"
backend-core  | 2023-11-27 17:02:55,745 [INFO] repository.chat.update_message_by_id: Message b4bc4325-1a9c-477a-9533-a079dee22656 updated
