### ISSUE TITLE
[Bug]: First time migration.sh create all tables workflow yielding 'ERROR:  relation "migrations" does not exist'

### ISSUE THREAD

**Issue by sebastiantimwagner** [StanGirard/quivr#1775]
### What happened?

I'm running the `./install_helper.sh` script for the first time on an empty Supabase database. After having input all the credentials and secrets, I select `'Create all tables (First Time)'`. It was my impression that this will create all necessary tables that I need in the database. However, it outputs an error that the migrations table does not exist.
The local repo is on `commit d29a69c863827aa794e690147e8f1f5cd2288e24`. 
Expected behavior from my side would be that it creates the migrations table and any other relevant table. I'm executing this on Ubuntu 22.04 with the fish shell, but bash yields the same behavior. 

### Relevant log output

```bash
⋊> ~/quivr on main ◦ ./install_helper.sh                                                                                                                                      10:51:07
Running the migration scripts...
ERROR:  relation "migrations" does not exist
LINE 1: SELECT name FROM migrations ORDER BY executed_at DESC LIMIT ...
                         ^
Error running migration scripts.
```

**Comment by StanGirard** [comment]
Fixed :)

**Comment by sebastiantimwagner** [comment]
Thanks @StanGirard and @namas191297, it's working for me after your fix 🚀🙏
