### ISSUE TITLE
[Feature]: Crawl entire website

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#1789]
### The Feature

<img width="1093" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/fd3e0a39-6e95-4e80-9d24-9624fbf94f1a">

I'd like Quivr to be able to crawl an entire website with a max number of pages. 

### Motivation, pitch

Could be amazing

**Comment by idiglove** [comment]
I'd like to take this on.

Follow up questions:
1. Who sets the max number?
2. If user doesn't set, where can I get this number?
3. If it's ready from an API or something, then I should just display it?

**Comment by StanGirard** [comment]
@idiglove can't wait !

User would set it.

**Comment by joelsprunger** [comment]
I can suggest looking at this...
https://python.langchain.com/docs/templates/rag-gpt-crawler

**Comment by joelsprunger** [comment]
And this...
https://python.langchain.com/docs/integrations/document_loaders/recursive_url

**Comment by joelsprunger** [comment]
I have a good implementation of this working. No front end. But I the backend works well - very fast. It does an asynchronous breadth first search. This fills up a queue with urls and then empties out the queue to extract the text. This allows for better crawl status as you can keep tabs on how many urls are remaining in the queue. We could also log the current depth of the crawler if we want.

**Comment by idiglove** [comment]
Hi @joelsprunger you can assign this ticket to yourself. I still have to get up to speed in this project, and other things in life is busy too. Thanks!

**Comment by joelsprunger** [comment]
Sure thing

**Comment by joelsprunger** [comment]
@StanGirard it looks like there is already a recursive crawl method in crawler.py. Are you happy with this and you just need some frontend work, or do you want the backend crawler changed? I have been working from a forked version of this and I think the breadth first asynchronous crawler is faster, but if you like the recursive crawler that you have then it's just a matter of adding the controls to the frontend.
