### ISSUE TITLE
[Feature]:  Embed a Quivr chat on a website

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#1791]
### The Feature

<img width="1200" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/f8a15271-24c1-418b-a420-76fd9e86736a">

I'd like users to be able to embed a chat on their website. The chat would be connected to a brain. Allowing people to create chatbots on their websites easily.

### Motivation, pitch

Would be amazing

**Comment by MeTaNoV** [comment]
@StanGirard we can discuss this in details since I did an integration of some UI component already but it is not that straightforward...

**Comment by StanGirard** [comment]
@MeTaNoV what i started to do is implement a way to create api keys that can only chat with brains and nothing else.

And yes that would be awesome to reuse components.
