### ISSUE TITLE
[Feature]: API Key Management

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#1793]
### The Feature

Currently when the user creates an API key on quivr.app it is valid until the end of the month. 

I'd like users to be able to:
- See their api keys (hidden a bit)
- See the name of their api keys
- Choose how long they want it to be valid
- See last usage
- Setup rights for api keys. For example I want some api keys to only allow users to chat. Not do anything else. 

This is currently in the user profile

<img width="1121" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/988e89be-2a12-462d-b325-70d7df6df894">

### Motivation, pitch

Tired of updating each month

**Comment by MeTaNoV** [comment]
@StanGirard can you reopen the issue and assign it to me?
