### ISSUE TITLE
Why the hard requirement of using Supabase?

### ISSUE THREAD

**Issue by xD0135** [StanGirard/quivr#181]
This project is quite interesting but I don't understand why the need to make Supabase a hard requirement, which makes it impossible to use it offline within my own environment. Do you mind explaining the reason for this? Requiring a third-party cloud provider sort of defeats this statement, since you don't have full control of the environment:
> Secure: Your data, your control. Always.

Since you're already using docker compose, why not reference a local Postgresql instance instead? Thanks.

**Comment by StanGirard** [comment]
Hello 👋 thanks for the question. The project is two weeks old and supabase allows you to have a database for free with pgvector running. I used it at first in the demo because I needed a database.  

We will move away from supabase in the following weeks for the vector store and add a PostgreSQL integration. We just don't have the time yet :)

**Comment by EgyptianM** [comment]
> Hello 👋 thanks for the question. The project is two weeks old and supabase allows you to have a database for free with pgvector running. I used it at first in the demo because I needed a database.
> 
> We will move away from supabase in the following weeks for the vector store and add a PostgreSQL integration. We just don't have the time yet :)
> 
> I haven't had the time but supabase is opensource and is dockered. So we could run supabase locally

Did you make PostgreSQL integration or not yet?

**Comment by SAPSentinel** [comment]
How to use ./migration.sh if supabase is setup as docker container. 
There is one issue though. Docker supabase doesn't have many of the options as cloud version. 
No option even to see parameters like keys, JWT or passwords.

Can anyone provide a dockerfile or docker compose.yml to have both supabase and quivr running as one stack. Thanks.

![image](https://github.com/StanGirard/quivr/assets/69308174/1e3c52b0-d8e4-4d8d-ad6b-fe3397917051)
