### ISSUE TITLE
[Dark mode]: Dark mode is not working problem.

### ISSUE THREAD

**Issue by sakthi-lucia0567** [StanGirard/quivr#1818]
### What happened?

Dark mode is not working properly, text is not visible when in the dark mode 
hers is the ss of the problem.

![image](https://github.com/StanGirard/quivr/assets/81083482/8e0bc4f0-c543-45d0-bab6-3a78a83d71a5)

also ss fro light mode.
![image](https://github.com/StanGirard/quivr/assets/81083482/5529c730-a210-42d4-bcfb-76330a19bcb6)

### Twitter / LinkedIn details

https://www.linkedin.com/in/sakthivela/

**Comment by danboyce92** [comment]
Pretty sure this bug has been resolved now
