### ISSUE TITLE
[Bug]: Hero Page is not properly visible

### ISSUE THREAD

**Issue by MaruthiKo** [StanGirard/quivr#1852]
### What happened?

I am unable to see the Hero section of the website on my device. I am using ASUS Vivo Book 14.  To replicate this issue use dev tools and set the resolution to 1024 x 620. I have added a Screenshot of the bug. If possible I would like to work on it.
<img width="906" alt="Quivr" src="https://github.com/StanGirard/quivr/assets/63769209/4658f86e-8f62-4150-ab03-025219057458">

**Comment by StanGirard** [comment]
Thanks !

**Comment by NeerajBhandari007** [comment]
Assign this issue to me I can contribute to the solve this issue
