### ISSUE TITLE
supabase.client.SupabaseException: Invalid URL.

### ISSUE THREAD

**Issue by yujian-cool** [StanGirard/quivr#186]
In the Ubuntu 20.04 operating system, the function os.environ.get("SUPABASE_URL") retrieves an environmental variable that contains additional quotation marks "", causing the error supabase.client.SupabaseException: Invalid URL.

**Comment by mamadoudicko** [comment]
In the .backend_env.example file, there are some extra quotation marks around the `SUPABASE_URL` variable. When setting the value, please exclude those quotation marks.

For instance, instead of:

```SUPABASE_URL="https://*.supabase.co"```

You should have:

```SUPABASE_URL=https://*.supabase.co```

**Comment by yujian-cool** [comment]
Yes, I've solved the issue, thank you.
To prevent others from encountering the same problem, I believe the author should adjust the env.example file.

**Comment by mamadoudicko** [comment]
Thank you for your suggestion!

The env files have been adjusted in this PR https://github.com/StanGirard/quivr/pull/189
