### ISSUE TITLE
[Bug]:  Error in docker-compose-ollama.yml

### ISSUE THREAD

**Issue by bw-Deejee** [StanGirard/quivr#1871]
### What happened?

Hi.
I followed the [installation guide in the readme](https://github.com/StanGirard/quivr#60-seconds-installation-) using Quivr with Ollama instead of OpenAI.

I made my way to step 4: where im told to run
`docker compose -f docker-compose-ollama.yml up --build`

This results in the following error:
`failed to solve: process "/bin/sh -c apt-get clean && apt-get update && apt-get install -y     libgeos-dev     libcurl4-openssl-dev     libssl-dev     binutils     pandoc     curl     git     poppler-utils     tesseract-ocr     build-essential &&     rm -rf /var/lib/apt/lists/* && apt-get clean" did not complete successfully: exit code: 100`

I've seen other issues with the same problem:
https://github.com/StanGirard/quivr/issues/915 - propsed fix does not fix the issure for me
https://github.com/StanGirard/quivr/issues/1640 - no real answere. `docker system prune` didn't help

Side note: I'm on a Azure VM (ubuntu), with a proxy, which i configured correctly so up until this step everything could be installed and downloaded correctly, but maybe there is some additional twist here. Please help 🥲

**Comment by bw-Deejee** [comment]
Not a helpful answer. Can anyone have a look at this?

**Comment by StanGirard** [comment]
try `docker system prune --all --force --volumes`

Sometimes when debian releases a new version of their packages you need to rebuild the entire thing.

**Comment by bw-Deejee** [comment]
Thanks for your response. I tried it, but I still get the same error.
Here is the full output:

```
------
 > [beat 3/9] RUN apt-get clean && apt-get update && apt-get install -y     libgeos-dev     libcurl4-openssl-dev     libssl-dev     binutils     pandoc     curl     git     poppler-utils     tesseract-ocr     build-essential &&     rm -rf /var/lib/apt/lists/* && apt-get clean:
30.86 Err:1 http://deb.debian.org/debian bullseye InRelease
30.86   Could not connect to debian.map.fastlydns.net:80 (146.75.122.132), connection timed out Unable to connect to deb.debian.org:http:
30.86 Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
30.86   Unable to connect to deb.debian.org:http:
30.86 Err:3 http://deb.debian.org/debian bullseye-updates InRelease
30.86   Unable to connect to deb.debian.org:http:
30.86 Reading package lists...
30.87 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not connect to debian.map.fastlydns.net:80 (146.75.122.132), connection timed out Unable to connect to deb.debian.org:http:
30.87 W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Unable to connect to deb.debian.org:http:
30.87 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Unable to connect to deb.debian.org:http:
30.87 W: Some index files failed to download. They have been ignored, or old ones used instead.
30.87 Reading package lists...
30.88 Building dependency tree...
30.88 Reading state information...
30.88 E: Unable to locate package libgeos-dev
30.88 E: Unable to locate package libcurl4-openssl-dev
30.88 E: Unable to locate package libssl-dev
30.88 E: Unable to locate package binutils
30.88 E: Unable to locate package pandoc
30.88 E: Unable to locate package curl
30.88 E: Unable to locate package git
30.88 E: Unable to locate package poppler-utils
30.88 E: Unable to locate package tesseract-ocr
30.88 E: Unable to locate package build-essential
------
failed to solve: process "/bin/sh -c apt-get clean && apt-get update && apt-get install -y     libgeos-dev     libcurl4-openssl-dev     libssl-dev     binutils     pandoc     curl     git     poppler-utils     tesseract-ocr     build-essential &&     rm -rf /var/lib/apt/lists/* && apt-get clean" did not complete successfully: exit code: 100
```
