### ISSUE TITLE
Supabase invalid URL error

### ISSUE THREAD

**Issue by Elicherla01** [StanGirard/quivr#188]
# Issue template for Quivr - Your Second Brain, Empowered by Generative AI

I am using MacOS Apli1 M1 max

While doing Docker compose up I am getting below error. I gave a print statement for supabase_url and SUPABASE_SERVICE_KEY. I see them as supabase_url XXXXX and supabase_key eyXXXXX. Please help

<img width="1142" alt="image" src="https://github.com/StanGirard/quivr/assets/14846630/1c079e83-42d6-4cfd-8257-3e62b4300651">

**Comment by mamadoudicko** [comment]
Hi @ravindraprasad75,

Just a quick check: Did you create the `/backend/.env` file and update the relevant values (e.g., `SUPABASE_URL` and `SUPABASE_SERVICE_KEY`) as instructed in the README file's "Installation Steps 💽"?

**Comment by nathan927** [comment]
> 

I also did it but encountered the same error. Thanks.

**Comment by ravindraprasad75** [comment]
> 

Yes @mamadoudicko . I followed to the T

**Comment by tommy3wood** [comment]
Seeing the same issue.
