### ISSUE TITLE
Data leaking to OpenAI?

### ISSUE THREAD

**Issue by xD0135** [StanGirard/quivr#190]
As I'm playing around with this project, I purposefully added an incorrect API key under `backend/.env:OPENAI_API_KEY` as I wanted my data to stay local, but after going to http://localhost:3000/upload and uploading a file, it seems that Quivr actually tries to upload the content to OpenAI and the operation fails:
```
backend     | INFO:     127.0.0.1:30156 - "OPTIONS /upload HTTP/1.1" 200 OK
backend     | 2023-05-28 21:34:19,534:INFO - error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
backend     | INFO:     127.0.0.1:30156 - "POST /upload HTTP/1.1" 500 Internal Server Error
backend     | ERROR:    Exception in ASGI application
```
Can you help me understand what is taking place regarding the interaction with OpenAI? This would certainly go against the premise of this project:
>Secure: Your data, your control. Always.

Thanks.

**Comment by StanGirard** [comment]
Can you please explain why using the API goes again the security of the data ? 

Please read the Data usage policies of OpenAI
<img width="1608" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/efc4ccd3-66ef-4dfa-be33-a725816475d8">


Link here if needed https://openai.com/policies/api-data-usage-policies

**Comment by StanGirard** [comment]
Not an issue. Closing ;)

**Comment by HelloJack0** [comment]
I have also been very curious, how to call openAPI and ensure that the data is local. It seems that we have misunderstood it. This security refers to the non-shared data mode of choosing to call the API.
