### ISSUE TITLE
[Bug]: docker compose gets stuck on  Creating an optimized production build...

### ISSUE THREAD

**Issue by webyacusa** [StanGirard/quivr#1911]
### What happened?

I am trying to run Quivr on a Mac with Sonoma 14.2 (M1 max chip). After I run the docker compose up, it runs for a little bit, but then it gets stuck when building the front end with next, more specifically on this line:

- info Creating an optimized production build...

Any suggestions what to do?

### Relevant log output

```bash
[...]
[4/4] Building fresh packages...
Done in 69.69s.
--> e726b19d7e9c
[3/4] STEP 1/17: FROM 65c1498de5cce7da532b9fdb61b194f09e076aec1184c2f67d0888d33c1754ef AS builder
[3/4] STEP 2/17: WORKDIR /app
--> 8823fed6f898
[3/4] STEP 3/17: COPY --from=deps /app/node_modules ./node_modules
--> 5bb3ce19a1e6
[3/4] STEP 4/17: COPY . .
--> 1a52c6416427
[3/4] STEP 5/17: ARG NEXT_PUBLIC_ENV
--> 64127f502070
[3/4] STEP 6/17: ARG NEXT_PUBLIC_BACKEND_URL
--> e1c0164428c9
[3/4] STEP 7/17: ARG NEXT_PUBLIC_SUPABASE_URL
--> 3717aa1b6eb4
[3/4] STEP 8/17: ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
--> d02795bad034
[3/4] STEP 9/17: ARG NEXT_PUBLIC_CMS_URL
--> bddaaed14f07
[3/4] STEP 10/17: ARG NEXT_PUBLIC_FRONTEND_URL
--> 3c418800e892
[3/4] STEP 11/17: ENV NEXT_PUBLIC_ENV=$NEXT_PUBLIC_ENV
--> 82fc12c87da5
[3/4] STEP 12/17: ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
--> 1362d9d48e92
[3/4] STEP 13/17: ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
--> ef56abd451ed
[3/4] STEP 14/17: ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
--> 77c93f502ce9
[3/4] STEP 15/17: ENV NEXT_PUBLIC_CMS_URL=$NEXT_PUBLIC_CMS_URL
--> 44e3ae083620
[3/4] STEP 16/17: ENV NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL
--> 50fb63e8e41b
[3/4] STEP 17/17: RUN yarn build
yarn run v1.22.19
$ next build
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

- info Creating an optimized production build...
```

**Comment by abdulkabiraliyu** [comment]
I am also stuck on creating an optimized build during docker-compose build


=> CACHED [flower 8/8] COPY . .                                                                                                                                                                         0.0s
 => [flower] exporting to image                                                                                                                                                                          0.0s
 => => exporting layers                                                                                                                                                                                  0.0s
 => => writing image sha256:65714335f8de7e8504dfa7bce4f1c2fecf992b31b90536f30d4cc3c85e632c01                                                                                                             0.0s
 => => naming to docker.io/stangirard/quivr-backend-prebuilt:latest                                                                                                                                      0.0s
 => [frontend deps 1/5] RUN apk add --no-cache libc6-compat python3 make g++                                                                                                                             4.8s
 => [frontend runner 1/8] WORKDIR /app                                                                                                                                                                   0.1s
 => [frontend runner 2/8] RUN addgroup --system --gid 1001 nodejs                                                                                                                                        0.9s
 => [frontend runner 3/8] RUN adduser --system --uid 1001 nextjs                                                                                                                                         0.8s
 => [frontend deps 2/5] RUN yarn global add node-gyp                                                                                                                                                     4.3s
 => [frontend deps 3/5] WORKDIR /app                                                                                                                                                                     0.0s
 => [frontend deps 4/5] COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./                                                                                                               0.2s
 => [frontend deps 5/5] RUN     if [ -f yarn.lock ]; then yarn --frozen-lockfile;     elif [ -f package-lock.json ]; then npm ci;     elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i  127.7s
 => [frontend builder 2/4] COPY --from=deps /app/node_modules ./node_modules                                                                                                                            43.6s
 => [frontend builder 3/4] COPY . .                                                                                                                                                                      0.9s
 => [frontend builder 4/4] RUN yarn build                                                                                                                                                               59.3s
 => => # $ next build                                                                                                                                                                                        
 => => # Attention: Next.js now collects completely anonymous telemetry regarding usage.                                                                                                                     
 => => # This information is used to shape Next.js' roadmap and prioritize features.                                                                                                                         
 => => # You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:                                                             
 => => # https://nextjs.org/telemetry                                                                                                                                                                        
 => => # - info Creating an optimized production build...

**Comment by abdulkabiraliyu** [comment]
@dosubot

I am also stuck on creating an optimized build during docker-compose build

=> CACHED [flower 8/8] COPY . . 0.0s
=> [flower] exporting to image 0.0s
=> => exporting layers 0.0s
=> => writing image sha256:65714335f8de7e8504dfa7bce4f1c2fecf992b31b90536f30d4cc3c85e632c01 0.0s
=> => naming to docker.io/stangirard/quivr-backend-prebuilt:latest 0.0s
=> [frontend deps 1/5] RUN apk add --no-cache libc6-compat python3 make g++ 4.8s
=> [frontend runner 1/8] WORKDIR /app 0.1s
=> [frontend runner 2/8] RUN addgroup --system --gid 1001 nodejs 0.9s
=> [frontend runner 3/8] RUN adduser --system --uid 1001 nextjs 0.8s
=> [frontend deps 2/5] RUN yarn global add node-gyp 4.3s
=> [frontend deps 3/5] WORKDIR /app 0.0s
=> [frontend deps 4/5] COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./ 0.2s
=> [frontend deps 5/5] RUN if [ -f yarn.lock ]; then yarn --frozen-lockfile; elif [ -f package-lock.json ]; then npm ci; elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i 127.7s
=> [frontend builder 2/4] COPY --from=deps /app/node_modules ./node_modules 43.6s
=> [frontend builder 3/4] COPY . . 0.9s
=> [frontend builder 4/4] RUN yarn build 59.3s
=> => # $ next build
=> => # Attention: Next.js now collects completely anonymous telemetry regarding usage.
=> => # This information is used to shape Next.js' roadmap and prioritize features.
=> => # You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
=> => # https://nextjs.org/telemetry
=> => # - info Creating an optimized production build...

**Comment by abdulkabiraliyu** [comment]
> ### What happened?
> I am trying to run Quivr on a Mac with Sonoma 14.2 (M1 max chip). After I run the docker compose up, it runs for a little bit, but then it gets stuck when building the front end with next, more specifically on this line:
> 
> * info Creating an optimized production build...
> 
> Any suggestions what to do?
> 
> ### Relevant log output
> ```shell
> [...]
> [4/4] Building fresh packages...
> Done in 69.69s.
> --> e726b19d7e9c
> [3/4] STEP 1/17: FROM 65c1498de5cce7da532b9fdb61b194f09e076aec1184c2f67d0888d33c1754ef AS builder
> [3/4] STEP 2/17: WORKDIR /app
> --> 8823fed6f898
> [3/4] STEP 3/17: COPY --from=deps /app/node_modules ./node_modules
> --> 5bb3ce19a1e6
> [3/4] STEP 4/17: COPY . .
> --> 1a52c6416427
> [3/4] STEP 5/17: ARG NEXT_PUBLIC_ENV
> --> 64127f502070
> [3/4] STEP 6/17: ARG NEXT_PUBLIC_BACKEND_URL
> --> e1c0164428c9
> [3/4] STEP 7/17: ARG NEXT_PUBLIC_SUPABASE_URL
> --> 3717aa1b6eb4
> [3/4] STEP 8/17: ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
> --> d02795bad034
> [3/4] STEP 9/17: ARG NEXT_PUBLIC_CMS_URL
> --> bddaaed14f07
> [3/4] STEP 10/17: ARG NEXT_PUBLIC_FRONTEND_URL
> --> 3c418800e892
> [3/4] STEP 11/17: ENV NEXT_PUBLIC_ENV=$NEXT_PUBLIC_ENV
> --> 82fc12c87da5
> [3/4] STEP 12/17: ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
> --> 1362d9d48e92
> [3/4] STEP 13/17: ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
> --> ef56abd451ed
> [3/4] STEP 14/17: ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
> --> 77c93f502ce9
> [3/4] STEP 15/17: ENV NEXT_PUBLIC_CMS_URL=$NEXT_PUBLIC_CMS_URL
> --> 44e3ae083620
> [3/4] STEP 16/17: ENV NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL
> --> 50fb63e8e41b
> [3/4] STEP 17/17: RUN yarn build
> yarn run v1.22.19
> $ next build
> Attention: Next.js now collects completely anonymous telemetry regarding usage.
> This information is used to shape Next.js' roadmap and prioritize features.
> You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> https://nextjs.org/telemetry
> 
> - info Creating an optimized production build...
> ```
> 
> ### Twitter / LinkedIn details
> _No response_

Please sir, how are you able to solve this issue

**Comment by webyacusa** [comment]
> > ### What happened?
> > I am trying to run Quivr on a Mac with Sonoma 14.2 (M1 max chip). After I run the docker compose up, it runs for a little bit, but then it gets stuck when building the front end with next, more specifically on this line:
> > 
> > * info Creating an optimized production build...
> > 
> > Any suggestions what to do?
> > ### Relevant log output
> > ```shell
> > [...]
> > [4/4] Building fresh packages...
> > Done in 69.69s.
> > --> e726b19d7e9c
> > [3/4] STEP 1/17: FROM 65c1498de5cce7da532b9fdb61b194f09e076aec1184c2f67d0888d33c1754ef AS builder
> > [3/4] STEP 2/17: WORKDIR /app
> > --> 8823fed6f898
> > [3/4] STEP 3/17: COPY --from=deps /app/node_modules ./node_modules
> > --> 5bb3ce19a1e6
> > [3/4] STEP 4/17: COPY . .
> > --> 1a52c6416427
> > [3/4] STEP 5/17: ARG NEXT_PUBLIC_ENV
> > --> 64127f502070
> > [3/4] STEP 6/17: ARG NEXT_PUBLIC_BACKEND_URL
> > --> e1c0164428c9
> > [3/4] STEP 7/17: ARG NEXT_PUBLIC_SUPABASE_URL
> > --> 3717aa1b6eb4
> > [3/4] STEP 8/17: ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
> > --> d02795bad034
> > [3/4] STEP 9/17: ARG NEXT_PUBLIC_CMS_URL
> > --> bddaaed14f07
> > [3/4] STEP 10/17: ARG NEXT_PUBLIC_FRONTEND_URL
> > --> 3c418800e892
> > [3/4] STEP 11/17: ENV NEXT_PUBLIC_ENV=$NEXT_PUBLIC_ENV
> > --> 82fc12c87da5
> > [3/4] STEP 12/17: ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
> > --> 1362d9d48e92
> > [3/4] STEP 13/17: ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
> > --> ef56abd451ed
> > [3/4] STEP 14/17: ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
> > --> 77c93f502ce9
> > [3/4] STEP 15/17: ENV NEXT_PUBLIC_CMS_URL=$NEXT_PUBLIC_CMS_URL
> > --> 44e3ae083620
> > [3/4] STEP 16/17: ENV NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL
> > --> 50fb63e8e41b
> > [3/4] STEP 17/17: RUN yarn build
> > yarn run v1.22.19
> > $ next build
> > Attention: Next.js now collects completely anonymous telemetry regarding usage.
> > This information is used to shape Next.js' roadmap and prioritize features.
> > You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> > https://nextjs.org/telemetry
> > 
> > - info Creating an optimized production build...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Twitter / LinkedIn details
> > _No response_
> 
> Please sir, how are you able to solve this issue

This issue unfortunately is not solvable. I gave up and started using Secure AI tools: https://github.com/SecureAI-Tools/SecureAI-Tools
