### ISSUE TITLE
[Bug]: Various details frontend

### ISSUE THREAD

**Issue by Yusuke1998** [StanGirard/quivr#1912]
### What happened?

If profile is clicked and turned back, the configured theme changes the color only in some parts. For example, if you had the theme in dark, and you go to profile and then return to the chat, there is text that remains blank even though the background is already light and makes it impossible to see, in addition, the responsive chat also seems to have some problems taking full width.

If a document is attached and the conversation begins, the response in the chat remains incomplete. I don't know if they have a limit of text to generate, but I could see that the response was left halfway without even finishing the paragraph I was writing.

**Comment by pankaj-2503** [comment]
Assign this issue to me i can contribute to the frontend so that it behaved as expected

**Comment by pankaj-2503** [comment]
Initially it was white that why it was not visible i have made some changes on changing theme from light to dark the left box would  look like this . 
![image](https://github.com/StanGirard/quivr/assets/90036864/d8783ea4-f3a3-4102-966b-7891937b967f)
