### ISSUE TITLE
Is it posible to use Quivr in google colab?[Feature]: 

### ISSUE THREAD

**Issue by Ignaciol0** [StanGirard/quivr#1916]
### The Feature

I have been having isues with the docker and I use other ai models on colab so I thought if it was posible to use Quivr in google colab.

### Motivation, pitch

I think this would be a good adition to make the ai more accesible to the less computer literate of us.

**Comment by StanGirard** [comment]
Hey @Ignaciol0, Quivr is a webapp and running it on Google Collabs would require lots of changes and I'm not even sure it is possible. 

I'm closing the issue for now. But don't hesitate to reopen it if anyone has an idea on how to do it.
