### ISSUE TITLE
always need login when visit http://localhost:3000/

### ISSUE THREAD

**Issue by pockywei** [StanGirard/quivr#195]
I have followed the readme. I am not sure why I need login. I have tried signed up and login in, the error message is “invalid api key”

**Comment by iMADi-ARCH** [comment]
Did you click on the a confirmation link sent to your email after you signup?

**Comment by pockywei** [comment]
![image](https://github.com/StanGirard/quivr/assets/12387843/7136579a-0767-4cc9-afbd-6883dc32dc6b)
When I tried sign up,
- there were an error msg “invalid api key”. （openai apikey or Supabase apikey？）
- I did not sign up success（with the error msg）, so I did not receive the confirmation link.

**Comment by iMADi-ARCH** [comment]
It is probably supabase api key as we are using supabase for authentication.

**Comment by mamadoudicko** [comment]
As @iMADi-ARCH  said, it seems that the issue is related to your Supabase API key.

Have you made sure to update the `NEXT_PUBLIC_SUPABASE_ANON_KEY` value in the `/frontend/.env` file

**Comment by pockywei** [comment]
thanks, it works! @mamadoudicko  I did not fill the NEXT_PUBLIC_SUPABASE_ANON_KEY field. I did not aware that the NEXT_PUBLIC_SUPABASE_ANON_KEY is the same as supabase_service_key.

**Comment by mamadoudicko** [comment]
I'm glad to hear that everything is working well now!

**Comment by Buantum** [comment]
hello！I meet the same problem, but I find that my NEXT_PUBLIC_SUPABASE_ANON_KEY is filled with the same as SUPABASE_SERVICE_KEY.

**Comment by Colin-coder** [comment]
@Buantum  You can verify if the NEXT_PUBLIC_SUPABASE_ANON_KEY is correct.
