### ISSUE TITLE
How to overcome the limitations of Supabase's free plan? Is deploying a local Supabase instance a solution without any limitation?

### ISSUE THREAD

**Issue by shiliu2023** [StanGirard/quivr#196]
How to overcome the limitations of Supabase's free plan? Is deploying a local Supabase instance a solution without any limitation?

**Comment by StanGirard** [comment]
What are the limitations you are encountering?

**Comment by shiliu2023** [comment]
Supabase's free plan 500MB

**Comment by StanGirard** [comment]
$$$ 😂
