### ISSUE TITLE
Supabase configuration error after fetch

### ISSUE THREAD

**Issue by andrea-DO** [StanGirard/quivr#197]
While attempting to compile the Quivr application, I encountered an issue related to the Supabase configuration. The issue seems to originate from @supabase/auth-helpers-nextjs/dist/index.js at line 111, function createMiddlewareSupabaseClient. The error message suggests that NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY environment variables, or alternatively, supabaseUrl and supabaseKey parameters are required.

It was correctly working (I already had my keys and url set) until I fetched the latest version from Github this morning, already checked and my .env file is alright.

```
- wait compiling /_error (client and server)...
web      | - error node_modules/@supabase/auth-helpers-nextjs/dist/index.js (111:0) @ createMiddlewareSupabaseClient
web      | - error either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!
web      | null
```

<img width="1249" alt="Screenshot 2023-05-29 at 10 35 28" src="https://github.com/StanGirard/quivr/assets/92207020/9219d1e4-a01f-4c8c-895e-09c46f954a3b">

**Comment by mamadoudicko** [comment]
It seems like the system can't find `NEXT_PUBLIC_SUPABASE_ANON_KEY` and/or `NEXT_PUBLIC_SUPABASE_URL` in `/frontend/.env.` 

Please check the file name (`.env`) and location (`/frontend/`).

Additionally, I found a relevant GitHub discussion that might help. You can check it out [here](https://github.com/orgs/supabase/discussions/3218)

**Comment by andrea-DO** [comment]
The .env files were the old version, I updated them with the new templates from the latest version, and everything works fine.
