### ISSUE TITLE
When using docker compose I get " either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!"

### ISSUE THREAD

**Issue by benhealthee** [StanGirard/quivr#200]
I followed the instructions in the github.
I copied .env and updated the variables.

When I run it by running: "docker compose build && docker compose up"
I am getting in the browser the attached message.
and in the console the following:
"either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!"
<img width="1440" alt="Screenshot 2023-05-29 at 14 02 21" src="https://github.com/StanGirard/quivr/assets/122786658/41437aac-958b-4b6e-bb33-eb6823d1367e">

**Comment by StanGirard** [comment]
Please read the readme and update the .env in frontend.
