### ISSUE TITLE
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by shiliu2023** [StanGirard/quivr#201]
new version.
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

when I upload.

**Comment by StanGirard** [comment]
Hello @shiliu2023 this is not the first but maybe the 4rth issue you open that doesn't follow the standards. Also if you want to chat or ask questions please come to the discord ;) don't open issues ! 

We are not paid to work on this, please make good issues that are relevant so we don't waste our time. 

Issues are bugs. 

You issue is incomplete, doesn't allow reproduction and is not inherent to the code but from a malformed .env file.

**Comment by shiliu2023** [comment]
ok i see。discord
