### ISSUE TITLE
Failed to upload file？

### ISSUE THREAD

**Issue by shiliu2023** [StanGirard/quivr#202]
Failed to upload file: {"message":"Network Error","name":"AxiosError","stack":"AxiosError: Network Error\n    at XMLHttpRequest.handleError (webpack-internal:///(app-client)/./node_modules/axios/lib/adapters/xhr.js:172:14)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjg1MzcwMTk4LCJzdWIiOiI1NjVmMjY0NC0zMmUyLTQxNzUtODJiNy1mOGY5NGQ1YzgyODAiLCJlbWFpbCI6ImJhb3poZW5saUAxMjYuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2ODUzNjY1OTh9XSwic2Vzc2lvbl9pZCI6IjczOWMwNzBkLTQ1YjAtNDUwZC1iZWExLTk5NTQyYWNlNmJhMyJ9.N1Orp3kPTbi879Q1azmV9-jGbq6YN1zK0P6qU6ogA2o"},"method":"post","url":"http://43.xxx.85.139:5050/upload","data":{}},"code":"ERR_NETWORK","status":null}

**Comment by iMADi-ARCH** [comment]
This is due to a network error on your side.
Try doing it again in some time.

**Comment by StanGirard** [comment]
@shiliu2023 do not open another issue that doesn't follow the standards or you'll get banned.
