### ISSUE TITLE
Error while upload files/crawl website

### ISSUE THREAD

**Issue by murrenschwalben** [StanGirard/quivr#209]
Dear Github Community,

I am having trouble uploading files and receiving an error message.

To provide some context, I am using Windows 11 Home 22H2 and have downloaded the latest version of Docker from the official website.
The error message I am receiving reads as follows: 
_Failed to upload file: {"message":"Request failed with status code 404","name":"AxiosError","stack":"AxiosError: Request failed with status code 404\n    at settle (webpack-internal:///(app-client)/./node_modules/axios/lib/core/settle.js:24:12)\n    at XMLHttpRequest.onloadend (webpack-internal:///(app-client)/./node_modules/axios/lib/adapters/xhr.js:121:66)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjg1NDMxOTU2LCJzdWIiOiIwZjFjOTY1OS1hMjY0LTRhNDctOWRkMC02Nzk5M2M3OTA5Y2MiLCJlbWFpbCI6Imx5MTAwNjk4MTczQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnt9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6Im90cCIsInRpbWVzdGFtcCI6MTY4NTQyODM1Nn1dLCJzZXNzaW9uX2lkIjoiZjQyNDVjNWUtZmU2Mi00ZTFlLTlkZDMtZTc1MmQzNmVkMjk3In0.BVyBuMYLrMdP68iq3bA6Zpz4dJvBTq2M-8P_YkuHwIs"},"method":"post","url":"undefined/upload","data":{}},"code":"ERR_BAD_REQUEST","status":404}_

I would greatly appreciate any guidance on how to resolve this issue. Thank you for your time and assistance.

![testquivr](https://github.com/StanGirard/quivr/assets/39298699/336cd793-7c85-4a80-a8bb-7597aed6f0ff)

**Comment by mamadoudicko** [comment]
@murrenschwalben, it appears that your `.env` file in the `frontend` directory does not have the `NEXT_PUBLIC_BACKEND_URL` variable set. 

This variable is required for the proper functioning of the application. 

You can find detailed instructions on how to set it in the installation steps mentioned in the [following link](https://github.com/StanGirard/quivr#installation-steps-). 

Please make sure to follow the instructions carefully to ensure the correct configuration of your environment.

**Comment by murrenschwalben** [comment]
> 

THX sir! It worked. I added "NEXT_PUBLIC_BACKEND_URL=http://localhost:5050" like the .env.example file did and it worked. Now the issue's perfectly fixed.

**Comment by technyx-ali-rehman** [comment]
> @murrenschwalben, it appears that your `.env` file in the `frontend` directory does not have the `NEXT_PUBLIC_BACKEND_URL` variable set.
> 
> This variable is required for the proper functioning of the application.
> 
> You can find detailed instructions on how to set it in the installation steps mentioned in the [following link](https://github.com/StanGirard/quivr#installation-steps-).
> 
> Please make sure to follow the instructions carefully to ensure the correct configuration of your environment.

I already have this but I am still getting mixed content over https if i force on http everything works perfectly

Any clues what could be the issue ?

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/257

**Comment by Linus6666** [comment]
> > 
> 
> 谢谢先生！有效。我像 .env.example 文件一样添加了“NEXT_PUBLIC_BACKEND_URL= [http://localhost:5050 ”并且它起作用了。](http://localhost:5050)现在问题已经完美解决。

My front end .env have **NEXT_PUBLIC_BACKEND_URL=http://localhost:5050**, but still happened the same issue, can you tell me the detail how you fixed this issue?

**Comment by highly-illiquid** [comment]
bump.. I'm still having the same issue

**Comment by wardle2403** [comment]
bump.. I'm still having the same issue

**Comment by sagaholdennoren** [comment]
Has this been solved? 404 usually is a missing page or missing internet connection. But how does Quivr browse the urls, like a chrome plugin? In my instance of Quivr (0.0.61), when adding an url it only saves the damn cookie notices of the urls uploaded and I've been looking for a way to get around this.
