### ISSUE TITLE
ABackend, I'm deployed in Vercel

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#210]
- Deploy the backend in vercel

## Acceptance criteria

The backend is deployed

**Comment by johnfelipe** [comment]
Can u share or update readme file with steps for do it?

**Comment by coxxxs** [comment]
We could do a full deployment tutorial

**Comment by giachat** [comment]
Tutorial would be awesome!

**Comment by StanGirard** [comment]
This is a user story of the next feature 😂 not implemented yet. I'll do it tomorrow probably

**Comment by masapasa** [comment]
Hi @StanGirard did you host both fastapi backend and nextjs frontend in vercel? Any detailed instructions that i can follow? Thanks a a lot!

**Comment by youmengme** [comment]
Looking forward to it
