### ISSUE TITLE
How to run Quivr and Supabase on the same system

### ISSUE THREAD

**Issue by Mirloc608** [StanGirard/quivr#214]
I have installed Supabase on a linux installation, (using their Docker installer) and have also added Quivr on the same system, I've come to find that Quivr and Supabase use the same port (3000). Is there a way to use a different port in Quivr?

Thanks

**Comment by technyx-ali-rehman** [comment]
@Mirloc608 
You can change your frontend port from 3000 to any port you like

For this you might have to edit 
- docker-compose.yml
- inside frontend folder DockerFile

Edit these 2 files and modify the port configs and serve the project again, hopefully that should fix your conflicting ports issue
