### ISSUE TITLE
When I upload a document, I get the following error.

### ISSUE THREAD

**Issue by ken723** [StanGirard/quivr#220]
When I upload a document, I get the following error.
![e4c59c48fa43084c58c0800012286cd](https://github.com/StanGirard/quivr/assets/28696619/2ade37ab-2169-4f23-8a9c-3be9e9377fbf)

**Comment by technyx-ali-rehman** [comment]
@ken723 
Is it just scroll or Crawl also doesn't work ?

Are you on https ?

**Comment by santhosh82** [comment]
I am seeing the same issue and I am not on https.
