### ISSUE TITLE
Uploads success but doesn't show up

### ISSUE THREAD

**Issue by technyx-ali-rehman** [StanGirard/quivr#225]
I have uploaded 6 files and all are showing up but when i add the 7th file it shows success but it never shows up in the list
and no error

any ideas ?

**Comment by technyx-ali-rehman** [comment]
Closing this found out that there is Max rows limit set on SUPABASE in database settings
by default its set to 1000 i modified to my needs and its working perfectly now

**Comment by jameshburt** [comment]
Maybe the root file is hidden as the root, look under hidden-files.
