### ISSUE TITLE
What is the specification of the machine to run Quivr? 

### ISSUE THREAD

**Issue by ashokrs** [StanGirard/quivr#230]
I did this project on an AWS EC2 Instance (r5a.large)
r5a.large | Mem: 16 GiB | 2 vCPUs | Storage: EBS only | Network: Up to 10 Gigabit | Linux On Demand Cost: $0.1130 hourly 

However, after I bring up "docker compose up", the system struggles to perform and complains about lack of memory. Please note that I installed "X2go" server on the EC2 instance and connected from my windows laptop using x2go client. The x2go launch on to the instance is very slow. Why the docker is making it slower?

What am I doing wrong? Why would the system struggle with 2 CPUs and 16 GB RAM?

**Comment by astorm-z** [comment]
i got the same problem
