### ISSUE TITLE
File name too long overflow

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#232]
<img width="854" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/bd99161a-de67-44b7-a29b-647729140fbc">

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by tarunsamanta2k20** [comment]
do you want any truncation patterns?

**Comment by iMADi-ARCH** [comment]
Reference - https://tailwindcss.com/docs/word-break

Adding a `break-all` class wraps everything including whole words should this be the intended behaviour? @StanGirard 

```tsx
        <p className="text-lg leading-tight max-w-sm break-all">
          {document.name}
        </p>
```
![image](https://github.com/StanGirard/quivr/assets/61308761/9690cafc-b506-40a8-8e50-aa523fc97ec3)
in (1) MDN is a whole word but it gets wrapped

**Comment by mamadoudicko** [comment]
LGTM!

Short comment on the section [here](https://github.com/StanGirard/quivr/issues/233#issuecomment-1575057088)

**Comment by tarunsamanta2k20** [comment]
I am getting this error upon running the server.
![image](https://github.com/StanGirard/quivr/assets/55488549/5bee4ade-d64a-4782-aa23-8063dd82f0b4)

**Comment by StanGirard** [comment]
@tarunsamanta2k20 this is not the place for this issue. 
Also this issue means you haven't changed the supabase URL in your env files ;)

**Comment by tarunsamanta2k20** [comment]
@StanGirard  2023-06-04 18:51:40,456:INFO - error_code=None error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False

**Comment by StanGirard** [comment]
@tarunsamanta2k20 please open an issue for your issue 😂
