### ISSUE TITLE
File name too long overflow Explore content

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#233]
<img width="1104" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/f26b90b6-a6ef-4cda-a80a-1925455b3836">

**Comment by tarunsamanta2k20** [comment]
What will be the expected behavior?

**Comment by StanGirard** [comment]
Good question 😊 what's your take ?

**Comment by tarunsamanta2k20** [comment]
@StanGirard by using css Or dynamic container.

**Comment by StanGirard** [comment]
Overflow probably no ?

**Comment by tarunsamanta2k20** [comment]
Do you want whole filename?

**Comment by mamadoudicko** [comment]
@tarunsamanta2k20 

For the modal title (one line), using a format like `3f98cf88-5b96-44e2-a2£4....pdf` (part of name + extension) or `3f98cf88-5b96-44e2-a2£4- e91...`(filename with ellipsis) appears suitable

Regarding the filename attributes, we have two options: displaying the full name (in multiple lines) or using the same pattern as mentioned above

Go ahead and enjoy yourself!
