### ISSUE TITLE
Save chat history in local storage

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#234]
When I refresh or change page I loose chat History.

I should be able to come back to it and also reset the chat

<img width="1133" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/8e452cdd-5c0f-462a-8ec2-3009cc7b4209">

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by StanGirard** [comment]
Go ahead :)

**Comment by mamadoudicko** [comment]
@tarunsamanta2k20  👍🏽

Feel free to regularly push your code without hesitation (sharing your progress and gathering small feedbacks)

You can also join our Discord community for further interaction

Enjoy it!

**Comment by tarunsamanta2k20** [comment]
is it done?

**Comment by StanGirard** [comment]
Nope

**Comment by tarunsamanta2k20** [comment]
@StanGirard if you have any API key for use then please share it. I have tried creating new api key, nothing works.

**Comment by ravikiranp123** [comment]
Can we close this as https://github.com/StanGirard/quivr/pull/267 is merged?
