### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#238]
We currently don't have a footer :D 

It would be nice to have a footer that ->
- Redirects to Github
- Redirects to Twitter

**Comment by ynzulak** [comment]
Hello? Can you work on this issue?

**Comment by StanGirard** [comment]
Yes please 🙏 

I just have a deadline in 36h. 

If not done by then I'll do it. No pressure 😂😘

**Comment by ynzulak** [comment]
@shuruheel thanks for stealing my task... ;) I was about to do this in the morning...

**Comment by StanGirard** [comment]
You can always improve the footer ;)

**Comment by StanGirard** [comment]
There are some small issues

**Comment by ynzulak** [comment]
i think ill pass. Do it by yourself. I was having so much problems with this freacking docker and my memory and someone just stole my task without asking. Such a waste of time

**Comment by StanGirard** [comment]
That is the beauty of open source. 
That is why features need to be small. You never know when someone will publish code. 

Thanks a lot for your enthusiasm 🤩 hope you'll find something you like

**Comment by sheldor07** [comment]
Hey, I just checked and there is a footer on the website. Is this issue still open and if so, what sort of improvements are you looking for?
