### ISSUE TITLE
Need guidance/explaination on SUPABASE envs

### ISSUE THREAD

**Issue by yhyu13** [StanGirard/quivr#245]
Question:

.env for backend contains such envs, where I found on my supabase project page
```
SUPABASE_URL=XXXXX
SUPABASE_SERVICE_KEY=eyXXXXX
```

But there are also supabase env in the frontend .env
```
NEXT_PUBLIC_SUPABASE_URL=XXXX
NEXT_PUBLIC_SUPABASE_ANON_KEY=XXX
```

What values should I fill in these part?

**Comment by sheldor07** [comment]
From what I understand and what worked for me, you should fill in the same to get it up and running in your local environment.
