### ISSUE TITLE
Getting OpenApi RateLimit Error

### ISSUE THREAD

**Issue by tarunsamanta2k20** [StanGirard/quivr#250]
**### Bug Title: Getting OpenApi RateLimit Error when trying to upload a file.**

- Your Operating System: Linux Mint
- Your Docker and Docker Compose versions: Docker version 20.10.7, build f0df350, Docker Compose version v2.18.1
- Your Supabase version and setup: Latest and all good
- Detailed steps to reproduce the issue: Setup your localhost by following ReadMe.md and run localhost:3000 then try to upload any file and observe the console log.
Please remember to use OpenApi api Key.

**Example:**
Screenshots: 

![image](https://github.com/StanGirard/quivr/assets/55488549/3b192b80-4fc3-415e-9eef-28cf9a9624fb)

![image](https://github.com/StanGirard/quivr/assets/55488549/f552e381-6d01-4e82-b91f-9cced60a10af)

Short and descriptive example bug report title

**Current Behavior:** For local host, when i am trying to upload any file then i am getting "openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details."

**Expected Behavior:** This should allow me to upload a file.

**Comment by JarrodWoodard** [comment]
New accounts on OpenAI are rate limited for the first 48 hrs. If you just signed up for the paid API service that could be the cause.
