### ISSUE TITLE
Login credentials required on localhost?

### ISSUE THREAD

**Issue by bartonfriedland** [StanGirard/quivr#261]
When I spin up localhost:3000 it wants a login - when I try to register, it does not complete.

I did not see any instructions for setting up the login in the readme.md. My apologies if I missed something.

**Comment by mamadoudicko** [comment]
Have you properly set your `NEXT_PUBLIC_SUPABASE_URL` and `NEXT_PUBLIC_SUPABASE_ANON_KEY` in `frontend/.env` ?

**Comment by bartonfriedland** [comment]
I believe so - I also see no errors that such is missing in the console
<img width="297" alt="Screenshot 2023-06-06 at 12 36 28" src="https://github.com/StanGirard/quivr/assets/2925476/81256d66-ca67-4c39-ba5f-4d0aecc07129">

**Comment by wholydrops** [comment]
Hey Ive been getting the same error, @bartonfriedland  did you manage to fix it ?

**Comment by bartonfriedland** [comment]
I have not solved it :(

**Comment by Passerby1011** [comment]
Does anyone know how to solve it?

**Comment by Faintabc** [comment]
same problem, tryed all of "Login" discussed topics, still not solved

**Comment by bulijojodibulido** [comment]
![8515dedd5a39b76c3e8f65f6da4904c](https://github.com/StanGirard/quivr/assets/54763152/b6a17681-14e9-4e26-8f4d-0c7b9d4d966b)
supabase.com need to configure

**Comment by bartonfriedland** [comment]
Thanks @bulijojodibulido, but this was already configured as you show on the screen shot

**Comment by BrokenArrow1404** [comment]
Does any know how to fix it? I cant login either

**Comment by tompayne36** [comment]
Similar issue. I am asked for credentials or to create an account. When I try to create an account, I see this

<img width="272" alt="image" src="https://github.com/StanGirard/quivr/assets/77896317/436f34d7-06b7-45df-9d5e-870800d02c92">

**Comment by elarsn** [comment]
I had the same issue but found a solution:

In Supabase under Authentication got to Users and ad a user. This login profile works for me

**Comment by zhouchangxin1** [comment]
> I had the same issue but found a solution:
> 
> In Supabase under Authentication got to Users and ad a user. This login profile works for me


---------------- it works ! thanks for a lot !!
