### ISSUE TITLE
Invalid URL: XXXX/auth/v1

### ISSUE THREAD

**Issue by Sheldenburg** [StanGirard/quivr#265]
https://github.com/StanGirard/quivr/issues/188

![image](https://github.com/StanGirard/quivr/assets/18107058/f1c62d65-2e46-417e-9f1a-29ab5f408452)

I tried everything I can. Have updated .env file in both frontend and backend folder. But I'm still getting this error. I have got supabase api key and url. Please can someone comment? 
![image](https://github.com/StanGirard/quivr/assets/18107058/c5f1fe2f-e1f2-4d5d-8b85-d9898cd96d08)

**Comment by Sheldenburg** [comment]
ok... I'm going to answer my own question... just realised you need to update these two variables in frontend/.env as well! 
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=

**Comment by moyy** [comment]
is same value in NEXT_PUBLIC_SUPABASE_ANON_KEY and SUPABASE_SERVICE_KEY ?

**Comment by romulocordova** [comment]
Do I have to use the same values?

**Comment by Sheldenburg** [comment]
> Do I have to use the same values?

Yes same value as your backend
