### ISSUE TITLE
How do I run this step?

### ISSUE THREAD

**Issue by nyngwang** [StanGirard/quivr#27]
> Run the migration script on the Supabase database via the web interface

Sorry, I'm new to this stuff and this simple sentence is very beginner-unfriendly to me. Could you point me out where to find the web interface?

**Comment by StanGirard** [comment]
<img width="1840" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/dbebf9e9-8e8d-488e-9487-b751f6391e35">

**Comment by StanGirard** [comment]
On your supabase project :)

**Comment by nyngwang** [comment]
Wow! You're super-responsive, thank you <3
