### ISSUE TITLE
Roadmap Quivr

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#272]
Here is the Roadmap of Quivr

[Roadmap](https://getquivr.notion.site/d9ee1a3c5e2547da9d05c0bcdd19f72d?v=e225ca0806fa424db95f12c1eb5d3b26&pvs=4)

If you want to tackle something don't hesitate :)

**Comment by limcheekin** [comment]
Thanks for sharing codes and the roadmap of Quivr.

Regarding "multiple brains per user" not sure what do you have in mind, are you plan to let's user create the brain manually? Personally, I would like to have self-organized and self-discovery brains based on topics of uploaded contents of Quivr.

I just come across of Topic modeling with BERTopic recently. The ChatGPT come back with the following response when I prompted it "Explain BERTopic like I am 5.":
```
BERTopic is like a smart friend who helps organize and understand lots of different stories. Imagine you have a big pile of books, each about different topics. BERTopic can read all those books and figure out what each one is talking about. Then, it puts similar books together in groups, so you can easily find the ones that talk about the same thing. It's like having a magical bookshelf that organizes your books based on what they're about. BERTopic makes it easier for us to understand and explore lots of information by grouping similar things together.
```

You can find out more about BERTopic with the following links:
- https://huggingface.co/blog/bertopic
- https://www.pinecone.io/learn/bertopic/

What do you think? I'd love to hear from you soon. :)

**Comment by tanmay-veer** [comment]
Can it exlplain code from entire git cloned dir :0
Model Wizardcoder 13B
