### ISSUE TITLE
Quivr deployment issues

### ISSUE THREAD

**Issue by coxxxs** [StanGirard/quivr#279]
First of all, I would like to thank you for your open source sharing, which allows me, an Internet novice, to experience such an amazing product. Can the author republish another issue of quivr deployment tutorial?

**Comment by xiaoccai** [comment]
Yes, thank you for the author's sharing. I followed the previous video and still had network issues. I hope to release the latest deployment video again

**Comment by StanGirard** [comment]
You can go to https://quivr.app and try ;)
