### ISSUE TITLE
Chat Memory Problem - instant-Forgot

### ISSUE THREAD

**Issue by darkanubis0100** [StanGirard/quivr#280]
Hello everyone.

Yesterday I was trying to talk to the ChatBot using some PDFs I provided and something intrigued me. In the first message it gave me an answer but when I replied to that message, ChatGPT didn't know what I was talking about. It was almost the same thing you would say if I appeared in front of you one day and said "Yesterday we sure had a good time, we went with camila to the park". ChatGPT has been the same way every time I answer your messages.

**Comment by darkanubis0100** [comment]
> Assistant
> A transformer is a device that changes electrical energy of a given voltage into electrical energy at a different voltage level. It consists of two coils that are not electrically connected, but are arranged so that the magnetic field surrounding one coil cuts through the other coil. When an alternating voltage is applied to (across) one coil, the varying magnetic field set up around that coil creates an alternating voltage in the other coil by mutual induction.
> 
> User
> What kind of phases does it have?
> 
> Assistant
> The context provides information about phase relationships between voltage and current in alternating current circuits. It describes in-phase and out-of-phase conditions, as well as phase differences of 90° and 180° between voltage waves. However, without more specific information about what "it" refers to, I cannot provide a more accurate answer.

As you can see in this example conversation, ChatGPT does not know the message it has sent previously enough to use it as a context. Instead, he thinks it is a new message and answers you with what he thinks is more optimal. If I am talking about transformers, why is he answering me with voltage curves? If I talk directly to ChatGPT or Playground these things don't happen.

**Comment by lewistham9x** [comment]
Happening even on your production site at quivr.app

**Comment by lewistham9x** [comment]
<img width="866" alt="image" src="https://github.com/StanGirard/quivr/assets/3887946/7b405dbd-d5bc-45d2-8828-3dc7a5f2d2cc">

**Comment by darkanubis0100** [comment]
> <img alt="image" width="866" src="https://user-images.githubusercontent.com/3887946/245418636-7b405dbd-d5bc-45d2-8828-3dc7a5f2d2cc.png">

Exactly, that's what I mean. That happens because instead of a Chat he are using the "InstructGPT" architecture, InstructGPT only accepts orders from one way, technically we are in front of a "Text Completion" with Chat appearance.

@StanGirard Any ideas? Sometimes the output that he releases about a book is very interesting but it becomes unfortunate that in the next message he doesn't even know that you had written to him.

**Comment by StanGirard** [comment]
Implemented ;)

**Comment by ebaldaddy** [comment]
Has this issue been fixed.  I'm having exactly the same problem, having just installed everything with the latest yesterday.  It's a very ironic bug considering the entire point of quivr is to have a much larger memory to have conversations with but it doesn't remember/read what you just talked about.
