### ISSUE TITLE
Localhost:3000 doesn't load the app

### ISSUE THREAD

**Issue by tombrewsviews** [StanGirard/quivr#281]
Looks like everything installed and started without errors.
I have passed all the env variables in the end files.
I'm getting this output
<img width="1018" alt="Screenshot 2023-06-08 at 20 05 45" src="https://github.com/StanGirard/quivr/assets/3190986/69410151-f5ef-4e96-b7b8-20704cd564e3">

Nothing on local host, as if the app didn't start. Please help @danielcgilibert @Ruben1701 @StanGirard 
Thank you in advance

**Comment by Ruben1701** [comment]
@tombrewsviews so when going to localhost:3000 is it loading or it doesn't even start the server?
