### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by iamsuperzb** [StanGirard/quivr#282]
# Issue template for Quivr - Your Second Brain, Empowered by Generative AI

Failed to upload file: {"message":"Network Error","name":"AxiosError","stack":"AxiosError: Network Error\n    at u.onerror (http://172.104.217.18:3000/_next/static/chunks/214-44ea1e8cd37dee91.js:6:40676)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjg2MjgyNjc4LCJzdWIiOiI5YjQ0NmVmNy0zZGJiLTQ4MDMtODYxMS1lZjI4NWViNzk3OWIiLCJlbWFpbCI6ImlhbXN1cGVyemJAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoib3RwIiwidGltZXN0YW1wIjoxNjg2Mjc5MDc4fV0sInNlc3Npb25faWQiOiIxMDlhOTI4Mi03MjA1LTRmY2MtYjZlMS0wNjQ4NGZkYTQxZmIifQ.9rUSCM2XwfDGgHaD3ohPUfE7QlvOOwdOti560y6fr4o"},"baseURL":"http://localhost:5050","method":"post","url":"/upload","data":{}},"code":"ERR_NETWORK","status":null}

![image](https://github.com/StanGirard/quivr/assets/20504581/59425729-3d58-4d81-9ac0-a0f212002a8e)

![image](https://github.com/StanGirard/quivr/assets/20504581/29f2cf6b-6ef4-4ad1-a9a1-78d13e7755ec)

Thanx.

**Comment by Wuhall** [comment]
"localhost:5050/upload network:connection:refused"
You should first check if the firewall has opened port 5050.

**Comment by giuliastro** [comment]
I experience a Network Error too. I have everything installed locally in docker (so the firewall is not a problem) and I can correctly see connections open with the backend url. Whenever I try to upload a document I get a Network Error, and this error shows up in the log:

backend  | INFO:     172.22.0.1:44618 - "GET / HTTP/1.1" 200 OK
backend  | INFO:     172.22.0.1:44618 - "GET /favicon.ico HTTP/1.1" 404 Not Found
backend  | INFO:     172.22.0.1:45752 - "POST /upload HTTP/1.1" 500 Internal Server Error
backend  | ERROR:    Exception in ASGI application
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend  |     result = await app(  # type: ignore[func-returns-value]
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend  |     return await self.app(scope, receive, send)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend  |     await super().__call__(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend  |     await self.middleware_stack(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend  |     await self.app(scope, receive, _send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend  |     await self.app(scope, receive, sender)
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend  |     raise e
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend  |     await route.handle(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend  |     response = await func(request)
backend  |                ^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend  |     raw_response = await run_endpoint_function(
backend  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend  |     return await dependant.call(**values)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/main.py", line 42, in upload_file
backend  |     user = User(email=credentials.get('email', 'none'))
backend  |                       ^^^^^^^^^^^^^^^
backend  | AttributeError: 'bool' object has no attribute 'get'

Thank you in advance

**Comment by darkanubis0100** [comment]
@giuliastro You may have the ENV configured incorrectly, check it.

**Comment by zhengr** [comment]
Same error out.
![Xnip2023-06-10_19-31-03](https://github.com/StanGirard/quivr/assets/1487805/ab7a33c1-5e69-43f3-81cc-a0e63b2ccc08)

**Comment by zhengr** [comment]
Same error out.

![Xnip2023-06-10_19-31-03](https://github.com/StanGirard/quivr/assets/1487805/026501f0-c012-4a90-ab24-676eb26b1ac6)

**Comment by darkanubis0100** [comment]
@zhengr https://github.com/StanGirard/quivr/issues/282#issuecomment-1584903335

**Comment by giuliastro** [comment]
> @giuliastro You may have the ENV configured incorrectly, check it.

Could it be because I have Supabase installed locally and not using the cloud service as you have been shown in your videos / instructions? I sincerely don't know what it could be configured wrong since the auth works, meaning Supabase can be accessed.

I don't have GOOGLE_APPLICATION_CREDENTIALS or GOOGLE_CLOUD_PROJECT set but neither I have them set in Supabase, could it be them?

Thank you in advance.

**Comment by giuliastro** [comment]
Just to add some more info, this is the error I see inside Chrome console:

Access to XMLHttpRequest at 'http://localhost:5050/upload' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by giuliastro** [comment]
After the latest git pull the error changed:

backend  | INFO:     Application startup complete.
backend  | INFO:     172.22.0.1:44994 - "OPTIONS /upload HTTP/1.1" 200 OK
backend  | INFO:     172.22.0.1:44994 - "POST /upload HTTP/1.1" 500 Internal Server Error
backend  | ERROR:    Exception in ASGI application
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
backend  |     yield
backend  |   File "/usr/local/lib/python3.11/site-packages/httpcore/backends/sync.py", line 94, in connect_tcp
backend  |     sock = socket.create_connection(
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
backend  |     raise exceptions[0]
backend  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
backend  |     sock.connect(sa)
backend  | OSError: [Errno 99] Cannot assign requested address
backend  |
backend  | During handling of the above exception, another exception occurred:
backend  |
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
backend  |     yield
backend  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 218, in handle_request
backend  |     resp = self._pool.handle_request(req)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
backend  |     response = connection.handle_request(request)
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
backend  |     stream = self._connect(request)
backend  |              ^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 111, in _connect
backend  |     stream = self._network_backend.connect_tcp(**kwargs)
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/httpcore/backends/sync.py", line 93, in connect_tcp
backend  |     with map_exceptions(exc_map):
backend  |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
backend  |     self.gen.throw(typ, value, traceback)
backend  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
backend  |     raise to_exc(exc)
backend  | httpcore.ConnectError: [Errno 99] Cannot assign requested address
backend  |
backend  | The above exception was the direct cause of the following exception:
backend  |
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend  |     result = await app(  # type: ignore[func-returns-value]
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend  |     return await self.app(scope, receive, send)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend  |     await super().__call__(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend  |     await self.middleware_stack(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend  |     await self.app(scope, receive, _send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend  |     await self.app(scope, receive, sender)
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend  |     raise e
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend  |     await route.handle(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend  |     response = await func(request)
backend  |                ^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend  |     raw_response = await run_endpoint_function(
backend  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend  |     return await dependant.call(**values)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/routes/upload_routes.py", line 25, in upload_file
backend  |     .execute()
backend  |      ^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 55, in execute
backend  |     r = self.session.request(
backend  |         ^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 821, in request
backend  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 908, in send
backend  |     response = self._send_handling_auth(
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 936, in _send_handling_auth
backend  |     response = self._send_handling_redirects(
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
backend  |     response = self._send_single_request(request)
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1009, in _send_single_request
backend  |     response = transport.handle_request(request)
backend  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 217, in handle_request
backend  |     with map_httpcore_exceptions():
backend  |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
backend  |     self.gen.throw(typ, value, traceback)
backend  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
backend  |     raise mapped_exc(message) from exc
backend  | httpx.ConnectError: [Errno 99] Cannot assign requested address

**Comment by iamsuperzb** [comment]
If you are using a remote VPS, change NEXT_PUBLIC_BACKEND_URL to your own IP address. It's work 4 me. @giuliastro @zhengr

**Comment by giuliastro** [comment]
Unfortunately, I have everything instaled locally

**Comment by prime-optimal** [comment]
> If you are using a remote VPS, change NEXT_PUBLIC_BACKEND_URL to your own IP address. It's work 4 me. @giuliastro @zhengr
Thanks for the help!

This worked for me.  But also you need to re run docker compose.  For some reason docker build was giving me errors the first time around, but now it seems to have fixed itself and run fine 🤷‍♂️

**Comment by Nachasic** [comment]
Came here because I was experiencing the same issue. I run a local instance via `docker compose up`, and when uploading files in bulk, I get the same behavior. 

However strangely, it works perfectly fine when I upload individual files one-by-one.
