### ISSUE TITLE
The docker-compose build almost made me fall asleep, can we make it faster～

### ISSUE THREAD

**Issue by LvBay** [StanGirard/quivr#284]
Executing docker-compose build two weeks ago could end within 5 minutes, and now it’s almost 10 minutes, and it’s not over yet

**Comment by LvBay** [comment]
![image](https://github.com/StanGirard/quivr/assets/18084744/11336a1d-5323-4555-8141-1759af2fa790)

**Comment by StanGirard** [comment]
The issue is that the docker compose became bigger because we added a lot more things.

I won’t be able to reduce it down. 
I’ll try to push a docker image you can just pull

**Comment by darkanubis0100** [comment]
> The issue is that the docker compose became bigger because we added a lot more things.
> 
> I won’t be able to reduce it down. I’ll try to push a docker image you can just pull

Then what you say makes no sense.

How is it that yesterday I was able to perform the installation in just 112 seconds and he was able to do it in 790 seconds? The answer is simple.

**Comment by LvBay** [comment]
> 

Great！Looking forward to it

**Comment by LvBay** [comment]
> The issue is that the docker compose became bigger because we added a lot more things.
> 
> I won’t be able to reduce it down. I’ll try to push a docker image you can just pull

Great！Look forward to it
