### ISSUE TITLE
When I upload the file, there will appear the error, what should I do to deal it?

### ISSUE THREAD

**Issue by BUAAZFK** [StanGirard/quivr#285]
![image](https://github.com/StanGirard/quivr/assets/92039791/91a8715b-94da-400e-ad86-88a76424c258)

**Comment by darkanubis0100** [comment]
> ![image](https://user-images.githubusercontent.com/92039791/244711053-91a8715b-94da-400e-ad86-88a76424c258.png)

If you were using the OpenAI Free Trial, you have already finished it.

Another case is that in your OpenAI account you have established a usage limit (Hard Limit and Soft Limit) and the Hard Limit has been reached, that makes you unable to use the OpenAI API.

**Comment by StanGirard** [comment]
Put your credit card on platform.openai.com 👍

**Comment by BUAAZFK** [comment]
Thank you very much! I have noticed that my free tial of OpenAI has been out of date.
