### ISSUE TITLE
github action fails

### ISSUE THREAD

**Issue by masapasa** [StanGirard/quivr#288]
github action fails
d0234e125bf3: Retrying in 1 second
266508f0ed49: Retrying in 1 second
fa3764f5e153: Retrying in 1 second
EOF
Error: Process completed with exit code 1
any idea?

**Comment by StanGirard** [comment]
More details please 🙏

**Comment by masapasa** [comment]
"WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container 35fa1c3d29c6
 ---> b0d951b97514
Step 6/7 : COPY . /code/
 ---> 11714fd422a9
Step 7/7 : CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "5050"]
 ---> Running in 0e4e728b6d6d
Removing intermediate container 0e4e728b6d6d
 ---> 50ab6dc8ea3d
Successfully built 50ab6dc8ea3d
Successfully tagged ***.dkr.ecr.eu-west-3.amazonaws.com/quivr:680dec622a65fe25ddb43e2148c9fe3381b32cbe
The push refers to repository [***.dkr.ecr.eu-west-3.amazonaws.com/quivr]
d7609fbac4ea: Preparing
266508f0ed49: Preparing d0234e125bf3: Retrying in 1 second
266508f0ed49: Retrying in 1 second
fa3764f5e153: Retrying in 1 second
EOF
Error: Process completed with exit code 1.

it fails at "Build, tag, and push image to Amazon ECR"

**Comment by masapasa** [comment]
i added my aws credentials to secrets in github settings

**Comment by StanGirard** [comment]
Update the ecr is with yours

**Comment by StanGirard** [comment]
And you need to deploy a Fargate cluster and all

**Comment by masapasa** [comment]
ok, any instructions that i can follow?

**Comment by StanGirard** [comment]
Unfortunately not yet I'm sorry I don't have the time but it will come in the following weeks 👍
