### ISSUE TITLE
how to use proxy in quivr?

### ISSUE THREAD

**Issue by snailg** [StanGirard/quivr#293]
Because my LAN cannot access the OpenAI API directly, I need to access the OpenAI API by setting up a reverse proxy.

**Comment by astorm-z** [comment]
+1

**Comment by zhaolong1990ok** [comment]
OpenAI and LangChain both have solutions, but I'm not sure if Quivr is compatible with resolving proxy issues by setting OPENAI_BASE.

**Comment by Crossme0809** [comment]
OpenAI and LangChain both have solutions, but I'm not sure if Quivr is compatible with resolving proxy issues by setting OPENAI_BASE.

**Comment by AllenZzzzkk** [comment]
有解决吗？

**Comment by YakirLove** [comment]
+1 need proxy
