### ISSUE TITLE
I want to enable multiple users to share a common knowledge base. What should I modify in the code file?

### ISSUE THREAD

**Issue by shiliu2023** [StanGirard/quivr#294]
I want to enable multiple users to share a common knowledge base. What should I modify in the code file?

**Comment by JarrodWoodard** [comment]
I have noticed that by default all of the user that sign up on my locally ran instance have the same knowledgebase.

**Comment by Laixinsz** [comment]
Yes, I also have this need！

**Comment by ravikiranp123** [comment]
This should be feasible if you are self hosting as @JarrodWoodard suggested. To take it a step further, you need to set up a quivr instance on a server and probably setup a domain. As far as the official app itself is concerned, that will probably require time to develop.

**Comment by zhaolong1990ok** [comment]
Thank you for your support. I also have the same need for sharing the same knowledge base to reduce the duplication of uploading knowledge bases. I hope this feature can be supported as soon as possible. Thank you.

**Comment by Crossme0809** [comment]
Thank you for your support. I also have the same need for sharing the same knowledge base to reduce the duplication of uploading knowledge bases. I hope this feature can be supported as soon as possible. Thank you.
