### ISSUE TITLE
Whisper limits

### ISSUE THREAD

**Issue by alexruben007** [StanGirard/quivr#3]
Whisper API limits upload to 25MB. If it is case maybe you will need to chunk the audio file before processsing

**Comment by altryne** [comment]
One can use the whisper api of Deepgram which is cheaper and faster but
would require an additional key

**Comment by StanGirard** [comment]
@alexruben007 @altryne Lets add it then ;) 

https://github.com/StanGirard/quiver/blob/main/loaders/audio.py

We could have different tools depending on the user settings

**Comment by StanGirard** [comment]
Closing in favor of #1. 

You can join the discussion on Discord or in the discussion panel 😉
