### ISSUE TITLE
Multiple URLs Input

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#30]
Add support for multiple URLs loading.

Looking for a contributor

**Comment by YifeiShi99** [comment]
Hello there, would this be adding the abilities to input multiple URLs from the UI?
![image](https://github.com/StanGirard/quivr/assets/51186185/52b0c211-d341-4d9b-a22f-8dd1358e56c0)
If so, could you please clarify the format for entering multiple URLs? Is it possible to have one URL per line?
