### ISSUE TITLE
"Error occurred while fetching your chats"

### ISSUE THREAD

**Issue by codingbutstillalive** [StanGirard/quivr#301]
## Versions
- Latest release of Quiver
- MacOS 13.4 (intel version)
- Docker Desktop 4.19.0
- Supabase tables: [stats, summaries, users, vectors]
 
## Detailed steps to reproduce the issue

I uploaded a PDF and then clicked on "Chat".

## Error

- The web UI shows a message saying "An error has occurred while fetching your chats".
- The web UI gets stuck in the "Thinking" loop.

**Comment by jibo-zz** [comment]
Hi, I have similar issue when I upload this error shows on terminal:

File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 68, in execute
backend  |     raise APIError(r.json())
backend  | postgrest.exceptions.APIError: {'code': '42P01', 'details': None, 'hint': None, 'message': 'relation "public.chats" does not exist'}

**Comment by StanGirard** [comment]
Sorry Readme is not up to date -> 

Run all the scripts in `scripts` folder and then run the script in the `supabase` folder :)

Don't worry if there are errors it just means the order is wrong ;)

**Comment by codingbutstillalive** [comment]
Can you run them in from console directly? Please, make a note of the order
in the README. I actually tried to paste the text from the "chats" script
via the Supabase Web Interface, but got discouraged due to an error showing
up.

Stan Girard ***@***.***> schrieb am So. 11. Juni 2023 um
19:25:

**Comment by madruga8** [comment]
I recreated the database and still get this same error....

**Comment by StanGirard** [comment]
<img width="889" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/2ba290f2-da76-4324-be43-089538ea01c8">
Fixed :)

**Comment by codingbutstillalive** [comment]
> <img alt="image" width="889" src="https://user-images.githubusercontent.com/19614572/244961692-2ba290f2-da76-4324-be43-089538ea01c8.png"> Fixed :)

Now it works. And the setup is much easier. Great! Thanks a lot! :)

**Comment by jibo-zz** [comment]
> <img alt="image" width="889" src="https://user-images.githubusercontent.com/19614572/244961692-2ba290f2-da76-4324-be43-089538ea01c8.png"> Fixed :)

Is Working for me too now thanks a lot.

**Comment by kevinrench** [comment]
> <img alt="image" width="889" src="https://user-images.githubusercontent.com/19614572/244961692-2ba290f2-da76-4324-be43-089538ea01c8.png"> Fixed :)  固定的 ：）

Yes, I update the supabase database, from 3 sheets (old) to 5 sheets(new), and it's worked. Thank you!
