### ISSUE TITLE
[API Key Gen] AAUser I can see how many API keys and delete them in the FE

### ISSUE THREAD

**Issue by mattzcarey** [StanGirard/quivr#316]

**Comment by mattzcarey** [comment]
We want to be able to see how many keys and when they were created in a table in the front end. 

You need to have the option to delete keys.

**Comment by iMADi-ARCH** [comment]
are you working on this @mattzcarey ?

**Comment by mattzcarey** [comment]
> are you working on this @mattzcarey ?

Not right now. I will unassign.

**Comment by StanGirard** [comment]
Fix

**Comment by govind-kumarr** [comment]
@mattzcarey  can I work on this?

**Comment by mattzcarey** [comment]
> @mattzcarey  can I work on this?

Go for it!
