### ISSUE TITLE
402 Payment Required？

### ISSUE THREAD

**Issue by kevinrench** [StanGirard/quivr#319]
I install Quivr in localhost，and provide a Openai API Key with enough fund, but when I upload my docs, it return 402 Payment Required. What's wrong with me?
backend     | INFO:     10.0.2.2:14253 - "POST /upload HTTP/1.1" 402 Payment Required
backend     | INFO:     10.0.2.2:14396 - "POST /upload HTTP/1.1" 402 Payment Required
backend     | INFO:     10.0.2.2:14377 - "POST /upload HTTP/1.1" 402 Payment Required
backend     | INFO:     10.0.2.2:14133 - "POST /upload HTTP/1.1" 402 Payment Required
backend     | INFO:     10.0.2.2:14630 - "POST /upload HTTP/1.1" 402 Payment Required
backend     | INFO:     10.0.2.2:14531 - "POST /upload HTTP/1.1" 402 Payment Required
backend     | INFO:     10.0.2.2:14253 - "POST /upload HTTP/1.1" 402 Payment Required
backend     | INFO:     10.0.2.2:14396 - "POST /upload HTTP/1.1" 402 Payment Required
backend     | INFO:     10.0.2.2:14377 - "POST /upload HTTP/1.1" 402 Payment Required
backend     | INFO:     10.0.2.2:14133 - "POST /upload HTTP/1.1" 402 Payment Required
backend     | INFO:     10.0.2.2:14630 - "POST /upload HTTP/1.1" 402 Payment Required

**Comment by linge1688** [comment]
Problem solved? I have this problem too
