### ISSUE TITLE
Input Zip File

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#32]
Allow users to load a zip that will be de-zipped

Looking for a contributor

**Comment by EvanCarlson** [comment]
Hello! I love the idea of this project and would like to contribute. May I start with this issue?

**Comment by StanGirard** [comment]
Yeah go ahead :)

**Comment by EvanCarlson** [comment]
Are you open to docstrings and typing for methods? Also do you use any linters? I personally prefer numpy docstrings and pylint, but am open to suggestions. If you are interested in these ideas, we could add pre-commit hooks in a separate PR for future contributions.

**Comment by StanGirard** [comment]
I'm not a python expert. Please feel free to add what you think is good. 

I'm working on #46 if you are interested

**Comment by EvanCarlson** [comment]
I'm interested in helping out with V2. I'll make a PR with my changes then can help out with V2.

**Comment by EvanCarlson** [comment]
I apologize if I missed something, but when I tried push my branch I was denied.
```
(venv) evan@evan:~/code/Quivr$ git push -u origin upload_zip_file
ERROR: Permission to StanGirard/Quivr.git denied to EvanCarlson.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by EvanCarlson** [comment]
When I tried to push my changes to a branch here I was denied (see below):
```
(venv) evan@evan:~/code/Quivr$ git push -u origin upload_zip_file
ERROR: Permission to StanGirard/Quivr.git denied to EvanCarlson.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Do you want me to fork this repo and create a PR there instead?

**Comment by StanGirard** [comment]
Yes :)

**Comment by EvanCarlson** [comment]
I have! Just joined a couple days ago.
