### ISSUE TITLE
im getting 404 not found for this scripts after the update:  /_vercel/insights/script.js 

### ISSUE THREAD

**Issue by madruga8** [StanGirard/quivr#320]
im getting 404 not found for this scripts after the update:  /_vercel/insights/script.js

**Comment by madruga8** [comment]
ive installed now and the issue continues... anybody saw the same error

**Comment by WGKLoveStudy** [comment]
I have the same problem. In addition, I also have an issue with API error 401, as shown in the figure
![image](https://github.com/StanGirard/quivr/assets/20789962/39872265-487a-4a6e-91f7-28c6522eb073)
