### ISSUE TITLE
402问题如何解决啊，太棘手了

### ISSUE THREAD

**Issue by linge1688** [StanGirard/quivr#321]
backend  | 2023-06-14 01:40:20,579:INFO - Copying copyright to /root/bin ...
backend  | INFO:     Application startup complete.
backend  | INFO:     172.18.0.1:52096 - "OPTIONS /upload HTTP/1.1" 200 OK
backend  | INFO:     172.18.0.1:52096 - "POST /upload HTTP/1.1" 402 Payment Required
backend  | INFO:     172.18.0.1:52100 - "POST /upload HTTP/1.1" 402 Payment Required
backend  | INFO:     172.18.0.1:52104 - "POST /upload HTTP/1.1" 402 Payment Required
backend  | INFO:     172.18.0.1:52118 - "OPTIONS /user HTTP/1.1" 200 OK
backend  | INFO:     172.18.0.1:52118 - "GET /user HTTP/1.1" 402 Payment Required
backend  | INFO:     172.18.0.1:52132 - "POST /upload HTTP/1.1" 402 Payment Required

**Comment by JerryFeng7468** [comment]
我也是这个问题，请问您解决了吗

**Comment by JerryFeng7468** [comment]
如果你的api可以使用的话，注意不要再.backend_env.example和.frontend_env.example里update信息
