### ISSUE TITLE
[Hosting] AAContributor I can deploy Quivr on multiple cloud providers (AWS, GCP, ?)

### ISSUE THREAD

**Issue by mattzcarey** [StanGirard/quivr#322]
Be able to deploy frontend to Amplify

Deploy BE to ECS Fargate

Include docs on how to do this.

**Comment by Klaudioz** [comment]
I'd like to have the same for GCP as well.

**Comment by dabrodev** [comment]
Would be nice to document the railway and render deployments.

**Comment by masapasa** [comment]
Hi all, any progress on this? I am having difficulties deploying to ecs fargate

**Comment by antstanley** [comment]
Are there any thoughts on providing alternative database options beyond Supabase? Would like to run the entire project on one cloud provider, and not have data in 3rd parties.

Happy to contribute to make this happen if needed.

**Comment by mattzcarey** [comment]
@antstanley yes there is. It is an ongoing improvement discussed here: #646. Once we extract Supabase from the core db logic, you can swap in an alternative. 

There are currently no plans to create an option to remove Supabase entirely, however. For instance, supabase will still be needed for auth. You are always welcome to create a PR. The auth handler functionality should be quite simple to adjust to use Cognito or another provider. 

The fallback is that you can always self-host Supabase. 

I hope that answers your question and looking forward to seeing you for Serverless days Cape Town?!

**Comment by antstanley** [comment]
Ok. After a quick look at Auth it looks like you're using the Supabase auth client libraries. To make Auth more agnostic you'll need to swap them out with something like [Auth.js](https://authjs.dev/), formerly NextAuth, which gives you a huge variety of provider support. Only problem is Auth.js doesn't support Supabase at this time. 

Will create a separate issue on swapping out Auth providers to allow choice there, and document options. Once I've done that I'll submit a PR to get it done. Sound ok?

**Comment by mattzcarey** [comment]
@antstanley sounds good!!
