### ISSUE TITLE
Responsive chat bar 

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#335]
After opening the chat bar with the chat history, if you go to another page and come back it doesn't  save the state if it was open or closed. Meaning if you want the chat bar to always be open you'll have to reopen it all the time 

<img width="1840" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/8d49a1c3-90a4-4ba4-b485-d94dfab94779">
By default it is always closed. I'd like it to remember the state of it.

**Comment by Ruben1701** [comment]
@StanGirard from an UX point of view isn't it better for it to start open until the bar is closed for the first time? That way a user will always know what is behind the tab without having to click around first.

**Comment by StanGirard** [comment]
Yes but it should also remember if the user closed it and not reopen it ;)

**Comment by Ruben1701** [comment]
@StanGirard yeah next step
