### ISSUE TITLE
Copy/Paste Content

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#34]
Allow users to copy paste content in a text.input_area

Looking for a contributor

**Comment by dkswami** [comment]
Hey this seems an easy one!
can you assign me this issue. Thank you

**Comment by syedddanishalinaqvi** [comment]
You need copy paste button for ask a question Text Input area?

**Comment by dkswami** [comment]
yes, could you please tell which text.input_area?

**Comment by StanGirard** [comment]
Isn't it already working with the new UI ?
