### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#349]
[Quivr mockup 1.0.pdf](https://github.com/StanGirard/quivr/files/11798086/Quivr.mockup.1.0.pdf)

**Comment by gozineb** [comment]
#WHAT 

Mobile improvements:



- /upload page: OK

- /chat page: KO
- - Change the change bar to be closed when arriving on /chat

![Image](https://github.com/StanGirard/quivr/assets/100568984/cb449c7e-0759-41f4-817e-e0d6300da281)
![Image](https://github.com/StanGirard/quivr/assets/100568984/36883116-9b4e-4102-a9d1-6919926e8ade)

-- On click on chat in chats bar -> close the chats bar

-- The chat page takes more than the space of the mobile screen (not responsive)

![Image](https://github.com/StanGirard/quivr/assets/100568984/61dd98d2-035d-4900-9d31-7869bd6ecb4b)

-- Limit the box history size to the screen. Fix header and question asking box. and only make history chat -> Header should contain the chat Name. Need to scroll to see footer.

--

**Comment by mamadoudicko** [comment]
- On desktop, when user goes on chat page, page is scrolling down

**Comment by mamadoudicko** [comment]
- Make chats list (on left) fix

**Comment by mamadoudicko** [comment]
- Make header fix

**Comment by mamadoudicko** [comment]
- Remove footer and add twitter and github link to the sidebar

**Comment by mamadoudicko** [comment]
- Add discord link to the footer

**Comment by mamadoudicko** [comment]
-- On click on chat in chats bar -> close the chats bar

**Comment by mamadoudicko** [comment]
-- The chat page takes more than the space of the mobile screen (not responsive)

![Image](https://github.com/StanGirard/quivr/assets/100568984/61dd98d2-035d-4900-9d31-7869bd6ecb4b)
