### ISSUE TITLE
Add sources to output

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#35]
Add source to output messages

Looking for a contributor

**Comment by Marsh-sudo** [comment]
can you kindly give me more explanation about this issue

**Comment by MrBurnsAI** [comment]
Hi,

The document which was used to retrieve the results should be mentioned in the output (citation)

**Comment by StanGirard** [comment]
If anyone want to tackle this issue it is fairly easy :) 

https://python.langchain.com/en/latest/use_cases/question_answering.html

<img width="920" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/f12298c1-b9a8-482d-be95-75c4496cdd64">

**Comment by Marsh-sudo** [comment]
Would like to give it a shot then 👀

**Comment by StanGirard** [comment]
Go ahead :)
