### ISSUE TITLE
[Multiple brains] AAUser, I can add and remove  files from a brain

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#359]
[] Use brainId instead of userId in: 
- vectors -> old user_id is default brain id + remove user_id
- users -> user_id is replaced by auth.users.id (user_id created by Supabase)
- add default brain boolean column to brains_users

[] Change backend:
- Modify process_file
- Modify match function in SQL table (match_vectors)
- Modify 'file_already_exists_from_content'

**Comment by StanGirard** [comment]
Done
