### ISSUE TITLE
Failed to upload file: ("message":"Network Erro eyJhbGciOiJIUzl1NilsInR5cCI6IkpXVCJ9.eyJhd 8ZbOXPEnQGBpl3OLU"),"baseURL":"http://192

### ISSUE THREAD

**Issue by wujie990181816** [StanGirard/quivr#369]
Failed to upload file: ("message":"Network Erro eyJhbGciOiJIUzl1NilsInR5cCI6IkpXVCJ9.eyJhd
8ZbOXPEnQGBpl3OLU"),"baseURL":"http://192

**Comment by caspartse** [comment]
1. check whether the **NEXT_PUBLIC_BACKEND_URL** in `frontend/.env` is filled in correctly. 
2. check whether the network environment where the quivr service is located can access `api.openai.com` properly.

**Comment by sunupup** [comment]
I, too, checked that the environment variables were correct, and deployed twice will report an error when creating the brain!
