### ISSUE TITLE
Multiple brains with their own data and settings

### ISSUE THREAD

**Issue by shuruheel** [StanGirard/quivr#37]
Individuals and organizations would need multiple brains depending on the use case. For example, I may create separate brains for programming, growth strategy, product management, philosophy, negotiation, healthcare innovation, politics, and artificial intelligence.

Each could require its own set documents, chunk size, chunk overlap, foundation model, and in the future, even its own data model. For example, each brain may require not just retrieval of context relevant to the query, but for the retrieved context to cover various types of data. For a financial advisor, depending on the query, it may make sense for the context to include some mix of news, market data, and applied reasoning data (equity research reports).

**Comment by iyengarm** [comment]
I second that request. Our use case needs multiple brains for each project. Since the context is different but the content can have minute variations across different docs. Also it doesn't make sense to add the data for one to remove it for another. All the processing would have gone wasted.

**Comment by mattlebel** [comment]
+1 to the idea of naming the purpose behind the Quivr instance upon initialization, perhaps something akin to a "System Prompt."

This might fit well in the "Configuration" sidebar, with the value being added upon initialization of `chat_history` in [`question.py`](https://github.com/StanGirard/quivr/blob/987d15e66969431c6c40fc75f216020db91484ad/question.py)

![quivr--system-prompt-example](https://github.com/StanGirard/quivr/assets/1132438/087b6242-8c45-4f17-9378-66cdd29af819)

**Comment by StanGirard** [comment]
#76 in the roadmap
