### ISSUE TITLE
Error occured while fetching your chats and Error occurred while getting answer!

### ISSUE THREAD

**Issue by ccccccface** [StanGirard/quivr#370]
![image](https://github.com/StanGirard/quivr/assets/132448599/99296e9a-d5dc-4087-ad05-dac300737948)
![9e5ab388bcc1fa71c314943b21e517f](https://github.com/StanGirard/quivr/assets/132448599/b23217a5-733f-4f84-b237-011ef22d7189)
Attaching to backend, web
web      | yarn run v1.22.19
web      | $ next start
backend  | WARNING: Package(s) not found: gpt4all
web      | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
backend  | INFO:     Will watch for changes in these directories: ['/code']
backend  | INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
backend  | INFO:     Started reloader process [8] using StatReload
web      | - info Loaded env from /app/.env
backend  | INFO:     Started server process [10]
backend  | INFO:     Waiting for application startup.
backend  | [INFO] Using already downloaded file pandoc-3.1.4-1-amd64.deb
backend  | 2023-06-25 08:56:35,290:INFO - Using already downloaded file pandoc-3.1.4-1-amd64.deb
backend  | [INFO] Unpacking pandoc-3.1.4-1-amd64.deb to tempfolder...
backend  | 2023-06-25 08:56:35,290:INFO - Unpacking pandoc-3.1.4-1-amd64.deb to tempfolder...
backend  | [INFO] Copying pandoc to /root/bin ...
backend  | 2023-06-25 08:56:36,400:INFO - Copying pandoc to /root/bin ...
backend  | [INFO] Making /root/bin/pandoc executeable...
backend  | 2023-06-25 08:56:36,584:INFO - Making /root/bin/pandoc executeable...
backend  | [INFO] Copying copyright to /root/bin ...
backend  | 2023-06-25 08:56:36,584:INFO - Copying copyright to /root/bin ...
backend  | INFO:     Application startup complete.
backend  | INFO:     171.41.131.81:51831 - "GET / HTTP/1.1" 200 OK
backend  | INFO:     171.41.131.81:51861 - "OPTIONS /chat HTTP/1.1" 200 OK
backend  | INFO:     171.41.131.81:51861 - "GET /chat HTTP/1.1" 500 Internal Server Error
backend  | ERROR:    Exception in ASGI application
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend  |     result = await app(  # type: ignore[func-returns-value]
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend  |     return await self.app(scope, receive, send)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend  |     await super().__call__(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend  |     await self.middleware_stack(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend  |     await self.app(scope, receive, _send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend  |     await self.app(scope, receive, sender)
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend  |     raise e
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend  |     await route.handle(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend  |     response = await func(request)
backend  |                ^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 227, in app
backend  |     solved_result = await solve_dependencies(
backend  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 622, in solve_dependencies
backend  |     solved = await call(**sub_values)
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/auth/auth_bearer.py", line 24, in __call__
backend  |     return await self.authenticate(
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/auth/auth_bearer.py", line 44, in authenticate
backend  |     elif await verify_api_key(
backend  |          ^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/auth/api_key_handler.py", line 21, in verify_api_key
backend  |     .execute()
backend  |      ^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 68, in execute
backend  |     raise APIError(r.json())
backend  | postgrest.exceptions.APIError: {'code': '42P01', 'details': None, 'hint': None, 'message': 'relation "public.api_keys" does not exist'}

What is the problem?

**Comment by caspartse** [comment]
Your screenshot shows that, the `JWT_SECRET_KEY` (line 5) is not filled in correctly, which may have something to do with this.

**Comment by sncjdinwoie** [comment]
I have the same problem , and I also fill the JWT_SECRET_KEY, still not working
