### ISSUE TITLE
how to fix `backend  | exec /code/scripts/start.sh: no such file or directory`

### ISSUE THREAD

**Issue by timczm** [StanGirard/quivr#372]
backend  | exec /code/scripts/start.sh: no such file or directory
web      | yarn run v1.22.19
web      | $ next start
web      | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
web      | - info Loaded env from /app/.env
backend exited with code 0
backend  | exec /code/scripts/start.sh: no such file or directory
backend  | exec /code/scripts/start.sh: no such file or directory
backend  | exec /code/scripts/start.sh: no such file or directory
backend  | exec /code/scripts/start.sh: no such file or directory
backend exited with code 1

**Comment by yunmemory** [comment]
i got the same error

**Comment by mahdilunalabs** [comment]
i have the same issue

**Comment by mahdilunalabs** [comment]
help please

**Comment by giuliastro** [comment]
it seems like the script checks if gpt4all is installed it and installs it otherwise, something added recently.
If you don't care about gpt4all, just edit Quivr/backend/Dockerfile and replace this:

`ENTRYPOINT ["/code/scripts/start.sh"]`

with this:

`ENTRYPOINT exec uvicorn main:app --reload --host 0.0.0.0 --port 5050`

**Comment by mahdilunalabs** [comment]
thanks a lot man, it worked as expected, what if i care about gpt4all, what should i do?

**Comment by mattzcarey** [comment]
This error seems like a Docker caching error. The best thing to do is add a meaningless line to the Dockerfile to stop the previous image from being used. 

```
ARG CACHEBUST=1 
```

You can then remove it the next time you run the app. Let me know if that works :)

**Comment by yikuangli** [comment]
The root cause of this issue is that the line break type in the start.sh script is set to CRLF. By switching it to LF, the problem should be resolved.

**Comment by giuliastro** [comment]
> The root cause of this issue is that the line break type in the start.sh script is set to CRLF. By switching it to LF, the problem should be resolved.

Thank you Yikuangli, unfortunately this doesn't seem to work either. I get the same error if running it under Ubuntu Linux or converting the file from CRLF to LF under Windows, this doesn't seem to be the problem.

**Comment by rmgravina** [comment]
Same problem here.. (I do care for gpt4all)

**Comment by BasedAnon** [comment]
Anyone else notice the total lack of a /code/ directory, or am I the only one to notice that?
Seems like a huge deal...

**Comment by BasedAnon** [comment]
> This error seems like a Docker caching error. The best thing to do is add a meaningless line to the Dockerfile to stop the previous image from being used.
> 
> ```
> ARG CACHEBUST=1 
> ```
> 
> You can then remove it the next time you run the app. Let me know if that works :)

Which dockerfile?  The main one, or the backend one?

**Comment by mattzcarey** [comment]
> Anyone else notice the total lack of a /code/ directory, or am I the only one to notice that?
> 
> Seems like a huge deal...

The code directory is created as the working directory in the container. Check the backend dockerfile.

**Comment by mattzcarey** [comment]
Potentially it could be an issue with how windows laptops define permissions for scripts. Can everyone having this issue run  chmod +x ./backend/scripts/start.sh or equivalent for their terminal.

**Comment by giuliastro** [comment]
> 

That has already been suggested, thank you. Unfortunately permissions is not the problem.

**Comment by BasedAnon** [comment]
> chmod

I'm running windows

**Comment by BasedAnon** [comment]
> > Anyone else notice the total lack of a /code/ directory, or am I the only one to notice that?
> > Seems like a huge deal...
> 
> The code directory is created as the working directory in the container. Check the backend dockerfile.

Thank you so much for explaining this!  I was trying to wrap my head around it, and I was so confused, until I saw this post, and went through the code and found that function.  I've spent way too much time on this to give up at this point, and I think I got it working.

**Comment by BasedAnon** [comment]
> The root cause of this issue is that the line break type in the start.sh script is set to CRLF. By switching it to LF, the problem should be resolved.

I ignored this at first, because I didn't know what it meant, but following it solved my problem.
After much thrashing about for hours trying to solve my problem:
I opened it up in VScodium, and found the line break type option on the bottom right of my screen.  (I had no clue such a thing existed)
![image](https://github.com/StanGirard/quivr/assets/7894815/6c577e5f-8790-48a9-a58f-87873f129b42)
I changed it from CRLF to LF, saved the file, and suddenly it works.   O_O

**Comment by rmgravina** [comment]
> > The root cause of this issue is that the line break type in the start.sh script is set to CRLF. By switching it to LF, the problem should be resolved.
> 
> I ignored this at first, because I didn't know what it meant, but following it solved my problem. After much thrashing about for hours trying to solve my problem: I opened it up in VScodium, and found the line break type option on the bottom right of my screen. (I had no clue such a thing existed) ![image](https://user-images.githubusercontent.com/7894815/252047369-6c577e5f-8790-48a9-a58f-87873f129b42.png) I changed it from CRLF to LF, saved the file, and suddenly it works. O_O

unfortunately, that didnt work for me ( Windows 11)

**Comment by rmgravina** [comment]
It's weird because the file is in the correct directory inside Docker, but for some reason it can't find it... 

![image](https://github.com/StanGirard/quivr/assets/30808348/6c136a12-af33-4ff6-bfaa-f501ca1b7681)

probably what I'm going to ask is a noob question, but the fact that the container is successfully created, and then when will it run the ' attaching to backend, web' the problem appears, saying that it did not find the specified file, is it because it changes the directory at some point and then the access with "/code/scripts/start.sh" fails?

**Comment by rmgravina** [comment]
![image](https://github.com/StanGirard/quivr/assets/30808348/096ce67f-b479-4cc1-aed2-0fb99f707dfa)

**Comment by BasedAnon** [comment]
> It's weird because the file is in the correct directory inside Docker, but for some reason it can't find it...
It's a "Working Directory", temporarily created by a script:  took me a moment to wrap my head around that.
![image](https://github.com/StanGirard/quivr/assets/7894815/ae203d11-a0a6-44c9-b873-7bc01627e83b)
That's where I found the file.


> ![image](https://user-images.githubusercontent.com/30808348/252122433-096ce67f-b479-4cc1-aed2-0fb99f707dfa.png)
I also had this problem, I changed the 0.0.0.0 ip to "localhost" instead and that got it working for me.  
![image](https://github.com/StanGirard/quivr/assets/7894815/f8b05383-2f11-46cd-876d-f32b951cd701)
I missed some variables the first time around.

Right now, I'm trying to figure out how to run the scripts for SupaBase, so I can finally get some brains.

**Comment by Buantum** [comment]
> it seems like the script checks if gpt4all is installed it and installs it otherwise, something added recently. If you don't care about gpt4all, just edit Quivr/backend/Dockerfile and replace this:
> 
> `ENTRYPOINT ["/code/scripts/start.sh"]`
> 
> with this:
> 
> `ENTRYPOINT exec uvicorn main:app --reload --host 0.0.0.0 --port 5050`
<img width="859" alt="微信截图_20230709204910" src="https://github.com/StanGirard/quivr/assets/49450053/08d1c05c-7658-49b8-9a23-20f73f0cc377">
I have tried many times to solve this problem, however, it failed.

**Comment by taroxx9** [comment]
you guys just need to remove .example from the name in frontend and backend so its frontend.env

**Comment by Mattang-Tim** [comment]
This will get you fixed
![image](https://github.com/StanGirard/quivr/assets/104371306/69257f0a-47ae-4897-8c21-ef1490cc5805)

**Comment by fabiomilson** [comment]
> 

thank you very much, it worked perfectly, in my case I experienced this error, because I copied the project from a windows machine and ran it in an ubuntu vm

**Comment by fabiomilson** [comment]
> This will get you fixed ![image](https://user-images.githubusercontent.com/104371306/252394809-69257f0a-47ae-4897-8c21-ef1490cc5805.png)

thank you very much, it worked perfectly, in my case I experienced this error, because I copied the project from a windows machine and ran it in an ubuntu vm

**Comment by rmgravina** [comment]
I think I'm in the path of find a solution...

I changed the "ENTRYPOINT [""/code/scripts/start.sh"] to "ENTRYPOINT ["sh", "/code/scripts/start.sh"]"

![image](https://github.com/StanGirard/quivr/assets/30808348/f38c29fb-ca8a-4e5d-8aa2-f469ec942f32)

Now, seems like the file is found, but have a problem with the syntax: "backend  | /code/scripts/start.sh: 21: Syntax error: end of file unexpected (expecting "then")"

![image](https://github.com/StanGirard/quivr/assets/30808348/f95d157d-8337-4787-96ae-7f0ec9059dd9)

The @Mattang-Tim solution may work if you are in a linux machine, but since I'm in a Windows machine, I cant run 'chmod' and 'dos2unix' before.. so I need to find a way to convert the file in a windows machine (are dos2unix for windows?)..

**Comment by giuliastro** [comment]
> I changed the "ENTRYPOINT [""/code/scripts/start.sh"] to "ENTRYPOINT ["sh", "/code/scripts/start.sh"]"

You got it! (almost)
The shell is bash, not sh. This should fix all errors:

`ENTRYPOINT ["bash", "/code/scripts/start.sh"]`

this, together with the EOL conversion for the files shoud fix this problem definately.

**Comment by Mattang-Tim** [comment]
> I think I'm in the path of find a solution...
> 
> I changed the "ENTRYPOINT [""/code/scripts/start.sh"] to "ENTRYPOINT ["sh", "/code/scripts/start.sh"]"
> 
> ![image](https://user-images.githubusercontent.com/30808348/252477108-f38c29fb-ca8a-4e5d-8aa2-f469ec942f32.png)
> 
> Now, seems like the file is found, but have a problem with the syntax: "backend | /code/scripts/start.sh: 21: Syntax error: end of file unexpected (expecting "then")"
> 
> ![image](https://user-images.githubusercontent.com/30808348/252477541-f95d157d-8337-4787-96ae-7f0ec9059dd9.png)
> 
> The @Mattang-Tim solution may work if you are in a linux machine, but since I'm in a Windows machine, I cant run 'chmod' and 'dos2unix' before.. so I need to find a way to convert the file in a windows machine (are dos2unix for windows?)..
> 
> Solution: In Notepad++
> 
> (found in stackoverflow, answered by [kle10](https://stackoverflow.com/users/5613696/kle10))
> 
> Go to: Edit -> EOL Conversion -> Unix.

I am using VSCode on Windows. I simply opened a bash terminal in VSCode

**Comment by mattzcarey** [comment]
Thanks everyone for your help debugging this issue 🧡

When I implemented the start script I didn't foresee all the compatibility issues it would cause. You will be happy to know that it will be removed following the completion of this ticket:

https://github.com/StanGirard/quivr/issues/640
