### ISSUE TITLE
How can contribute for translate to Spanish GUI?

### ISSUE THREAD

**Issue by johnfelipe** [StanGirard/quivr#373]

**Comment by mamadoudicko** [comment]
Hello @johnfelipe,

It won't be a quick win, but it will definitely be interesting to have!

You can use `https://github.com/amannn/next-intl` and implement a language selection feature with a select list.

First, refactor the code to use `intl` for the entire app in English, and then add support for the Spanish language.

Happy coding!

**Comment by johnfelipe** [comment]
There Is possible add that coding step to roadmap?
I want contribute with translation strings to Spanish and French...

**Comment by johnfelipe** [comment]
@mamadoudicko can u give me a gist, or md file with steps?
