### ISSUE TITLE
failed to upload on a remote public instance

### ISSUE THREAD

**Issue by shadowing** [StanGirard/quivr#386]
Yes I have checked previous issues and some were raised but not properly solved. 

my installation was on a remote instance in Seoul, using caddy as the reverse proxy for all docker containers. the frontend was accessed from `https://FRONT.DOMAIN.NAME`, and  I already set 

`NEXT_PUBLIC_BACKEND_URL=http://MY.DOMAIN.NAME:5050` 

now when I clicked Upload button, it still made a request to `http://localhost:5050`. 

what could be the problem? does `NEXT_PUBLIC_ENV=local` matter? should I change `local` to another variable?

**Comment by orlandobcr** [comment]
hi, im in the same situation? did you manage to solve this ?

**Comment by orlandobcr** [comment]
hi, im in the same situation, did you manage to solve this ?

**Comment by madruga8** [comment]
how did u solve this ?

**Comment by madruga8** [comment]
Hi thanks for you help !!!!

after changin as above im still getting this on vps... maybe for the lack of https ? 

upload:1 Access to XMLHttpRequest at 'http://xxxx:5050/upload?brain_id=cc09f224-d6c7-45b8-bec1-d11edd7beda0' from origin 'http://xxx:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
