### ISSUE TITLE
SUPABASE_SERVICE_KEY and NEXT_PUBLIC_SUPABASE_ANON_KEY the same?

### ISSUE THREAD

**Issue by shadowing** [StanGirard/quivr#387]
quoting README

> Your supabase_service_key can be found in your Supabase dashboard under Project Settings -> API. Use the anon public key found in the Project API keys section.

looks like they should be the same one?

**Comment by caspartse** [comment]
Supabase provides two default keys when you create a project: an `anon` key, and a `service_role` key. 

You should use `service_role` key as `SUPABASE_SERVICE_KEY`, and use `anon` key as `NEXT_PUBLIC_SUPABASE_ANON_KEY`.

More detailed description can be found in this article:  [https://supabase.com/docs/guides/api/api-keys](https://supabase.com/docs/guides/api/api-keys)
