### ISSUE TITLE
How can I find all text being sent from quivr (or langchain) to the LLM? 

### ISSUE THREAD

**Issue by JarrodWoodard** [StanGirard/quivr#390]
When I minimize the prompt in LANGUAGE_PROMPT.py from: 

""""Your name is Quivr. You are a second brain. A person will ask you a question and you will provide a helpful answer. Write the answer in the same language as the question. If you don't know the answer, just say that you don't know. Don't try to make up an answer. Use the following context to answer the question:

to: 

"""Use the following context and the maximum amount of tokens to fullfill the request:

OpenAI sometimes responds in French. What could be causing this?

I have noticed a drastic difference in quality of response between asking gpt-3.5-turbo directly, and going through quivr (even without a database) and would like to know how to determine what is causing the drop in response quality. The database aspect is not useful if the response quality is not high enough. 

I am wondering if some of the commands + messaging going from quivr (or an underlying library) to openai is in French (or another language) and this is causing confusion for the AI in how it should respond... which causes it to spend tokens and resources navigating that issue rather than responding to the user request.

**Comment by mattzcarey** [comment]
Thanks for your issue.

The French question is something I have noticed as well. We are looking into it.

Have you tried any of the other models for quality? 

gpt-3.5-turbo-0613 uses a different method in the backend. 

I would be interested to see what you think?

**Comment by JarrodWoodard** [comment]
I would love to provide feedback but unfortunately I can hardly ever get the latest release to be reliable enough to test. I just pulled the latest updates... ran the migration script, and none of my chats are recognized, or vectors. When I try to upload a new document, I get 'Error occurred while creating a brain' 

The last I had a 0.0.18 version running, from my recall, I got errors with every model except 0613. If there is a stable latest release I am happy to give it a test. 

I am currently using 0.0.16 when I need it as a vector DB.

**Comment by mattzcarey** [comment]
Okay, fair enough. Give us a week and it will be more stable. We are adding CI/CD and testing at the moment.

**Comment by JarrodWoodard** [comment]
I came back to check up on the stability and I cannot seem to get it installed / running now.

**Comment by mattzcarey** [comment]
Hey you will need to run all the sql migrations.

**Comment by JarrodWoodard** [comment]
When I tried doing that manually (because I don't understand how to use the migration bash script) I kept getting errors so I just wiped the database and started over. 

New (latest) instance is running alright though.  

@mattzcarey What and where would be the best place for me to provide feedback on the quality of responses I am getting. I have a lot of experience testing similar paid vector databases. 

Right now, in some areas quivr is outperforming others, when I switch to the gpt-3.5-16k, (longer/detailed responses tend to be better and 0613 is bad at following directions + it's token limitation is really a burden). Sorry I cannot test with gpt 4 as I don't have API access for that. 

I tried uploading a pdf directly, and in chat the llm had no concept of several things that were in the document. I tried copying and pasting it's contents to a to a text file with the same results. I used this service (https://www.ocr2edit.com/pdf-to-text) to convert the pdf to a text file and afterward... the results were much better. 

This is the document I uploaded: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10211430/

**Comment by JarrodWoodard** [comment]
Gpt-4 does not work for me, the backend says 'gpt-4' does no exist... I think a stipulation is that you have been billed successfully for your api use, and I have no used it enough for them to charge me. I'm using more though and I am gonna host quivr for friends so that should change soon. 

Thank you for the google form, I will provide feedback there!
