### ISSUE TITLE
Network errors

### ISSUE THREAD

**Issue by leonardsellem** [StanGirard/quivr#395]
- **Operating System**: MacOS 13.5 Beta (22G5038d)
- **Docker version**: 
Client:
 Cloud integration: v1.0.31
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        297e128
 Built:             Tue Apr  4 18:21:21 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.18.0 (104112)
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       5d6db84
  Built:            Tue Apr  4 18:17:07 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- **Docker-compose** v2.17.2

- **Supabase tables**:
 api_keys: 6 columns
 brains: 6 columns
 brains_users: 3 columns
 brains_vectors: 3 columns
 chat_history: 5 col
 chats: 5 col
 stats: 6 col
 summaries: 5 col
 users: 4 col
 vectors: 5 cols

- GUI Settings:
![CleanShot 2023-06-28 at 14 55 50](https://github.com/StanGirard/quivr/assets/2162208/add6b358-1349-4a3a-b01a-38505defa1b3)

- **Detailed steps to reproduce the issue**
After following all the steps to setup Quilvr, the frontend works, but I get an error when I want to send a command. For example, when I add an URL in the upload menu, I get the following error:
````markdown
Failed to crawl website: {"message":"Network Error","name":"AxiosError","stack":"AxiosError: Network Error\n    at u.onerror (http://localhost:3000/_next/static/chunks/117-587c1ea058c272d0.js:6:40676)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer TOKEN_STARTING_LIKE_MY_SERVICE_KEY_BUT_LONGER"},"baseURL":"http://localhost:5050","method":"post","url":"/crawl/","data":"{\"url\":\"https://www.technologyreview.com/s/609123/the-ai-issue/\",\"js\":false,\"depth\":1,\"max_pages\":100,\"max_time\":60}"},"code":"ERR_NETWORK","status":null}
````

When I open the "chat" tab, an error tells me "Error occurred while fetching your chats"

When I click on my profile on the topbar, I get an infinite loader with the message "Fetching your data..."

I am stuck.

**Comment by madruga8** [comment]
i also have this error !

**Comment by Jbusma** [comment]
also have this!

**Comment by rustyrayzor** [comment]
Same for me :(

**Comment by lugfug** [comment]
How to fix it?

**Comment by jcdescy** [comment]
It's also in the hosted version a lot.

**Comment by weir1** [comment]
Same

**Comment by davidfkane** [comment]
Same.  Showstopper. How do we fix it?

**Comment by jchico77** [comment]
Same here!!!
![image](https://github.com/StanGirard/quivr/assets/9368131/6a811bbf-3945-447b-80fa-04f728b5e2a2)

**Comment by gkiri** [comment]
I observe this same error when I deploy in aws cloud.
