### ISSUE TITLE
hash mismatch issue persists even after updating the hash in the requirements.txt file.

### ISSUE THREAD

**Issue by ihop-56** [StanGirard/quivr#396]
### How do I resolve this issue?

 % docker-compose up -d --build                   
[+] Building 9.1s (21/24)                                                                                                            
 => [backend internal] load build definition from Dockerfile                                                                    0.1s
 => => transferring dockerfile: 426B                                                                                            0.0s
 => [backend internal] load .dockerignore                                                                                       0.1s
 => => transferring context: 2B                                                                                                 0.0s
 => [backend internal] load metadata for docker.io/library/python:3.11-buster                                                   2.8s
 => [frontend internal] load build definition from Dockerfile                                                                   0.1s
 => => transferring dockerfile: 844B                                                                                            0.0s
 => [frontend internal] load .dockerignore                                                                                      0.1s
 => => transferring context: 2B                                                                                                 0.0s
 => [frontend internal] load metadata for docker.io/library/node:18-alpine                                                      2.3s
 => [frontend  1/10] FROM docker.io/library/node:18-alpine@sha256:d5b2a7869a4016b1847986ea52098fa404421e44281bb7615a9e3615e07f  0.0s
 => [frontend internal] load build context                                                                                      0.1s
 => => transferring context: 14.06kB                                                                                            0.0s
 => CACHED [frontend  2/10] RUN apk add --update --no-cache python3 make g++ && ln -sf python3 /usr/bin/python                  0.0s
 => CACHED [frontend  3/10] RUN python3 -m ensurepip                                                                            0.0s
 => CACHED [frontend  4/10] RUN pip3 install --no-cache --upgrade pip setuptools                                                0.0s
 => CACHED [frontend  5/10] RUN mkdir -p /app                                                                                   0.0s
 => CACHED [frontend  6/10] WORKDIR /app                                                                                        0.0s
 => CACHED [frontend  7/10] COPY package*.json yarn.lock ./                                                                     0.0s
 => CANCELED [frontend  8/10] RUN yarn install                                                                                  6.4s
 => [backend 1/6] FROM docker.io/library/python:3.11-buster@sha256:3a19b4d6ce4402d11bb19aa11416e4a262a60a57707a5cda5787a81285d  0.0s
 => [backend internal] load build context                                                                                       0.1s
 => => transferring context: 3.42kB                                                                                             0.0s
 => CACHED [backend 2/6] RUN apt-get update && apt-get install -y libgeos-dev                                                   0.0s
 => CACHED [backend 3/6] WORKDIR /code                                                                                          0.0s
 => [backend 4/6] COPY ./requirements.txt /code/requirements.txt                                                                0.1s
 => ERROR [backend 5/6] RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt --timeout 100                        5.8s
------                                                                                                                               
 > [backend 5/6] RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt --timeout 100:
#0 5.026 Usage: pip [options]
#0 5.026 
#0 5.028 ERROR: Invalid requirement: pymupdf==1.22.3  --hash=eddb0975ddd0bcf39812616b5675c26d740f83b12a39c3b5c4425f02c3da754
#0 5.028 pip: error: Arguments to --hash must be a hash name followed by a value, like --hash=sha256:abcde...
#0 5.028 
------
failed to solve: process "/bin/sh -c pip install --no-cache-dir --upgrade -r /code/requirements.txt --timeout 100" did not complete successfully: exit code: 1

**Comment by mgunnin** [comment]
Seems to be an active issue.. https://github.com/StanGirard/quivr/issues/565

Can work around by commenting out "sentence_transformers" in requirements.txt.
