### ISSUE TITLE
Failed to upload file Axios Error

### ISSUE THREAD

**Issue by ihop-56** [StanGirard/quivr#397]
How to resolve the following issue ?

Failed to upload file: {"message":"Network Error","name":Failed to upload file:"stack":"AxiosError: Network Error\n    at u.onerror (http://localhost:3000/_next/static/chunks/214-44ea1e8cd37dee91.js:6:40676)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjg4MDE1NzU1LCJzdWIiOiI0NTgzMDliZC01NjU4LTRhZWYtOGNlNS03NjQxMDg3YmJhNTYiLCJlbWFpbCI6InJzaGFuYWJzMUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvdHAiLCJ0aW1lc3RhbXAiOjE2ODgwMDc0MjB9XSwic2Vzc2lvbl9pZCI6IjY3MDZkMWRkLTliNzMtNDgzMS1hM2NlLWM4NjNiY2Q3ZWZkMSJ9.0dnmKb5gIB8RIv1WK6BJdvP0RMGh9Isme6i-H6PDPK0"},"baseURL":"http://localhost:5050","method":"post","url":"/upload","data":{}},"code":"ERR_NETWORK","status":null}

**Comment by jsu-github** [comment]
Me too

**Comment by lugfug** [comment]
ME TOO
