### ISSUE TITLE
Unit testing Frontend

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#401]

**Comment by govind-kumarr** [comment]
@StanGirard  I can do unit testing

**Comment by mamadoudicko** [comment]
Welcome, @govind-kumarr!

I've started creating some tickets regarding the issue and have added the basic configuration. 

Feel free to review and provide any feedback or suggestions

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/issues/429

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/issues/430

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/issues/431

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/issues/432

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/issues/433

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/issues/434

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/issues/436

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/issues/436

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/issues/429
