### ISSUE TITLE
bug!!! 

### ISSUE THREAD

**Issue by shiliu2023** [StanGirard/quivr#410]
File "/code/routes/brain_routes.py", line 56, in get_default_brain_endpoint
    default_brain = get_default_user_brain(current_user)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/models/brains.py", line 187, in get_default_user_brain
    .execute()
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 72, in execute
    raise APIError(generate_default_error_message(r))
postgrest.exceptions.APIError: {'message': 'JSON could not be generated', 'code': 404, 'hint': 'Refer to full message for details', 'details': "b'<html>\\r\\n<head><title>404 Not Found</title></head>\\r\\n<body>\\r\\n<center><h1>404 Not Found</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n'"}

**Comment by mattzcarey** [comment]
Can you share some more info about how to replicate this bug.

@zineb is on this.

**Comment by shiliu2023** [comment]
when can fix it？/brain  this api erro
