### ISSUE TITLE
Steps after installing locally - "Error occured while creating a brain"

### ISSUE THREAD

**Issue by johnfelipe** [StanGirard/quivr#414]
https://github.com/StanGirard/quivr/assets/428820/1fc7c43e-31b1-4edd-854b-dfbfd093efb8

i install correctly in ubuntu 20 with docker and docker compose

	 ✔ Network quivr_default  Created                                          0.4s
	 ✔ Container backend      Created                                          0.4s
	 ✔ Container web          Created                                          0.4s
	Attaching to backend, web
	backend  | WARNING: Package(s) not found: gpt4all
	backend  | INFO:     Will watch for changes in these directories: ['/code']
	backend  | INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
	backend  | INFO:     Started reloader process [8] using StatReload
	web      | yarn run v1.22.19
	web      | $ next start
	web      | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
	web      | - info Loaded env from /app/.env
	backend  | INFO:     Started server process [10]
	backend  | INFO:     Waiting for application startup.
	backend  | [INFO] Downloading pandoc from https://github.com/jgm/pandoc/releases/download/3.1.4/pandoc-3.1.4-1-amd64.deb ...
	backend  | 2023-06-29 17:14:52,293:INFO - Downloading pandoc from https://github.com/jgm/pandoc/releases/download/3.1.4/pandoc-3.1.4-1-amd64.deb ...
	backend  | [INFO] Unpacking pandoc-3.1.4-1-amd64.deb to tempfolder...
	backend  | 2023-06-29 17:15:00,691:INFO - Unpacking pandoc-3.1.4-1-amd64.deb to tempfolder...
	backend  | [INFO] Copying pandoc to /root/bin ...
	backend  | 2023-06-29 17:15:03,581:INFO - Copying pandoc to /root/bin ...
	backend  | [INFO] Making /root/bin/pandoc executeable...
	backend  | 2023-06-29 17:15:04,583:INFO - Making /root/bin/pandoc executeable...
	backend  | [INFO] Copying copyright to /root/bin ...
	backend  | 2023-06-29 17:15:04,583:INFO - Copying copyright to /root/bin ...
	backend  | INFO:     Application startup complete.
	web      | Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
	web      | Read more: https://nextjs.org/docs/messages/sharp-missing-in-production

how can add brain?

![SNAG-0146](https://github.com/StanGirard/quivr/assets/428820/bbbc6211-7978-4a82-ae59-59a691961933)

**Comment by gozineb** [comment]
In the navbar on your top right, you have a brain icon which you can use to create a new Brain

**Comment by johnfelipe** [comment]
Pls Review video, in 60 seconds of video show error for create brain...

**Comment by johnfelipe** [comment]
@gozineb i do git pull and rebuild and still have same error
"Error occured while creating a brain"
how solve it?

**Comment by gozineb** [comment]
Sorry about that @johnfelipe, i'm going to push a fix asap

**Comment by gozineb** [comment]
Can you give more details about the error you get from the backend please ?

**Comment by johnfelipe** [comment]
im using 
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-117-generic x86_64)
Docker version 20.10.17, build 100c701
Docker Compose version v2.17.3

NAME                STATUS              CONFIG FILES
quivr               running(2)          /root/Quivr/docker-compose.yml

pls tell me command or path for log and tell you `error you get from the backend`

Do u have discord or chat for this matters?

**Comment by gozineb** [comment]
Right over here for the [discord](https://discord.gg/HUpRgp2HG8)

**Comment by johnfelipe** [comment]
> Right over here for the [discord](https://discord.gg/HUpRgp2HG8)

can u help me there pls....

**Comment by zzzziqi** [comment]
I got the same issue 

I'm using 
MacOS 13.0.1 (22A400)
Docker version 24.0.2, build cb74dfc
Docker Compose version v2.18.1


it seems to be the database issue,
<img width="1383" alt="image" src="https://github.com/StanGirard/quivr/assets/72575892/23ceea36-8ad5-46d1-9048-2d33af657e5d">

I got the error message like this
<img width="1383" alt="image" src="https://github.com/StanGirard/quivr/assets/72575892/47304f94-5fba-478e-a4da-695318ab1716">

and I check it in supabase, it's ture
<img width="1304" alt="image" src="https://github.com/StanGirard/quivr/assets/72575892/dda73662-028f-458b-acbc-4f4e7c15a43f">

I've run the script in https://github.com/StanGirard/quivr/blob/main/scripts/tables.sql

if there any context I can provide?

**Comment by shiliu2023** [comment]
I got the same issue.

**Comment by shiliu2023** [comment]
docker supabase erro
