### ISSUE TITLE
Additional prerequisite: pycryptodome

### ISSUE THREAD

**Issue by jpadfield** [StanGirard/quivr#43]
Hi, 

I was just trying to install this code and it failed for me because I did not have **pycryptodome**, so I was wondering if it would be good to add it to the list?

This was on a new clean install of Ubuntu 22.04

Joe

**Comment by Shaunwei** [comment]
thx for reporting it. Is there an error log?

**Comment by ShiftyStickler** [comment]
PyCryptodome is required for AES algorithm

**Comment by jpadfield** [comment]
Sorry, I did not save the error, I just received a message saying it was needed and installed it :-)
