### ISSUE TITLE
Add tests to frontend/(auth)/signup

### ISSUE THREAD

**Issue by mamadoudicko** [StanGirard/quivr#431]

**Comment by mamadoudicko** [comment]
To create a test, follow these steps:

1. Navigate to the relevant page and create or update a file with the name `__tests__/<XXXXX>.test.ts`.

2. To run the test, execute the command `yarn test-unit`.

For an example of how this is done, you can refer to the following link: [https://github.com/StanGirard/quivr/pull/426](https://github.com/StanGirard/quivr/pull/426)

Have fun!

**Comment by Prakashcreator** [comment]
Hi @mamadoudicko,

I am new to open source, could you please guide me how to add unit testing for issue ?

**Comment by mamadoudicko** [comment]
Hi @Prakashcreator,

For this issue:

# Settings:

1. Fork the repository.
2. Follow the [ReadMe](https://github.com/StanGirard/quivr/blob/main/README.md) file to make the required settings.

# Development:

1. Create a new branch, e.g., `tests/frontend-signup`, for the issue.
2. Add relevant tests.
3. Create a pull request (PR) from your branch to [StanGirard:main](https://github.com/StanGirard/quivr/tree/main).

## Relevant tests: similar to `useLogin.test.ts`

1. Refer to `frontend/app/(auth)/login` for inspiration and create `useSignUp`.
2. In the new `useSignUp` hook, include a function called `handleSignUp`, which will serve as the test. The current goal is to ensure that we call `supabase.auth.signUp` with the relevant parameters (`email` and `password`).


Please let me know if the provided information is unclear or if you have any further questions.
