### ISSUE TITLE
[FRONT - TEST] Add tests to frontend/user/*

### ISSUE THREAD

**Issue by mamadoudicko** [StanGirard/quivr#436]

**Comment by mamadoudicko** [comment]
To create a test, follow these steps:

1. Navigate to the relevant page and create or update a file with the name `__tests__/<XXXXX>.test.ts`.

2. To run the test, execute the command `yarn test-unit`.

For an example of how this is done, you can refer to the following link: [https://github.com/StanGirard/quivr/pull/426](https://github.com/StanGirard/quivr/pull/426)

Have fun!

**Comment by Justinshi1** [comment]
Id love to start on this issue
