### ISSUE TITLE
impossible delete chat latest version pulled

### ISSUE THREAD

**Issue by johnfelipe** [StanGirard/quivr#441]
backend  | INFO:     192.168.0.238:53251 - "DELETE /chat/cbf05bf6-2624-4d57-aa0d-aa28454aae36 HTTP/1.1" 500 Internal Server Error

review this video:

https://github.com/StanGirard/quivr/assets/428820/92d99a5a-841d-440d-8445-d4929fcd7754

	:5050/chat/cbf05bf6-2624-4d57-aa0d-aa28454aae36:1     Failed to load resource: net::ERR_FAILED
	cbf05bf6-2624-4d57-aa0d-aa28454aae36:1 Access to XMLHttpRequest at 'http://192.168.0.75:5050/chat/cbf05bf6-2624-4d57-aa0d-aa28454aae36' from origin 'http://192.168.0.75:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
	139-3fa1ce7dfff2c17b.js:1 Error deleting chat: to {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
	window.console.error @ 139-3fa1ce7dfff2c17b.js:1
	d @ 472-40e322d29c0ee072.js:1
	await in d (async)
	onClick @ 472-40e322d29c0ee072.js:1
	ae @ 2443530c-da70b571b1f7722c.js:9
	ao @ 2443530c-da70b571b1f7722c.js:9
	(anonymous) @ 2443530c-da70b571b1f7722c.js:9
	u8 @ 2443530c-da70b571b1f7722c.js:9
	u6 @ 2443530c-da70b571b1f7722c.js:9
	(anonymous) @ 2443530c-da70b571b1f7722c.js:9
	oC @ 2443530c-da70b571b1f7722c.js:9
	io @ 2443530c-da70b571b1f7722c.js:9
	sn @ 2443530c-da70b571b1f7722c.js:9
	i9 @ 2443530c-da70b571b1f7722c.js:9
	i5 @ 2443530c-da70b571b1f7722c.js:9
	117-587c1ea058c272d0.js:6     DELETE http://192.168.0.75:5050/chat/cbf05bf6-2624-4d57-aa0d-aa28454aae36 net::ERR_FAILED 500 (Internal Server Error)

**Comment by caspartse** [comment]
It may also be due to the primary key constraint of the database.
Modifying `/backend/routes/chat_routes.py` can temporarily solve this problem, refer to this issue https://github.com/StanGirard/quivr/issues/384

cc @mamadoudicko @gozineb

**Comment by johnfelipe** [comment]
But this have latest GitHub pull and SQL script for that temporary issue...

**Comment by caspartse** [comment]
This issue has not been fixed yet, I am also using the latest version and I have the same problem.
Maybe you can try my way, for v0.0.21, add the following code before line 45 in `backend/routes/chat_routes.py`.

```python
commons["supabase"].table("chat_history").delete().match({"chat_id": chat_id}).execute()
```

https://github.com/StanGirard/quivr/blob/1e47024d17027552bf4541c1f1c54cdae1e4d495/backend/routes/chat_routes.py#L44-L45

**Comment by StanGirard** [comment]
It is going to be included in next release ;) 

Working on it.

**Comment by StanGirard** [comment]
https://github.com/StanGirard/quivr/releases/tag/v0.0.22
