### ISSUE TITLE
Restriction on accessing Quivr from special locations

### ISSUE THREAD

**Issue by p0mad** [StanGirard/quivr#455]
Hi, It is not possible to access quivr from everywhere!
Are there any limitations?

**Comment by StanGirard** [comment]
Are you trying to access from https://quivr.app ? 

There is no limitation

**Comment by p0mad** [comment]
![image](https://github.com/StanGirard/quivr/assets/131435526/0beb41c2-8ebd-4093-8c04-1613100a8f01)
@StanGirard 
yes the same link!
but when i use VPN, it works!
does your ISP restricts it?

**Comment by StanGirard** [comment]
I use vercel.com to host the website. There is no restriction at all. Your isp must block it.
