### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for BrainSettings

### ISSUE THREAD

**Issue by limumua** [StanGirard/quivr#460]
I followed the steps of readme to install and deploy on the server, and when I ran it, I received this error。
and I have modified the startup port in Docker Compose.yml, but it does not work and still uses 3000 and 5050.

 ✔ Container backend  Recreated                                                                                                                          0.0s
 ✔ Container web      Created                                                                                                                            0.0s
Attaching to backend, web
web      | yarn run v1.22.19
web      | $ next start
web      | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
backend  | WARNING: Package(s) not found: gpt4all
web      | - info Loaded env from /app/.env
backend  | INFO:     Will watch for changes in these directories: ['/code']
backend  | INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
backend  | INFO:     Started reloader process [8] using StatReload
backend  | Process SpawnProcess-1:
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
backend  |     self.run()
backend  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
backend  |     self._target(*self._args, **self._kwargs)
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
backend  |     target(sockets=sockets)
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
backend  |     return asyncio.run(self.serve(sockets=sockets))
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
backend  |     return runner.run(main)
backend  |            ^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
backend  |     return self._loop.run_until_complete(task)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
backend  |     return future.result()
backend  |            ^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
backend  |     config.load()
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
backend  |     self.loaded_app = import_from_string(self.app)
backend  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
backend  |     module = importlib.import_module(module_str)
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend  |     return _bootstrap._gcd_import(name[level:], package, level)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend  |   File "/code/main.py", line 11, in <module>
backend  |     from routes.chat_routes import chat_router
backend  |   File "/code/routes/chat_routes.py", line 10, in <module>
backend  |     from llm.brainpicking import BrainPicking
backend  |   File "/code/llm/brainpicking.py", line 29, in <module>
backend  |     class BrainPicking(BaseModel):
backend  |   File "/code/llm/brainpicking.py", line 36, in BrainPicking
backend  |     settings = BrainSettings()
backend  |                ^^^^^^^^^^^^^^^
backend  |   File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
backend  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend  | pydantic.error_wrappers.ValidationError: 1 validation error for BrainSettings
backend  | anthropic_api_key
backend  |   field required (type=value_error.missing)

**Comment by StanGirard** [comment]
It means you didn't set the env variable correctly in the backend :)

**Comment by StanGirard** [comment]
anthropic_api_key needs to be set even to null

**Comment by limumua** [comment]
> anthropic_api_key 甚至需要设置为 null

thank you replay。I will try
