### ISSUE TITLE
[Multiple Brains] 0-AAUser, I can only modify or delete a file or brain if i'm owner or editor

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#472]
Epic: [#469](https://github.com/StanGirard/quivr/issues/469)

# What: 
- If no relationship, no access
- If reader, can't do anything but read
- If editor, can modify files/brains
- If owner, can modify and delete files/brains
-> Have explicit errors
      - no access
      - no rights to edit
      - no rights to delete

# How: 
Update endpoints for: 
- [] explore: get (all files, one file)+ delete
- [] brains: create + get + delete + update

**Comment by Chloeroumengas** [comment]
Works well for owner ! Doesn't work for editor... editor can't delete files now, while they should be able to delete files @mamadoudicko
