### ISSUE TITLE
sign up error!! help.ToT

### ISSUE THREAD

**Issue by limumua** [StanGirard/quivr#473]
When I was preparing to register, I clicked on the email link and received an error. I am sure my URL is filled out correctly, why?? ToT
![image](https://github.com/StanGirard/quivr/assets/40764041/9b666d70-9c10-41b7-90b1-1420acaccb6e)

![image](https://github.com/StanGirard/quivr/assets/40764041/9e08a684-b7a5-49e9-afc4-dfeab5df65d5)

**Comment by StanGirard** [comment]
Please use the install helper script you can find in the readme :)

**Comment by limumua** [comment]
> Please use the install helper script you can find in the readme :)

I tried install.sh and it ran successfully, but it ran slowly, possibly due to my network issue. Thank you very much

**Comment by limumua** [comment]
> 

![image](https://github.com/StanGirard/quivr/assets/40764041/49371c11-5d4a-48db-9a71-dd5e2ddf9f54)
