### ISSUE TITLE
[Brain management]  2- AAUser, on the brainsManagementPage, i have 3 tabs in the layout

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#476]
# Epic

#531 

# Functional

Please explain in detail the functionality.
Please also include relevant motivation and context.

### Tech

- [ ] BrainConfiguration
- [ ] BrainUsers
- [ ] BrainKnowledge

### Tests

- [] it ...

### Validation Checks

- [] it ...

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/753
