### ISSUE TITLE
[Source Documents] Add source documents to answer

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#480]
### The What

When the user's wants to ask a question, he can chhose wether to see the sources or not. 
With the answer, show the list of sources 

Toggle to include or not to include sources ( both in frontend and backend) -> field in the ChatMessage Object

### The How

https://python.langchain.com/en/latest/modules/chains/index_examples/qa_with_sources.html

To perform question answering with sources, you can use the load_qa_with_sources_chain function from the Langchain library. This function takes two parameters: input_documents and question. The input_documents parameter should contain the documents you want to use for question answering, and the question parameter should contain the question you want to ask.

Here is an example of how to use the load_qa_with_sources_chain function:

from langchain.chains import load_qa_with_sources_chain

input_documents = [
    {
        "page_content": "Document 1 content",
        "metadata": {"source": "Document 1 source"}
    },
    {
        "page_content": "Document 2 content",
        "metadata": {"source": "Document 2 source"}
    }
]

question = "What is the answer to the question?"

qa_with_sources_chain = load_qa_with_sources_chain(input_documents=input_documents, question=question)
This will load the question answering chain with the specified input documents and question. The qa_with_sources_chain object can then be used to get the answer to the question.

Additionally, you can specify the return_only_outputs parameter as True to only get the answer and not the sources involved in the answer.

**Comment by nerdynigel** [comment]
Very interested in this feature
