### ISSUE TITLE
[PrivateLLMs]

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#482]

**Comment by mattzcarey** [comment]
![Image](https://github.com/StanGirard/quivr/assets/77928207/272eee29-1bf5-4f5a-9d1f-bcc5abffa2d0)

**Comment by GdRottoli** [comment]
What's the state of tis feature? Thanks!

**Comment by Ananderz** [comment]
Also wondering about this. Getting private embeddings and potentially a ChromaDB connection instead of Supabase
