### ISSUE TITLE
[Metadata Enrichment] Enrich the metadata with insights on doc

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#483]
# What

Find ways to add some metadatas that are relevant for question answering + document filtering etc:

Objective: Have context aware metadata

# How
Use llm, nlp, anything ?

**Comment by dukemagus** [comment]
IMO, Quivr needs more options to visualize and edit the embeddings manually to serve as scaffolding to build automated actions on top of

Right now it isn't possible to get a partial or full "spreadsheet view" of the data generated after embeddings ar processed, let alone enrich it with new columns for metadata categories ("genres" or "director" in a movie script database, for example).

Pinecone has support for making these changes manually (https://docs.pinecone.io/docs/metadata-filtering), but if you intend to do a deeper retrieval or labeling, (using regex or looking for keywords in each page or chunk of a document), everything starts to become messy.
