### ISSUE TITLE
Website redesign for www.quivr.app

### ISSUE THREAD

**Issue by iMADi-ARCH** [StanGirard/quivr#50]
Hi there, I would like to work on the website redesign for [quivr.app](https://www.quivr.app/). Could you please assign this issue to me? I have experience with website design and development with Next JS, and I am excited to contribute to this project. Thank you!

**Comment by StanGirard** [comment]
Yes sure :) 

I'm also working on the new version of the app with a NextJS front and a FastAPI back. 
don't hesitate to participate on that too :)

**Comment by dkswami** [comment]
Hey! This is quite interesting, I work with Next.js and nest js on daily basis...
Can I contribute to this ?

**Comment by StanGirard** [comment]
Yes ! Join the discussion on our discord :)
https://discord.gg/HUpRgp2HG8
