### ISSUE TITLE
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory  [Issue]

### ISSUE THREAD

**Issue by limumua** [StanGirard/quivr#501]
When I ran install.sh, I got an error, but the webpage opened normally and I still couldn't register an account. I'm not sure if this error was causing it，Can anyone provide help，thanks
I don't know how to handle this error. I installed and started PostgreSQL, but it didn't work。。。
Running the migration scripts...
./migration.sh: line 29: gum: command not found
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
Last migration executed:
Running migration 20230606131110_add_uuid_user_id.sql
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
Running migration 20230620170840_add_vectors_brains.sql
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
Running migration 20230620183620_use_supabase_user_id.sql
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
Running migration 20230627151100_update_match_vectors.sql
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
Running migration 20230629143400_add_file_sha1_brains_vectors.sql
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
Migration script completed.
Launching the app...
[+] Building 0.0s (0/2)
[+] Building 0.2s (2/3)
 => [internal] load build definition from Dockerfile                                                                                                  0.0s
 => => transferring dockerfile: 525B                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                       0.0s
[+] Building 1.3s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                  0.0s
 => => transferring dockerfile: 525B                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/python:3.11-bullseye                                                                               1.2s
 => [1/8] FROM docker.io/library/python:3.11-bullseye@sha256:5b401676aff858495a5c9c726c60b8b73fe52833e9e16eccdb59e93d52741727                         0.0s
 => [internal] load build context                                                                                                                     0.0s
 => => transferring context: 8.64kB                                                                                                                   0.0s
 => CACHED [2/8] RUN apt-get update && apt-get install -y libgeos-dev                                                                                 0.0s
 => CACHED [3/8] WORKDIR /code                                                                                                                        0.0s
 => CACHED [4/8] COPY ./requirements.txt /code/requirements.txt                                                                                       0.0s
 => CACHED [5/8] RUN pip install --no-cache-dir -r /code/requirements.txt --timeout 100                                                               0.0s
 => CACHED [6/8] COPY ./scripts/start.sh /code/scripts/start.sh                                                                                       0.0s
[+] Building 1.4s (15/15) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                  0.0s
 => => transferring dockerfile: 810B                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                     0.0s
 => => transferring context: 60B                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/node:18-alpine                                                                                     1.3s
 => [ 1/10] FROM docker.io/library/node:18-alpine@sha256:d5b2a7869a4016b1847986ea52098fa404421e44281bb7615a9e3615e07f37fb                             0.0s
 => [internal] load build context                                                                                                                     0.0s
 => => transferring context: 13.77kB                                                                                                                  0.0s
 => CACHED [ 2/10] RUN apk add --update --no-cache python3 make g++ && ln -sf python3 /usr/bin/python                                                 0.0s
 => CACHED [ 3/10] RUN python3 -m ensurepip                                                                                                           0.0s
 => CACHED [ 4/10] RUN pip3 install --no-cache --upgrade pip setuptools                                                                               0.0s
 => CACHED [ 5/10] RUN mkdir -p /app                                                                                                                  0.0s
 => CACHED [ 6/10] WORKDIR /app                                                                                                                       0.0s
 => CACHED [ 7/10] COPY package*.json yarn.lock ./                                                                                                    0.0s
 => CACHED [ 8/10] RUN yarn install                                                                                                                   0.0s
 => CACHED [ 9/10] COPY . .                                                                                                                           0.0s
 => CACHED [10/10] RUN yarn build                                                                                                                     0.0s
 => exporting to image                                                                                                                                0.0s
 => => exporting layers                                                                                                                               0.0s
 => => writing image sha256:d1ca514741dfad131e79d2ed1365a27b6f9882feda643b124e631a2c2637b3c4                                                          0.0s
 => => naming to docker.io/library/quivr-frontend                                                                                                     0.0s
[+] Running 2/0
 ✔ Container backend  Created                                                                                                                         0.0s
 ✔ Container web      Created                                                                                                                         0.0s
Attaching to backend, web
web      | yarn run v1.22.19
web      | $ next start -p 7017
backend  | WARNING: Package(s) not found: gpt4all
web      | - ready started server on 0.0.0.0:7017, url: http://localhost:7017
backend  | INFO:     Will watch for changes in these directories: ['/code']
backend  | INFO:     Uvicorn running on http://0.0.0.0:7018 (Press CTRL+C to quit)
backend  | INFO:     Started reloader process [8] using StatReload
web      | - info Loaded env from /app/.env
backend  | INFO:     Started server process [10]
backend  | INFO:     Waiting for application startup.
backend  | [INFO] Using already downloaded file pandoc-3.1.4-1-amd64.deb
backend  | 2023-07-04 06:00:44,140:INFO - Using already downloaded file pandoc-3.1.4-1-amd64.deb
backend  | [INFO] Unpacking pandoc-3.1.4-1-amd64.deb to tempfolder...
backend  | 2023-07-04 06:00:44,140:INFO - Unpacking pandoc-3.1.4-1-amd64.deb to tempfolder

**Comment by limumua** [comment]
I am deployed on the server and I want my friends to be able to access and use it as well

**Comment by limumua** [comment]
> When I ran install.sh, I got an error, but the webpage opened normally and I still couldn't register an account. I'm not sure if this error was causing it，Can anyone provide help，thanks I don't know how to handle this error. I installed and started PostgreSQL, but it didn't work。。。 Running the migration scripts... ./migration.sh: line 29: gum: command not found psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket? Last migration executed: Running migration 20230606131110_add_uuid_user_id.sql psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket? psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket? Running migration 20230620170840_add_vectors_brains.sql psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket? psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket? Running migration 20230620183620_use_supabase_user_id.sql psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket? psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket? Running migration 20230627151100_update_match_vectors.sql psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket? psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket? Running migration 20230629143400_add_file_sha1_brains_vectors.sql psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket? psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket? Migration script completed. Launching the app... [+] Building 0.0s (0/2) [+] Building 0.2s (2/3) => [internal] load build definition from Dockerfile 0.0s => => transferring dockerfile: 525B 0.0s => [internal] load .dockerignore 0.0s => => transferring context: 2B 0.0s [+] Building 1.3s (13/13) FINISHED => [internal] load build definition from Dockerfile 0.0s => => transferring dockerfile: 525B 0.0s => [internal] load .dockerignore 0.0s => => transferring context: 2B 0.0s => [internal] load metadata for docker.io/library/python:3.11-bullseye 1.2s => [1/8] FROM docker.io/library/python:3.11-bullseye@sha256:5b401676aff858495a5c9c726c60b8b73fe52833e9e16eccdb59e93d52741727 0.0s => [internal] load build context 0.0s => => transferring context: 8.64kB 0.0s => CACHED [2/8] RUN apt-get update && apt-get install -y libgeos-dev 0.0s => CACHED [3/8] WORKDIR /code 0.0s => CACHED [4/8] COPY ./requirements.txt /code/requirements.txt 0.0s => CACHED [5/8] RUN pip install --no-cache-dir -r /code/requirements.txt --timeout 100 0.0s => CACHED [6/8] COPY ./scripts/start.sh /code/scripts/start.sh 0.0s [+] Building 1.4s (15/15) FINISHED => [internal] load build definition from Dockerfile 0.0s => => transferring dockerfile: 810B 0.0s => [internal] load .dockerignore 0.0s => => transferring context: 60B 0.0s => [internal] load metadata for docker.io/library/node:18-alpine 1.3s => [ 1/10] FROM docker.io/library/node:18-alpine@sha256:d5b2a7869a4016b1847986ea52098fa404421e44281bb7615a9e3615e07f37fb 0.0s => [internal] load build context 0.0s => => transferring context: 13.77kB 0.0s => CACHED [ 2/10] RUN apk add --update --no-cache python3 make g++ && ln -sf python3 /usr/bin/python 0.0s => CACHED [ 3/10] RUN python3 -m ensurepip 0.0s => CACHED [ 4/10] RUN pip3 install --no-cache --upgrade pip setuptools 0.0s => CACHED [ 5/10] RUN mkdir -p /app 0.0s => CACHED [ 6/10] WORKDIR /app 0.0s => CACHED [ 7/10] COPY package*.json yarn.lock ./ 0.0s => CACHED [ 8/10] RUN yarn install 0.0s => CACHED [ 9/10] COPY . . 0.0s => CACHED [10/10] RUN yarn build 0.0s => exporting to image 0.0s => => exporting layers 0.0s => => writing image sha256:d1ca514741dfad131e79d2ed1365a27b6f9882feda643b124e631a2c2637b3c4 0.0s => => naming to docker.io/library/quivr-frontend 0.0s [+] Running 2/0 ✔ Container backend Created 0.0s ✔ Container web Created 0.0s Attaching to backend, web web | yarn run v1.22.19 web | $ next start -p 7017 backend | WARNING: Package(s) not found: gpt4all web | - ready started server on 0.0.0.0:7017, url: http://localhost:7017 backend | INFO: Will watch for changes in these directories: ['/code'] backend | INFO: Uvicorn running on http://0.0.0.0:7018 (Press CTRL+C to quit) backend | INFO: Started reloader process [8] using StatReload web | - info Loaded env from /app/.env backend | INFO: Started server process [10] backend | INFO: Waiting for application startup. backend | [INFO] Using already downloaded file pandoc-3.1.4-1-amd64.deb backend | 2023-07-04 06:00:44,140:INFO - Using already downloaded file pandoc-3.1.4-1-amd64.deb backend | [INFO] Unpacking pandoc-3.1.4-1-amd64.deb to tempfolder... backend | 2023-07-04 06:00:44,140:INFO - Unpacking pandoc-3.1.4-1-amd64.deb to tempfolder

this is my frontend .env,They don't seem to have any problems ：：
NEXT_PUBLIC_ENV=local
NEXT_PUBLIC_BACKEND_URL=http://localhost:7017
NEXT_PUBLIC_SUPABASE_URL=https://eyuojpsbh***
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.*****
NEXT_PUBLIC_JUNE_API_KEY=null

backend .env
SUPABASE_URL=https://eyuojpsbhhn***
SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp***
OPENAI_API_KEY=sk-7VdjA30viDB3iLH1ng5mT3Blb****
ANTHROPIC_API_KEY=null
JWT_SECRET_KEY=xGRGCUZ+mMlE5liveZt3eec7gz0ILks258***
AUTHENTICATE=true
GOOGLE_APPLICATION_CREDENTIALS=null
GOOGLE_CLOUD_PROJECT=null
MAX_BRAIN_SIZE=52428800
MAX_REQUESTS_NUMBER=200

#Private LLM Variables
PRIVATE=False
MODEL_PATH=./local_models/ggml-gpt4all-j-v1.3-groovy.bin
MODEL_N_CTX=1000
MODEL_N_BATCH=8

**Comment by StanGirard** [comment]
The issue comes from migration.sh script. Are you sure it worked ? verify your .migration_info file

**Comment by limumua** [comment]
> The issue comes from migration.sh script. Are you sure it worked ? verify your .migration_info file

Yes, I have not configured this file. Should this be added to readme? thank you very much ! 😀

**Comment by StanGirard** [comment]
It is added in the readme :) Simply run `migration.sh` 

<img width="1465" alt="image" src="https://github.com/StanGirard/quivr/assets/19614572/0e4cc423-b5b8-43bb-94d8-2a00624e7f2e">

**Comment by limumua** [comment]
> 它已添加在自述文件中:)只需运行`migration.sh`
> 
> <img alt="图像" width="1465" src="https://user-images.githubusercontent.com/19614572/250795717-0e4cc423-b5b8-43bb-94d8-2a00624e7f2e.png">

thank you :)

**Comment by limumua** [comment]
> > 它已添加在自述文件中:)只需运行`migration.sh`
> > <img alt="图像" width="1465" src="https://user-images.githubusercontent.com/19614572/250795717-0e4cc423-b5b8-43bb-94d8-2a00624e7f2e.png">
> 
> 谢谢 ：）

I want to create a database myself。

**Comment by StanGirard** [comment]
We dn't support it yet
