### ISSUE TITLE
[Bug] Number of vectors id returned too high

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#502]
## Problem:  APIError - Json could not be generated

https://quivr-brain.sentry.io/issues/4288938524/?project=4505455607808000&query=is%3Aunresolved&referrer=issue-stream&stream_index=2

## Cause: When we request the vectors and we apply a filter the URI is too long

![image](https://github.com/StanGirard/quivr/assets/19614572/48343275-770c-46a4-b56e-e37b7af91eaf)

## Action:

Implement Pagination or something like or change the table brains_vectors to brains_files

**Comment by gozineb** [comment]
URI needs to be < 1000 characters, with 10 vector ids it's over 1024 characters. 
Implementing chunking -> sending batches of 5 vector ids max to avoid this issue.

**Comment by shiliu2023** [comment]
have fixed?

**Comment by gozineb** [comment]
@shiliu2023, yes this was fixed !
