### ISSUE TITLE
Unable to create brain![Issue]

### ISSUE THREAD

**Issue by limumua** [StanGirard/quivr#504]
how to use this？？
![image](https://github.com/StanGirard/quivr/assets/40764041/c5ceb652-1e7f-408f-aec4-591c54c20b0a)

There's nothing in my supabase
![image](https://github.com/StanGirard/quivr/assets/40764041/b04dff3e-b9f5-400e-8d87-bc8b5a0caaf9)

I created PostSQL on Ubuntu, but I don't understand the difference in usage between PostSQL and Supabase here, and when I run install_ Helper.sh, regardless of whether you choose to create_ Tables or choose run_ Migrations, I will receive errors psql: error: connection to server at "127.0.0.1", port 5432 failed: FATAL: password authentication failed for user "lilin", I am sure I created the user and password according to the normal steps。Even if I switch to other users, it's the same mistake, it's strange。Did I do something wrong? It's so difficult for me to use on Ubuntu。TTTToTTTTT

**Comment by FWG16** [comment]
![1688629467927](https://github.com/StanGirard/quivr/assets/56780585/9b825fe0-610c-4b54-bb10-d25e0cd0d92d)
same problem Unable to create brain
