### ISSUE TITLE
vectors is done through the OpenAI API. Is it possible to generate vectors directly?

### ISSUE THREAD

**Issue by shiliu2023** [StanGirard/quivr#510]
vectors is done through the OpenAI API. Is it possible to generate vectors directly? because my  server don't connection internet.

WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbe3be61cd0>, 'Connection to api.openai.com timed out. (connect timeout=600)')': /v1/engines/text-embedding-ada-002/embeddings

**Comment by kerneltravel** [comment]
[this issue](https://github.com/StanGirard/quivr/issues/422) maybe help
