### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by goldenhawksu** [StanGirard/quivr#511]
I am using Ubuntu 20.04 LTS and folllowed instructions of Quivr installation, step1 ~step 4,

in step 5, after I run comman line "docker compose -f docker-compose.yml up --build", I got error as follows,
I believe my internet connection is ok as other packages were in the progress of  installation, they were ok at the same time.

> [frontend  8/10] RUN yarn install:                                                                                                  
#0 7.070 yarn install v1.22.19                                                                                                         
#0 7.881 [1/4] Resolving packages...                                                                                                   
#0 11.97 [2/4] Fetching packages...                                                                                                    
#0 113.3 info There appears to be trouble with your network connection. Retrying...                                                    
#0 148.6 info There appears to be trouble with your network connection. Retrying...
#0 180.6 info There appears to be trouble with your network connection. Retrying...
#0 213.6 info There appears to be trouble with your network connection. Retrying...
#0 269.1 info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
#0 269.1 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#0 269.2 error An unexpected error occurred: "https://registry.yarnpkg.com/date-fns/-/date-fns-2.30.0.tgz: ESOCKETTIMEDOUT".
#0 400.3 info There appears to be trouble with your network connection. Retrying...

**Comment by kerneltravel** [comment]
as mentioned in readme.md [here](https://github.com/StanGirard/quivr#key-features-), OS Compatible: Ubuntu 22 or upper.

**Comment by goldenhawksu** [comment]
OK
