### ISSUE TITLE
[ShareableBrains]: AAU, when I hover one of my brains, I can see an icon "share"

### ISSUE THREAD

**Issue by Chloeroumengas** [StanGirard/quivr#519]
# Epic

#400 

# Functional
When I hover one of my brains, I can see an icon "share" next to the bin. 

## Schema
<img width="283" alt="Capture d’écran 2023-07-05 à 15 05 06" src="https://github.com/StanGirard/quivr/assets/138109838/f8bb8e79-1ca7-4b83-a726-6a0478abea51">

### Tech

- [] To-do

### Tests

- [] it ...

### Validation Checks

- [] it ...

**Comment by kuluruvineeth** [comment]
@gozineb could you please tell me if what i am thinking is correct or not. This issue is still open because share icon is visible on hovering the brains instead there should be invite person icon should be visible....if so can i make the change.
