### ISSUE TITLE
custom OpenAPI URL

### ISSUE THREAD

**Issue by aston314** [StanGirard/quivr#528]
Please support the custom OpenAPI URL functionality because it is difficult for some countries to directly access the OpenAPI URL. People connect to the OpenAPI through proxy OpenAPI URL links.
Like this:

![Screenshot (1)](https://github.com/StanGirard/quivr/assets/2224932/fac9f7f4-4f72-47d2-962f-49302aaea2b0)

**Comment by stefan2904** [comment]
I guess you mean "OpenAI API" and not "OpenAPI"?

**Comment by kpchen** [comment]
need this feature
