### ISSUE TITLE
[Shareable brains]: 7- AAU, I can unsubscribe from a brain

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#538]
# Epic

https://github.com/StanGirard/quivr/issues/400

# Functional

A user can decide to unsubscribe to a brain. 
- If the user is the 'reader/editor' -> on click on the 'bin', he will unsubscribe to the brain -> call delete on /brain/{brain_id}/subscription
- If the user is the 'Owner', he is the only owner -> the brain will get deleted
- If the user is not the only 'Owner' -> the brain wont get deleted but the entry brains_users for that brain_id et user_id

### Tech

- [] To-do

### Tests

- [] it ...

### Validation Checks

- [] it ...

**Comment by mamadoudicko** [comment]
![Screenshot 2023-07-13 at 15 06 25](https://github.com/StanGirard/quivr/assets/63923024/3db08df4-d474-4cba-8f7d-305e1b8e5435)
