### ISSUE TITLE
[Shareable Brains]: 6- AA Unauthenticated User, I'm first redirected to login/signup page then upon authentification, im redirected to the subscription invite modal

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#541]
# Epic

#400 

# Functional
When not logged in, I'm first redirected to login/signup page.
Then upon authentification, im redirected to the subscription invite modal to accept or decline subscribing to the brain.

### Tech

- [] Use local storage to store invitation to subscribe to brain_id  -> new `entry_url` in localStorage ?
- [] Redirection system 

### Tests

- [] it ...

### Validation Checks

- [] it ...

**Comment by mamadoudicko** [comment]
PR: https://github.com/StanGirard/quivr/pull/628
