### ISSUE TITLE
[Issue] Error creating brain

### ISSUE THREAD

**Issue by johnfelipe** [StanGirard/quivr#547]
i have pull from latest version and when i want create a brain show me this error in console:

    139-3fa1ce7dfff2c17b.js:1 Error creating brain test1 to {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}

**Comment by StanGirard** [comment]
And in the backend ?

**Comment by johnfelipe** [comment]
pls give me command for review logs in backend...

**Comment by johnfelipe** [comment]
https://youtu.be/rFEbz93G9U8?t=447

may be helper script is not working?

because installed all locally and manually is working
Can u review and solve issues...

**Comment by johnfelipe** [comment]
bro finally got it

dont use script helper

do it manually:
https://github.com/StanGirard/quivr/blob/main/scripts/tables.sql
https://github.com/StanGirard/quivr/blob/main/scripts/20230629143400_add_file_sha1_brains_vectors.sql

**Comment by BrokenArrow1404** [comment]
> bro finally got it
> 
> dont use script helper
> 
> do it manually: https://github.com/StanGirard/quivr/blob/main/scripts/tables.sql https://github.com/StanGirard/quivr/blob/main/scripts/20230629143400_add_file_sha1_brains_vectors.sql

Hi, I'm not sure what should I do as the first installation, I have already pasted and run the tables.sql in supabase, should I run [20230629143400_add_file_sha1_brains_vectors.sql](https://github.com/StanGirard/quivr/blob/main/scripts/20230629143400_add_file_sha1_brains_vectors.sql)?

**Comment by johnfelipe** [comment]
@BrokenArrow1404 yes dear, run that script and docker run...

**Comment by SAPSentinel** [comment]
Creating brain finally working for me now locally. The steps I followed.
1.) git clone repo quivr
2.) copied env.example to .env for front end and backend.
3.) populated the supabase details in both files.
4.) Docker compose up in Vscode.
5.) Once container running, I copied the above discussed 2 tables and ran as queries in supabase.
6.) refreshed localhost:3000
7.) I can already see Default brain in drop down. Very happy!
8.) I could also create a new brain in a jiffy.
Thanks all for your ideas and support. 

![image](https://github.com/StanGirard/quivr/assets/69308174/3e8bc6e0-4aa9-49f2-9b7e-ac0b7d62f05f)

**Comment by johnfelipe** [comment]
Yes 
Like I say try to do all manually not using .sh script for automatic help and run.

**Comment by jamiejk** [comment]
Thanks for the walkthrough! Could you elaborate on points 4 & 5, I'm completely unfamiliar with Docker and Supabase :)

4.) Docker compose up in Vscode.
5.) Once container running, I copied the above discussed 2 tables and ran as queries in supabase.

**Comment by ioncandel** [comment]
> > bro finally got it
> > dont use script helper
> > do it manually: https://github.com/StanGirard/quivr/blob/main/scripts/tables.sql https://github.com/StanGirard/quivr/blob/main/scripts/20230629143400_add_file_sha1_brains_vectors.sql
> 
> Hi, I'm not sure what should I do as the first installation, I have already pasted and run the tables.sql in supabase, should I run [20230629143400_add_file_sha1_brains_vectors.sql](https://github.com/StanGirard/quivr/blob/main/scripts/20230629143400_add_file_sha1_brains_vectors.sql)?

Hi,

What OS are you on? Ubuntu? Win or MacOS?

Ran the two tables and it did not work, still got the same error.

**Comment by ioncandel** [comment]
> Yes Like I say try to do all manually not using .sh script for automatic help and run.

Looks like the issue is here:

backend  | INFO:     172.19.0.1:61434 - "GET /brains/ HTTP/1.1" 500 Internal Server Error

I am just curious what is the contents of the brains table at the very beginning (first run)? 'Cause it seems to me that the software is trying to get a brain id BEFORE any brain is created....

**Comment by Flinana** [comment]
Hi, I am still having the same issue. Can someone explain please?

**Comment by FelixGunzer** [comment]
also not working for me. still after all steps SAPSentinel proposed

Is it an OS issue; I am on windows

**Comment by FelixGunzer** [comment]
have the same issue even after all steps proposed here. Is it an OS issue? am on windows

**Comment by tc0715888** [comment]
I can't create either, as soon as I try to create, my brain gives an error!

**Comment by tc0715888** [comment]
> 兄弟终于明白了
> 
> 不要使用脚本帮助程序
> 
>  手动操作： https://github.com/StanGirard/quivr/blob/main/scripts/tables.sql https://github.com/StanGirard/quivr/blob/main/scripts/20230629143400_add_file_sha1_brains_vectors.sql

I can't find it. May I ask how you resolved it?
