### ISSUE TITLE
[Issue]  Resource punkt not found.

### ISSUE THREAD

**Issue by wjwark** [StanGirard/quivr#554]
when I try to upload an epub, it cause an error like this, I have download the 'nltk_data' to my computer from internet, but where should I put this folder?

backend  | LookupError:
backend  | **********************************************************************
backend  |   Resource punkt not found.
backend  |   Please use the NLTK Downloader to obtain the resource:
backend  |
backend  |   >>> import nltk
backend  |   >>> nltk.download('punkt')
backend  |
backend  |   For more information see: https://www.nltk.org/data.html
backend  |
backend  |   Attempted to load tokenizers/punkt/PY3/english.pickle
backend  |
backend  |   Searched in:
backend  |     - '/root/nltk_data'
backend  |     - '/usr/local/nltk_data'
backend  |     - '/usr/local/share/nltk_data'
backend  |     - '/usr/local/lib/nltk_data'
backend  |     - '/usr/share/nltk_data'
backend  |     - '/usr/local/share/nltk_data'
backend  |     - '/usr/lib/nltk_data'
backend  |     - '/usr/local/lib/nltk_data'
backend  |     - ''
backend  | **********************************************************************

**Comment by wjwark** [comment]
in fact I have put 'nltk_data' into C:\Users\***\AppData\Roaming   and install it ,but still get this eeror

- Your Operating System----window 11
- Your Docker and Docker Compose versions  ----version 4.20.0 (109717)
- Your Supabase version and setup

**Comment by now-ing** [comment]
Can you tell me how do you solve it?
