### ISSUE TITLE
backend docker can't find start.sh

### ISSUE THREAD

**Issue by mishal-harbi** [StanGirard/quivr#556]
hi,
the frontend works, however, the backend didn't run and giving the following message:

exec /code/scripts/start.sh: no such file or directory

Install is on windows 11. the file "start.sh" exists where it should be. not sure about the issue.
![Screenshot 2023-07-07 223348](https://github.com/StanGirard/quivr/assets/3707835/dfcdfbec-409b-483d-a922-19f51526a62b)

**Comment by MaKeG0** [comment]
same here

**Comment by realto-abe** [comment]
facing same error

**Comment by laodev1** [comment]
ditto

**Comment by cyberautomate** [comment]
Same problem. I can see the start.sh in the files of the container.

**Comment by judrogue3** [comment]
Same here, help!
![Capture1](https://github.com/StanGirard/quivr/assets/44454339/f27d85ae-17cd-4493-afe7-d4bbe5299adc)

**Comment by LiveRuDomest** [comment]
same issue, guys :( 
I thought that my stupid (actually I am)
backend exited with code 0
backend  | exec /code/scripts/start.sh: no such file or directory
backend  | exec /code/scripts/start.sh: no such file or directory
backend  | exec /code/scripts/start.sh: no such file or directory
backend exited with code 1

**Comment by laodev1** [comment]
Hey guys, here is how to fix it: 
If you don't care about gpt4all, just edit Quivr/backend/Dockerfile and replace this:

ENTRYPOINT ["/code/scripts/start.sh"]

with this:

ENTRYPOINT exec uvicorn main:app --reload --host 0.0.0.0 --port 5050

from [this issue](https://github.com/StanGirard/quivr/issues/372)

**Comment by T0by021** [comment]
it seems like the script checks if gpt4all is installed it and installs it otherwise, something added recently.
If you don't care about gpt4all, just edit Quivr/backend/Dockerfile and replace this:

ENTRYPOINT ["/code/scripts/start.sh"]

with this:

ENTRYPOINT exec uvicorn main:app --reload --host 0.0.0.0 --port 5050

**Comment by BasedAnon** [comment]
I am in the same boar

**Comment by BasedAnon** [comment]
> Hey guys, here is how to fix it:

This makes it impossible for me to access quivr from my end.

**Comment by BasedAnon** [comment]
I have no /code/ directory...
There is no such thing in the source code either...
WTF?  Am I crazy, or is everyone else?

**Comment by Kehdar** [comment]
If you are on windows try to change the line ending of the start.sh from CRLF to LF. This solved it for me.

**Comment by LiveRuDomest** [comment]
> Hey guys, here is how to fix it: If you don't care about gpt4all, just edit Quivr/backend/Dockerfile and replace this:
> 
> ENTRYPOINT ["/code/scripts/start.sh"]
> 
> with this:
> 
> ENTRYPOINT exec uvicorn main:app --reload --host 0.0.0.0 --port 5050
> 
> from [this issue](https://github.com/StanGirard/quivr/issues/372)

Thank you, it helped, but now I'm stuck with: PermissionError: [Errno 13] Permission denied: 'log.txt' 
![image](https://github.com/StanGirard/quivr/assets/68866190/ff24eb45-f8df-4b30-8714-0a92076b3782)

@laodev1 The world is not falling apart only because of people like you :) Much appreciate your help

**Comment by LiveRuDomest** [comment]
Oh, and I have just found that my backend .env was with default values, but I did make changes to it
![image](https://github.com/StanGirard/quivr/assets/68866190/767c5aa1-f411-4f38-9bbf-11ba2b5c15ff)

**Comment by Mattang-Tim** [comment]
> Hey guys, here is how to fix it: If you don't care about gpt4all, just edit Quivr/backend/Dockerfile and replace this:
> 
> ENTRYPOINT ["/code/scripts/start.sh"]
> 
> with this:
> 
> ENTRYPOINT exec uvicorn main:app --reload --host 0.0.0.0 --port 5050
> 
> from [this issue](https://github.com/StanGirard/quivr/issues/372)

Nicely done!

Thanks!

**Comment by BasedAnon** [comment]
> If you are on windows try to change the line ending of the start.sh from CRLF to LF. This solved it for me.

I saw this mentioned by someone else, but I have absolutely no clue what it means.  T_T
How do I do that?

**Comment by freshlesh3** [comment]
> > If you are on windows try to change the line ending of the start.sh from CRLF to LF. This solved it for me.
> 
> I saw this mentioned by someone else, but I have absolutely no clue what it means. T_T How do I do that?
> 
> Edit: after looking around, I found the setting in the bottom right of VSCodium. ![image](https://user-images.githubusercontent.com/7894815/252022699-ba91d53f-a1f2-4b43-a072-7316cdba59fb.png)

For anyone looking for 'start.sh' file, it can be found here:
quivr\backend\scripts\start.sh 
Open in vscode and changed the 'Select end of line sequence' as noted by BasedAnon hope it helps.

**Comment by hklein42** [comment]
Thank you very much. That cost me a lifetime. I would never have thought of "LF". I am programme code focused and fixed! I have installed Quivr under Windows (VSCODE, Win-Docker).  It works with Supabase.com. Thanks again.

**Comment by mattzcarey** [comment]
Thanks everyone for your help solving this issue. Since we develop mostly on macOS it got missed.

**Comment by iooiie** [comment]
非常棒， 我已经运行成功了。很感谢
