### ISSUE TITLE
[Issue]Could not find a production build in the '/app/.next' directory

### ISSUE THREAD

**Issue by georgeqin96** [StanGirard/quivr#558]
$ next start
web      | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
web      | - info Loaded env from /app/.env
web      | Error: Could not find a production build in the '/app/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
web      |     at NextNodeServer.getBuildId (/app/node_modules/next/dist/server/next-server.js:342:23)
web      |     at new Server (/app/node_modules/next/dist/server/base-server.js:151:29)
web      |     at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:172:9)
web      |     at NextServer.createServer (/app/node_modules/next/dist/server/next.js:171:24)
web      |     at async /app/node_modules/next/dist/server/next.js:196:31
web      |     at async NextServer.prepare (/app/node_modules/next/dist/server/next.js:153:24)
web      |     at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/render-server.js:121:17) {
web      |   type: 'Error'
web      | }
web      | error Command failed with exit code 1.
web      | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by AbrahimZaman360** [comment]
Create Production Build First then use following Command (:

**Comment by georgeqin96** [comment]
resolved, thanks!

**Comment by 499512742** [comment]
How to deal with this problem？

**Comment by AbrahimZaman360** [comment]
yarn build or npm run build  - according to what package manager you used.

> How to deal with this problem？
