### ISSUE TITLE
Error signing up: Invalid API key

### ISSUE THREAD

**Issue by drgnmsr** [StanGirard/quivr#563]
I get an "Error signing up: Invalid API key" when I try to Sign Up using an email and password. Does anyone know how to fix this? I followed the video thoroughly, so I am unsure which API key it refers to.

**Comment by drgnmsr** [comment]
✔ Network quivr_default  Created                                                                                           0.0s 
 ✔ Container backend      Created                                                                                           0.0s 
 ✔ Container web          Created                                                                                           0.0s 
Attaching to backend, web
web      | yarn run v1.22.19
web      | $ next start
backend  | WARNING: Package(s) not found: gpt4all
web      | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
backend  | INFO:     Will watch for changes in these directories: ['/code']
backend  | INFO:     Uvicorn running on http://0.0.0.0:5050 (Press CTRL+C to quit)
backend  | INFO:     Started reloader process [8] using StatReload
web      | - info Loaded env from /app/.env
backend  | INFO:     Started server process [10]
backend  | INFO:     Waiting for application startup.
backend  | [INFO] Using already downloaded file pandoc-3.1.5-1-amd64.deb
backend  | 2023-07-08 18:33:37,968:INFO - Using already downloaded file pandoc-3.1.5-1-amd64.deb
backend  | [INFO] Unpacking pandoc-3.1.5-1-amd64.deb to tempfolder...
backend  | 2023-07-08 18:33:37,968:INFO - Unpacking pandoc-3.1.5-1-amd64.deb to tempfolder...
backend  | [INFO] Copying pandoc to /root/bin ...
backend  | 2023-07-08 18:33:39,250:INFO - Copying pandoc to /root/bin ...
backend  | [INFO] Making /root/bin/pandoc executeable...
backend  | 2023-07-08 18:33:39,345:INFO - Making /root/bin/pandoc executeable...
backend  | [INFO] Copying copyright to /root/bin ...
backend  | 2023-07-08 18:33:39,345:INFO - Copying copyright to /root/bin ...
backend  | INFO:     Application startup complete.
web      | Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
web      | Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
backend  | INFO:     172.18.0.1:35308 - "OPTIONS /brains/ HTTP/1.1" 200 OK
backend  | INFO:     172.18.0.1:35318 - "OPTIONS /brains/default/ HTTP/1.1" 200 OK
backend  | INFO:     172.18.0.1:35308 - "GET /brains/ HTTP/1.1" 403 Forbidden
backend  | INFO:     172.18.0.1:35318 - "GET /brains/default/ HTTP/1.1" 403 Forbidden
backend  | INFO:     172.18.0.1:56678 - "OPTIONS /brains/ HTTP/1.1" 200 OK
backend  | INFO:     172.18.0.1:56680 - "OPTIONS /brains/default/ HTTP/1.1" 200 OK
backend  | INFO:     172.18.0.1:56680 - "GET /brains/default/ HTTP/1.1" 403 Forbidden
backend  | INFO:     172.18.0.1:56678 - "GET /brains/ HTTP/1.1" 403 Forbidden

This is the log in my terminal. I am assuming that it has something to do with the 403 Forbidden parts that are showing up.

**Comment by strykerx** [comment]
I'm having the same issue.  My supabase api key is in my frontend and backend .env

**Comment by tompayne36** [comment]
I see the same log issues:

INFO:     Application startup complete.
web      | Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
web      | Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
backend  | INFO:     172.18.0.1:51452 - "OPTIONS /brains/default/ HTTP/1.1" 200 OK
backend  | INFO:     172.18.0.1:51456 - "OPTIONS /brains/ HTTP/1.1" 200 OK
backend  | INFO:     172.18.0.1:51456 - "GET /brains/default/ HTTP/1.1" 403 Forbidden
backend  | INFO:     172.18.0.1:51452 - "GET /brains/ HTTP/1.1" 403 Forbidden

**Comment by dermotbarron** [comment]
I'm getting the same issue, has anyone resolved yet?

**Comment by pchopra** [comment]
Make sure you login to Quivr app (top right) or create a user account in db

**Comment by SearchRe** [comment]
There does not seem to be a solution posted here. I'm having this issue also.

**Comment by alex-ber** [comment]
I'm running quivr frontend & backend locally, but supabase remotely. I can't login for the second time neither to supabase (remotely) from localhost neither for quivr frontend & backend locally.

**Comment by Giusemoli312** [comment]
Same error, both from local and app version. Can't insert an api-key. Not the one in the backend, and not a ew generated one...

**Comment by riccardopandolfi** [comment]
Same issue, does anyone know any way to fix?

**Comment by Zuelow** [comment]
same issue, still not solved :(

**Comment by DaKdeGO** [comment]
I am having this issue as well
 :-(

**Comment by Tech-LiKai** [comment]
same issue, still not solved ....
