### ISSUE TITLE
500 Internal Server Error.

### ISSUE THREAD

**Issue by Buantum** [StanGirard/quivr#572]
500 Internal Server Error.
```
Error [TypeError]: Invalid URL: <change-me>/auth/v1
    at new URLImpl (evalmachine.<anonymous>:2830:17)
    at exports.setup (evalmachine.<anonymous>:3037:16)
    at new URL (evalmachine.<anonymous>:3091:26)
    at new SupabaseClient (file:///app/.next/server/middleware.js:9553:41)
    at createClient (file:///app/.next/server/middleware.js:9711:12)
    at createServerSupabaseClient (file:///app/.next/server/middleware.js:13404:10)
    at createMiddlewareSupabaseClient (file:///app/.next/server/middleware.js:121:68)
    at Object.middleware [as handler] (file:///app/.next/server/middleware.js:2136:115)
    at adapter (file:///app/.next/server/middleware.js:1967:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Prc292** [comment]
same error here

**Comment by Prc292** [comment]
I got the same error. realized I had forgotten to save one of the env files in Visual Studio code before starting. after saving it started fine

**Comment by hash00x1** [comment]
you need to add your supabase url to your backend and frontent .env files. The above Error states: `Invalid URL: <change-me>/auth/v1` >> `<change-me>` should actually be the url that links with your supabase instance. Just add it into the .env-file, and remove the <>-brackets.

**Comment by fozrok** [comment]
I'm getting the same 500 Internal Error, even though I have double checked both Front End and Back End Env files config, and they have been save. No idea what to do now.

**Comment by wuzhejia** [comment]
I have changed url in backend/.env as the document, but I haven't change anything in frontend/.env. There is no information in document. Could you give me some prompts?

**Comment by Buantum** [comment]
![image](https://github.com/StanGirard/quivr/assets/49450053/5be7501b-910e-40b3-b7d6-4c359ece9ca6)
![image](https://github.com/StanGirard/quivr/assets/49450053/40e91e8f-fb33-4637-a350-e6a638397bd7)
I have solved my problems and the codes shows above. however, I am not sure why there are no issues....and my quivr works successfully

**Comment by wuzhejia** [comment]
@Buantum Thank you! I changed the env in frontend. It is working well.
<img width="921" alt="image" src="https://github.com/StanGirard/quivr/assets/95853356/06ff8939-dc88-4a5e-999b-f36e4ab10a75">
Just copy SUPABASE_URL and SUPABASE_SERVICE_KEY in env in the backend.

**Comment by Gordon233** [comment]
> ![image](https://user-images.githubusercontent.com/49450053/253227336-5be7501b-910e-40b3-b7d6-4c359ece9ca6.png) ![image](https://user-images.githubusercontent.com/49450053/253227445-40e91e8f-fb33-4637-a350-e6a638397bd7.png) I have solved my problems and the codes shows above. however, I am not sure why there are no issues....and my quivr works successfully

![image](https://github.com/StanGirard/quivr/assets/58379658/9ac4b7c1-6fbf-46af-92cb-6ebee2cd4a63)
it work! thanks!

**Comment by dileepmaurya87** [comment]
How you guys solved this error
I am unable to figure out 
I filled all environment vars correct still 500.
I am using docker command
