### ISSUE TITLE
[Issue] people already made this three months ago - i.e vaultAI 

### ISSUE THREAD

**Issue by su77ungr** [StanGirard/quivr#576]
"Secure: Your data, your control. Always."

bullshit this is miles away from an air-gapped system if supabase is required. 

Is this a thing now? copying repos for engagement farming 

https://github.com/pashpashpash/vault-ai 

For myself I made this work with llamacpp on laptops four months ago https://github.com/su77ungr/casalioy

**Comment by pseudotensor** [comment]
Both privateGPT and Vault-AI haven't been maintained for over 3 weeks, even longer for any substantial changes.
