### ISSUE TITLE
Console errors when trying to chat. [Issue]

### ISSUE THREAD

**Issue by JacobGoldenArt** [StanGirard/quivr#577]
# Issue template for Quivr - Your Second Brain, Empowered by Generative AI

- Your Operating System: Mac OS Ventura 13
- Your Docker version: Engine: 24.0.2 and Docker Compose version: Compose: v2.18.1
- Your Supabase version and setup: Setup as described in documentation.
- Detailed steps to reproduce the issue. 

I uploaded a small pdf then clicked chat and entered a prompt. There is no response but my dev tools shows that it's trying to connect to june and also there is some sort of versel error:

From my Dev Tools Console: 
[168892883836241255] Script Started
727-a984e2dbd450b729.js:1     GET http://localhost:3000/_vercel/insights/script.js net::ERR_ABORTED 404 (Not Found)
32-f3ff194f06b434f7.js:1     POST https://api.june.so/sdk/page 401
chat:1 Unchecked runtime.lastError: The message port closed before a response was received.

I see there is a place to put a june api key in the frontend .env but I don't see any mention of this in the documentation.

Thank you! 
<img width="1278" alt="Screenshot 2023-07-09 at 11 54 48 AM" src="https://github.com/StanGirard/quivr/assets/126922704/d7b58d22-575b-4d28-a1cd-c1f385aaf154">

**Comment by pandaupc** [comment]
same promlem

**Comment by StanGirard** [comment]
Yeah this is our analytics tools on the front end to understand how people use the tool. 

Unfortunately, it sends an error because you don't have the API keys of these tools.

**Comment by zhong-zhilong** [comment]
https://analytics.june.so
