### ISSUE TITLE
[Issue] AttributeError: 'PrivateGPT4AllBrainPicking' object has no attribute 'generate_answer'

### ISSUE THREAD

**Issue by Thinkcore88** [StanGirard/quivr#592]
Problem on Ubuntu 22.04 when try to use private GPT: (everything is ok when using OpenAI CHAT)

AttributeError: 'PrivateGPT4AllBrainPicking' object has no attribute 'generate_answer'

Maybe someone know the issue?

**Comment by rmgravina** [comment]
Same here.

**Comment by ovitrif** [comment]
Same on MacOS, I don't think it has anything to do with the OS tho'.

**Comment by mattzcarey** [comment]
Thanks all, you found pretty big bug. However there is an issue with Langchain and GPT4All compatibility. See this issue: https://github.com/nomic-ai/gpt4all/issues/1117

**Comment by mattzcarey** [comment]
#595
