### ISSUE TITLE
[Issue] An error occurred while processing [FileName]

### ISSUE THREAD

**Issue by 21023395-Goh-Xin-Ru** [StanGirard/quivr#607]
This appear when I tried to upload a file 
![image](https://github.com/StanGirard/quivr/assets/106546777/fb848bc0-6358-41d7-a683-7c1abb5ec126)
![image](https://github.com/StanGirard/quivr/assets/106546777/604a3f87-e84d-4d0a-a8d5-48072924de77)

**Comment by mattzcarey** [comment]
Working on this now

**Comment by mattzcarey** [comment]
Found the cause. The update of Langchain to a newer version broke the supabase integration. 
<img width="1162" alt="Screenshot 2023-07-12 at 09 44 18" src="https://github.com/StanGirard/quivr/assets/77928207/e8c4fc53-5dd3-476d-812c-47045e153c34">

**Comment by piraces** [comment]
Hi @mattzcarey I'm having the same problem and I have verified that the migration is applied... Something could be missing? I have my repo up to date... 😞

**Comment by mattzcarey** [comment]
Have you run the latest migration script?

**Comment by piraces** [comment]
Yep, it has the latest changes... I'm going to review everything again or recreate the database

**Comment by mattzcarey** [comment]
This is maybe a related bug. @mamadoudicko has a PR in to fix it.

**Comment by piraces** [comment]
Working now! Thank you... This was probably my issue 😞
