### ISSUE TITLE
[Suggestion] Clarify role of Supabase in Readme

### ISSUE THREAD

**Issue by stefan2904** [StanGirard/quivr#612]
First of all, thanks for the project! 
I have a small proposal for the documentation:

In the README, it first says "Your data, your control. Always." but then you have to setup an Supabase account.

Can you clarify in the README for what this account is needed and what data it receives, and to what extend cloud services are involved in quivr?

Thanks!

**Comment by stefan2904** [comment]
The same is probably true for the OpenAI and Google API keys in `.backend_env.example`. Does this mean quivr sends the data to those services?

**Comment by duaneking** [comment]
Requiring third parties is a security risk.

**Comment by thunguyen1012** [comment]
I also want to clear this point
