### ISSUE TITLE
[Issue] How do you use this with Anthropic?

### ISSUE THREAD

**Issue by TheCatster** [StanGirard/quivr#614]
I see in the `.env` that Anthropic is supported, but no matter what I do OpenAI is the only option. What should I do? This should be better documented.

Thank you!

**Comment by wwzeng1** [comment]
Hi! I’m one of the founders of Sweep, a github app that solves issues by writing pull requests. 
This looks like a good issue for Sweep https://github.com/sweepai/sweep to try. It might need a bit more detail from the maintainers though. 
We have onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)
