### ISSUE TITLE
Supabase dependency is a security risk, needs removed.

### ISSUE THREAD

**Issue by duaneking** [StanGirard/quivr#618]
Requiring a third party for this in any way is a complete violation of security parameters and creates the problem of lack of trust as I can't control this third party and I can't control what they do with any data that they are sent, so I would rather they just not be involved because they're not trustworthy as a third party that I cant control.

**Comment by bright258** [comment]
@duaneking sounds right. What better alternatives do you suggest?

**Comment by duaneking** [comment]
In the interest of fairness, and out of the desire to not get drawn out into lengthy discussions about what the best alternative is, I can only advocate for something that is self contained, self hosting, something that can be used freely by the local OS, and be self contained to that host

**Comment by Ananderz** [comment]
Chroma would do it!

**Comment by Meathelix1** [comment]
Yeah I agree, lets get Chroma for this.

**Comment by mariocuellar1** [comment]
+1 Chroma
