### ISSUE TITLE
[Issue] "quivr_default" not found

### ISSUE THREAD

**Issue by smallma** [StanGirard/quivr#623]
- Your Operating System: Ubuntu 22.04 LTS
- Your Docker and Docker Compose versions: podman-compose instead of
- Your Supabase version and setup: 
- Detailed steps to reproduce the issue

After setting up step 1 ~ step 4, and then executing "podman-compose -f docker-compose.yml up --build".

The errors shows up as below. Please help to clarify. Thanks. 

<img width="1114" alt="image" src="https://github.com/StanGirard/quivr/assets/429250/7227b937-48b6-488e-9e30-3e049f351938">

**Comment by tompayne36** [comment]
Similar issue. I was excited to try Quivr on a free Oracle Cloud VM I have, but I have not been able to get it working yet. I get to the Docker compose step…but found out the Oracle machine is using “podman” (a docker clone?). The compose runs for quite some time but eventually exits with an error code. Does the Quivr/Docker expect a Windows or MacOS architecture? Specific flavors of Linux?
