### ISSUE TITLE
backend: Error processing file: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by 2000calories** [StanGirard/quivr#624]
Operating System: macOS Ventura V13.4
Docker and Docker Compose versions: 4.21.1 (114176)

```
backend  | 575afffc-a618-46ee-9cf1-bba277feb06e brain_id
backend  | brain id=UUID('575afffc-a618-46ee-9cf1-bba277feb06e') name='Default brain' status='public' model='gpt-3.5-turbo-0613' temperature=0.0 max_tokens=256 max_brain_size=52428800 files=[]
backend  | file sha1 da6e970acec64a695c7ebddae91858c46f2ec523
backend  | file_sha1 da6e970acec64a695c7ebddae91858c46f2ec523
backend  | vectors_ids []
backend  | len(vectors_ids) 0
backend  | response.data []
backend  | documents.......

backend  | Error processing file: 'NoneType' object is not subscriptable
backend  | INFO:     172.18.0.1:42714 - "POST /upload?brain_id=575afffc-a618-46ee-9cf1-bba277feb06e HTTP/1.1" 200 OK
```

**Comment by TrishalPoojary** [comment]
Observed similar issue while using private LLM

**Comment by shlomi-lachmish** [comment]
I get the same error, but noticed that there is a prior error that might be related
utils.vectors: Error creating vector for document {'code': '22P02', 'details': None, 'hint': None, 'message': 'invalid input syntax for type bigint: "f4f730e0-d6a3-4acd-a483-caff2d403bb2"'}

**Comment by ongraphpythondev** [comment]
The code 22P02 is Postgres error code which means you are trying to insert an incompatible value in the column. In this case, its due to the change in the id column type of the vector table. Reset the database and re-run the db setup will solve the issue.

**Comment by WTL129** [comment]
what should i do i am also getting this same error?

backend  | 2023-07-14 19:13:35,616 [ERROR] utils.vectors: Error creating vector for document {'code': '22P02', 'details': None, 'hint': None, 'message': 'invalid input syntax for type bigint: "b9fad147-f28d-45ec-93e9-9ccd9c5328ae"'}
backend  |
backend  | Error processing file: 'NoneType' object is not subscriptable
backend  | INFO:     172.18.0.1:44222 - "POST /upload?brain_id=70b2a726-3967-4eba-ba82-eda793548d6d HTTP/1.1" 200 OK
backend  |

**Comment by S1ow** [comment]
同样出现了该问题：
2023-07-15 23:38:59 2023-07-15 15:38:59,670 [ERROR] utils.vectors: Error creating vector for document You exceeded your current quota, please check your plan and billing details.
2023-07-15 23:38:25 p/tmpponi1beb xxxxxxxx 脱敏一下
2023-07-15 23:38:59 Error processing file: 'NoneType' object is not subscriptable
2023-07-15 23:38:59 INFO:     172.18.0.1:37242 - "POST /upload?brain_id=2cb10479-98f7-4151-a844-260d78271656 HTTP/1.1" 200 OK
