### ISSUE TITLE
AuthApiError: Invalid Refresh Token: Refresh Token Not Found

### ISSUE THREAD

**Issue by jooewood** [StanGirard/quivr#636]
web      |  [AuthApiError: Invalid Refresh Token: Refresh Token Not Found] {
web      |   __isAuthError: true,
web      |   name: 'AuthApiError',
web      |   status: 400
web      | }
web      |  [AuthApiError: Rate limit exceeded] {
web      |   __isAuthError: true,
web      |   name: 'AuthApiError',
web      |   status: 429
web      | }
web      |  [AuthApiError: Rate limit exceeded] {
web      |   __isAuthError: true,
web      |   name: 'AuthApiError',
web      |   status: 429
web      | }
web      |  [AuthApiError: Rate limit exceeded] {
web      |   __isAuthError: true,
web      |   name: 'AuthApiError',
web      |   status: 429
web      | }
web      |  [AuthApiError: Rate limit exceeded] {
web      |   __isAuthError: true,
web      |   name: 'AuthApiError',
web      |   status: 429
web      | }
web      |  [AuthApiError: Rate limit exceeded] {
web      |   __isAuthError: true,
web      |   name: 'AuthApiError',
web      |   status: 429
web      | }
web      |  [AuthApiError: Rate limit exceeded] {
web      |   __isAuthError: true,
web      |   name: 'AuthApiError',
web      |   status: 429
web      | }
web      |  [AuthApiError: Rate limit exceeded] {
web      |   __isAuthError: true,
web      |   name: 'AuthApiError',
web      |   status: 429
web      | }
web      |  [AuthApiError: Rate limit exceeded] {
web      |   __isAuthError: true,
web      |   name: 'AuthApiError',
web      |   status: 429
web      | }

**Comment by aravindshaj** [comment]
I'm getting the same error! Any leads?

**Comment by mrshehzad1** [comment]
getting the same error
