### ISSUE TITLE
[Epic](FEATURE REQUEST): expose document chunking settings on quivr's GUI

### ISSUE THREAD

**Issue by dukemagus** [StanGirard/quivr#644]
# The why

Language models are constantly evolving, and one of the areas that is showing constant growth is max token size per request/message.

As of right now, the standard vector DB workflow used in langchain involves chunking text, with a default size conservatively fitting OpenAI's text-embeddings-ada-002's capabilities.

But it's pretty possible that in a couple monhts we'll get a token limit increase for GPT 3.5 or GPT 4or a new model capable of taking massive ammount of token inputs in a single query.

In order to be prepared to that change and also keep flexibility between models, i suggest an "advanced settings" tab to control the variables of the chunking script

# The what

## What are we developing?

- New settings with fields and controls to fine tune file chunking while processing uploaded files to add in each brain.
- The upload document page should have an extra tab with these settings. this should either be collapsable or in a tabbed view, so people that don't care about the settings aren't bothered by them

## What are the validation criteria to validate this feature?

- presentation doesn't break the intended appearance of quivr's webUI
- nothing crashes
- the system prevents the user from inputting values beyond the model's token limit
  - SUGGESTION: add a slider with min and max chunk size
- the user should be notified after the embeddings are processed about the number of chunks generated and reminded of the size used.
  - EXAMPLE: `file examplefile.pdf was processed sucessfully, generating 999 chunks with up to 4096 characters each`

EDGE CASES:

- User settings making chunks bigger than the embeddings model can handle. The process should stop and expose the error and instructions to lower chunk size if this happens
- Users inputting invalid values: validation should be added in each field and invalid values should be discarded, reverting the field data to the default.
- Server errors when reading settings: the default action should always be raise a warning and use default constant values if some field is null somehow

## What’s out of scope for this feature?

- Data filtering (to avoid empty pages, junk data, html tags and other strings that have no relevant info: good to have, but too complex to add together with this feature)
- Chunk metadata edit (that's a different feature)
- Chunk preview (different feature, would make quivr run slower)
- chunk saving/exporting (could help with debugging, but out of scope right now)
- chunk saving, comparison and check for duplicates (should be handled after the chunking preprocessing)

## Should this feature be feature flagged?

What is a feature flag?

# The how

## How are we going to code this feature?

- Store new constants with the current token limit of the embedding models used 
  - example: OpenAi's ada-002 has a 8192 token limit, but Azure AI's ada-002, even with the same name, has a token limit of 2048).
- Create a new safety constant with a character limit calculated based on the token limit of the embedding model (recommended: char limit = modelTokenLimit*3)
- store two new set of variables on the brain settings: a set of "default" values for the chunking process per file type and a set of "temporary" values in case the user wants to process each document with different chunking settings. 
- The values exposed should at least contain:
  - embedding model (in case the user wants to use a local embeddings model or if ada-002 ever gets a more advanced counterpart)
  - chunk size in characters
  -chunk overlap size in characters
  - tooltip or text message explaining the overlap will always be rounded to the the largest ammount of characters without adding incomplete words (just to be sure)
- create a collapsable or tabbed view to check and edit these values before uploading a document or link
  - OPTIONAL: add tooltips with a summary of what each value does
- use the values in these values in processors scripts, like backend/parsers/common.py or backend/models/files.py depending on what's used.
  - OPTIONAL: give the user the option to use the new values only for this document or all files of the same type (save new defaults for the brain)

## Are there any technical decisions made that should be shared?

Double check the order the functions will be called to prevent anything being changed during or after the text is being split or submitted for indexing.

## What is preventing us from delivering this feature?

Adding new options will always open more points where the software can break and will also make the experience less streamlined for the user (just having a settings button can already raise doubts for some users), and the actual default values are "good enough" for the models we have until july/2023.

More importantly, making these look correct and not obtrusive in the GUI is something i have no knowledge about how it can be done.

## What can the feature potentially break?

Page Layout and embeddings if anyone does a PR without testing the GUI on multiple page orientations and sizes or if the file upload and splitting/chunking process doesn't check availiable memory before (if an user goes overboard and tries to load a PDF with hundreds of megabytes of text and very long overlapping sections, it can baloon out of control really fast)

**Comment by StanGirard** [comment]
Thanks for the epic proposition. I'll dive into it :)
