### ISSUE TITLE
[Error occurred while getting answer]

### ISSUE THREAD

**Issue by zinojeng** [StanGirard/quivr#645]
1. Chat with error message:
had access local host and upload two files documents. 
Error message "**Error occurred while getting answer**" appears in a chat with a question.

2. Failed to crawl website

Please help, thanks

[![](https://i.imgur.com/TMPnOpF.png)](url)
[![](https://i.imgur.com/3fKf4tJ.png)](url)

**Comment by mattzcarey** [comment]
Try and select a brain first. I have a PR which should fix this issue #635
