### ISSUE TITLE
Error with Docker compose for backend 

### ISSUE THREAD

**Issue by arsdorintbp2003** [StanGirard/quivr#651]
Hello, it seems that during the Docker compose run, I receive this error:         
![image](https://github.com/StanGirard/quivr/assets/88639992/7311832c-cb37-4a0f-b8ea-7818688d6296)
I assume that this is because I use other application with port 3000:3000 (more specifically Grafana). I have try to terminate this port, but can't solve the issue.
Then, I decide to change the port inside the docker-compose.yml file to port 3002:3000, and receive this error.                                                                               
![image](https://github.com/StanGirard/quivr/assets/88639992/ca6012f1-ad0a-4d96-b263-f369f2000663)
At this point, I think it might be the problems with permission of the file. So is this correct, or is there any others reasons? And how to fix it. Thanks for your help.

**Comment by rrrr98** [comment]
Hi, I suppose this run on Windows. Try changing line endings CRLF to LF for `backend/scripts/start.sh` file and build the Docker image again (maybe need --no-cache option -> `docker compose build --no-cache` or just try `docker compose up --build`)

**Comment by mattzcarey** [comment]
The start script will be removed in the next week. It is causing too many issues with compatibility :)

**Comment by ProTechnomancy** [comment]
ah, ive been banging my head against this for 48hrs now, im down to my last idea; if it doesn't work then ill wait for your update :) cant wait to sync my teeth into this awesome app!

**Comment by SkillTPA23** [comment]
Hi I trying quivr using using docker and suopabase but won't build saying backend docker file IP address not found? any help appreciated
