### ISSUE TITLE
[Issue] Error creating brain after using 'install_helper.sh'

### ISSUE THREAD

**Issue by xgdfalcon** [StanGirard/quivr#655]
I am running on MacBookPro with M2 chip and macOS 13.2.1

I have tried both ways to do the setup and they result in the same issue.

I have triple verified that all my keys/urls are absolutely correct.

When I login and create a new brain, I get the following errors on console.

------------------------------

```sh
backend  | INFO:     172.20.0.1:42098 - "POST /brains/ HTTP/1.1" 500 Internal Server Error
backend  | ERROR:    Exception in ASGI application
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend  |     result = await app(  # type: ignore[func-returns-value]
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend  |     return await self.app(scope, receive, send)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend  |     await super().__call__(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend  |     await self.middleware_stack(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend  |     await self.app(scope, receive, _send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend  |     await self.app(scope, receive, sender)
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend  |     raise e
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend  |     await route.handle(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend  |     response = await func(request)
backend  |                ^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend  |     raw_response = await run_endpoint_function(
backend  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend  |     return await dependant.call(**values)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/routes/brain_routes.py", line 163, in create_brain_endpoint
backend  |     brain.create_brain()  # pyright: ignore reportPrivateUsage=none
backend  |     ^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/models/brains.py", line 123, in create_brain
backend  |     commons["supabase"].table("brains").insert({"name": self.name}).execute()
backend  |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 68, in execute
backend  |     raise APIError(r.json())
backend  | postgrest.exceptions.APIError: {}

```

**Comment by rsoutar** [comment]
Check on Supabase and see if it create a tables for you?

If not then check if you have `psql` installed on your Mac.

You can install via Homebrew `brew install libpq` then `echo 'export PATH="/usr/local/opt/libpq/bin:$PATH"' >> ~/.zshrc`

**Comment by ioncandel** [comment]
I too have this error.  I am running Ubuntu 22.04.2 LTS.

I have tried various fixes about the ENTRYPOINT and the start.sh file, but I still get this error:

"GET /brains/ HTTP/1.1" 500 Internal Server Error
backend  | ERROR:    Exception in ASGI application
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend  |     result = await app(  # type: ignore[func-returns-value]
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend  |     return await self.app(scope, receive, send)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend  |     await super().__call__(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend  |     await self.middleware_stack(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend  |     await self.app(scope, receive, _send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend  |     raise exc
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend  |     await self.app(scope, receive, sender)
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend  |     raise e
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend  |     await route.handle(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend  |     await self.app(scope, receive, send)
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend  |     response = await func(request)
backend  |                ^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 227, in app
backend  |     solved_result = await solve_dependencies(
backend  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 622, in solve_dependencies
backend  |     solved = await call(**sub_values)
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/auth/auth_bearer.py", line 25, in __call__
backend  |     return await self.authenticate(
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/auth/auth_bearer.py", line 42, in authenticate
backend  |     return self.get_test_user()
backend  |            ^^^^^^^^^^^^^^^^^^^^
backend  |   File "/code/auth/auth_bearer.py", line 55, in get_test_user
backend  |     return User(
backend  |            ^^^^^
backend  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend  | pydantic.error_wrappers.ValidationError: 1 validation error for User
backend  | id
backend  |   value is not a valid uuid (type=type_error.uuid)

Are there any Ubuntu users that made it work?
