### ISSUE TITLE
 if not os.path.exists(pypandoc.get_pandoc_path()):?

### ISSUE THREAD

**Issue by shiliu2023** [StanGirard/quivr#658]
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/code/main.py", line 35, in startup_event
    if not os.path.exists(pypandoc.get_pandoc_path()):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypandoc/__init__.py", line 622, in get_pandoc_path
    _ensure_pandoc_path()
  File "/usr/local/lib/python3.11/site-packages/pypandoc/__init__.py", line 750, in _ensure_pandoc_path
    raise OSError("No pandoc was found: either install pandoc and add it\n"
OSError: No pandoc was found: either install pandoc and add it
to your PATH or or call pypandoc.download_pandoc(...) or
install pypandoc wheels with included pandoc.

ERROR:    Application startup failed. Exiting.

**Comment by fluorescentoast** [comment]
open your docker terminal and run `apt-get install pandoc`

**Comment by aravindshaj** [comment]
How do I overcome this on my mac?


ERROR:    Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
backend  |     async with self.lifespan_context(app) as maybe_state:
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
backend  |     await self._router.startup()
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
backend  |     await handler()
backend  |   File "/code/main.py", line 35, in startup_event
backend  |     if not os.path.exists(pypandoc.get_pandoc_path()):
backend  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/__init__.py", line 622, in get_pandoc_path
backend  |     _ensure_pandoc_path()
backend  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/__init__.py", line 750, in _ensure_pandoc_path
backend  |     raise OSError("No pandoc was found: either install pandoc and add it\n"
backend  | OSError: No pandoc was found: either install pandoc and add it
backend  | to your PATH or or call pypandoc.download_pandoc(...) or
backend  | install pypandoc wheels with included pandoc.
backend  | 
backend  | ERROR:    Application startup failed. Exiting.

Thank youfor your time!

**Comment by malikmmoaz** [comment]
> How do I overcome this on my mac?
> 
> ERROR: Traceback (most recent call last): backend | File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan backend | async with self.lifespan_context(app) as maybe_state: backend | File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in **aenter** backend | await self._router.startup() backend | File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup backend | await handler() backend | File "/code/main.py", line 35, in startup_event backend | if not os.path.exists(pypandoc.get_pandoc_path()): backend | ^^^^^^^^^^^^^^^^^^^^^^^^^^ backend | File "/usr/local/lib/python3.11/site-packages/pypandoc/**init**.py", line 622, in get_pandoc_path backend | _ensure_pandoc_path() backend | File "/usr/local/lib/python3.11/site-packages/pypandoc/**init**.py", line 750, in _ensure_pandoc_path backend | raise OSError("No pandoc was found: either install pandoc and add it\n" backend | OSError: No pandoc was found: either install pandoc and add it backend | to your PATH or or call pypandoc.download_pandoc(...) or backend | install pypandoc wheels with included pandoc. backend | backend | ERROR: Application startup failed. Exiting.
> 
> Thank youfor your time!

same issue

**Comment by CTGS-Innovations** [comment]
I added this to my /backend/scripts/start.sh 

I remove the gpt4all code as I still can't get it working but this solved the issue of the missing pandoc after each build

```
#!/bin/bash

# Move to the code directory
cd /code

apt-get install pandoc

# Start your app
uvicorn main:app --reload --host 0.0.0.0 --port 5050

```

**Comment by StanGirard** [comment]
I just merge a change that should fix it :)

**Comment by rhoconlinux** [comment]
Hello, same error here, but without the start.sh script I don´t know how to solve it. Sorry I´m not familiar with Docker. 
I tried to fix my own Dockerfile without success. 
Can anyone give me a hand? 

'''
web      | - info Loaded env from /app/.env
backend  | INFO:     Started server process [10]
backend  | INFO:     Waiting for application startup.
backend  | [INFO] Maybe try:
backend  |
backend  |     sudo apt-get install pandoc
backend  |
backend  | 2023-07-16 09:47:04,155:INFO - Maybe try:
backend  |
backend  |     sudo apt-get install pandoc
backend  |
backend  | [INFO] See http://johnmacfarlane.net/pandoc/installing.html
backend  | for installation options
backend  |
backend  | 2023-07-16 09:47:04,155:INFO - See http://johnmacfarlane.net/pandoc/installing.html
backend  | for installation options
backend  |
backend  |
backend  | [INFO] ---------------------------------------------------------------
backend  |
backend  |
backend  | 2023-07-16 09:47:04,156:INFO - ---------------------------------------------------------------
backend  |
backend  |
backend  |
backend  | ERROR:    Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
backend  |     async with self.lifespan_context(app) as maybe_state:
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
backend  |     await self._router.startup()
backend  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
backend  |     await handler()
backend  |   File "/code/main.py", line 35, in startup_event
backend  |     if not os.path.exists(pypandoc.get_pandoc_path()):
backend  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/__init__.py", line 622, in get_pandoc_path
backend  |     _ensure_pandoc_path()
backend  |   File "/usr/local/lib/python3.11/site-packages/pypandoc/__init__.py", line 750, in _ensure_pandoc_path
backend  |     raise OSError("No pandoc was found: either install pandoc and add it\n"
backend  | OSError: No pandoc was found: either install pandoc and add it
backend  | to your PATH or or call pypandoc.download_pandoc(...) or
backend  | install pypandoc wheels with included pandoc.
backend  |
backend  | ERROR:    Application startup failed. Exiting.
'''

**Comment by malikmmoaz** [comment]
This is how I have managed to fix it, runs fine,

`#!/bin/bash

# Check if gpt4all is already installed
#if ! pip show gpt4all > /dev/null; then
#    if [[ $PRIVATE == "True" ]]; then
#        apt-get install -y liblzma-dev cmake

#        cd /tmp && git clone --recurse-submodules https://github.com/nomic-ai/gpt4all
#        cd gpt4all/gpt4all-backend/
#        mkdir build && cd build
#        cmake .. && cmake --build . --parallel
#        cd ../../gpt4all-bindings/python
#        pip3 install -e .
#    fi
#fi

# Move to the code directory
cd /code

apt-get install pandoc -y

# Start your app
uvicorn main:app --reload --host 0.0.0.0 --port 5050`

The -y flag provides a 'yes' flag to the confirmation message and install the required dependencies.
