### ISSUE TITLE
On MacOS: "psql: command not found" when running install_helper.sh or migration.sh

### ISSUE THREAD

**Issue by codingbutstillalive** [StanGirard/quivr#660]
I am running latest version of MacOS and tried a fresh install of quivr.

Obviously, tables are not created in my Supabase account. There is a an error saying "psql: command not found at migration.sh, line 6"

**Comment by rsoutar** [comment]
Try this https://github.com/StanGirard/quivr/issues/655#issuecomment-1635965425

**Comment by rhoconlinux** [comment]
Hi there, solved by running these commands in a terminal:

```
brew doctor
brew update
brew install libpq
brew link --force libpq
```

Cheers!

**Comment by codingbutstillalive** [comment]
'brew doctor' - what does it do?

thanks a lot :)
