### ISSUE TITLE
Using gpt4all

### ISSUE THREAD

**Issue by MaryamAAra** [StanGirard/quivr#664]
Hi
I use private LLM, but when I upload files, it seems that requests are sent to the Open AI API. (I updated PRIVATE=True on  backend/.env 
).  Do I need to do anything else?

**Comment by MaryamAAra** [comment]
so we can't  use local embeddings instead of openai embeddings:(

**Comment by beifeng777** [comment]
WARNING: Package(s) not found: gpt4all
