### ISSUE TITLE
 ERROR: Exception in ASGI application

### ISSUE THREAD

**Issue by ioncandel** [StanGirard/quivr#669]
Are there any Ubuntu users that made it work?

Here is the error I am getting right when I try to login to the link:  

"GET /brains/ HTTP/1.1" 500 Internal Server Error
backend | ERROR: Exception in ASGI application
backend | Traceback (most recent call last):
backend | File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend | result = await app( # type: ignore[func-returns-value]
backend | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend | File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in call
backend | return await self.app(scope, receive, send)
backend | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend | File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in call
backend | await super().call(scope, receive, send)
backend | File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in call
backend | await self.middleware_stack(scope, receive, send)
backend | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in call
backend | raise exc
backend | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in call
backend | await self.app(scope, receive, _send)
backend | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in call
backend | await self.simple_response(scope, receive, send, request_headers=headers)
backend | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend | await self.app(scope, receive, send)
backend | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in call
backend | raise exc
backend | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in call
backend | await self.app(scope, receive, sender)
backend | File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in call
backend | raise e
backend | File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in call
backend | await self.app(scope, receive, send)
backend | File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in call
backend | await route.handle(scope, receive, send)
backend | File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend | await self.app(scope, receive, send)
backend | File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend | response = await func(request)
backend | ^^^^^^^^^^^^^^^^^^^
backend | File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 227, in app
backend | solved_result = await solve_dependencies(
backend | ^^^^^^^^^^^^^^^^^^^^^^^^^
backend | File "/usr/local/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 622, in solve_dependencies
backend | solved = await call(**sub_values)
backend | ^^^^^^^^^^^^^^^^^^^^^^^^
backend | File "/code/auth/auth_bearer.py", line 25, in call
backend | return await self.authenticate(
backend | ^^^^^^^^^^^^^^^^^^^^^^^^
backend | File "/code/auth/auth_bearer.py", line 42, in authenticate
backend | return self.get_test_user()
backend | ^^^^^^^^^^^^^^^^^^^^
backend | File "/code/auth/auth_bearer.py", line 55, in get_test_user
backend | return User(
backend | ^^^^^
backend | File "pydantic/main.py", line 341, in pydantic.main.BaseModel.init
backend | pydantic.error_wrappers.ValidationError: 1 validation error for User
backend | id
backend | value is not a valid uuid (type=type_error.uuid)

**Comment by ioncandel** [comment]
The error appears when trying to create a new brain.

**Comment by hklein42** [comment]
Windows 11, VSCODE up to date
Hi,
the installation worked fine with the new version today on Windows (start.sh under VSCODE in the path "/backend/core/scripts/" saved with LF) and also on the VBox under Ubuntu 22.04. The web and backend Docker also started immediately without any problems (thanks, for that). 
BUT:
However, the same error always appears when uploading PDF, XLSX, TXT ... no matter which brain I select or create. Deleting the documents works, but not the upload!  
My error message:
ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core  |     await self.app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core  |     raise e
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend-core  |     raw_response = await run_endpoint_function(
backend-core  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend-core  |     return await dependant.call(**values)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/routes/upload_routes.py", line 49, in upload_file
backend-core  |     brain.max_brain_size = os.getenv(
backend-core  |     ^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
backend-core  | ValueError: "Brain" object has no field "max_brain_size"
Many thanks in advance

**Comment by ioncandel** [comment]
If the recent updates were intended to fix that issue and mine.. it did not work. I have pulled the latest modifications and I STILL get the same error!

Are there any issues with regards to the user name (i.e. special characters that are not allowed, etc.)?

**Comment by ioncandel** [comment]
So after digging some more I localized the source in the backend/core/auth/auth_bearer.py file line 41:

  return self.get_test_user()

then the line 54:

def get_test_user(self) -> User:
        return User(
            email="test@example.com", id="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"  # type: ignore
        )  # replace with test user information 

How come this function is called when I try to connect on local????

**Comment by val-samonte** [comment]
> So after digging some more I localized the source in the backend/core/auth/auth_bearer.py file line 41:
> 
> return self.get_test_user()
> 
> then the line 54:
> 
> def get_test_user(self) -> User: return User( email="[test@example.com](mailto:test@example.com)", id="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" # type: ignore ) # replace with test user information
> 
> How come this function is called when I try to connect on local????

Check your backend .env and make sure `AUTHENTICATE=true`

**Comment by ioncandel** [comment]
Thank you for your message Val! I did as you said, but now I have another issue:

web           | - info Loaded env from /app/.env
backend-core  | Process SpawnProcess-1:
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
backend-core  |     self.run()
backend-core  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
backend-core  |     self._target(*self._args, **self._kwargs)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
backend-core  |     target(sockets=sockets)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
backend-core  |     return asyncio.run(self.serve(sockets=sockets))
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
backend-core  |     return runner.run(main)
backend-core  |            ^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
backend-core  |     return self._loop.run_until_complete(task)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
backend-core  |     return future.result()
backend-core  |            ^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
backend-core  |     config.load()
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
backend-core  |     self.loaded_app = import_from_string(self.app)
backend-core  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
backend-core  |     module = importlib.import_module(module_str)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend-core  |     return _bootstrap._gcd_import(name[level:], package, level)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend-core  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend-core  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend-core  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend-core  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend-core  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend-core  |   File "/code/main.py", line 11, in <module>
backend-core  |     from routes.brain_routes import brain_router
backend-core  |   File "/code/routes/brain_routes.py", line 6, in <module>
backend-core  |     from models.brains import (
backend-core  |   File "/code/models/brains.py", line 6, in <module>
backend-core  |     from utils.vectors import get_unique_files_from_vector_ids
backend-core  |   File "/code/utils/vectors.py", line 12, in <module>
backend-core  |     class Neurons(BaseModel):
backend-core  |   File "/code/utils/vectors.py", line 14, in Neurons
backend-core  |     settings = BrainSettings()  # pyright: ignore reportPrivateUsage=none
backend-core  |                ^^^^^^^^^^^^^^^
backend-core  |   File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
backend-core  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-core  | pydantic.error_wrappers.ValidationError: 1 validation error for BrainSettings
backend-core  | pg_database_url
backend-core  |   field required (type=value_error.missing)
