### ISSUE TITLE
[Error]: $'\r': command not found

### ISSUE THREAD

**Issue by dennis-gonzales** [StanGirard/quivr#670]
Got this error when I run `./install_helper.sh`. then received the same error on `./migration.sh`:
` /code/scripts/start.sh: line 2: $'\r': command not found`

![image](https://github.com/StanGirard/quivr/assets/43110624/efaae67d-eb5e-48ef-b865-26555b2c2a93)

- Windows 11
- 24.0.2, build cb74dfc - v2.18.1
- Postgres: 15.1.0.103

To reproduce, I just run the scripts above.

**Comment by yunmemory** [comment]
i got the same issue, have you resolved this? Thanks

**Comment by hklein42** [comment]
Error:
backend-core exited with code 2
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file

**Comment by BenGriffithsPEP** [comment]
I had the same issue and managed to solve it by doing this:

Open start.sh in VS Code.
In the bottom-right corner, click on "CRLF".
In the dropdown menu that appears, select "LF".
Save the file.
After doing this, try running the script again. The error should be resolved.

Explanation:

The error message you're seeing is related to the difference in how line endings are handled in Unix-based systems (like Linux or macOS) and Windows.

In Unix-based systems, lines in text files end with a Line Feed (LF), represented as '\n'. In Windows, lines end with a Carriage Return followed by a Line Feed (CRLF), represented as '\r\n'.

The error message backend-core | /code/scripts/start.sh: line 2: $'\r': command not found suggests that the shell script start.sh has Windows-style line endings (CRLF), but it's being run in a Unix-like environment (likely a Linux container or subsystem on your Windows machine) that expects Unix-style line endings (LF).

To resolve this issue, you need to convert the line endings in start.sh from CRLF to LF.

**Comment by codewithpedro** [comment]
I still get the error even after switch to LF

```
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
```

**Comment by magusarcanum39** [comment]
@BenGriffithsPEP Thank you so much :)
