### ISSUE TITLE
[Issue] After the new file is imported, it is not displayed in the brain and cannot be used

### ISSUE THREAD

**Issue by beifeng777** [StanGirard/quivr#678]
<img width="669" alt="image" src="https://github.com/StanGirard/quivr/assets/29267921/b50a0f60-3024-4bad-bc46-975bd583bb80">
The three files were successfully uploaded, but the brain volume showed 0.
<img width="856" alt="image" src="https://github.com/StanGirard/quivr/assets/29267921/f3579a59-ffc5-4a73-b94d-3245f7cd22f0">
I can still upload new files, but I can't display them in my brain anymore, nor can I use them. What should I do?

**Comment by shiliu2023** [comment]
实在解决不了可以联系我们付点费用解决😂

**Comment by beifeng777** [comment]
> 

感谢，不需要哈

**Comment by AllenZzzzkk** [comment]
> > 
> 
> 感谢，不需要哈
你好，我也遇到了这个问题，怎么解决呢？

**Comment by AllenZzzzkk** [comment]
> <img alt="图像" width="669" src="https://user-images.githubusercontent.com/29267921/254016917-b50a0f60-3024-4bad-bc46-975bd583bb80.png"> 三个文件上传成功，但是脑容量显示为0。 <img alt="图像" width="856" src="https://user-images.githubusercontent.com/29267921/254017088-f3579a59-ffc5-4a73-b94d-3245f7cd22f0.png"> 我还能上传新文件，但是我的大脑里已经无法显示它们了，也无法使用它们了。我应该怎么办？

我也遇到了这个问题，应该如何解决呢？
