### ISSUE TITLE
Deploying on Vercel ?

### ISSUE THREAD

**Issue by Sean19899999** [StanGirard/quivr#68]
Could you please show how to deploy this project on Vercel for better access, (such as how to set the needed openai_api_key\supabase_service_key\supabase_url, etc, tried to set them into the env.vars but got 404), thanks!

**Comment by syedddanishalinaqvi** [comment]
you have to change the file name .streamlit/secrets.toml.example to .streamlit/secrets.toml and in that you have to enter you details like:
supabase_url = "SUPABASE_URL"
supabase_service_key = "SUPABASE_SERVICE_KEY"
openai_api_key = "OPENAI_API_KEY"
anthropic_api_key = "ANTHROPIC_API_KEY" # Optional
