### ISSUE TITLE
[Issue]migration.sh execution fails

### ISSUE THREAD

**Issue by beifeng777** [StanGirard/quivr#684]
MacBook-Air quivr % chmod +x migration.sh
./migration.sh
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
Migration script completed.
hongrongji@hongrongjideMacBook-Air quivr % chmod +x migration.sh
./migration.sh
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
Last migration executed: 
Running migration 20230606131110_add_uuid_user_id.sql
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
Running migration 20230620170840_add_vectors_brains.sql
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
Running migration 20230620183620_use_supabase_user_id.sql
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
Running migration 20230627151100_update_match_vectors.sql
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
Running migration 20230629143400_add_file_sha1_brains_vectors.sql
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
Running migration 202307111517030_add_subscription_invitations_table.sql
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
Running migration 202307111517031_change_vectors_id_type.sql
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
Migration script completed.

**Comment by nicksan222** [comment]
Looks like something is wrong with the .env about supabase informations

**Comment by beifeng777** [comment]
<img width="1002" alt="image" src="https://github.com/StanGirard/quivr/assets/29267921/930644ec-0f34-4a22-baa6-803c10ff2990">
<img width="1002" alt="image" src="https://github.com/StanGirard/quivr/assets/29267921/f47c24ab-8b56-429a-80a7-f535dbef93c2">
Is there a problem with this evn configuration?

**Comment by XWN11** [comment]
Please enter the following database connection information that can be found in Supabase in Settings -> database:
    DB_HOST=$(gum input --placeholder "Host")
    DB_NAME=$(gum input --placeholder "Database name")
    DB_PORT=$(gum input --placeholder "Port")
    DB_USER=$(gum input --placeholder "User")
    DB_PASSWORD=$(gum input --placeholder "Password" --password)

Or， Write them in migration.sh or .migration_info is also acceptable.

**Comment by beifeng777** [comment]
> Please enter the following database connection information that can be found in Supabase in Settings -> database: DB_HOST=$(gum input --placeholder "Host") DB_NAME=$(gum input --placeholder "Database name") DB_PORT=$(gum input --placeholder "Port") DB_USER=$(gum input --placeholder "User") DB_PASSWORD=$(gum input --placeholder "Password" --password)请输入以下数据库连接信息，这些信息可以在 Supabase 的设置 -> 数据库中找到：DB_HOST=$（口香糖输入 --占位符“主机”）DB_NAME=$（口香糖输入 --占位符“数据库名称”）DB_PORT=$（口香糖输入 --占位符“端口”）DB_USER=$（口香糖输入 --占位符“用户”）DB_PASSWORD=$（口香糖输入 --占位符“密码” --密码）
> 
> Or， Write them in migration.sh or .migration_info is also acceptable.或者，用 migration.sh 或.migration_info写它们也是可以接受的。

hongrongji@hongrongjideMacBook-Air quivr % chmod +x migration.sh
./migration.sh
psql:scripts/tables.sql:8: NOTICE:  relation "users" already exists, skipping
CREATE TABLE
psql:scripts/tables.sql:17: NOTICE:  relation "chats" already exists, skipping
CREATE TABLE
psql:scripts/tables.sql:27: NOTICE:  relation "chat_history" already exists, skipping
CREATE TABLE
psql:scripts/tables.sql:30: NOTICE:  extension "vector" already exists, skipping
CREATE EXTENSION
psql:scripts/tables.sql:38: NOTICE:  relation "vectors" already exists, skipping
CREATE TABLE
CREATE FUNCTION
psql:scripts/tables.sql:79: NOTICE:  relation "stats" already exists, skipping
CREATE TABLE
psql:scripts/tables.sql:88: NOTICE:  relation "summaries" already exists, skipping
CREATE TABLE
CREATE FUNCTION
psql:scripts/tables.sql:127: NOTICE:  relation "api_keys" already exists, skipping
CREATE TABLE
psql:scripts/tables.sql:137: NOTICE:  relation "brains" already exists, skipping
CREATE TABLE
psql:scripts/tables.sql:148: NOTICE:  relation "brains_users" already exists, skipping
CREATE TABLE
psql:scripts/tables.sql:158: NOTICE:  relation "brains_vectors" already exists, skipping
CREATE TABLE
psql:scripts/tables.sql:167: NOTICE:  relation "brain_subscription_invitations" already exists, skipping
CREATE TABLE
psql:scripts/tables.sql:172: NOTICE:  relation "migrations" already exists, skipping
CREATE TABLE
INSERT 0 0
Migration script completed.
hongrongji@hongrongjideMacBook-Air quivr % chmod +x migration.sh
./migration.sh
Last migration executed: 202307111517030_add_subscription_invitations_table
Running migration 202307111517031_change_vectors_id_type.sql
BEGIN
CREATE TABLE
psql:scripts/202307111517031_change_vectors_id_type.sql:12: ERROR:  column "old_id" is of type bigint but expression is of type uuid
LINE 2: SELECT id, uuid_generate_v4() FROM vectors;
               ^
HINT:  You will need to rewrite or cast the expression.
psql:scripts/202307111517031_change_vectors_id_type.sql:20: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:26: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:29: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:30: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:33: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:34: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:40: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:45: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:48: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:49: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:51: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:52: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:55: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:56: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:59: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:88: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:scripts/202307111517031_change_vectors_id_type.sql:95: ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
ERROR:  column "id" of relation "migrations" does not exist
LINE 1: INSERT INTO migrations (id) VALUES ('202307111517031_change_...
                                ^
Migration script completed.
