### ISSUE TITLE
What is "Backend URL" in the quivr.app settings?

### ISSUE THREAD

**Issue by transcendr** [StanGirard/quivr#697]
I can't find any documentation anywhere. What is it? It seems to work without it. I filled in open ai key, supabase details but "backend URL" is blank and I can't find a single reference to it anywhere. Have I totally missed some sort of guide or documentation to configure quivr.app account?

**Comment by gozineb** [comment]
It's where your backend is running. It could be locally (with docker it's localhost:5050), but it could be different if you're just running your backend on a different machine ( AWS ECS, vitural environments, etc.)
Hope this helps !

**Comment by transcendr** [comment]
@gozineb  thanks, does that mean it is unrelated to and not required for use of quivr.app or do I still need to deploy an publicly accessible backend of quivr even if I'm using the quivr.app app? Or, is it optional?
