### ISSUE TITLE
[Issue] How to deploy just the API?

### ISSUE THREAD

**Issue by theDazzler** [StanGirard/quivr#700]
I would like to use the API in a project but it seems very unreliable as is. Is there a way to deploy just the API myself?

**Comment by Aleksandar1932** [comment]
Yes you can, just `docker-compose up backend-core`.

**Comment by theDazzler** [comment]
Thanks! But how do you authenticate to make API calls since it says you need to sign in to the frontend application to get an API key?

**Comment by adriens** [comment]
I'm looking fot a ay to get an API key for my online quivr instance but could not find how to get one :thought_balloon: 
So is it only available locally ?

**Comment by Aleksandar1932** [comment]
Yes, you can generate a jwt token from supabase, or use the router that is used by the frontend to login a user.

**Comment by theDazzler** [comment]
Yea I cant figure out how to get an API key to use for the API. I tried using the ones generated at https://www.quivr.app/config but I just get "Invalid token or api key." error. How are you supposed to use the API backend on its own?

**Comment by StanGirard** [comment]
https://brain.quivr.app
