### ISSUE TITLE
[Issue]Inter from Google Fonts pull Failed 

### ISSUE THREAD

**Issue by cyf-zzz** [StanGirard/quivr#704]
[+] Building 108.9s (25/28)
 => [frontend internal] load .dockerignore                                                                         0.0s
 => => transferring context: 61B                                                                                   0.0s
 => [frontend internal] load build definition from Dockerfile                                                      0.0s
 => => transferring dockerfile: 854B                                                                               0.0s
 => [backend-core internal] load .dockerignore                                                                     0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [backend-core internal] load build definition from Dockerfile                                                  0.0s
 => => transferring dockerfile: 578B                                                                               0.0s
 => [frontend internal] load metadata for docker.io/library/node:18-alpine                                         8.8s
 => [backend-core internal] load metadata for docker.io/library/python:3.11-bullseye                              11.6s
 => [frontend auth] library/node:pull token for registry-1.docker.io                                               0.0s
 => [backend-core auth] library/python:pull token for registry-1.docker.io                                         0.0s
 => [frontend internal] load build context                                                                         0.1s
 => => transferring context: 22.12kB                                                                               0.1s
 => [frontend  1/10] FROM docker.io/library/node:18-alpine@sha256:d5b2a7869a4016b1847986ea52098fa404421e44281bb76  0.0s
 => CACHED [frontend  2/10] RUN apk add --update --no-cache python3 make g++ && ln -sf python3 /usr/bin/python     0.0s
 => CACHED [frontend  3/10] RUN python3 -m ensurepip                                                               0.0s
 => CACHED [frontend  4/10] RUN pip3 install --no-cache --upgrade pip setuptools                                   0.0s
 => CACHED [frontend  5/10] RUN mkdir -p /app                                                                      0.0s
 => CACHED [frontend  6/10] WORKDIR /app                                                                           0.0s
 => CACHED [frontend  7/10] COPY package*.json yarn.lock ./                                                        0.0s
 => CACHED [frontend  8/10] RUN yarn install --network-timeout 1000000                                             0.0s
 => CACHED [frontend  9/10] COPY . .                                                                               0.0s
 => ERROR [frontend 10/10] RUN yarn build                                                                         99.1s
 => [backend-core internal] load build context                                                                     0.1s
 => => transferring context: 4.83kB                                                                                0.0s
 => [backend-core 1/8] FROM docker.io/library/python:3.11-bullseye@sha256:0723d0a5f1860a887c15f64d9768282b62f186a  0.0s
 => CACHED [backend-core 2/8] RUN apt-get update && apt-get install -y libgeos-dev pandoc                          0.0s
 => CACHED [backend-core 3/8] WORKDIR /code                                                                        0.0s
 => CACHED [backend-core 4/8] COPY ./core/requirements.txt /code/requirements.txt                                  0.0s
 => CANCELED [backend-core 5/8] RUN pip install --no-cache-dir -r /code/requirements.txt --timeout 100            97.1s
------
 > [frontend 10/10] RUN yarn build:
2.548 yarn run v1.22.19
2.710 $ next build
4.004 - info Loaded env from /app/.env
4.477 Attention: Next.js now collects completely anonymous telemetry regarding usage.
4.478 This information is used to shape Next.js' roadmap and prioritize features.
4.478 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
4.478 https://nextjs.org/telemetry
4.479
5.116 - info Creating an optimized production build...
22.89 FetchError: request to https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap failed, reason: connect ECONNREFUSED 127.0.0.1:443
22.89     at ClientRequest.<anonymous> (/app/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
22.89     at ClientRequest.emit (node:events:513:28)
22.89     at ClientRequest.emit (node:domain:489:12)
22.89     at TLSSocket.socketErrorListener (node:_http_client:502:9)
22.89     at TLSSocket.emit (node:events:513:28)
22.89     at TLSSocket.emit (node:domain:489:12)
22.89     at emitErrorNT (node:internal/streams/destroy:151:8)
22.89     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
22.89     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
22.89   type: 'system',
22.89   errno: 'ECONNREFUSED',
22.89   code: 'ECONNREFUSED'
22.89 }
98.10 Failed to compile.
98.10
98.10 app/layout.tsx
98.10 `next/font` error:
98.10 Failed to fetch `Inter` from Google Fonts.
98.10
98.10
98.11 > Build failed because of webpack errors
98.24 error Command failed with exit code 1.
98.24 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1

**Comment by AshishBarvaliya** [comment]
@cyf-zzz This problem isn't exclusively related to this repository.
[https://github.com/vercel/next.js/discussions/46012](https://github.com/vercel/next.js/discussions/46012)
[https://stackoverflow.com/questions/74889692/next-js-example-takes-a-long-time-to-compile-due-to-inter-google-fonts](https://stackoverflow.com/questions/74889692/next-js-example-takes-a-long-time-to-compile-due-to-inter-google-fonts)
