### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/root/bin/pandoc'

### ISSUE THREAD

**Issue by joelsprunger1** [StanGirard/quivr#712]
My machine setup:
- Ubuntu 22.04.2 LTS
- Docker version 20.10.24, build 297e128
- Docker compose version v2.17.2
- Your Supabase version 1.0.3 (from requirements.txt)
- reproduce this error README getting started

Error occurs when "Attaching backend-core, web" before opening the browser at all:
![image](https://github.com/StanGirard/quivr/assets/137963701/2e7736fa-73e6-4348-9093-2e3245627844)

I follow the same instruction on my Mac laptop and do not get this error. Any help is appreciated.

**Comment by joelsprunger1** [comment]
I installed Ubuntu 20.x an another partition and I am not getting the error.
![image](https://github.com/StanGirard/quivr/assets/137963701/17220065-928c-4695-a80a-31022b8ac7e1)
Does anyone know why?

**Comment by ioncandel** [comment]
I had the same issue. I made it work by removing Docker and installing without snap.

**Comment by joelsprunger1** [comment]
This is resolved
