### ISSUE TITLE
[Issue] Why are Anthropic models disabled?

### ISSUE THREAD

**Issue by Shekhars** [StanGirard/quivr#713]
I am trying to run the app locally with all the API keys set. Seems like chat and embeddings both happen via OpenAI. However, once embeddings is created, Anthropic (which seems be supported)  can be used for chat. 
On looking into the code, looks like the Anthropic Models are commented out. Also, the settings page of the app doesn't allow choosing Anthropic models. 
Was there a reason to disable them?

Thanks for making this fantastic app.

**Comment by StanGirard** [comment]
You can un comment and add them again :) 

It was a dirty way to allow people to only use openai on the demo 😂

**Comment by rowbot1** [comment]
Can you provide a guide on how to add the lama 2 model instead of openai, as i want to keep my second brain completely offline. Thank you

**Comment by Shekhars** [comment]
@StanGirard Actually I tried that. Looks like the underlying calls to Anthropic are not implemented either. Am I wrong about that? Is that in the pipeline anytime soon?
