### ISSUE TITLE
When are we able to host local model instead of api

### ISSUE THREAD

**Issue by dality17** [StanGirard/quivr#716]
Every almost every project. Require api 
And this project has its promises that it wil be able to host local model without the need of api. But we have been waiting for months to have this happend.

**Comment by StanGirard** [comment]
The project is two month old ;) 

Also https://brain.quivr.app/docs/backend/llm/private-llm ;)

**Comment by dality17** [comment]
Thank you for your reply StanGirard. The problem is even if i try to to load the backend .env of local model.  First it wil be hanging for like 5 minutes. When i try to chat with local model. Then after that it gives me error of incorrect openai key so what should i do?
