### ISSUE TITLE
[Issue] Authentication URL unaffected by NEXT_PUBLIC_BACKEND_URL

### ISSUE THREAD

**Issue by IamUSER** [StanGirard/quivr#723]
Problem:
"NEXT_PUBLIC_BACKEND_URL" has no impact on the redirect URL's which still reference localhost:3000 in the tokenized authentication confirmation emails.

Services Impacted:
Affects google sign up and magic link.

Solution:
Replacing the inaccurate host (localhost) with the backend IP address int he URL corrects this issue and allows authentication tokens to pass thus allowing access.

**Comment by StanGirard** [comment]
You need to update in your supabase account for the redirect url
