### ISSUE TITLE
[Brain management] 1-AAUser, when I click on the temporary 'B' icon, i am redirect to a brainsmanagement page with my list of brains

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#724]
# Epic

#531 

# Functional

### Tech

- [ ] Create a BrainsManagementPage with 2 components: BrainsListBar + BrainManagement (same layout as chatpage)
      - [ ] BrainsListBar : on the left, in one column : BrainsList (sort by brain name) + AddBrain + SearchForBrain (Same page ratio as chat)
       - [ ] BrainManagement : console log brain Id for now

- [ ] Create a Temporary button in the navbar, on click, redirect to BrainsManagementPage

### Tests

- [ ] it ...

### Validation Checks

- [ ] it ...

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/752
