### ISSUE TITLE
failed to solve: process "/bin/sh -c apk add --update --no-cache python3 make g++ && ln -sf python3 /usr/bin/python" did not complete successfully: exit code: 3

### ISSUE THREAD

**Issue by ZvanYang** [StanGirard/quivr#727]
# The why

=> ERROR [frontend  2/10] RUN apk add --update --no-cache python3 make g++ && ln -sf python3 /usr/bin/python                       78.4s
 => [backend-core 1/8] FROM docker.io/library/python:3.11-bullseye@sha256:0723d0a5f1860a887c15f64d9768282b62f186af532f0c95babd756fd  0.0s
 => [backend-core internal] load build context                                                                                       0.0s
 => => transferring context: 184.25kB                                                                                                0.0s
 => CACHED [backend-core 2/8] RUN apt-get update && apt-get install -y libgeos-dev pandoc                                            0.0s
 => CACHED [backend-core 3/8] WORKDIR /code                                                                                          0.0s
 => CACHED [backend-core 4/8] COPY ./requirements.txt /code/requirements.txt                                                         0.0s
 => CANCELED [backend-core 5/8] RUN pip install --no-cache-dir -r /code/requirements.txt --timeout 100                              77.2s
------
 > [frontend  2/10] RUN apk add --update --no-cache python3 make g++ && ln -sf python3 /usr/bin/python:
0.820 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
75.89 487BB3550D7F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:303:
75.89 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/main: Permission denied
75.89 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
78.17 ERROR: unable to select packages:
78.17   g++ (no such package):
78.17     required by: world[g++]
78.17   make (no such package):
78.17     required by: world[make]
78.17   python3 (no such package):
78.17     required by: world[python3]
------
failed to solve: process "/bin/sh -c apk add --update --no-cache python3 make g++ && ln -sf python3 /usr/bin/python" did not complete successfully: exit code: 3

**Comment by xys123** [comment]
看到和我一样问题的了，一看还是个京爷，那么就是国内网络环境的问题了，直接vpn全局美国，解决。
芜湖MAGA
