### ISSUE TITLE
start.sh: line 22: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by georgeqin96** [StanGirard/quivr#736]
windows 10 docker desktop, quivr-0.0.39
/code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file

**Comment by georgeqin96** [comment]
delete CR

**Comment by akkiverma** [comment]
facing same issue on Windows 11, what was the solution?
