### ISSUE TITLE
:grey_question: Documentation to get API key (online version) :memo: 

### ISSUE THREAD

**Issue by adriens** [StanGirard/quivr#740]
# :grey_question: About

I would like to integrate & prototype an idea around quivr online.  There is an awesome API that matches my needs, but I was not able to find where to manage my API keys.

# :pray: Action

Can you please provide a quick guid which explains _"How to get your Quivr API key for dummies"_.

It would follow the steps:

1. Create your account online
2. Create a first brain "Dummy"
3. Task 1
4. Task 2
5. Now you get your API
6. `http` request that list brains

Thank you in advance for your help.

**Comment by gozineb** [comment]
Hello @adriens, thanks for your interest in Quivr ! 
So currently, you can generate your Quivr API Key in the bottom of the 'settings' page. However, this is going to change in the next few days. It will be moved to the user's page. 
We will add a quick guide then, now that you have pointed it out ! Thanks

**Comment by adriens** [comment]
ARGHH 'got it :laughing: 
![image](https://github.com/StanGirard/quivr/assets/5235127/43ec0312-4e37-484a-95c5-1e339255d603)


I was not looking at this place :sweat_smile: 

>  It will be moved to the user's page.

It will be much much easier :+1: 

> We will add a quick guide then, now that you have pointed it out ! Thanks

Not sure it will be necessary as it usually the place where we're looking for it :+1: 

Thanks a lot for qui anwser :pray: :star_struck:
