### ISSUE TITLE
[Brain management] 10 - AAUser, I can add my own API Key in the User page

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#749]
# Epic

Include the issue that represents the epic.

# Functional

Please explain in detail the functionality.
Please also include relevant motivation and context.

### Tech

- [x] Add API key config in User Page
- [x] Add User table
- [x] Show a warning to say that api keys are saved in db and no encrypted
- [ ] If brain API Key, use brain's. Else, if user's, use user's. Else use quivr's.
- [x] Move the Quivr API key config to user's page
- [x] Add a quick guide to Quivr's API key generation -> see issue ❔ Documentation to get API key (online version) 📝  #740

### Tests

- [] it ...

### Validation Checks

- [] it ...

**Comment by Chloeroumengas** [comment]
AAUser, When I am on the user page and I add my own API key I should : 

- [ ] Be notified if the API key is wrong : red popup "Wrong API key, try again"

- [ ] Be notified if the key if the Key is saved : green popup "API Key saved"

AAUser, When I am on the user page and I already add my own API key, when I come back on the user page I should : 

- [ ] See the saved API key written above the text field and a placeholder in the text field saying "Enter a new Open AI key" : 

![Image](https://github.com/StanGirard/quivr/assets/138109838/a51d78cd-285c-4dea-82f5-9679e7202e85)
