### ISSUE TITLE
[Issue] Can't run SQL scripts in Supabase while installing Quivr for first time

### ISSUE THREAD

**Issue by moayadeldin** [StanGirard/quivr#757]
Hello,

I am trying to follow the readme file instructions in order to install Quivr on my local machine for the first time but I am stuck at step 4.

How may I run the following code in SQL given it is a shell command? 
```
chmod +x migration.sh
./migration.sh
```

I tried to run it in Supabase SQL snippet and of course it gave me invalid SQL query and I tried to run it in my terminal and it keeps saying command not found for each .sql file in the migrations.sh.

then the rest of the guidelines in Step 4 mentions choosing create_scripts if it is my first time and i can't find any files named as such

I opened the video tutorial and the scripts used in it are removed and not found in this repo, the author says that the tutorial is a little bit outdated and the readme is to be followed but It doesn't seem obvious for me.

Is there something I am getting wrong here? How can I perform step 4 properly and run the SQL queries in Supabase?

**Comment by flake9** [comment]
+1

**Comment by jchapmanCR** [comment]
You need to copy what is in scripts/tables.sql and paste it into the SQL query window in Supabase. Execute that query and you'll have the latest table schemas (no need for migrations).

**Comment by maxsvetlik** [comment]
The README is underspecified for this step. You can simply run
```
chmod +x migration.sh
./migration.sh
```
It will ask you for your database `host` `name` `port` and `password`. These can be found in Supabase via `Project Settings > Database`
_then_ it will give you the option of creating new tables (if this is your first time, this is the option you should choose) or migrating an existing database.

The script will use your credentials to create the database schemas for you.

**Comment by usmbok** [comment]
Far from stale - I have same issue - and its the script we need…
