### ISSUE TITLE
[wasn't able to use my pdf file in chat as context]

### ISSUE THREAD

**Issue by jignnsd** [StanGirard/quivr#758]
I'm running locally in a Rocky linux computer
git version 0.0.40

The file is uploded and chunked in the database, but when I chat with it, it is not used as context.
Application error: a client-side exception has occurred (see the browser console for more information).
When I try to view the file in the explore section, it says: 0 cApplication error: a client-side exception has occurred (see the browser console for more information).hunks, then crashes and says in the browser:
Application error: a client-side exception has occurred (see the browser console for more information).

in the console i got:

backend-core  | INFO:     192.22.60.22:65268 - "GET /explore/?brain_id=7b40e2b9-1b76-4da5-8786-455945a26a8c HTTP/1.1" 200 OK
backend-core  | INFO:     192.22.60.22:65268 - "OPTIONS /explore/?brain_id=d1e8a59d-5969-4845-b31a-f86348be9e96 HTTP/1.1" 200 OK
backend-core  | document [{'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}]
backend-core  | INFO:     192.22.60.22:65268 - "GET /explore/?brain_id=d1e8a59d-5969-4845-b31a-f86348be9e96 HTTP/1.1" 200 OK
backend-core  | INFO:     192.22.60.22:65268 - "OPTIONS /explore/PODER%20VARA.pdf/ HTTP/1.1" 200 OK
backend-core  | INFO:     192.22.60.22:65268 - "GET /explore/PODER%20VARA.pdf/ HTTP/1.1" 200 OK
web           | Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
web           | Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
backend-core  | INFO:     192.22.60.22:65268 - "OPTIONS /brains/ HTTP/1.1" 200 OK
backend-core  | INFO:     192.22.60.22:65268 - "GET /brains/ HTTP/1.1" 200 OK
backend-core  | document [{'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PApplication error: a client-side exception has occurred (see the browser console for more information).ODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}, {'name': 'PODER VARA.pdf', 'size': '0'}]
backend-core  | INFO:     192.22.60.22:65274 - "GET /explore/?brain_id=d1e8a59d-5969-4845-b31a-f86348be9e96 HTTP/1.1" 200 OK
![photo_5618635230210533340_y](https://github.com/StanGirard/quivr/assets/90939257/886ef7ca-fd4a-407c-9b12-47d55ecd6896)

here is the vector in supabase.

https://github.com/StanGirard/quivr/assets/90939257/e8e4d8b8-e579-4cee-8437-337f71a7137f

many thanks for your effort.
Please let me know if you need more info
Javier

**Comment by jignnsd** [comment]
I just figure it out that if I add the sentence: "according to the context provided" and then it will use the context of the files, so never mind about the problem of the context. In the other hand, the problem of the explore, clicking in view of any file, will show 0 chunks and then fail, just as in the video that I upload. Don't know why. I just reload the page and I'm in again, but if I try to click in view of any file again, same thing. Many thanks.

**Comment by AllenZzzzkk** [comment]
I also encountered this problem, did you solve it?

**Comment by jignnsd** [comment]
I update to new latest version and the issue was solved.
