### ISSUE TITLE
Backoff in case of OpenAI Rate Limit

### ISSUE THREAD

**Issue by PhillipRt** [StanGirard/quivr#759]
New API accounts will have a RPM limit of 60:
![image](https://github.com/StanGirard/quivr/assets/65727386/981546a2-ab02-4d50-b503-d0547d628c4f)

The backend backs of for 4 seconds in case of Ratelimit:
error_code=rate_limit_exceeded error_message='Rate limit reached for default-text-embedding-ada-002 in organization org-xxx on requests per min. Limit: 60 / min. Please try again in 1s. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=requests message='OpenAI API error received' stream_error=False
backend-core  | 2023-07-25 10:49:35,934:WARNING - Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-F2zbJA2YWd1h0wfBr0sPICQI on requests per min. Limit: 60 / min. Please try again in 1s. Contact us through our help center at help.openai.com if you continue to have issues..

The retry will be sucsessfull, but the next chunk will run into a Ratelimit again immediatly.
I think there shoud be a logic of waiting 1 second between each request as soon as the backend hits a ratelimit once per document.

**Comment by PhillipRt** [comment]
In addition, if exceed your daily limit, there you get an error toast (as it should be), but the document is still added to the brain, probably with incomplete or non exisig embeddings. There should be a way to validate and recreate your embeddings for a file or just reject the file compleatly

**Comment by funkytaco** [comment]
Here is the User experience for this. 
<img width="1505" alt="Screenshot 2023-08-02 at 7 42 24 AM" src="https://github.com/StanGirard/quivr/assets/1712205/f0370de9-1e8f-466c-ac9c-4b1903dc50cf">
<img width="935" alt="Screenshot 2023-08-02 at 7 45 22 AM" src="https://github.com/StanGirard/quivr/assets/1712205/51479c70-2ec3-4799-89b8-3cde8a283282">

Additionally, when this happens:

- it seems to prevent other data from being passed. 
- it just says "Thinking"
- The error uploading PDF doesn't display this is an API Rate Limit Error. That is relevant information that the user needs (it was found in logs, not UI).
- Also, the brain cannot be selected while this is happening, so it's a show stopper.

Error creating vector for document Rate limit reached for default-text-embedding-ada-002 in organization org-xyz on requests per day. Limit: 200 / day. Please try again in 7m12s. Contact us through our help center at [help.openai.com](http://help.openai.com/) if you continue to have issues.
