### ISSUE TITLE
AAUser, When I click on the explore button and I want to « view » the file, I should see the document informations and not a bug

### ISSUE THREAD

**Issue by Chloeroumengas** [StanGirard/quivr#763]

**Comment by Chloeroumengas** [comment]
![Image](https://github.com/StanGirard/quivr/assets/138109838/9804012f-e06e-4723-92e4-ca76ce176d46)

**Comment by zesty-v** [comment]
Getting the same. Here is some more information from the console output:

Failed to load resource: the server responded with a status of 404 (Not Found)
api.june.so/sdk/identify:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/page:1     Failed to load resource: the server responded with a status of 401 ()
page-378d0a9a95a755c3.js:1 Fetching user stats from http://localhost:5050/user
api.june.so/sdk/identify:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/page:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/identify:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/page:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/identify:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/track:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/identify:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/track:1     Failed to load resource: the server responded with a status of 401 ()
page-378d0a9a95a755c3.js:1 Fetching user stats from http://localhost:5050/user
api.june.so/sdk/identify:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/page:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/identify:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/page:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/identify:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/page:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/identify:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/page:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/identify:1     Failed to load resource: the server responded with a status of 401 ()
api.june.so/sdk/page:1     Failed to load resource: the server responded with a status of 401 ()
page-5d220a03e5043306.js:1 Bacterial wilt Fact Sheet (2015).pdf 30 true Bacterial wilt Fact Sheet (201...
page-5d220a03e5043306.js:1 The Host Plant and Virus Vector Table (2017).pdf 30 true The Host Plant and Virus Vecto...
..
..
..
page-5d220a03e5043306.js:1 Fusarium Diseases Fact Sheet (2018).pdf 30 true Fusarium Diseases Fact Sheet (...
8139-6ab047564f05645a.js:1 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bbrain_id%2C%20vector_id%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nz (2443530c-e48cfb8d95f71afb.js:9:29502)
    at d (2443530c-e48cfb8d95f71afb.js:9:31435)
    at 2443530c-e48cfb8d95f71afb.js:9:33835
    at s (2443530c-e48cfb8d95f71afb.js:9:34126)
    at u (2443530c-e48cfb8d95f71afb.js:9:35215)
    at ls (2443530c-e48cfb8d95f71afb.js:9:52229)
    at iv (2443530c-e48cfb8d95f71afb.js:9:115626)
    at oR (2443530c-e48cfb8d95f71afb.js:9:90032)
    at 2443530c-e48cfb8d95f71afb.js:9:89881
    at oD (2443530c-e48cfb8d95f71afb.js:9:89888)
window.console.error @ 8139-6ab047564f05645a.js:1
