### ISSUE TITLE
[Crawl] Allow users to crawl an entire website

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#77]
Have a recursive crawling over a website, pulls every other website linked in the website

**Comment by StanGirard** [comment]
The endpoint and options already exist in the backend but it doesn't have the code behind :D

**Comment by StanGirard** [comment]
#108 adds an input in the frontend for an URL. There should be a setting to add JS rendering and crawling website

**Comment by shashank-crypto** [comment]
@Ruben1701 @StanGirard  Do you mind if I take over?

**Comment by StanGirard** [comment]
No go ahead @shashank-crypto

**Comment by Ruben1701** [comment]
@shashank-crypto if you check the pull requests there is a working version just with a bug I cant seem to figure out!

**Comment by Ruben1701** [comment]
@shashank-crypto yep if you check the console you will see it returns all the different urls it scrapes but the file only contains the original url content. Kinda caught up in my graduation right now so haven't had a chance to look at it yet.

**Comment by shashank-crypto** [comment]
Sure @Ruben1701, I will try to work with your PR.

**Comment by shashank-crypto** [comment]
Which server ? @Ruben1701

**Comment by Ruben1701** [comment]
> Which server ? @Ruben1701

https://discord.gg/VTgSYEg7

@shashank-crypto

**Comment by shashank-crypto** [comment]
@StanGirard I have raised a PR https://github.com/StanGirard/quivr/pull/247 for this. I have tested in my local. It's uploading the page contents. Functionality is working. I have tested with langchanin, aws and beautifulsoup documentation pages. There are few edge cases of collecting links and adding to paths. I have covered the most common cases for now.

**Comment by bdalalhaljwysm** [comment]
let appName = "Swifty Compiler"
let str = "Hello, \(amira)"
print(str)

**Comment by bdalalhaljwysm** [comment]
New Features

For example, specifying a filter predicate as a parameter to the @Query attribute will now require explicitly providing the model type used in the predicate, i.e. #Predicate<ModelType> { … } instead of #Predicate { … }:
