### ISSUE TITLE
Error in /*backend/core/auth/auth_bearer.py

### ISSUE THREAD

**Issue by ioncandel** [StanGirard/quivr#783]
Hi all,

I am getting the following error :

backend-core  | INFO:     172.18.0.1:44164 - "GET /brains/default/ HTTP/1.1" 500 Internal Server Error
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core  |     await self.app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core  |     raise e
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 227, in app
backend-core  |     solved_result = await solve_dependencies(
backend-core  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 622, in solve_dependencies
backend-core  |     solved = await call(**sub_values)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/auth/auth_bearer.py", line 24, in __call__
backend-core  |     return await self.authenticate(
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/auth/auth_bearer.py", line 41, in authenticate
backend-core  |     return self.get_test_user()
backend-core  |            ^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/auth/auth_bearer.py", line 54, in get_test_user
backend-core  |     return User(
backend-core  |            ^^^^^
backend-core  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-core  | pydantic.error_wrappers.ValidationError: 1 validation error for User
backend-core  | id
backend-core  |   value is not a valid uuid (type=type_error.uuid)

So after digging some more I localized the source in the backend/core/auth/auth_bearer.py file line 41:

  return self.get_test_user()

then the line 54:

def get_test_user(self) -> User:
        return User(
            email="test@example.com", id="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"  # type: ignore
        )  # replace with test user information 

How come this function is called when I try to connect on local????

**Comment by StanGirard** [comment]
Because you have the full webapp. Therefore you need to authenticate on your instance too. 

There is no difference in terms of code between what you have and what there is on quivr.app

**Comment by ioncandel** [comment]
> Because you have the full webapp. Therefore you need to authenticate on your instance too.
> 
> There is no difference in terms of code between what you have and what there is on quivr.app

Thank you for your reply Stan.

The error appears when I try to authenticate. Is there another user name that needs to be used on local?
