### ISSUE TITLE
Gpt4All Standard Installation

### ISSUE THREAD

**Issue by codingbutstillalive** [StanGirard/quivr#792]
I used the MacOS installer from https://gpt4all.io/index.html to install Gpt4All. But Quivr does not recognize it is installed.

**Comment by StanGirard** [comment]
https://brain.quivr.app 

You did not follow procedure ;)

**Comment by codingbutstillalive** [comment]
Thanks :)

So will I need to download models twice, or will it work with symlinks as
well?

Stan Girard ***@***.***> schrieb am Sa. 29. Juli 2023 um
11:10:
