### ISSUE TITLE
:art: Better descriptions for brains :brain: 

### ISSUE THREAD

**Issue by adriens** [StanGirard/quivr#794]
# :grey_question: About

Brains are a great way to organize knwoledge topics.... for now, they only have a title/name, the aim of thi featur request is ta add some data to better describe the brain.

To achieve this, would it possible to add:

- [ ] A thumbnail covert art (landscape,..)
- [ ] A markdown compatible description that explains what the brain is capable of

# :moneybag: Expected gains

Below the first biggest expected gains:

- :heavy_check_mark: Better UX while browsing and swthcing between brains (thanks to the cover art)
- :heavy_check_mark: Making it **possible to `LLM` agents to choose the right brain while asking them the question** : it would be possible to create a Quivr tool on top of all brains, thanks to the description

**Comment by adriens** [comment]
Hi, any chance to get this feature request implemented ?

**Comment by StanGirard** [comment]
@gozineb

**Comment by adriens** [comment]
🙏 🤞
