### ISSUE TITLE
[Make possible to select multiple Brains, in order to chat with all of the selected brains at the same time]

### ISSUE THREAD

**Issue by jignnsd** [StanGirard/quivr#795]
## Submitting a Feature Request 💡

There are some times that you may want to chat with multiple brains at the same time.

**Example:**

Be able to select multiple brains to chat with the information of all of them at the same time.

DESCRIPTION. Now you are just able to select one Brain to chat with, if you need to interact with the information of two or more brains at the same time, you either have to make the same interaction with each brain or have a new brain with the cumulative information of many brains, and interact with it. With this will have identical files processed, pay for the embeddings, and incurring in extra expenses that make no sense, is already done for each brain.

RATIONALE. Examples of use are many, here are some that came in the top of my mind. 1) Let's say that you are a school director and have information of each group of your school, all grades and all groups, as an example, 1st grade (a, b and c groups), for second grade (a, b and c groups), 3rd grade the same and so on. You divide each group and have a brain for each one, so you can interact with the documents of each specific group, so you will have 1A brain, 1B brain, 1C brain, 2A Brain, 2B brain and so on. This can be done with the implementation as is now, but if you want to interact with the documents of all first grade? Or interact with the documents of the whole school? You can't the way is now, now you will have 2 options, interact with each brain alone, but you will miss the interaction between the documents altogether and will have just pieces of information. You can also make another brain for all 1st grade and again add information of 1A, 1B and 1C, so you can interact at the same time and between them. Makes no sense because you already have the information chunked, vectorized and processed. You will be making more expenses.

All this could be replicated in other scenarios like information of different branches, each in different brains. 

Other example is a law firm, that has documents from case1 in brain1, case2 in brain2, and so on. Bot maybe they have to do some cross reference between 2 or more cases. Let's say that they want to seek for similitudes in cases from the same associate, so the will have to interact at the same time with the cases that he/she was involved. Or interact at the same time with cases of the same client, etc...

The example list can go on and on, but I'm sure the point is clear that are many cases that you will wan to interact at the same time with information of many brains.

IMPLEMENTATION. I think this could be done pretty easily just adding the option that instead of single select you can have multiple selection of brains. (The inside of the scripts maybe more work)

Many thanks for all your effort on this project, I'm really enjoying it!
Javier

**Comment by jignnsd** [comment]
Hey Stan, contributors. What do you think about this idea? 
Is this possible?
Many thanks for lo your effort.

**Comment by carterrees-entrata** [comment]
Also interested in @jignnsd's idea. We have data documentation, user instructions/faqs and data tables that we would like a single LLM to be able to interact with when deemed appropriate. Similar to the idea that an LLM can select the correct table from multiple db tables to answer specific data questions.
