### ISSUE TITLE
[ISSUE] ReferenceError: sessionStorage is not defined web

### ISSUE THREAD

**Issue by agentgill** [StanGirard/quivr#799]
Any saving within the UI, throws the following in the console/terminal view - ReferenceError: sessionStorage is not defined web

Setup
- Mac OS, Apple Silicon 13.5 (22G74)
- Docker 4.21.1 (114176) & Docker Compose: v2.19.1
- Your Supabase version and setup - Not sure how to get version, setup followed video
- Followed the readme for setup
- Used the tables.sql script to create backend tables

Any saving within the UI, throws the following in the console/terminal view

```bash
backend-core  | 2023-07-29 14:44:24,930 [INFO] llm.openai_functions: Getting model response
backend-core  | INFO:     172.22.0.1:58686 - "POST /chat/3479e975-4709-4ada-9915-665fd483fe79/question?brain_id=456959e7-c9f8-4c86-ac34-d8fadd48cb15 HTTP/1.1" 200 OK
web           | ReferenceError: sessionStorage is not defined
web           |     at redirectToLogin (/app/.next/server/app/upload/page.js:1104:5)
web           |     at Layout (/app/.next/server/chunks/142.js:1026:51)
web           |     at Je (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
```

**Comment by StanGirard** [comment]
@mamadoudicko

**Comment by mrshehzad1** [comment]
same issues on windows 11.

**Comment by Dadadahhhhh** [comment]
I am also getting a similar error using the version that said supported the local LLM models (v 0.0.46)

running on a Debian virtual box

`error lib/router/redirectToLogin.ts (7:2) @ sessionStorage
web           | - error ReferenceError: sessionStorage is not defined
web           |     at redirectToLogin (./lib/router/redirectToLogin.ts:9:5)
web           |     at UploadPage (./app/upload/page.tsx:35:85)
web           |    5 | 
web           |    6 | export const redirectToLogin: RedirectToLogin = (type?: RedirectType) => {
web           | >  7 |   sessionStorage.setItem("previous-page", window.location.pathname);
web           |      |  ^
web           |    8 | 
web           |    9 |   redirect("/login", type);
web           |   10 | };`
