### ISSUE TITLE
[Issue] Something is wrong with the Step 4

### ISSUE THREAD

**Issue by zandekan** [StanGirard/quivr#803]
The migration.sh script doesnt works when I run it on Supabase. So closest thing that I found to it was the [tables.sql](https://github.com/StanGirard/quivr/blob/main/scripts/tables.sql) which worked but when I try to run the app it gives me these errors:
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file

Read Me file says:

Step 4: Run the following migration scripts on the Supabase database via the web interface (SQL Editor -> New query)

Use the migration.sh script to run the migration scripts

chmod +x migration.sh
./migration.sh
Choose either create_scripts if it's your first time or migrations if you are updating your database.

All the scripts can be found in the [scripts](https://github.com/StanGirard/quivr/blob/main/scripts) folder

If you come from an old version of Quivr, run the scripts in [migration script](https://github.com/StanGirard/quivr/blob/main/scripts) to migrate your data to the new version in the order of date

**Comment by rustyrayzor** [comment]
same for me

**Comment by tan1193** [comment]
try to convert the line endings of the start.sh script from Windows-style to Unix-style. You can use the dos2unix command as explained in the previous response.

**Comment by rustyrayzor** [comment]
> try to convert the line endings of the start.sh script from Windows-style to Unix-style. You can use the dos2unix command as explained in the previous response.

Thanks, just figured it out :)

**Comment by rustyrayzor** [comment]
correction, it ran but all i got was  
Please enter the following database connection information that can be found in Supabase in Settings -> database:
./migration.sh: line 26: gum: command not found
./migration.sh: line 27: gum: command not found
./migration.sh: line 28: gum: command not found
./migration.sh: line 29: gum: command not found
./migration.sh: line 30: gum: command not found
./migration.sh: line 41: gum: command not found
./migration.sh: line 49: psql: command not found
Last migration executed:
Running migration 20230606131110_add_uuid_user_id.sql
./migration.sh: line 6: psql: command not found
./migration.sh: line 62: psql: command not found
Running migration 20230620170840_add_vectors_brains.sql
./migration.sh: line 6: psql: command not found
./migration.sh: line 62: psql: command not found
Running migration 20230620183620_use_supabase_user_id.sql
./migration.sh: line 6: psql: command not found
./migration.sh: line 62: psql: command not found
Running migration 20230627151100_update_match_vectors.sql
./migration.sh: line 6: psql: command not found
./migration.sh: line 62: psql: command not found
Running migration 20230629143400_add_file_sha1_brains_vectors.sql
./migration.sh: line 6: psql: command not found
./migration.sh: line 62: psql: command not found
Running migration 202307111517030_add_subscription_invitations_table.sql
./migration.sh: line 6: psql: command not found
./migration.sh: line 62: psql: command not found
Running migration 202307111517031_change_vectors_id_type.sql
./migration.sh: line 6: psql: command not found
./migration.sh: line 62: psql: command not found
Running migration 20230717164900_add_get_user_email_by_user_id.sql
./migration.sh: line 6: psql: command not found
./migration.sh: line 62: psql: command not found
Running migration 20230717173000_add_get_user_id_by_user_email.sql
./migration.sh: line 6: psql: command not found
./migration.sh: line 62: psql: command not found
Running migration 202307241530031_add_fields_to_brain.sql
./migration.sh: line 6: psql: command not found
./migration.sh: line 62: psql: command not found
Migration script completed.

**Comment by incube8lab** [comment]
I also got the same as above as I dont have psql or gum installed. I tried to run the scripts manually in the SupaBase query editor. tables.sql and few others run successfully while most fail.

For instance when i run _**20230620170840_add_vectors_brains**_, i get 

`Failed to run sql query: column v.user_id does not exist`

**Comment by kegsss** [comment]
Hey @incube8lab, did you ever figure out that `Failed to run sql query: column v.user_id does not exist` error? I'm running into the same thing.
