### ISSUE TITLE
Interact with your voice

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#81]

**Comment by StanGirard** [comment]
Ask your brain questions with your voice

**Comment by codingbutstillalive** [comment]
Whisper Integration would be great. Especially with a local runtime.

**Comment by StanGirard** [comment]
Whisper works with Quivr 😏 have you tried uploading an audio file ?

**Comment by codingbutstillalive** [comment]
Not yet. Currently there are so many projects that I was keep reading here
to get a feeling of who is behind this project.

I like what I see and maybe I will even be able to support this project.

Thanks for your answers!

Stan Girard ***@***.***> schrieb am Sa. 27. Mai 2023 um 17:10:
