### ISSUE TITLE
Specify chunk size and increase context window[Issue]

### ISSUE THREAD

**Issue by 3koozy** [StanGirard/quivr#829]
Hello everyone, and thank you for this amazing tool :D
after minimal testing, I uploaded a document with a big table of contents and when I asked the AI to list down the ToC ,
it only listed almost half the table and stopped, ending with: "Please note that this is a partial table of contents. The complete table of contents may include additional sections." even after increasing the context window to the max (500).

I am assuming that its because either the context window is too small or that the chunk size is too small in the vector store.
adding the ability to freely adjust any of them seems like a handful option :)

Thanks, Aziz.

**Comment by jignnsd** [comment]
This looks like a great idea
