### ISSUE TITLE
[Epic]: User story UNKNOWN OPEN AI API KEY

### ISSUE THREAD

**Issue by razeta** [StanGirard/quivr#830]
Hello, this is the fifth time trying to install and run this on my windows 10 pc.

I manage to install everything, but when reaching the brain creation, I always get an error. 
![image](https://github.com/StanGirard/quivr/assets/849572/81efc9a9-8aef-4c42-a7b2-84b6ccb1d172)

I have this key alway showing up, No idea where it came from and is not my open ai api key. 
![image](https://github.com/StanGirard/quivr/assets/849572/87f97a27-9bd9-4441-837f-e29776a97edf)
![image](https://github.com/StanGirard/quivr/assets/849572/01f3c53a-5540-4e18-beaa-d8ee397ecec5)

My question is, where does that key come from? I am certain that the correct key is on the .env file.
Even if I change the key in that textbox and save it. It still using the Gsmfo key...

**Comment by mamadoudicko** [comment]
@Chloeroumengas

**Comment by WaylonTian** [comment]
Same issue too

**Comment by sunupup** [comment]
me too
