### ISSUE TITLE
[Issue] model stuck on smaller model gpt-3.5-turbo-0613

### ISSUE THREAD

**Issue by joelsprunger1** [StanGirard/quivr#832]
I can't change the model in any of my brains on quivr.app. I see some have settings from a few days ago for various models. However, I went to change the model in one of my brains. I get the "brain updated successfully" message and then if I reload the page the model goes back to gpt-3.5-turbo-0613.

This matches what I see locally. I follow these steps:

1. fresh clone of repo
2. setup new project in supabase (so there's nothing to migrate)
3. run the install_helper.sh, which with prompts, now does everything.

After registering a user and verifying in the email. I am seeing similar behavior.

I can add brains, but they don't hold my api key or model selection on page refresh. If I edit the supabase brains table manually from supabase with the correct settings the settings show up correctly in the quivr frontend on page refresh. However, when I start a new chat and ask the same question of the document I am working with, I am getting a much less detailed answer than I was a week or 2 ago.

I suspect it is still using the gpt-3.5-turbo-0613 model even though the brain settings show otherwise.

**Comment by joelsprunger1** [comment]
Looking at the backend-core log from my local install it shows the streaming request for gpt-3.5-turbo-0613
![image](https://github.com/StanGirard/quivr/assets/137963701/b8c65750-b664-4104-95d7-1f731458fec0)
It also references the default brain, which I manually set in supabase to be gpt-4
![image](https://github.com/StanGirard/quivr/assets/137963701/d5d7c095-f5f8-4f1d-91c7-891df67f31cb)

**Comment by devturp** [comment]
I'm noticing the exact same issue.  @StanGirard, do you know when this will be addressed?

**Comment by joelsprunger** [comment]
This was resolved by PR 902

**Comment by raisindetre** [comment]
I installed from HEAD yesterday and just pulled (#2e4fdc8) on OSX 13.5 using Docker and still get this issue. Only GPT-3.5-Turbo is appearing as a model option. I have tried regenerating keys in OpenAI and manually setting "gpt-4" in the "brains" table in Supabase but it immediately resets in the selector to 3.5.

**Comment by raisindetre** [comment]
For the benefit of anyone else reading, I was able to resolve this by directly editing the JSON data in the "models" field of the "user_settings" table fo the Quivr database from Supabase. To add GPT-4 the contents of the field should be:
`[
  "gpt-3.5-turbo",
  "gpt-4"
]`

May need a restart of the backend too.
