### ISSUE TITLE
Please change the order of the table creation because of the table prompts (reference error)

### ISSUE THREAD

**Issue by hklein42** [StanGirard/quivr#836]
Please change the order of table creation in tables.sql script because of the table prompts (reference error when creating tables in Supabase): 
...

--- Create prompts table
CREATE TABLE IF NOT EXISTS prompts (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title VARCHAR(255),
    content TEXT,
    status VARCHAR(255) DEFAULT 'private'
);

CREATE TABLE IF NOT EXISTS brains (
  brain_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT,
  description TEXT,
  model TEXT,
  max_tokens INT,
  temperature FLOAT,
  openai_api_key TEXT,
  prompt_id UUID REFERENCES prompts(id)
);

Thx 
LG Heinzpeter 
...

**Comment by StanGirard** [comment]
@mamadoudicko
