### ISSUE TITLE
validation error for BrainSettings

### ISSUE THREAD

**Issue by trapperl** [StanGirard/quivr#845]
I hope I did this right.

I tried a number of changes to the .env file, but couldn't fix it without making a change to the code.

- Ubuntu 20.04
- Docker version 24.0.5, build ced0996
- Your Supabase postgress version 15.1.0.103,.
- I updated from a previous version to the current one 0.0.51. 
- Started getting the error after running this command:
 `sudo docker compose -f docker-compose.yml up --build`

The Error:
web           | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
web           | - info Loaded env from /app/.env
backend-core  | Process SpawnProcess-1:
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
backend-core  |     self.run()
backend-core  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
backend-core  |     self._target(*self._args, **self._kwargs)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
backend-core  |     target(sockets=sockets)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
backend-core  |     return asyncio.run(self.serve(sockets=sockets))
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
backend-core  |     return runner.run(main)
backend-core  |            ^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
backend-core  |     return self._loop.run_until_complete(task)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
backend-core  |     return future.result()
backend-core  |            ^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
backend-core  |     config.load()
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
backend-core  |     self.loaded_app = import_from_string(self.app)
backend-core  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
backend-core  |     module = importlib.import_module(module_str)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
backend-core  |     return _bootstrap._gcd_import(name[level:], package, level)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
backend-core  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
backend-core  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
backend-core  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
backend-core  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
backend-core  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend-core  |   File "/code/main.py", line 12, in <module>
backend-core  |     from routes.chat_routes import chat_router
backend-core  |   File "/code/routes/chat_routes.py", line 10, in <module>
backend-core  |     from llm.openai import OpenAIBrainPicking
backend-core  |   File "/code/llm/__init__.py", line 1, in <module>
backend-core  |     from .base import BaseBrainPicking
backend-core  |   File "/code/llm/base.py", line 14, in <module>
backend-core  |     class BaseBrainPicking(BaseModel):
backend-core  |   File "/code/llm/base.py", line 21, in BaseBrainPicking
backend-core  |     brain_settings = BrainSettings()  # type: ignore other parameters are optional
backend-core  |                      ^^^^^^^^^^^^^^^
backend-core  |   File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
backend-core  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-core  | pydantic.error_wrappers.ValidationError: 1 validation error for BrainSettings
backend-core  | pg_database_url
backend-core  |   field required (type=value_error.missing)

To fix it, I changed the pg_database_url line in the /quivr/backend/core/settings.py file.
From` pg_database_url: str` to `pg_database_url: str = None`
```
class BrainSettings(BaseSettings):
    openai_api_key: str
    anthropic_api_key: str
    supabase_url: str
    supabase_service_key: str
    pg_database_url: str = None
    resend_api_key: str = "null"
    resend_email_address: str = "brain@mail.quivr.app"
```

**Comment by jchapmanCR** [comment]
I am also getting this error after the latest pull +1

**Comment by mamadoudicko** [comment]
There is a new env var to add to `backend/core/.env`: 

`PG_DATABASE_URL=<change-me>`

**Comment by StanGirard** [comment]
Fixed
