### ISSUE TITLE
[Issue] Bug - there us a 2nd property decorator on line 32 of backend.models.files.py.. 

### ISSUE THREAD

**Issue by davidbzyk** [StanGirard/quivr#846]
There are 2 @property decorators on line 31  backend.models.files.py

@property
@property
def supabase_db(self) -> SupabaseDB:
    return get_supabase_db()

This caused me not to be able to upload docs.  you would get a TypeError: 'property' object is not callable.  Need to remove one and it works fine.

**Comment by mamadoudicko** [comment]
Fixed in this PR: https://github.com/StanGirard/quivr/pull/847
