### ISSUE TITLE
[Issue] start.sh script file

### ISSUE THREAD

**Issue by To1p5** [StanGirard/quivr#854]
I am trying to set up the quivr application so I can talk to my documents right now I am at the stage where I am building the docker container using 'docker-compose -f docker-compose.yml up --build' everytime I try to build my application I get these two errors '/code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core  | /code/scripts/start.sh: line 22: syntax error: unexpected end of file' ChatGpt stated that these errors often occur when the file is created on windows and then used in a docker container I modified the Dockerfile to remedy the issue but that hasn't worked. here is the current docker file

'# Use the official Python 3.11 image as the base
FROM python:3.11-bullseye

# Install GEOS library
RUN apt-get update && apt-get install -y libgeos-dev pandoc

# Set the working directory in the container
WORKDIR /code

# Copy the requirements.txt file into the container
COPY ./requirements.txt /code/requirements.txt

# Install project dependencies
RUN pip install --no-cache-dir -r /code/requirements.txt --timeout 100

# Install dos2unix utility to handle line endings
RUN apt-get install -y dos2unix

# Copy the start.sh script into the container and convert line endings to Unix-style (LF)
COPY ./scripts/start.sh /code/scripts/start.sh
RUN dos2unix /code/scripts/start.sh

# Copy the rest of the project files into the container
COPY . /code

# Set the entry point for the container to the corrected start.sh script
ENTRYPOINT ["bash", "/code/scripts/start.sh"]'

**Comment by quincy451** [comment]
start.sh yea on windows I got something like that...I replaced \r\n with \n and it loaded cleanly.  
But then when I run the front end i get errors setting up a brain.  And my database when I get done has no data in any of the tables...I double chcked my database url, key etc...in the process of switching to ubuntu to see how far I get.  
    On Friday, August 4, 2023 at 01:36:07 PM CDT, To1p5 ***@***.***> wrote:  
 
 


I am trying to set up the quivr application so I can talk to my documents right now I am at the stage where I am building the docker container using 'docker-compose -f docker-compose.yml up --build' everytime I try to build my application I get these two errors '/code/scripts/start.sh: line 22: syntax error: unexpected end of file
backend-core | /code/scripts/start.sh: line 22: syntax error: unexpected end of file' ChatGpt stated that these errors often occur when the file is created on windows and then used in a docker container I modified the Dockerfile to remedy the issue but that hasn't worked. here is the current docker file

'# Use the official Python 3.11 image as the base
FROM python:3.11-bullseye

Install GEOS library

RUN apt-get update && apt-get install -y libgeos-dev pandoc

Set the working directory in the container

WORKDIR /code

Copy the requirements.txt file into the container

COPY ./requirements.txt /code/requirements.txt

Install project dependencies

RUN pip install --no-cache-dir -r /code/requirements.txt --timeout 100

Install dos2unix utility to handle line endings

RUN apt-get install -y dos2unix

Copy the start.sh script into the container and convert line endings to Unix-style (LF)

COPY ./scripts/start.sh /code/scripts/start.sh
RUN dos2unix /code/scripts/start.sh

Copy the rest of the project files into the container

COPY . /code

Set the entry point for the container to the corrected start.sh script

ENTRYPOINT ["bash", "/code/scripts/start.sh"]'

**Comment by To1p5** [comment]
Thanks for that information! I've been trying to find out where I can change all the files to LF so I won't have this problem but I don't see where I can do that is there extension or something you have to download? How did you fix the "LF" issue?

**Comment by To1p5** [comment]
I've fixed the issue by changing all the line endings for all the files in vscode. Here is how one can do that if they run into the issue.


 'Converting the End of Line Sequence from CRLF to LF in any of your project files
Execute the following commands in your root of your project folder
NOTE: Do not do the following steps without commiting your data. As it clears all the git cache and it will clear all your changes in your project.
First disable the autoCRLF in the git config by running the following command in your terminal git config core.autocrlf false

Then remove the cached files in the git. Run the following command: git rm --cached -r .

Then reset the project files by executing the following command to complete conversion. git reset --hard

That's it now all the files that have CRLF will be converted to LF.

Additionally you can add "files.eol": "\n" in your Vscode settings.'
