### ISSUE TITLE
[Issue] CORS error

### ISSUE THREAD

**Issue by coolbix** [StanGirard/quivr#877]
When I try to create a brain, I got some errors such as
Access to XMLHttpRequest at 'http://localhost:5050/brains/default/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by StanGirard** [comment]
Backend is wrongly configured. Check backend logs

**Comment by coolbix** [comment]
Hi,

Thanks for the reply.

I’ve fixed the issue by installing Postgresql on my WSL Ubuntu, such as

sudo apt install postgresql postgresql-contrib

 

It would be good to mention Postgresql in ***@***.***, I think. 😊

Thanks for sharing the great project.

**Comment by alex-crr** [comment]
> Backend is wrongly configured. Check backend logs

How would I check the logs for that. I have a similar issue, I ran the migration already, AndI've followed the instructions to set up
