### ISSUE TITLE
[UX-Chat] 1-a AAU, when I arrive on a fresh chat, I have a new UI for the empty dialog

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#880]
# Epic
[#779](https://github.com/StanGirard/quivr/issues/779)

# Functional

Dialogue: AAU, I can see keyboard shortcuts as a placeholder for the empty dialog (with feature flag) (see epic [#779](https://github.com/StanGirard/quivr/issues/779))

### Tech

- [] To-do

### Tests

- [] it ...

### Validation Checks

- Since the feature is flagged, this ticket can be validated in 2 ways:
1. Activate the feature on Growthbook dashboard and go to chat screen, create new one and check that before the first message, the design is the expected (preview on #890)
2. Just check the screenshot on #890

**Comment by mamadoudicko** [comment]
https://github.com/StanGirard/quivr/pull/890
