### ISSUE TITLE
Started successfully, but cannot access

### ISSUE THREAD

**Issue by lkjulius** [StanGirard/quivr#887]
<img width="711" alt="image" src="https://github.com/StanGirard/quivr/assets/52229268/291f12cd-1251-4238-8453-aa5bcc9f924d">
<img width="558" alt="image" src="https://github.com/StanGirard/quivr/assets/52229268/cf6fd004-eb9f-409f-8fd8-a05b8f4e6a19">
please help me check

**Comment by StanGirard** [comment]
Come to our discord but you are installing it on your own server and there are possibly infinite reasons why it doesn't work.
