### ISSUE TITLE
[Issue] Private LLM model not shown when creating new brain

### ISSUE THREAD

**Issue by kripper** [StanGirard/quivr#897]
We downloaded and configured the Private LLM as explained in documentation.
When trying to create a new brain, the model is not displayed here:

![image](https://github.com/StanGirard/quivr/assets/1479804/3616c02b-8e05-4a98-bc48-8240beab0c0b)

The logs say:
`WARNING: Package(s) not found: gpt4all
`

The documentation doesn't tell something about installing gpt4all.

OS is Redhat 8 (no desktop).

**Comment by kripper** [comment]
I see. I thought latest git version was > v0.0.46.
Thanks.

So gpt4all is not required right?

**Comment by Zizico2** [comment]
The way to set it up is correct, in the documentation, but it only works up until v0.0.46

**Comment by imcuttle** [comment]
+1, private LLM is not works now
