### ISSUE TITLE
[Issue]how to deploy Quivr for internet access? 

### ISSUE THREAD

**Issue by cocomany** [StanGirard/quivr#898]
I tried to deploy Quivr for internet access. 
when sign up, it sends an email. I can click the link in the email, but the link always redirects to localhost:3000.  That blocks me to logon Quivr. 

Please advise 
1 where to config the default redirect url in the mail link
2 is there a way to disable user logon? I mean everyone can use it when accessing with url.

**Comment by jsu-github** [comment]
Logon to supabase.
Go to authentication/providers/auth providers/email

disable the email confirmation
