### ISSUE TITLE
Docker run error

### ISSUE THREAD

**Issue by thuongtin** [StanGirard/quivr#90]
<img width="1400" alt="image" src="https://github.com/StanGirard/quivr/assets/3460591/42f12c67-33e8-4b49-ac41-461d284896e7">

**Comment by thuongtin** [comment]
It seems like I cloned the project while you were programming further.

**Comment by thuongtin** [comment]
How to increase the file upload limit in the new version?

**Comment by StanGirard** [comment]
Are you bumping into a limit ? :) There is no limit in the new

**Comment by StanGirard** [comment]
Fixed 👍
