### ISSUE TITLE
Terminal Errors (code/scripts/start.sh) + Login Problem + Brains creation problem

### ISSUE THREAD

**Issue by GabriielEger** [StanGirard/quivr#914]
I'm trying to get Quivr up and running locally, but I can't get anything done within the system. I'm not someone with a lot of experience. I'm just trying to make this work. And I thank you all for how amazing this system seems to be.

I don't know if the problems are linked (one is causing the other), so I'm pointing them all out here.

**1. Terminal Errors**

It's looping in the terminal:
```
backend-core | /code/scripts/start.sh: line 2: $'\r': command not found
backend-core | /code/scripts/start.sh: line 22: syntax error: unexpected end of file
```

**2. Login Problems**

In addition, when trying to login (which the account had already been created), it is showing "Fetching your data" in a loop as well.
![image](https://github.com/StanGirard/quivr/assets/37830968/6eed0e3b-430d-4e90-b0b1-bd823343c180)

**3. Can't create brains to start the use**

When trying to create a brain, I can't, because the following error appears
`{"message":"Network Error","name":"AxiosError","stack":"to@http://localhost:3000/_next/static/chunks/4214-318df6407f4780c5.js:6:26454\ n24214/tV</</u.onerror@http://localhost:3000/_next/static/chunks/4214-318df6407f4780c5.js:6:40771\n","config":{"transitional":{"silentJSONParsing ":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout" :0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers": {"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InVoQmNmQ0dPa2pPVFp1NTciLCJ0eXAiOiJKV1QifQ..iY8sYaOHXmBMdL cdt7CFUpFBVVMp4FXmZ0BbZpAb4GI"},"baseURL":"http ://localhost:5050","method":"post","url":"/brains/","data":"{\"name\":\"adwadawdadwd\",\"description\": \"\",\"max_tokens\":256,\"model\":\"gpt-3.5-turbo\",\"temperature\":0}"},"code":"ERR_NETWORK","status ":null}`

Thank you. :)

**Comment by ElliotBadinger** [comment]
Same issue here.

**Comment by GabriielEger** [comment]
> Same issue here.

Hey, Elliot! I've tried to download & run the last released version and now it's worked! You can get it right here: https://github.com/StanGirard/quivr/releases/tag/v0.0.54

Download the zip and run again all the processes.

I'm figuring it out how to use and I hope it'll be a great adventure. Hope that you can get it to work as well. :)

**Comment by ElliotBadinger** [comment]
Hi @GabriielEger , thanks for trying to assist, so what I did was to update the repo using ```git pull``` and I then besides that I did as you advised and went through the installation process again but it was to no avail as I still get an Axios error when I try to create a brain. I suspect that it is with the way I edited the .env files may I then ask as to how you did the setup from start to finish so as to be sure that I did not miss anything. Oh and by the way I'm running the repo on an AWS ubuntu instance.

**Comment by GabriielEger** [comment]
Hey, @ElliotBadinger ! You're welcome! I'm now using the last version of Quivr (to stay up-to-date) and I'm with the same problems again. I was able to help with some translations, but nothing of the system is working. It seems to be something with the connection between Quivr and Supabase (**start.sh** and **migration.sh** scripts are not working), something that was not happening when I ran tests in the 0.0.54v release, as I've mentioned.

**What I did while using 0.0.54v release**

-> Installed the source code (clean-setup, nothing connected with the Quivr repo on Github);
-> Ran the document steps for setup ([right here](https://github.com/StanGirard/quivr/blob/main/README.md#getting-started-));
-> And that's it. Check if you setup your supabase account correctly and all the infos in the codes (.env files).

I hope that all of this issues will be fixed soon enough and I hope that you get to make things work as well.

If you need something, please let me know and I'll try to help somehow.

**Comment by ElliotBadinger** [comment]
I followed your instructions and checked everything. I crossed the t's and dotted the i's  but to no avail once again. I'm still getting the axios error with the version you recommended I use. I think I'll stick to using Quivr on their website, will come back after a while to check if the Axios issue was resolved. May I ask as to how you got yours to work?

**Comment by GabriielEger** [comment]
Hey, @ElliotBadinger. I've tested the 0.0.46 version (in doc, it suggests that Private and Local LLM would work) and I wasn't able to put it to work properly (atleast not with a private LLM), but maybe with the OpenAI API Key it would work. Can you check it out this version ([download here](https://github.com/StanGirard/quivr/releases/tag/v0.0.46)) to see if it works for you?

**Comment by shlomitsur** [comment]
Guys the issue is that the file start.sh was saved to git with Windows character.
To fix this you need to run:
`dos2unix backend/core/scripts/start.sh`
and restart the docker compose
