### ISSUE TITLE
[Issue]"/bin/sh -c apt-get update && apt-get install -y libgeos-dev pandoc" did not complete successfully

### ISSUE THREAD

**Issue by beifeng777** [StanGirard/quivr#915]
> [backend-core 2/8] RUN apt-get update && apt-get install -y libgeos-dev pandoc:
0.649 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
0.717 Err:1 http://deb.debian.org/debian bullseye InRelease
0.717   At least one invalid signature was encountered.
1.002 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
1.070 Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
1.070   At least one invalid signature was encountered.
1.803 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
1.880 Err:3 http://deb.debian.org/debian bullseye-updates InRelease
1.880   At least one invalid signature was encountered.
1.884 Reading package lists...
1.896 W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
1.896 E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
1.896 W: GPG error: http://deb.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
1.896 E: The repository 'http://deb.debian.org/debian-security bullseye-security InRelease' is not signed.
1.896 W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
1.896 E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y libgeos-dev pandoc" did not complete successfully: exit code: 100

**Comment by jsugg** [comment]
@beifeng777 You can try just trusting the packages (not secure if you're deploying to prod though).

Edit `backend/Dockerfile`

After these lines
```
ARG DEV_MODE
ENV DEV_MODE=$DEV_MODE
```

Add this command
```
RUN echo "deb [trusted=yes] http://deb.debian.org/debian bullseye main" > /etc/apt/sources.list && \
    echo "deb [trusted=yes] http://deb.debian.org/debian-security bullseye-security main" >> /etc/apt/sources.list && \
    echo "deb [trusted=yes] http://deb.debian.org/debian bullseye-updates main" >> /etc/apt/sources.list
```

Good luck 🍀
