### ISSUE TITLE
[Issue]BrainID Params Missing / NULL

### ISSUE THREAD

**Issue by UsmanJav777** [StanGirard/quivr#918]
When I run Docker, this error regarding BrainID params possibly null comes up. Kindly share how can I fix it? I am using the latest Quivr version and latest Docker version. Kindly check the attached screen.
<img width="794" alt="Screen Shot 2023-08-10 at 3 06 46 PM" src="https://github.com/StanGirard/quivr/assets/139582211/5f849ce8-3b94-496c-9bfd-aeebd1c6a828">

**Comment by ketlinapuci** [comment]
Hi... I get the same error trying to setup Quivr just posted an issue like 30 min ago.
Did you manage to get it working?
