### ISSUE TITLE
[Issue]process "/bin/sh -c yarn build" did not complete successfully

### ISSUE THREAD

**Issue by beifeng777** [StanGirard/quivr#928]
brew install gum # Windows (via Scoop) scoop install charm-gum

chmod +x install_helper.sh
./install_helper.sh
zsh: unknown file attribute: v
grep: backend/.env: No such file or directory
Running the migration scripts...
Last migration executed: 20230809154300_add_prompt_id_brain_id_to_chat_history_table
Migration script completed.
Launching the app...
[+] Building 44.3s (27/27) FINISHED                                             
 => [backend-core internal] load build definition from Dockerfile          0.0s
 => => transferring dockerfile: 544B                                       0.0s
 => [backend-core internal] load .dockerignore                             0.0s
 => => transferring context: 2B                                            0.0s
 => [backend-core internal] load metadata for docker.io/library/python:3.  1.4s
 => [frontend internal] load .dockerignore                                 0.0s
 => => transferring context: 60B                                           0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 823B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:18-alpin  1.4s
 => [frontend  1/10] FROM docker.io/library/node:18-alpine@sha256:cdc1e8a  0.0s
 => [frontend internal] load build context                                 0.1s
 => => transferring context: 34.81kB                                       0.1s
 => [backend-core 1/8] FROM docker.io/library/python:3.11-bullseye@sha256  0.0s
 => [backend-core internal] load build context                             0.0s
 => => transferring context: 20.59kB                                       0.0s
 => CACHED [backend-core 2/8] RUN apt-get update && apt-get install -y li  0.0s
 => CACHED [backend-core 3/8] WORKDIR /code                                0.0s
 => CACHED [backend-core 4/8] COPY ./requirements.txt /code/requirements.  0.0s
 => CACHED [backend-core 5/8] RUN pip install --no-cache-dir -r /code/req  0.0s
 => CACHED [backend-core 6/8] COPY ./scripts/start.sh /code/scripts/start  0.0s
 => CACHED [backend-core 7/8] RUN chmod +x /code/scripts/start.sh          0.0s
 => CACHED [backend-core 8/8] COPY . /code                                 0.0s
 => [backend-core] exporting to image                                      0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:7c04b4912d5d5ff268982b13edde7122aa5c3726024c5  0.0s
 => => naming to docker.io/library/quivr-backend-core                      0.0s
 => CACHED [frontend  2/10] RUN apk add --update --no-cache python3 make   0.0s
 => CACHED [frontend  3/10] RUN python3 -m ensurepip                       0.0s
 => CACHED [frontend  4/10] RUN pip3 install --no-cache --upgrade pip set  0.0s
 => CACHED [frontend  5/10] RUN mkdir -p /app                              0.0s
 => CACHED [frontend  6/10] WORKDIR /app                                   0.0s
 => CACHED [frontend  7/10] COPY package*.json yarn.lock ./                0.0s
 => CACHED [frontend  8/10] RUN yarn install --network-timeout 1000000     0.0s
 => CACHED [frontend  9/10] COPY . .                                       0.0s
 => ERROR [frontend 10/10] RUN yarn build                                 42.8s
------
 > [frontend 10/10] RUN yarn build:
0.326 yarn run v1.22.19
0.355 $ next build
0.638 - info Loaded env from /app/.env
0.770 Attention: Next.js now collects completely anonymous telemetry regarding usage.
0.770 This information is used to shape Next.js' roadmap and prioritize features.
0.770 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
0.771 https://nextjs.org/telemetry
0.771 
0.855 - info Creating an optimized production build...
33.16 - info Compiled successfully
33.16 - info Linting and checking validity of types...
42.07 Failed to compile.
42.07 
42.07 ./app/invitation/[brainId]/hooks/useInvitation.ts:19:19
42.07 Type error: 'params' is possibly 'null'.
42.07 
42.07   17 |   const { t } = useTranslation(["brain","invitation"]);
42.07   18 |   const params = useParams();
42.07 > 19 |   const brainId = params.brainId as UUID | undefined;
42.07      |                   ^
42.07   20 |   const [isLoading, setIsLoading] = useState(false);
42.07   21 |   const [brainName, setBrainName] = useState<string>("");
42.07   22 |   const [role, setRole] = useState<BrainRoleType | undefined>();
42.44 error Command failed with exit code 1.
42.44 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
Navigate to localhost:3000 in your browser to access the app.

**Comment by Serdumps** [comment]
same issue
