### ISSUE TITLE
[Issue] Axios erros causing chat repsonses to not render

### ISSUE THREAD

**Issue by davidbzyk** [StanGirard/quivr#929]
There seems to be a new issue with Axios returning a couple of errs.  These errors effect the chat out, by not returning any.  
I don't have enough react/ts knowledge to figure out what the issue is here.
![iisue1](https://github.com/StanGirard/quivr/assets/130847618/4d96073f-0e07-4edf-b249-4008bbaa6701)
![issue2](https://github.com/StanGirard/quivr/assets/130847618/854c908f-e58d-4dd6-a40b-0c3736214a52)

**Comment by GabriielEger** [comment]
Hey, @davidbzyk! I'm having problems as well. I guess there are some problems with the connection between Quivr and Supabase (**start.sh** and **migration.sh** scripts are not working). I hope it'll be fixed soon enough. :)

**Comment by joejaytheking123** [comment]
Hey @davidbzyk how did you get hot reloading to work in docker, trying to figure that out so I can get live reloads

**Comment by davidbzyk** [comment]
> Hey @davidbzyk how did you get hot reloading to work in docker, trying to figure that out so I can get live reloads

What do you mean?   if the docker-compse.yml doesnt work try docker-compose-dev
