### ISSUE TITLE
[Issue]My internet connection is not good, and I don't want to install dynamically every time. Is there any other solution?

### ISSUE THREAD

**Issue by beifeng777** [StanGirard/quivr#936]
My internet connection is not good, and I don't want to install dynamically every time. Is there any other solution?

**Comment by GabriielEger** [comment]
Hey @beifeng777 ! How are you doing? There is an option by using a private LLM, which is currently compatible with the release 0.0.46 ([download here](https://github.com/StanGirard/quivr/releases/tag/v0.0.46)), according with the project document right [here](https://github.com/StanGirard/quivr#disclaimer-%EF%B8%8F). I hope that it will help you. Soon enough it will be correctly implemented in these new versions.

Take care. :)

**Comment by beifeng777** [comment]
> Hey @beifeng777 ! How are you doing? There is an option by using a private and local LLM, which is currently compatible with the release 0.0.46 ([download here](https://github.com/StanGirard/quivr/releases/tag/v0.0.46)), according with the project document right [here](https://github.com/StanGirard/quivr#disclaimer-%EF%B8%8F). I hope that it will help you. Soon enough it will be correctly implemented in these new versions.
> 
> Take care. :)

<img width="741" alt="image" src="https://github.com/StanGirard/quivr/assets/29267921/a042cf80-e9f8-401b-a4e3-1b27525acfa3">
I am stuck at this step, the download folder is the one that the Anthropic dog was able to download.

**Comment by beifeng777** [comment]
WARNING: Package(s) not found: gpt4all

**Comment by GabriielEger** [comment]
Hey, @beifeng777 ! I've run some tests and couldn't get it to work as well. I'll be waiting for some "working good" version.

**Comment by xmuruaga** [comment]
+1. Also looking for a solution to this issue.

**Comment by beifeng777** [comment]
<img width="812" alt="image" src="https://github.com/StanGirard/quivr/assets/29267921/48e38733-31b1-44cd-9add-c42501e2e8f2">

**Comment by beifeng777** [comment]
My network is unable to connect well to supabase. Is it possible to install a local database?

**Comment by beifeng777** [comment]
Is it possible to develop an easier upgrade program?

**Comment by hyg290** [comment]
> 

yes,you can install your database local.

**Comment by beifeng777** [comment]
> > 
> 
> yes,you can install your database local.

How do I install a local database?
