### ISSUE TITLE
[Issue] Chat not working, trackback 

### ISSUE THREAD

**Issue by davidbzyk** [StanGirard/quivr#938]
Wish i could be more helpful with debugging, but have been super swamped.

backend-core  | 2023-08-12 07:18:55,515:INFO - Streaming request for gpt-3.5-turbo
backend-core  | streaming
backend-core  | INFO:     172.18.0.1:44154 - "POST /chat/07ef65a7-30a4-428e-811e-e9d07c492c5b/question/stream?brain_id=3a976a47-5ed6-4a45-a844-344a575589dc HTTP/1.1" 200 OK
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core  |     await self.app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core  |     raise e
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 69, in app
backend-core  |     await response(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
backend-core  |     async with anyio.create_task_group() as task_group:
backend-core  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
backend-core  |     raise exceptions[0]
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
backend-core  |     await func()
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
backend-core  |     async for chunk in self.body_iterator:
backend-core  |   File "/code/llm/qa_base.py", line 249, in generate_stream
backend-core  |     streamed_chat_history = update_chat_history(
backend-core  |                             ^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/repository/chat/update_chat_history.py", line 11, in update_chat_history
backend-core  |     response: List[ChatHistory] = (supabase_db.update_chat_history(chat_history)).data
backend-core  |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/models/databases/supabase/chats.py", line 69, in update_chat_history
backend-core  |     .execute()
backend-core  |      ^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 68, in execute
backend-core  |     raise APIError(r.json())
backend-core  | postgrest.exceptions.APIError: {'code': 'PGRST204', 'details': None, 'hint': None, 'message': "Column 'brain_id' of relation 'chat_history' does not exist"}
backend-core  | 2023-08-12 07:19:00,619:INFO - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=15 request_id=adecbb2466028cdef40bdc50c0828c77 response_code=200
![image](https://github.com/StanGirard/quivr/assets/130847618/18333567-31e5-4626-a859-4b164e626925)

**Comment by StanGirard** [comment]
You have an issue with your database. Did you run the migrations?

**Comment by davidbzyk** [comment]
Yes I tried running the recent ones manually through supabase, they were
already there.  I tried entering the container but the migration script
wasn’t there I figured if I entered through the container it would work.
Let me know what I’m missing, running migrations locally looks for a local
Postgres db.

**Comment by davidbzyk** [comment]
disregard.. it just migrated.. thanks.

**Comment by davidbzyk** [comment]
ok migration was succesful, but it there is no input or output after chat is sent
![image](https://github.com/StanGirard/quivr/assets/130847618/f635600e-0d1e-491e-8088-125b61d2838f)
![image](https://github.com/StanGirard/quivr/assets/130847618/e59efb0c-e193-482f-8bf5-ba8757af0b2a)
