### ISSUE TITLE
How to disable demo mode?

### ISSUE THREAD

**Issue by SamuelMiller** [StanGirard/quivr#94]
I have installed Quivr locally on my Macbook pro Catalina OS and have it running in Docker. How do I disable the demo mode of the frontend so I can remove or increase the limit on the file size upload?

**Comment by StanGirard** [comment]
If you are using the streamlit version then there is an environment variable in the secrets.toml to change. 

Else with the new version there is no limit

**Comment by StanGirard** [comment]
Fixed ! Upload file are now 100mb max :)
