### ISSUE TITLE
Beyond Boundaries: Help Me Reach My Quivr Instance on Home PC from Anywhere!"

### ISSUE THREAD

**Issue by BabaSarf** [StanGirard/quivr#940]
Could someone kindly provide guidance on how to access my Quivr instance, which is running on my home PC with a static IP, from outside my local area? Currently, I can connect to Quivr, but I am unable to select or create any brain. I suspect this might be related to Supabase. Any assistance and guidance would be greatly appreciated.

**Comment by jsu-github** [comment]
I have the same problem when I expose my docker container beyond my local network to use it remotely. When on internal wifi its working. I really hope for some tips

**Comment by BabaSarf** [comment]
> I have the same problem when I expose my docker container beyond my local network to use it remotely. When on internal wifi its working. I really hope for some tips

Have you sortout your issue yet
