### ISSUE TITLE
what is the use of enable_summarization?

### ISSUE THREAD

**Issue by bugm** [StanGirard/quivr#945]
Hello guys, I am reading the source code of quivr. 
I found a parameter named enable_summarization on different parsers [backend/core/parsers]. But i do not find any action do summarize in related function.  and the only difference between set to True and set to False is the value of key "summarization" in metadata. 
So is this a future feature or I missed something?

**Comment by mamadoudicko** [comment]
Hello @bugm,

It is indeed a future feature
