### ISSUE TITLE
[Issue]有人愿意把这个项目汉化么？

### ISSUE THREAD

**Issue by beifeng777** [StanGirard/quivr#947]
我想用这个项目，但这个项目对大陆的网络环境似乎很不友好。有没有大佬帮忙改造一下，适合在大陆使用？

**Comment by beifeng777** [comment]
如果大陆能用一定能到40K星

**Comment by heywalter** [comment]
> 我想用这个项目，但这个项目对大陆的网络环境似乎很不友好。有没有大佬帮忙改造一下，适合在大陆使用？

Hi 主要是需要汉化哪方面呢，镜像下载 or GPT 连接？

**Comment by georgeqin96** [comment]
上传中文好像出错

**Comment by heywalter** [comment]
> 

向量存储已经在 Roadmap 里了，我觉得和作者沟通确认下数据库的选型，动态下载还没在 roadmap 里

**Comment by shiliu2023** [comment]
我们可以做汉化，向量数据库也可以放在本地。可以加微信：shiliukeji007
