### ISSUE TITLE
[Issue] Error Creating New Brain

### ISSUE THREAD

**Issue by kegsss** [StanGirard/quivr#961]
Running into this error after trying to create my first brain:

<img width="1152" alt="image" src="https://github.com/StanGirard/quivr/assets/71108752/1ad9d407-9a23-4a1e-a769-069d59532632">

I have run the migration scripts manually in Supabase (although "20230620170840_add_vectors_brains" and "20230620183620_use_supabase_user_id" seemed to fail - everything else was successful.

I triple checked that my .env files have the correct info in them as well. Is there anything else I'm not thinking of?

To replicate:
1. Sign in locally
2. Attempt to create first brain
3. Enter in all relevant info for the brain fields and attempt to create
4. Error is displayed

I even tried reinstalling fresh from the 0.056 source code as well just to be safe.

Any help is always appreciated :)!

**Comment by Flinana** [comment]
Hi, same error since yesterday.

**Comment by BabaSarf** [comment]
I think you are missing a field in your database

**Comment by kegsss** [comment]
@BabaSarf any idea on what to do to fix? Curious what made you think it was a missing db field?

**Comment by heywalter** [comment]
Same issue+1

**Comment by michaeljabbour** [comment]
same issue +1 - here is the error I get in the GUI when trying to create a brain
![image](https://github.com/StanGirard/quivr/assets/51451/258a84b0-91a9-42bc-bb22-ec227950ecba)

**Comment by BabaSarf** [comment]
> @BabaSarf any idea on what to do to fix? Curious what made you think it was a missing db field?

It was showing on my terminal I ran one of the script on supabase and it fixed the issue I think the brain_id was missing

**Comment by darkanubis0100** [comment]
> Running into this error after trying to create my first brain:
> 
> <img alt="image" width="1152" src="https://user-images.githubusercontent.com/71108752/261023595-1ad9d407-9a23-4a1e-a769-069d59532632.png">
> I have run the migration scripts manually in Supabase (although "20230620170840_add_vectors_brains" and "20230620183620_use_supabase_user_id" seemed to fail - everything else was successful.
> 
> I triple checked that my .env files have the correct info in them as well. Is there anything else I'm not thinking of?
> 
> To replicate:
> 
> 1. Sign in locally
> 2. Attempt to create first brain
> 3. Enter in all relevant info for the brain fields and attempt to create
> 4. Error is displayed
> 
> I even tried reinstalling fresh from the 0.056 source code as well just to be safe.
> 
> Any help is always appreciated :)!

This happens because some of the scripts were not correctly migrated to Supabase.

**Comment by BrewingCodeAndColdOnes** [comment]
> same issue +1 - here is the error I get in the GUI when trying to create a brain ![image](https://user-images.githubusercontent.com/51451/261480347-258a84b0-91a9-42bc-bb22-ec227950ecba.png)

I had this but my issue was a result of not running it locally, but rather I installed on my server.

To fix, in the frontend .env I needed to update: 
NEXT_PUBLIC_BACKEND_URL=localhost:5050
to the local IP
NEXT_PUBLIC_BACKEND_URL=http://192.168.1.15:5050

Also ensure you open 5050 in your firewall

**Comment by tsadigovAgmail** [comment]
@kegsss  I wonder if your frontend and backend use the same supabase instance or you have data inconsistency.
The log has this ` 'Key (user_id)=(da3f8164-2046-45cb-ad00-f6fd16ac272c) is not present in table "users".', 'hint': None, 'message': 'insert or update on table "brains_users" violates foreign key constraint "brains_users_user_id_fkey"'}`

**Comment by OkabeJotarou** [comment]
Same issue+1

**Comment by kegsss** [comment]
> @kegsss I wonder if your frontend and backend use the same supabase instance or you have data inconsistency. The log has this ` 'Key (user_id)=(da3f8164-2046-45cb-ad00-f6fd16ac272c) is not present in table "users".', 'hint': None, 'message': 'insert or update on table "brains_users" violates foreign key constraint "brains_users_user_id_fkey"'}`

Hey @tsadigovAgmail - my frontend and backend .env files are using the same supabase instance, are they not supposed to be? 

I also tried re-running the scripts and a few of them still fail (some of them seem to fail because they originally worked, but I can't get these first 2 to work at all):

<img width="871" alt="image" src="https://github.com/StanGirard/quivr/assets/71108752/2466efb5-8990-4048-b2ca-9d1f964020ab">

cc @darkanubis0100 @BabaSarf - any ideas on why these scripts seem to fail?
