### ISSUE TITLE
[BUG] Fix rate limiting : limite requests per user

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#965]
# Epic

Bugs

# Functional

A user should not be allowed to do more than 50 requests per day through Quivr unless they have their own OpenAI API Key or the brain has used has an OpenAI Api Key

### Tech

- Rename user table into user_usage
- Rename User class into UserUsage: 
- create_user -> create_user_usage
- handle_user_usage: create_user_usage + increment_user_request_count
- 
Make a separate User class
On both /question endpoints :
- handle_user_usage (eventual creation + increment)
- Send as a reply "You have reached your maximum number of requests for the day, set an OpenAI Key for your user account or for the brain you are currently using"

### Tests

- [] Unit tests for incrementing the number of requests

### Validation Checks

- [] When a user asks a question -> the number of requests for that day should be incremented by one if not using an openAiKey
- [] When a user reaches his max number of requests, he sees in the chat a message "You have reached your maximum number of requests for the day, set an OpenAI Key for your user account or for the brain you are currently using"

**Comment by kuluruvineeth** [comment]
@gozineb i would like to work on this, could you please assign this to me.
