### ISSUE TITLE
[Issue]HTTP response body: unexpected EOF

### ISSUE THREAD

**Issue by georgeqin96** [StanGirard/quivr#973]
win10 , quivr-0.0.58
2.247 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
3.725 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
5.062 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
8.873 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
10.97 Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [250 kB]
11.88 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [17.3 kB]
11.88 Fetched 8658 kB in 12s (746 kB/s)
11.88 Reading package lists...
12.30 Reading package lists...
12.71 Building dependency tree...
12.84 Reading state information...
12.94 The following additional packages will be installed:
12.94   libcmark-gfm-extensions0 libcmark-gfm0 libgeos-3.9.0 libgeos-c1v5
12.94   pandoc-data
12.94 Suggested packages:
12.94   libgdal-doc texlive-latex-recommended texlive-xetex texlive-luatex
12.94   pandoc-citeproc texlive-latex-extra context wkhtmltopdf librsvg2-bin groff
12.94   ghc nodejs php python ruby r-base-core libjs-mathjax node-katex
12.94   citation-style-language-styles
12.98 The following NEW packages will be installed:
12.98   libcmark-gfm-extensions0 libcmark-gfm0 libgeos-3.9.0 libgeos-c1v5
12.98   libgeos-dev pandoc pandoc-data
14.59 0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
14.59 Need to get 20.7 MB of archives.
14.59 After this operation, 161 MB of additional disk space will be used.
14.59 Err:1 http://deb.debian.org/debian bullseye/main amd64 libcmark-gfm0 amd64 0.29.0.gfm.0-6
14.59   500  reading HTTP response body: unexpected EOF [IP: 151.101.110.132 80]
16.66 Get:2 http://deb.debian.org/debian bullseye/main amd64 libcmark-gfm-extensions0 amd64 0.29.0.gfm.0-6 [46.1 kB]
19.21 Get:3 http://deb.debian.org/debian bullseye/main amd64 libgeos-3.9.0 amd64 3.9.0-1 [921 kB]
21.26 Get:4 http://deb.debian.org/debian bullseye/main amd64 libgeos-c1v5 amd64 3.9.0-1 [377 kB]
24.88 Get:5 http://deb.debian.org/debian bullseye/main amd64 libgeos-dev amd64 3.9.0-1 [399 kB]
27.35 Get:6 http://deb.debian.org/debian bullseye/main amd64 pandoc-data all 2.9.2.1-1 [376 kB]
33.23 Get:7 http://deb.debian.org/debian bullseye/main amd64 pandoc amd64 2.9.2.1-1+b1 [18.5 MB]
33.60 E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cmark-gfm/libcmark-gfm0_0.29.0.gfm.0-6_amd64.deb  500  reading HTTP response body: unexpected EOF [IP: 151.101.110.132 80]
33.60 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
33.60 Fetched 20.6 MB in 21s (999 kB/s)
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y libgeos-dev pandoc" did not complete successfully: exit code: 100

**Comment by jiuyueshenhua** [comment]
> network problem

Hello, I have encountered a similar issue. I am from China, and we need to use a VPN to download foreign software. I use Clash in global mode and have also enabled the tun mode. I can ping the relevant websites, but still cannot download. Can you tell me how you solved this?
![image](https://github.com/StanGirard/quivr/assets/109449284/b03b67e7-b950-46f3-af27-5ed7906fd1a5)
