### ISSUE TITLE
[Issue] Values missing in generating chat

### ISSUE THREAD

**Issue by devinJanzen** [StanGirard/quivr#982]
Running on Windows after adding to a Brain when I go to chat with it I am getting the following errors.

backend-chat     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-chat     |   File "/code/routes/chat_routes.py", line 269, in create_stream_question_handler
backend-chat     |     gpt_answer_generator = OpenAIBrainPicking(
backend-chat     |                            ^^^^^^^^^^^^^^^^^^^
backend-chat     |   File "/code/llm/openai.py", line 31, in __init__
backend-chat     |     super().__init__(
backend-chat     |   File "/code/llm/qa_base.py", line 59, in __init__
backend-chat     |     super().__init__(
backend-chat     |   File "/code/llm/base.py", line 55, in __init__
backend-chat     |     super().__init__(**data)
backend-chat     |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
backend-chat     | pydantic.error_wrappers.ValidationError: 4 validation errors for OpenAIBrainPicking
backend-chat     | supabase_client
backend-chat     |   field required (type=value_error.missing)
backend-chat     | vector_store
backend-chat     |   field required (type=value_error.missing)
backend-chat     | qa
backend-chat     |   field required (type=value_error.missing)
backend-chat     | embeddings
backend-chat     |   field required (type=value_error.missing)

When there is now docs in the brain the chat works but the second their are embeddings it is giving the above error.

**Comment by shiliu2023** [comment]
mee to

**Comment by snowfoxyao** [comment]
Getting this error too.

**Comment by mamadoudicko** [comment]
The issue has now been resolved. Please fetch the latest version from the main branch
