### ISSUE TITLE
Error processing file: process_audio() got an unexpected keyword argument 'brain_id' INFO:     172.18.0.2:60944 - "POST /upload?brain_id=5f231f13-0d99-4f39-b39d-5d8c6ef504a1 HTTP/1.1" 200 OK[Issue]

### ISSUE THREAD

**Issue by shiliu2023** [StanGirard/quivr#987]
Error processing file: process_audio() got an unexpected keyword argument 'brain_id'
INFO:     172.18.0.2:60944 - "POST /upload?brain_id=5f231f13-0d99-4f39-b39d-5d8c6ef504a1 HTTP/1.1" 200 OK

when upload mp4

**Comment by agonbina** [comment]
It's a bug in the implementation of `process_audio`. It appears this feature was not even tested at all 🤦‍♂️
