### ISSUE TITLE
[Issue] Error accessing brain and uploading documents through Internet does not work

### ISSUE THREAD

**Issue by jsu-github** [StanGirard/quivr#988]
In local network Quivr (docker container on liunx) is working fine. Accessing from front end also.
When I try to do the same from Internet I get the following:

1. Oh no! you need to select a brain first
2. If its still in the cache from using it locally I get a networking error while trying to upload documents

**Comment by StanGirard** [comment]
You ae having issue accessing your backend :)

**Comment by jsu-github** [comment]
yeah. that was clear. I found out I only openen port 3000, but I opened also 5050. thanks Port range even
