### ISSUE TITLE
End to end testing

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#99]
How do we end to end test the back end and the app ?

**Comment by rhinojosadev** [comment]
To test end to end the whole application I could help using cypress. 
But I'd like to discuss about the current flow of the application, since we would need to define what's the definition of done in each one of the features :D.

**Comment by Ruben1701** [comment]
> To test end to end the whole application I could help using cypress.
> But I'd like to discuss about the current flow of the application, since we would need to define what's the definition of done in each one of the features :D.

I second this I would like to help e2e testing and also recommend cypress but would need a more clear definition of done for different features.

**Comment by StanGirard** [comment]
Come and join the discord we can talk about it there :)
