### ISSUE TITLE
[Issue]No response to the conversation.

### ISSUE THREAD

**Issue by beifeng777** [StanGirard/quivr#990]
backend-chat     | INFO:     172.18.0.5:50366 - "GET /chat/ee078f82-7c71-4fe7-ad7b-ecc5c3e9608a/history HTTP/1.1" 200 OK
backend-chat     | INFO:     172.18.0.5:50366 - "GET /chat/71af79ec-b900-4c5a-a5d0-f3f44af38d38/history HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:38484 - "GET /brains/3dee3d42-739d-41a3-b4a1-1c461a8ea730/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:38484 - "GET /brains/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:38484 - "GET /brains/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:51444 - "GET /prompts HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:51446 - "GET /brains/3dee3d42-739d-41a3-b4a1-1c461a8ea730/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:37430 - "OPTIONS /brains/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:37430 - "GET /brains/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:37430 - "GET /brains/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:37430 - "GET /brains/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:37430 - "GET /brains/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:37430 - "OPTIONS /brains/3dee3d42-739d-41a3-b4a1-1c461a8ea730/ HTTP/1.1" 200 OK
backend-chat     | INFO:     172.18.0.5:43816 - "GET /chat/ee078f82-7c71-4fe7-ad7b-ecc5c3e9608a/history HTTP/1.1" 200 OK
backend-chat     | INFO:     172.18.0.5:43818 - "GET /chat/71af79ec-b900-4c5a-a5d0-f3f44af38d38/history HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:37430 - "GET /brains/3dee3d42-739d-41a3-b4a1-1c461a8ea730/ HTTP/1.1" 200 OK
backend-core     | INFO:     172.18.0.5:37430 - "POST //chat/71af79ec-b900-4c5a-a5d0-f3f44af38d38/question/stream?brain_id=3dee3d42-739d-41a3-b4a1-1c461a8ea730 HTTP/1.1" 404 Not Found
<img width="1176" alt="image" src="https://github.com/StanGirard/quivr/assets/29267921/a0727b2a-7250-4048-82bd-1e504e966b87">
<img width="1192" alt="image" src="https://github.com/StanGirard/quivr/assets/29267921/86d3389a-5475-4186-98c7-6473ec96b767">

**Comment by mamadoudicko** [comment]
Seems that something when wrong on the back side. 

Have you run the new required migration from [this PR](https://github.com/StanGirard/quivr/pull/980/commits/948443558614d150e86b22d42e00ffcf20199e43#diff-8f70d2486e7c0df85f3b20c1df1929b0ee3ab32584768e94a90d99acc6a0a3e3) ?
