### ISSUE TITLE
[Issue] AWS ECS backend AxiosError Network Error

### ISSUE THREAD

**Issue by xmuruaga** [StanGirard/quivr#993]
I had Quivr running locally. Supabase and the rest are configured and everything worked fine in localhost.
I'm now trying to run it in Vercel + AWS ECS Fargate.

I've deployed the frontend to Vercel, and the backend to AWS ECS Fargate. I've also ensured that the SG in AWS have inbound and outbound rules for port 5050. 

I've changed the frontend.env to the following:
NEXT_PUBLIC_ENV=production
NEXT_PUBLIC_BACKEND_URL=http://x.x.x.x:5050  (AWS ECS Public IP)

The ECS container is running, I can reach it through the browser (status 200):
![image](https://github.com/StanGirard/quivr/assets/17816550/5f98a2dd-458a-41e0-9caf-6ce079626ac4)

But when trying to create a Brain from the frontend I get the following error:
![image](https://github.com/StanGirard/quivr/assets/17816550/98ce2cc7-65ae-4562-addc-30e94c06975e)

{"message":"Network Error","name":"AxiosError","stack":"AxiosError: Network Error\n    at u.onerror (https://....)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"....."},"baseURL":"http://x.x.x.x:5050","method":"post","url":"/prompts","data":"{\"title\":\"asd\",\"content\":\"asd\"}"},"code":"ERR_NETWORK","status":null}

Has anyone face this same issue?

**Comment by lugfug** [comment]
What was the solution to this issue? I'm having a similar problem.

**Comment by Croccodoyle** [comment]
This was closed with no epxlanation?

**Comment by xmuruaga** [comment]
I closed it because the same is happening in quivr.app live version, and there is already an issue for that.

**Comment by jchico77** [comment]
> I closed it because the same is happening in quivr.app live version, and there is already an issue for that.

which issue? I'd like to follow it
